- src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java
- src/test/java/com/google/devtools/build/lib/remote/UploadManifestTest.java
This CL makes no behavioral changes; it only amends documentation to match reality and adds test coverage for it.
PiperOrigin-RevId: 607249997
Change-Id: I448801a4d696347184e2d307ad0df58eb79193cf
> [7.1.0] Clarify the behavior of --incompatible_remote_symlinks in the presence of a dangling symlink.

- src/main/java/com/google/devtools/build/lib/remote/UploadManifest.java
- src/test/java/com/google/devtools/build/lib/remote/GrpcCacheClientTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteExecutionServiceTest.java
- src/test/java/com/google/devtools/build/lib/remote/UploadManifestTest.java
Bazel doesn't preserve executable bits for outputs; all files in the output tree are chmodded to either 0555 or 0755 after action execution, depending on --experimental_writable_outputs.
With respect to the disk/remote cache protocol, Bazel always marks uploaded inputs as executable and always ignores the executable bit on downloaded outputs. For uploaded outputs, the behavior currently differs between directories and non-directories; this CL makes the behavior consistent.
This makes it more likely that the input Merkle tree to a remote action can hit a cache populated by a previous local action. (See unknown commit where the behavior was changed for non-directory outputs, with the same rationale.)
As a minor effect, it also avoids additional I/O to obtain the permission bits from the …
> [7.1.0] Set the executable bit on files in output directories uploaded to a disk or remote cache.

- src/main/java/com/google/devtools/build/lib/skyframe/TreeArtifactValue.java
PiperOrigin-RevId: 607649229
Change-Id: I7c3cc7f750bbba1c90d1b3e033ca9b7493f401f8
> [7.1.0] Call out that TreeArtifactVisitor.visit is called in a nondeterministic order.

- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
Calling isDirectory on a Path requires an extra system call. In most Unix filesystems, readdir is able to return the type directly (see the implementation in NativePosixFiles).
PiperOrigin-RevId: 607678196
Change-Id: I5d09f11d6aa4702a6f7a0310cca26616cfbac6d1
> [7.1.0] Optimize out a stat call.

- src/main/java/com/google/devtools/build/lib/remote/UploadManifest.java
- src/test/java/com/google/devtools/build/lib/remote/UploadManifestTest.java
Some users have very large tree artifacts (with hundreds of thousands of files) which are extremely slow to traverse sequentially. In one particular scenario with ~250k files, this change reduces the time spent computing the manifest from ~70s to ~5s.
(We could parallelize further across all outputs, but I prefer to wait until there is a concrete need for it.)
PiperOrigin-RevId: 607678324
Change-Id: Ia80d0a663909b8ed96c6720d9eb5393fb3027b48
> [7.1.0] Compute output directories in parallel when building the upload manifest.

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryModule.java
- src/test/shell/bazel/starlark_repository_test.sh
See https://github.com/bazelbuild/bazel/pull/21131#discussion_r1471924084
Closes #21390.
Commit https://github.com/bazelbuild/bazel/commit/38c1d5d27061481b1a688abb37c6f1dd8b288c26
PiperOrigin-RevId: 607821270
Change-Id: I031222ee80c4db4ca50372c549e2b522ac606cb7
> [7.1.0] Fix rule definition environment for repo rules

- src/main/java/com/google/devtools/build/lib/rules/java/JavaStarlarkCommon.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaTargetAttributes.java
The Starlark Java rules already add the direct JARs to the transitive classpath depset and pass the same depset to the full and the header compile action. By allowing them to bypass the logic that prepends the direct jars to the compile-time classpath, both actions retain the same `NestedSet` instead of both retaining a new one with identical elements.
Closes #21343.
Commit https://github.com/bazelbuild/bazel/commit/31fae9e8e6687cbaf0dfe55a466696210c80be96
PiperOrigin-RevId: 607790056
Change-Id: Ia08c834ae3e5b1151607459408cdfea85d47314f
> [7.1.0] Share classpath `NestedSet` between full and header compile actions

- src/main/java/com/google/devtools/build/lib/analysis/AnalysisEnvironment.java
- src/main/java/com/google/devtools/build/lib/analysis/CachingAnalysisEnvironment.java
- src/main/java/com/google/devtools/build/lib/analysis/RuleContext.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompilationHelper.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileActionBuilder.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileAction.java
- src/main/java/com/google/devtools/build/lib/skyframe/AspectFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/ConfiguredTargetFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeBuildView.java
- src/main/starlark/builtins_bzl/common/java/android_lint.bzl
- src/main/starlark/builtins_bzl/common/java/java_common.bzl
- src/main/starlark/builtins_bzl/common/java/java_common_internal_for_builtins.bzl
- src/main/starlark/builtins_bzl/common/java/java_helper.bzl
- src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisTestUtil.java
- src/test/java/com/google/devtools/build/lib/analysis/util/BUILD
- src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewForTesting.java
- src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewTestCase.java
- src/test/java/com/google/devtools/build/lib/rules/android/BUILD
- src/test/java/com/google/devtools/build/lib/rules/android/ResourceTestBase.java
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/bazel_java_test.sh
- src/test/shell/bazel/local_repository_test.sh
Buildozer fixes for Java strict deps violations referring to external repositories now contain labels in display form, which avoid canonical repository names that should never be added to BUILD files and aren't understood by `buildozer`.
The Starlark actions can use `Label.to_display_form()`. Java compilation actions, which are still implemented in Java, can't access the main repository mapping via `BazelModuleContext` and instead retrieve it from a new field on `AnalysisEnvironment`.
Closes #21180.
Commit https://github.com/bazelbuild/bazel/commit/b11fa7a7c7fdb37012c7a442b16f6fdcf90b9177
PiperOrigin-RevId: 607803030
Change-Id: I0cdccabfde0217c9201cef9ca9d260b0c8ca27cd
> [7.1.0] Emit labels in display form in Java rules

- src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
- src/main/java/com/google/devtools/build/lib/exec/ExpandedSpawnLogContext.java
- src/main/java/com/google/devtools/build/lib/exec/SpawnLogContext.java
For now, we don't publish the old formats, because in our experience their size tends to get out of control, and that doesn't play well with the automatic uploading of files referenced by the BEP.
PiperOrigin-RevId: 608385023
Change-Id: I772cedbf844648ae708abc3ae7e2e5579060a1e4
> [7.1.0] Publish the new execution log format to the build event protocol.

- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheClient.java
https://github.com/bazelbuild/bazel/commit/7a774ff7c5850e7bd57af840a0e097ad4ec25417 got the condition backwards. Note that referential integrity isn't required for correct operation, but lack of it can slow things down unnecessarily.
PiperOrigin-RevId: 608354674
Change-Id: If56bb9211a5167d5db9e8eceb6224269758acdb1
> [7.1.0] Ensure that the mtime of an AC entry is smaller, not larger, than the CAS blobs it references.

- src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverageRunner.java
- src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt
- src/test/shell/bazel/bazel_coverage_java_test.sh
When the java classpath exceeds the limit, we create a manifest JAR
and pass that on the classpath. JacocoCoverageRunner knows how to
extract information from this JAR. But if another JAR ends up on that
classpath, it confuses the coverage runner which is expecting only a
single jar in this case.
This changes the java_stub_template file to export the name of the
created manifest jar so the coverage runner can extract it.
We also change the template file so the relevant exports don't occur
in the middle of a larger function.
It's possible this is somewhat overengineered and that we could
always rely on the manifest jar always being the first one discovered
by the coverage runner, but it is not totally obvious to me that that
will always be true.
Fixes #21268
Closes #21365.
Commit …
> [7.1.0] Pass the name of the classpath manifest jar to JacocoCoverageRunner

- src/main/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStore.java
- src/main/java/com/google/devtools/build/lib/skyframe/FilesystemValueChecker.java
- src/main/java/com/google/devtools/build/lib/skyframe/TreeArtifactValue.java
- src/test/java/com/google/devtools/build/lib/actions/ActionCacheCheckerTest.java
- src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactBuildTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactValueTest.java
As explained in https://github.com/bazelbuild/bazel/issues/20418, when a tree artifact contains a symlink to a directory, it is collected as a single TreeFileArtifact with DirectoryArtifactValue metadata. With this change, the symlink is followed and the directory expanded into its contents, which is more incrementally correct and removes a special case that tree artifact consumers would otherwise have to be aware of.
This also addresses https://github.com/bazelbuild/bazel/issues/21171, which is due to the metadata for the directory contents not being available when building without the bytes, causing the input Merkle tree builder to fail. (While I could have fixed this by falling back to reading the directory contents from the filesystem, I prefer to abide by the principle that input …
> [7.1.0] Traverse symlinks to directories while collecting a TreeArtifactValue.

- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
- src/main/java/com/google/devtools/build/lib/exec/ExpandedSpawnLogContext.java
- src/main/java/com/google/devtools/build/lib/exec/SpawnLogContext.java
- src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java
https://github.com/bazelbuild/bazel/commit/9fd9aa57c456f5324383528c4094995f19124889 was a little too conservative: it didn't account for inputs/outputs declared as a file but materialized as a directory, which are still permitted by --noincompatible_disallow_unsound_directory_outputs.
Also fall back to the filesystem if input metadata isn't available to make the determination. This shouldn't happen most of the time, as metadata should already be available for most inputs, but there are some hard-to-fix edge cases where it doesn't hold.
PiperOrigin-RevId: 608584354
Change-Id: If9a4c6df4319ef66f487068dd89b382eea1b425e
> [7.1.0] Correctly handle file inputs/outputs with directory contents in the execution log.

- src/main/java/com/google/devtools/build/lib/remote/UploadManifest.java
- src/main/java/com/google/devtools/build/lib/remote/util/DigestUtil.java
Similar in spirit to https://github.com/bazelbuild/bazel/commit/bb8031989397633326520720013f23eff91d8a42. DigestUtil wraps DigestUtils, trading in Digests instead of byte arrays.
There are probably other callsites that would benefit from the optimization, but I'm focused on UploadManifest at the moment.
PiperOrigin-RevId: 607695005
Change-Id: Iaa9b1f07b26f05482cb6f3fe8dfaacf50e0c07f5
> [7.1.0] Avoid a superfluous stat() in DigestUtil.

- src/main/java/com/google/devtools/build/lib/authandtls/AuthAndTLSOptions.java
- src/main/java/com/google/devtools/build/lib/authandtls/GoogleAuthUtils.java
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/BUILD
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialCacheExpiry.java
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelperCredentials.java
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialModule.java
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/GetCredentialsResponse.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/test/java/com/google/devtools/build/lib/authandtls/credentialhelper/GetCredentialsResponseTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteModuleTest.java
This was recently specified in https://github.com/EngFlow/credential-helper-spec/pull/2.
RELNOTES[NEW]: Bazel now respects `expires` from Credential Helpers.
Closes #21249.
PiperOrigin-RevId: 608208538
Change-Id: Id168f654093c7491a40364e3988af66ad1767443
> [7.1.0] [credentialhelper] Respect `expires` field from helper

- src/main/java/com/google/devtools/build/lib/authandtls/AuthAndTLSOptions.java
Arguably, we should have a dedicated page for this on `bazel.build`, but until we have that, this post seems like a better source for users than the original design doc.
Closes #21382.
Commit https://github.com/bazelbuild/bazel/commit/f1b02a2c5ccad0451e35f3c73bd57b8508bd63c7
PiperOrigin-RevId: 608747673
Change-Id: Iaca0dc8364a6d622f685bdd53eea54068c4ea94c
> [7.1.0] [credentialhelper] Update flag doc to point to more convenient usage instructions

- src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
- src/main/java/com/google/devtools/build/lib/unix/NativePosixFiles.java
- src/main/java/com/google/devtools/build/lib/vfs/Dirent.java
- src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteActionFileSystemTest.java
- src/test/java/com/google/devtools/build/lib/unix/UnixFileSystemTest.java
- src/test/java/com/google/devtools/build/lib/vfs/FileSystemTest.java
Also add some tests to verify that all filesystem implementations follow the readdir spec. (RemoteActionFileSystemTest needs its own because it doesn't inherit from FileSystemTest. UnixFileSystemTest needs its own because it's the only implementation supporting special files.)
PiperOrigin-RevId: 608529008
Change-Id: I73dbbe8f218779b76d8879f4d4f5dfb228835157
> [7.1.0] Clarify the meaning of Dirent.Type.UNKNOWN.

- src/main/java/com/google/devtools/build/lib/skyframe/TreeArtifactValue.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactBuildTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactValueTest.java
As discussed in https://github.com/bazelbuild/bazel/issues/20891, the restriction is pointless, as it can already be bypassed with an absolute symlink. Note that the symlinks are still required not to dangle in all cases.
Also rename and reorganize the tests in TreeArtifactBuildTest in a more logical manner.
Fixes https://github.com/bazelbuild/bazel/issues/20891.
Closes #21263.
Commit https://github.com/bazelbuild/bazel/commit/5506a0fa81c8f122ee635f9866d891ac885051ef
PiperOrigin-RevId: 608926604
Change-Id: I967a383b9891360700f868abd5c2d292e0e7974e
> [7.1.0] Remove the restriction that relative symlinks in a tree artifact may not point outside the tree.

- src/main/java/com/google/devtools/build/lib/actions/AbstractAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/PathMappers.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/StrippingPathMapper.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileAction.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileAction.java
- src/test/shell/integration/config_stripped_outputs_test.sh
Rollforward of fd196bf03f4301cc3fbfc307570637f4de71c82c, which was rolled back in f5d76b1777ce861a7e551342fe25363517d53ff5.
The analysis-time memory regression (newly retained `NestedSet` instances) has been resolved separately in 31fae9e8e6687cbaf0dfe55a466696210c80be96. The execution-time memory regression (unconditionally flattened `NestedSet`s) is now only incurred with path mapping enabled.
Original description:
`JavaHeaderCompileAction` can apply an optimization where it compiles the source files only against direct dependencies, making use of the fact that Turbine includes sufficient information about transitive dependencies into the direct header jars in a special directory.
In order to ensure that downstream consumers of header compilation action can use its `.jdeps` file …
> [7.1.0] Reland "Also path map transitive header jar paths with direct classpath optimization"

- src/main/java/com/google/devtools/build/lib/analysis/actions/PathMappers.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompilationHelper.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileAction.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileAction.java
- src/main/java/com/google/devtools/build/lib/rules/java/ResourceJarActionBuilder.java
By removing Java rules from the hard-coded mnemonics allowlist for path mapping, users can rely on `--modify_execution_info` to selectively disable path mapping for them just like for Starlark actions.
This requires fixing two minor inconsistencies in how execution info is populated for Java actions:
* In `JavaCompilationHelper`, `buildKeepingLast` is used instead of `buildOrThrow` to prevent a crash when a target sets `supports-path-mapping` via `tags`.
* In `JavaHeaderCompileAction`, `--experimental_inmemory_jdeps_files` no longer causes all other execution info to be lost.
Fixes #21092
Closes #21093.
Commit https://github.com/bazelbuild/bazel/commit/f8337c754c8c1b27b34b84cde2c608c802266e96
PiperOrigin-RevId: 609064092
Change-Id: I6803e34a6861f19d185542e707b00029ee018a0a
> [7.1.0] Use execution info instead of hard-coded mnemonics for Java path mapping

- src/main/java/com/google/devtools/build/lib/remote/BUILD
- src/main/java/com/google/devtools/build/lib/remote/Scrubber.java
- src/main/java/com/google/devtools/build/lib/remote/merkletree/DirectoryTreeBuilder.java
- src/test/java/com/google/devtools/build/lib/remote/ScrubberTest.java
For runfiles, the effective path differs from the one reported by the ActionInput, and could even be in a different configuration prefix (e.g., an input bazel-out/xxx/foo may appear in a runfiles tree at bazel-out/yyy/bar.runfiles/foo).
This is a more general version of https://github.com/bazelbuild/bazel/pull/20926.
Fixes https://github.com/bazelbuild/bazel/pull/20926.
PiperOrigin-RevId: 609327629
Change-Id: I8ff2eef626835f012091045a7a4adad52877c7e4
> [7.1.0] Always decide whether to scrub an input by its effective path.

- scripts/ci/build.sh
Commit https://github.com/bazelbuild/bazel/commit/748e18a66e91b9344df00f2f017bba64a400b2c6
PiperOrigin-RevId: 609523222
Change-Id: I34b6ae7d497b69f64f80a54614a52fcf321d47e6
> [7.1.0] Set RC branch when creating GitHub releases

- MODULE.bazel.lock
- src/tools/bzlmod/utils.bzl
If `get_canonical_repo_name` no longer returns the repo name with version due to containing https://github.com/bazelbuild/bazel/commit/a54a393d209ab9c8cf5e80b2a0ef092196c17df3, the `_module_repo_name` should not either.
Fixes: https://github.com/bazelbuild/bazel/issues/21292
Closes #21324.
PiperOrigin-RevId: 606646238
Change-Id: I8835a84842c2c66929586b39156eb9f5a541652f
> Fixes _module_repo_name when building with Bazel@HEAD or Bazel 7.1

- src/main/java/com/google/devtools/build/lib/bazel/commands/VendorCommand.java
- src/test/py/bazel/bzlmod/bazel_vendor_test.py
If a repo is already vendored & up-to-date, we shouldn't vendor it again. As it may not exist under the external cache and this causes vendoring to fail.
PiperOrigin-RevId: 609728367
Change-Id: I5d0df83f254e860110a734270e25f8ce2193e437
> [7.1.0] Fix vendor existing repo

- src/test/py/bazel/bazel_windows_test.py
- tools/test/windows/tw.cc
This was an oversight from when exporting BAZEL_TEST on Linux.
fixes: https://github.com/bazelbuild/bazel/issues/21420
Closes #21444.
Commit https://github.com/bazelbuild/bazel/commit/0a9d61206cbd2d6e6a070b612cb3e9c4b4838aad
PiperOrigin-RevId: 610338496
Change-Id: Icbbdc42b6ea92a2de2b0c558aea47a24493c9d8a
> [7.1.0] [test][windows] Export BAZEL_TEST=1 on windows

- src/main/java/com/google/devtools/build/lib/rules/android/AarImport.java
- src/main/java/com/google/devtools/build/lib/rules/android/AarImportBaseRule.java
- src/test/shell/bazel/android/aar_integration_test.sh
- src/test/shell/bazel/android/android_sdk_integration_test.sh
Fixes #21225
Commit https://github.com/bazelbuild/bazel/commit/1e77944386a6c8a5fbdde6738be43859decfd19e
PiperOrigin-RevId: 610551472
Change-Id: I7e62919dd41d0d4e2b923df1942920162f554809
> [7.1.0] Enable aar_import JNI libs to work with --android_platforms.

- src/main/java/com/google/devtools/build/lib/bazel/rules/genrule/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/rules/genrule/BazelGenRule.java
- src/main/java/com/google/devtools/build/lib/bazel/rules/genrule/BazelGenRuleRule.java
- src/main/java/com/google/devtools/build/lib/rules/genrule/GenRuleBase.java
- src/test/java/com/google/devtools/build/lib/bazel/rules/genrule/GenRuleConfiguredTargetTest.java
Genrule does not support conditional stamping based on the value of the `--stamp` flag. This is because genrule treats the `stamp` attribute as `boolean`, while all other rules use the `tristate` type. After this change, the stamp attribute in genrule can be set to `-1` to request conditional stamping.
RELNOTES: `genrule` now supports setting `stamp = -1` to request conditional stamping (based on the value of the build's `--stamp` flag).
Closes https://github.com/bazelbuild/bazel/pull/21407.
Commit https://github.com/bazelbuild/bazel/commit/cb901b71b4beb57b263bcb5551d0d45afc2e38c5, https://github.com/bazelbuild/bazel/commit/ee57d991ccb56b78e8af0185f266e9a39554b1d4
PiperOrigin-RevId: 609085052
Change-Id: I873941e9aaae3760a545c1900cd13cb60a9ada39
> [7.1.0] Fix genrule autostamping in bazel

- BUILD
- src/test/shell/bazel/bazel_test_test.sh
Bazel cannot reach to bcr.bazel.build from a ipv4 only machine with --host_jvm_args=-Djava.net.preferIPv6Addresses=true set. Our GCP VMs are ipv4 only and we recently enabled ipv6 for bcr.bazel.build.
Related https://github.com/bazelbuild/bazel/issues/21525
PiperOrigin-RevId: 611465054
Change-Id: I0c3d144d12ab167a18075e6719ff8597161798d1
> [7.1.0] Remove --host_jvm_args=-Djava.net.preferIPv6Addresses=true

- src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java
- src/test/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloaderTest.java
Related to https://github.com/bazelbuild/bazel/issues/17829 and https://github.com/bazelbuild/bazel/commit/2697e0c7d798184cf80f8a5c16db3f0022d63256
I don't love this design but according to the Remote Asset API spec, this is an intended use of qualifiers: https://docs.google.com/document/d/10ari9WtTTSv9bqB_UU-oe2gBtaAA7HyQgkpP-RFP80c/edit#heading=h.sixrlhdnkfoa.
cc @Wyverald @jmillikin
Closes #21490.
Commit https://github.com/bazelbuild/bazel/commit/2195baabe7fc23be325d12159606e63e739b0ced
PiperOrigin-RevId: 610688317
Change-Id: I272f63a6bc4ea432503003ee907ca012f6d641cf
> [7.1.0] Passthrough HTTP headers to remote downloader service

- src/main/java/com/google/devtools/build/lib/runtime/CommandLinePathFactory.java
This allows us to ship built-in credential helpers (e.g., for `.netrc`) and move them out of Bazel core.
Closes #21419.
Commit https://github.com/bazelbuild/bazel/commit/ed5d444ed447061d7ef9e44c5a9a6da047486159
PiperOrigin-RevId: 611551189
Change-Id: I89c036ef87d4a1eac11c2eff5076e7884d274bb9
> [7.1.0] [credentialhelper] Support paths relative to `%install_base%`

- src/main/java/com/google/devtools/build/lib/rules/cpp/LibrariesToLinkCollector.java
Fixes #19696
Allow automatic linkage of DLL libraries when GNU toolchain used in Windows. .dll suffix has to be stripped before passing library name to `ld.exe` with `-l` option.
This [case](https://github.com/vvviktor/bazel_sandbox.git) was successfully tested :
Workspace structure:
```
D:.
│   .bazelrc
│   BUILD
│   MODULE.bazel
│   MODULE.bazel.lock
│   WORKSPACE
│
├───Main
│       BUILD
│       main.cpp
│       math.cpp
│       math.h
│       math_dll_interface.cpp
│       math_dll_interface.h
│       math_import_defs.h
│
└───toolchain
BUILD
toolchain_config.bzl
```
BUILD file:
```
DLL_HDRS = ["math_import_defs.h", "math_dll_interface.h"]
cc_binary(
name = "sum_numbers_mingw",
srcs = ["main.cpp"],
deps = [":math_d_shared"]
)
cc_import(
name = "math_d_shared",
hdrs = DLL_HDRS, …
```
> [7.1.0] Update LibrariesToLinkCollector.java for .dll suffix stripping

- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteModuleTest.java
Arguably a better fix would be for every test case to properly dispose of the RemoteModule via afterCommand() and making sure that the leak is stopped there. Leave a TODO accordingly.
PiperOrigin-RevId: 612417631
Change-Id: I2d6e6e94b405eb777a884c6e10f9d3f9a086fffc
> [7.1.0] Fix a flaky test by avoiding leaking the eager capability RPC thread.

- src/main/java/com/google/devtools/build/lib/remote/RemoteCacheClientFactory.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheClient.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteCacheClientFactoryTest.java
- src/test/java/com/google/devtools/build/lib/remote/disk/BUILD
- src/test/java/com/google/devtools/build/lib/remote/disk/DiskCacheClientTest.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/OnDiskBlobStoreCache.java
So that disk cache uploads or downloads that are collectively waited upon can make progress concurrently instead of sequentially. This provides a significant performance boost for actions that download or upload a large number of files.
PiperOrigin-RevId: 612432619
Change-Id: Id4e88b239a5475c49aecb1219045b047c9f5c319
> [7.1.0] Move the disk cache reads and writes into a thread pool.

- src/main/java/com/google/devtools/build/lib/remote/common/LazyFileInputStream.java
- src/main/java/com/google/devtools/build/lib/remote/common/LazyFileOutputStream.java
- src/main/java/com/google/devtools/build/lib/remote/http/HttpCacheClient.java
This reduces the chance of running out of file descriptors when uploading a large number of files simultaneously.
PiperOrigin-RevId: 612410120
Change-Id: I2573c26e60042a5867e7d23748fcb8d74ebe7e68
> [7.1.0] Lazily open files to be uploaded to an HTTP cache.

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
Related: https://github.com/bazelbuild/bazel/issues/20013
Commit https://github.com/bazelbuild/bazel/commit/5b4ba3e9b5a3d2532e96812ed7f1fd87c263a467
PiperOrigin-RevId: 585046630
Change-Id: Ifdf098e7d54c1d5dca85a39afd7694dc828331a4
> [7.1.0] StarlarkBaseExternalContext.java: propagate error message when deleting temporary directory failed

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepoRecordedInput.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContextTest.java
- src/test/shell/bazel/starlark_repository_test.sh
Watching a path in an undefined repo (eg. `$output_base/external/i_am_undefined/blah`) currently causes an NPE because we expect it to need a skyframe restart when it actually doesn't. The underlying reason is rather convoluted, but the gist is that we request `RepositoryDirectoryValue.Key(@@i_am_undefined)` explicitly, when we don't actually have to -- we can simply use `FileValue.Key($output_base/external/i_am_undefined/blah` directly, and rely on the fact that `FileFunction` knows to request the corresponding `RepositoryDirectoryValue` and behave appropriately when the repo is undefined. (This is due to logic in `ExternalFilesHelper.maybeHandleExternalFile`.)
Additionally, this PR removes the `rctx.symlink(watch_target=)` parameter. The symlink target's existence and its contents …
> [7.1.0] Fix watching paths in undefined repos in repo rules

- src/main/java/com/google/devtools/build/lib/analysis/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/CommonPrerequisiteValidator.java
- src/main/java/com/google/devtools/build/lib/analysis/RuleContext.java
- src/test/java/com/google/devtools/build/lib/analysis/VisibilityTest.java
Fixes: []
Commit https://github.com/bazelbuild/bazel/commit/f4c9c88bae15b1586f13412c72160d057ad98971
PiperOrigin-RevId: 612579829
Change-Id: I429ca24931482cc94543692532ea4c08692020e3
> [7.1.0] Implicit dependencies should be visible to rule/aspect definitions in `.bzl` files in the same package

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
Related: https://github.com/bazelbuild/bazel/issues/21593
PiperOrigin-RevId: 613199006
Change-Id: Id2ff16950a666545437fa9d6044f7c798cbf6ad2
> [7.1.0] Disable some tests because of JDK21

- src/main/java/com/google/devtools/build/lib/rules/android/ApkInfo.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/android/AndroidBootstrap.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/android/ApkInfoApi.java
Commit https://github.com/bazelbuild/bazel/commit/067b0ea5e3893fbd580aa8a76d6a78ad242e3dba
PiperOrigin-RevId: 579971552
Change-Id: I8de99d8875ee3cdd6bbd56d4b931377657fa33e2
> [7.1.0] Expose the ApkInfo provider constructor to Starlark.

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
The stacktrace in https://github.com/bazelbuild/bazel/issues/21478 suggests that the second `workerFuture.get()` (line 183 before) is snagging on a `CancellationException`. Closer inspection indicates that the exception handling in this entire block of code is just faulty -- one, `workerFuture.get()` on line 169 is very unlikely to throw an `InterruptedException` because this call happens after we've received a `DONE` from the signal queue, which is at the very end of the worker thread logic (in its own `finally` clause, actually); two, the second call to `workerFuture.get()` on line 183 doesn't actually do anything because `get()`-ing a cancelled future would just throw a `CancellationException` immediately.
This CL attempts to fix these two glaring errors. It now tries to handle …
> [7.1.0] Attempt to fix cancellation crash in repo fetching w/ worker thread

- src/main/java/com/google/devtools/build/lib/bazel/commands/ModCommand.java
- src/test/py/bazel/bzlmod/mod_command_test.py
Buildozer has a non-zero exit code if it didn't make any changes.
Work towards #21651
Closes #21657.
Commit https://github.com/bazelbuild/bazel/commit/98f29db0ac47b4b3c75bccdcfda20ffd50521597
PiperOrigin-RevId: 615184752
Change-Id: Ib89928974e2cd014cec968193d35fd74e2d01261
> [7.1.1] Fix `bazel mod tidy` failure with no changes

- src/main/starlark/builtins_bzl/common/java/java_toolchain.bzl
Work towards #21604
Closes #21610.
Commit https://github.com/bazelbuild/bazel/commit/061ddebac2511f78dcd77fa5e76b72ffe6727949
PiperOrigin-RevId: 613912980
Change-Id: Ibc620120b783c990d08b84ea6cd8ae224333ed8a
> [7.1.1] Let native Turbine image find `ct.sym` with non-hermetic `java_runtime`

- src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
This was the original intent in https://github.com/bazelbuild/bazel/commit/9eb3b0a340c620a8bbcfa930bf4711ec64686099.
PiperOrigin-RevId: 614986613
Change-Id: I356788d82a6d36a7a465a1bb828e4074aad11385
> [7.1.1] Actually use shouldPublish() to determine whether to publish the execution log to the BEP.

- src/test/java/com/google/devtools/build/lib/actions/ActionOutputDirectoryHelperTest.java
Failure to do causes a flaky test failure when simulating an IOException while the `knownDirectories` cache is disabled. The reason is that `ActionOutputDirectoryHelper#forceCreateDirectoryAndParents` calls either `createDirectory` or `createWritableDirectory`, depending on whether the parent directory is in the cache or not. However, "disabling" the cache sets its size to zero, which doesn't prevent insertion; rather, it causes inserted entries to be almost immediately deleted by a background thread. Thus, if only one of `createDirectory` and `createWritableDirectory` throws, the test outcome depends on how fast the background thread runs.
(We could make the zero-sized cache an actual no-op, but it's unlikely that anyone would want to set it to zero outside of test code, so it's not …
> [7.1.1] Also inject a failure for createWritableDirectory when testing that ActionOutputDirectoryHelper propagates exceptions.

- src/main/java/com/google/devtools/build/lib/sandbox/SandboxStash.java
Attempts to address NPE reported in: https://github.com/bazelbuild/bazel-skylib/issues/488#event-11993414211 and https://github.com/bazelbuild/bazel/issues/21665#issuecomment-1993967297
The `put()` call to the runfiles dir map is placed before the call that stashes the corresponding directory to address the race condition described here: https://github.com/bazelbuild/bazel-skylib/issues/488#issuecomment-1964209720.
The exception will now log:
- entries in the runfiles dir map
- environment variables
- stashes on disk
Closes #21668.
Commit https://github.com/bazelbuild/bazel/commit/59dbf7a146a6d8a8a1cbbe0946bd1367e103aef1
PiperOrigin-RevId: 615739651
Change-Id: Ida90e334d1d1f890cf204d272134726bb1f70eb9
> [7.1.1] Fix race condition and add more logging for null entry error message

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/ModuleArg.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/ModCommand.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/ModuleArgTest.java
- src/test/py/bazel/bzlmod/mod_command_test.py
Previously we enforced that the canonical repo name had to correspond to a module (i.e. not an extension-generated repo). This makes no sense, so this change simple deletes that enforcement.
To compensate for the lack of checks whether the repo exists at all, we add an additional check after requesting the BzlmodRepoRuleValues that all requested repos must exist.
Fixes https://github.com/bazelbuild/bazel/issues/21621
Commit https://github.com/bazelbuild/bazel/commit/5c2b37e56e77e9c96b1e5a6c99d803e31e17a03c
PiperOrigin-RevId: 615733963
Change-Id: Icf706b36f0e8d3c775bc26528948e5102910d4a0
> [7.1.1] Allow any canonical repo name to be used with `bazel mod show_repo`

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModTidyFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Discovery.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/InterimModule.java
- src/test/py/bazel/bzlmod/mod_command_test.py
* Fixes a crash when using a non-registry override with a specified version:
```
Caused by: java.lang.NullPointerException: null value in entry: foo=null
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54)
at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:345)
at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:454)
at com.google.devtools.build.lib.bazel.bzlmod.Module.getRepoMappingWithBazelDepsOnly(Module.java:67)
at com.google.devtools.build.lib.bazel.bzlmod.BazelDepGraphFunction.getExtensionUsagesById(BazelDepGraphFunction.java:233)
at com.google.devtools.build.lib.bazel.bzlmod.BazelDepGraphFunction.compute(BazelDepGraphFunc …
```
> [7.1.1] Fix two `bazel mod tidy` crashes

- src/main/java/com/google/devtools/build/lib/actions/ActionAnalysisMetadata.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileAction.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileActionBuilder.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileAction.java
* [Avoid making a copy in mergeMaps if one of the input maps is empty.](https://github.com/bazelbuild/bazel/commit/3e8ee270bfc2fb6e51ea8f757d3a77afdb6044a9)
* [Add the path for in-memory jdeps files to execution info on demand instead of storing it in `JavaCompileAction` and `JavaHeaderCompileAction`.](https://github.com/bazelbuild/bazel/commit/c830f21a627b973890fcf2b53b2a4a7ee40f33bf) 
Fixes https://github.com/bazelbuild/bazel/issues/21661
> Cherry-pick Java execution info improvements

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
This tests is very flaky in postsubmit on macOS Intel machines.
https://github.com/bazelbuild/bazel/issues/21495
Commit https://github.com/bazelbuild/bazel/commit/548bf4db56696557f2d1b732c56497e8098d3565
PiperOrigin-RevId: 610376373
Change-Id: Id215898317e8b1f1485e5dbaf72e9555307b83db
> [7.1.1] Disable //src/test/shell/bazel:srcs_test on Intel macOS

- src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java
We try to clean up the sandbox base from previous server instances
asynchronously, however sometimes this is not possible due to the old
directories being in a different filesystem. This can happen with overlays on
Docker after running bazel in different RUN commands. See
https://github.com/bazelbuild/bazel/issues/21719
This change fixes the crash by catching the IOException and falling back to
synchronous deletion.
Fixes #21719.
RELNOTES:none
Commit https://github.com/bazelbuild/bazel/commit/488b63072687899bdf7607bce949c47097fcd545
PiperOrigin-RevId: 617150522
Change-Id: I82a07ac0ade66cfb1e5732a90a5f3ab4e2e8caa7
> [7.1.1] Fix sandbox cleanup crashing after server restart

- src/main/java/com/google/devtools/build/lib/bazel/Bazel.java
So that the profile includes time spent in the beforeCommand for other modules.
PiperOrigin-RevId: 613582228
Change-Id: I9e8d0e7712005ad408346ce0a852b9e5ac313193
> [7.2.0] Register CommandProfilerModule early.

- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java
which accept an endpoint pointing to the local output service daemon.
Since the feature is still WIP, Bazel exits and prints an error if this flag is set.
Closes #21649.
PiperOrigin-RevId: 615357528
Change-Id: Ie4cc3a1636b1cf0e710d23883f6bb7b22de7d6c3
> [7.2.0] Add --experimental_remote_output_service flag

- src/main/starlark/builtins_bzl/bazel/java/bazel_java_binary_deploy_jar.bzl
- src/main/starlark/builtins_bzl/common/java/java_binary.bzl
- src/main/starlark/builtins_bzl/common/java/java_binary_deploy_jar.bzl
- src/test/shell/integration/java_integration_test.sh
This contains two commits
1) Do not add the runfiles middleman to the inputs of the deploy jar action.
Before https://github.com/bazelbuild/bazel/commit/a6d839d0d0c602bca94fe8b4ed0b208564db4fcf, it was useless because it did not actually make the runfiles appear on the inputs of the action. After that change, it does, thereby adding a large number of unnecessary inputs to the deploy jar actios (unnecessary because they worked before https://github.com/bazelbuild/bazel/commit/a6d839d0d0c602bca94fe8b4ed0b208564db4fcf...)
PiperOrigin-RevId: 603638505
Change-Id: I1a9d59e361fcad3c6cf4362b4251fd03dd521e22
Commit https://github.com/bazelbuild/bazel/commit/6a4d61ebf2dc2214ffe6abc807e4f597175e1a6c
2) Do not build the runfiles tree when creating deploy jars.
I missed this from …
> [7.2.0] java_binary: superfluous dependency on MANIFEST from runfiles

- site/en/remote/output-directories.md
- src/main/cpp/blaze_util_bsd.cc
- src/main/cpp/blaze_util_linux.cc
- src/test/cpp/startup_options_test.cc
It may well be that $HOME is on a read-only mount. In this case, it is the
convention in the Linux and BSD world that $XDG_CACHE_HOME points to an
appropriate writable location.
Fixes https://github.com/bazelbuild/bazel/issues/16937
RELNOTES: Bazel on Linux and BSD now respects the XDG_CACHE_HOME environment
variable instead of assuming that ~/.cache/bazel is writable.
PiperOrigin-RevId: 614772057
Change-Id: I6377d7a90fb929843d18e82f5ed3d0adc55ac5c6
Commit 05ae91f1a04b55af94aaa7b52ef34cb3a6ce7fa4
> [7.2.0] Respect $XDG_CACHE_HOME if available for Bazel's output root on Linux and BSD

- src/main/cpp/blaze_util_linux.cc
- src/main/cpp/startup_options.cc
- src/test/cpp/BUILD
- src/test/cpp/startup_options_test.cc
The Bazel server pre-processes the output root via PathFragmentConverter,
which absolutizes paths and expands leading "~" as the home directory. This
can cause the server and the client to treat different directories as output
root, leading to a server crash.
Thus, the client must make the output root absolute. We already do so when
the output root derives from $TEST_TMPDIR (without tilde expansion) in
StartupOptions::StartupOptions. And we do so (with tilde expansion, for
legacy reasons) when the output root derives from the --output_user_root
startup flag passed to the client, see StartupOptions::ProcessArg.
We must do the same when the output root derives from $HOME or
$XDG_CACHE_HOME - without tilde expansion, since it's generally expected
that tools do not perform tilde expansion on …
> [7.2.0] Ensure output root is an absolute path even if $HOME or $XDG_CACHE_HOME are relative

- src/main/cpp/blaze_util_bsd.cc
- src/main/cpp/blaze_util_linux.cc
Capture the exit code of this syscall and terminate Bazel accordingly. Otherwise, an incorrect value will be used as the time.
Closes #21246.
PiperOrigin-RevId: 611531510
Change-Id: I4b5f755d7292eafcf8eab882482d9dbc2d85d8d0
Commit https://github.com/bazelbuild/bazel/commit/5c8c4e9bf6c8213bb40ad211d0419d6b0feccc4b
> [7.2.0] cpp/blaze_util: handle clock_gettime failure

- MODULE.bazel.lock
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GsonTypeAdapterUtil.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/LockFileModuleExtension.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionUsage.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/test/tools/bzlmod/MODULE.bazel.lock
Prepare for the removal of the extension usages section of the lockfile by storing the usages fed into each extension as a hash.
Implements part of https://docs.google.com/document/d/1TjA7-M5njkI1F38IC0pm305S9EOmxcUwaCIvaSmansg/edit
Work towards #20369
Closes #21408.
PiperOrigin-RevId: 620014723
Change-Id: Ie781cee702ec4071710ba47a8635e0b039ea28e8
Commit https://github.com/bazelbuild/bazel/commit/87b53ab927f9a8e4b88b7fea00df5d21d28b42be
> [7.2.0] Store usages hash in module extension lockfile entries

- src/main/java/com/google/devtools/build/lib/bazel/repository/cache/RepositoryCache.java
- src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
- src/main/java/com/google/devtools/build/lib/vfs/FileSystemUtils.java
- src/main/java/com/google/devtools/build/lib/vfs/JavaIoFileSystem.java
- src/main/java/com/google/devtools/build/lib/vfs/Path.java
- src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java
- src/test/shell/bazel/starlark_repository_test.sh
This requires making the implementation of `renameTo` in `JavaIoFileSystem` and `WindowsFileSystem` atomic.
Fixes https://github.com/bazelbuild/bazel/issues/21823
Closes #21779.
PiperOrigin-RevId: 620719510
Change-Id: Id3ff4baa56c6ef693196e8268614b483713542a5
Commit https://github.com/bazelbuild/bazel/commit/753dc9750714af581147f6aa338adeb07a9dcb57
> [7.2.0] Make `RepositoryCache#put` resistant to concurrent file system operations

- src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java
- src/main/java/com/google/devtools/build/lib/skyframe/TreeArtifactValue.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteActionFileSystemTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStoreTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactBuildTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactValueTest.java
This improves the error message for a tree artifact containing a dangling symlink, which regressed in https://github.com/bazelbuild/bazel/commit/4247c20f1daeeb787e9b5cb64848d398467effb1 (see https://github.com/bazelbuild/bazel/issues/15454#issuecomment-2011456094).
PiperOrigin-RevId: 617870632
Change-Id: I6847084a52b1e4bb7d8a9384ad6cd5d015dddf1b
Commit https://github.com/bazelbuild/bazel/commit/b78d73fab1f01e2e8ae29bed667865a42800b626
> [7.1.2] Implement RemoteActionFileSystem#statIfFound correctly when the path cannot be canonicalized

- src/test/py/bazel/bzlmod/bazel_fetch_test.py
- src/test/py/bazel/bzlmod/bazel_lockfile_test.py
- src/test/py/bazel/bzlmod/bazel_module_test.py
- src/test/py/bazel/bzlmod/bazel_overrides_test.py
- src/test/py/bazel/bzlmod/bazel_repo_mapping_test.py
- src/test/py/bazel/bzlmod/bazel_vendor_test.py
- src/test/py/bazel/bzlmod/bazel_yanked_versions_test.py
- src/test/py/bazel/bzlmod/bzlmod_query_test.py
- src/test/py/bazel/bzlmod/external_repo_completion_test.py
- src/test/py/bazel/bzlmod/mod_command_test.py
- src/test/py/bazel/bzlmod/test_utils.py
This is in preparation for tracking the hashes of remote (non-`file:` URL) files in the lockfile. If the tests use local registries, they wouldn't be representative of the default situation.
Work towards #20369
Closes #21906.
PiperOrigin-RevId: 622290283
Change-Id: Ibe825d2bede84c1b0672dbb699aaf3ee5168a813
Commit https://github.com/bazelbuild/bazel/commit/3f9d80c35d88a280c2d53682f3d201b4733a3fff
> [7.2.0] Use an HTTP registry in Bzlmod tests

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
If `--experimental_remote_output_service` is set, Bazel issue StageArtifacts RPC to the output service after hitting the remote cache or executing action remotely.
Working towards https://github.com/bazelbuild/bazel/issues/21630.
Closes #21746.
PiperOrigin-RevId: 617834441
Change-Id: I85fb544a69d0ca779a793038ff0e6a4b755dd637
Commit https://github.com/bazelbuild/bazel/commit/4484f86ca43a874d5a28e59e6a1ecc77c6249ae3
> [7.2.0] Implement StageArtifacts

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
If `--experimental_remote_output_service` is set, Bazel issues a FinalizeArtifacts RPC to the output service after an action has been executed.
Working towards https://github.com/bazelbuild/bazel/issues/21630.
Closes #21759.
PiperOrigin-RevId: 618190373
Change-Id: I8ed981fcea7ebe146de0b1c48b1933392c86253f
Commit https://github.com/bazelbuild/bazel/commit/586bd13179636350a2d0f156dc95a4acc820bae2
> [7.2.0] Implement FinalizeArtifacts

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java
- src/main/java/com/google/devtools/build/lib/vfs/OutputService.java
- src/main/java/com/google/devtools/build/lib/vfs/XattrProvider.java
- src/test/java/com/google/devtools/build/lib/skyframe/OutputsInvalidationIntegrationTest.java
If `--experimental_remote_output_service` is set, a `XattrProvider` which uses `BatchStat` RPC to get the digest of a file will be used for Bazel to get digests for outputs.
Working towards https://github.com/bazelbuild/bazel/issues/21630.
Closes #21812.
PiperOrigin-RevId: 619539349
Change-Id: I71364e78c45c37e834c71e120a109c8de602db77
Commit https://github.com/bazelbuild/bazel/commit/30aa5d0e7e5782703b4ac1fd980fb6cabd408c3c
> [7.2.0] Implement XattrProvider which uses BatchStat to getFastDigest

- src/main/java/net/starlark/java/eval/MethodLibrary.java
- src/test/java/net/starlark/java/eval/testdata/min_max.star
- src/test/java/net/starlark/java/eval/testdata/sorted.star
This is required by the language spec, but was not implemented in Bazel.
See https://github.com/bazelbuild/starlark/blob/master/spec.md#max
Fixes https://github.com/bazelbuild/bazel/issues/15022
Also take the opportunity to adjust sorted's signature for `key` to match.
RELNOTES: Starlark `min` and `max` buitins now allow a `key` callback,
similarly to `sorted`.
PiperOrigin-RevId: 623547043
Change-Id: I71d44aa715793f9f2260f9b20b876694154ff352
Commit https://github.com/bazelbuild/bazel/commit/cf666726d0f8d1e8a3fed504810f80969dee4a4b
> [7.2.0] Support `key` callback in Starlark min/max builtins

- src/main/java/com/google/devtools/build/lib/rules/objc/XcodeConfig.java
Context: https://bazelbuild.slack.com/archives/C014RARENH0/p1709547684815279?thread_ts=1709324251.252319&cid=C014RARENH0
Closes #21938.
PiperOrigin-RevId: 623421163
Change-Id: I450b1b1e3b3c0544b391e571911f62f0709aa62c (cherry picked from commit c8fcfd4b412a10268040127ea2854ed8db23d451)
> [7.2.0] Improve unavailable Xcode message for Bzlmod

- src/main/java/net/starlark/java/eval/MethodLibrary.java
- src/test/java/net/starlark/java/eval/MethodLibraryTest.java
The argument was already available on 'print' and is necessary for full control over the formatting of error messages that rely on StarlarkValue's `debugPrint`.
Work towards #20486
Closes #21961.
PiperOrigin-RevId: 625022818
Change-Id: I895b5844d8543f936fc31d367b12bc6291a10bf8
Commit https://github.com/bazelbuild/bazel/commit/6b2e0db0a5ec6c3e56551195611abe1d1510b06d
> [7.2.0] Add `sep` keyword argument to `fail`

- src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD
- src/main/java/com/google/devtools/build/lib/starlarkdebug/proto/BUILD
This makes the build event stream and starlark debugging proto libraries public. This is for consumption by the vscode-bazel plugin, which already uses these but in a very hacky way.
Fixes #16335
Fixes #3684
Closes #21196.
PiperOrigin-RevId: 623740758
Change-Id: Ic47d6dd05fcf2af8beec4d9212d4c7fd65bcda44
Commit https://github.com/bazelbuild/bazel/commit/adfe016581150395b46248ac6c3b7f8ccc092226
> [7.2.0] Expose build event stream and starlark debugging protos

- site/en/install/compile-source.md
Fixes #21821.
PiperOrigin-RevId: 625316799
Change-Id: I2691b0304a80af483d2630491064371783f65422
Commit https://github.com/bazelbuild/bazel/commit/d1cecc8507f635eff74a441711f292ae9b515274
> [7.2.0] Update compile-source.md with JDK21 requirements.

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/ModuleArg.java
- src/test/py/bazel/bzlmod/mod_command_test.py
Fixes https://github.com/bazelbuild/bazel/issues/21621#issuecomment-2058607125
PiperOrigin-RevId: 625286656
Change-Id: Ibc5d153af96912de39b146e50f081030d1da7257
Commit https://github.com/bazelbuild/bazel/commit/2d54af169478a42d84d9551fab4b31852e0e85c3
> [7.2.0] Fix `resolveToModuleKeys` when checking module extension

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/YankedVersionsFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/YankedVersionsUtil.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/YankedVersionsValue.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyFunctions.java
- src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisMock.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodRepoRuleFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/DiscoveryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorTest.java
Ensures that yanked version information is only downloaded once per module name, which reduces the number of files fetched during module resolution. On my machine, this reduces `bazel mod deps` runtime on Bazel itself by ~15%.
This also prepares for storing yanked version information in the lockfile.
Work towards https://github.com/bazelbuild/bazel/issues/20369
Closes #21909.
PiperOrigin-RevId: 625617556
Change-Id: Ie4184def3b868470f93d584bbbbd7f704e1e9a82
Commit https://github.com/bazelbuild/bazel/commit/3052eff5d62b4c173265af471e3072a0433dda96
> [7.2.0] Extract yanked versions into a SkyFunction

- MODULE.bazel.lock
- src/test/tools/bzlmod/MODULE.bazel.lock
- tools/build_defs/repo/http.bzl
Fixes https://github.com/bazelbuild/bazel/issues/21885
PiperOrigin-RevId: 625651940
Change-Id: Id8a29c429e3b283dd0e2eecd1e13c023f0feb357
Commit https://github.com/bazelbuild/bazel/commit/445dfab8fdd7671fe6206ea938ef119c228019f0
> [7.2.0] http repo rules: Make sure netrc credentials are applied for remote patch files

- src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java
- src/test/shell/integration/sandboxing_test.sh
Whenever the sandbox base changed via --sandbox_base, the trash base used by the AsynchronousTreeDeleter wasn't being updated accordingly. If the new sandbox base was on a different filesystem (like tmpfs), new async deletions would result in the error (Invalid cross-device link) at the time of moving.
This would then trigger a precondition crash later when we checked whether everything had been deleted correctly.
PiperOrigin-RevId: 625430544
Change-Id: I1547b16bdb803eb5dcee649c9988bad73442a140
Commit https://github.com/bazelbuild/bazel/commit/dfd1763d3ece19bcbf6291fd1493c3cd07c65d46
> [7.2.0] Fix trash base not updated when sandbox_base changed

- src/test/shell/bazel/bazel_sandboxing_test.sh
- src/test/shell/integration/sandboxing_test.sh
Sandboxing tests should always run with Bazel defaults, which include no tmpfs path.
Work towards #21215
Closes #22002.
PiperOrigin-RevId: 625615279
Change-Id: If4146f04effeaabc1eb22d38cc5ac32247759c8c
Commit https://github.com/bazelbuild/bazel/commit/5086f65f1235f2ac239baa9d43e2fe6391e052e3
> [7.2.0] Clean up test setup for sandboxing tests

- src/main/java/com/google/devtools/build/lib/bazel/repository/cache/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/repository/cache/RepositoryCache.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/Checksum.java
- src/main/java/com/google/devtools/build/lib/vfs/bazel/BazelHashFunctions.java
- src/main/java/com/google/devtools/build/lib/vfs/bazel/Blake3HashFunction.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/cache/BUILD
- src/test/java/com/google/devtools/build/lib/bazel/repository/cache/RepositoryCacheTest.java
- src/test/java/com/google/devtools/build/lib/testutil/TestConstants.java
Support storing repository cache with blake3 hash function.
Closes #21998.
PiperOrigin-RevId: 625727463
Change-Id: I2198adac617c5d6301e56694fe416f3130c61033
Commit https://github.com/bazelbuild/bazel/commit/dc5ec2b09c9f9cb61e1a753b6c3837c279259bc4
> [7.2.0] RepositoryCache: add blake3 key type

- tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/LcovPrinter.java
- tools/test/CoverageOutputGenerator/javatests/com/google/devtools/coverageoutputgenerator/LcovPrinterTest.java
The calling code expects the exception, not a return boolean.
Fixes #21982.
Closes #21987.
PiperOrigin-RevId: 626086576
Change-Id: I4abd7a253715c84c323e036dfbdb2fcb94a4825d
Commit https://github.com/bazelbuild/bazel/commit/f8277cf9feebfae390b96218979a66f75693961c
> [7.2.0] Fix swallowed I/O exception in LcovPrinter

- src/main/java/com/google/devtools/build/lib/analysis/starlark/Args.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleImplementationFunctionsTest.java
When a command line item is subject to special default stringification behavior (currently, `Label` and `File` instances are), it does not suffice to fingerprint the information that computes the custom stringification; it is also necessary to track whether each individual item is subject to this special formatting. Otherwise, as demonstrated by numerous new test cases, command line items have identical fingerprints to their naive stringification, but may result in distinct command lines.
This is fixed by tracking element types via additional UUID markers, either individually or for entire `NestedSet`s based on the `Depset` type.
Closes #22025
Original commit: https://github.com/bazelbuild/bazel/commit/d8613c222f233406165c623b1a92179faed142ba
PiperOrigin-RevId: 627040284
Change-Id: …
> [7.2.0] Fix action key staleness for Args due to type confusion

- MODULE.bazel.lock
- src/MODULE.tools
- src/test/tools/bzlmod/MODULE.bazel.lock
Fixes https://github.com/bazelbuild/buildtools/pull/1263
Closes #22045.
PiperOrigin-RevId: 626307672
Change-Id: Ib088e73835ea3d7076976a9de4ab4207ff491b27
Commit https://github.com/bazelbuild/bazel/commit/7979dd6dfc56b6b61c3b6c65a806fe67c4fcd387
> [7.2.0] Update buildozer to v7.1.1.1

- src/main/java/com/google/devtools/build/lib/buildtool/AqueryProcessor.java
- src/main/java/com/google/devtools/build/lib/buildtool/CqueryProcessor.java
- src/main/java/com/google/devtools/build/lib/buildtool/PostAnalysisQueryProcessor.java
- src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java
- src/main/java/com/google/devtools/build/lib/query2/aquery/ActionGraphQueryEnvironment.java
- src/main/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryEnvironment.java
- src/test/java/com/google/devtools/build/lib/query2/aquery/ActionGraphQueryHelper.java
- src/test/java/com/google/devtools/build/lib/query2/aquery/BUILD
- src/test/java/com/google/devtools/build/lib/query2/cquery/BUILD
- src/test/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryHelper.java
- src/test/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryTest.java
- src/test/java/com/google/devtools/build/lib/query2/testutil/PostAnalysisQueryHelper.java
- src/test/java/com/google/devtools/build/lib/query2/testutil/PostAnalysisQueryTest.java
cquery acquired this behavior 4 years ago in unknown commit, but it was never ported to aquery. This fixes some potentially surprising behavior when multiple configured targets corresponding to the same label are present (see added test cases).
RELNOTES: aquery: `//foo:bar` now means "all configured targets with label `//foo:bar`" instead of "choose an arbitrary configured target with label `//foo:bar`". This is in line with cquery behavior.
PiperOrigin-RevId: 620091100
Change-Id: Ib5c5ee33e35fe7ac30bc31f703b119dec40185b7
Commit https://github.com/bazelbuild/bazel/commit/0662df0506507d872e1243c243719aeba72e6a3e
> [7.2.0] aquery: interpret "//foo:bar" as "all configured targets with label //foo:bar"

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GitOverride.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/test/py/bazel/bzlmod/bazel_overrides_test.py
Add `strip_prefix` arg go bzlmod's `git_override` and pass it down to `git_repository`.
This allows users to work with git repositories that have other Bazel modules in subdirectories.
A prime example of such is the `rules_python`](https://github.com/bazelbuild/rules_python) repo:
```
./rules_python
├── MODULE.bazel       # available on BCR as "rules_python"
└── gazelle
└── MODULE.bazel   # available on BCR as "rules_python_gazelle_plugin"
```
Fixes #22076.
RELNOTES:
bzlmod `git_repository` now accepts the `strip_prefix` arg and passes it to the underlying `git_repository` call.
Closes #22077.
PiperOrigin-RevId: 628059135
Change-Id: I8b9df3a5d41924302475fd9495aff6cd21ce6db2
Commit https://github.com/bazelbuild/bazel/commit/8edddb32dc900f6b0eb92e5f838bc48e2e8783e5
> [7.2.0] Add `strip_prefix` arg to bzlmod's `git_override`

- src/main/java/com/google/devtools/build/lib/skyframe/BUILD
- src/main/java/com/google/devtools/build/lib/skyframe/IncrementalPackageRoots.java
Consider the following scenario:
- Top level targets `A` and `B`
- To execute actions in `A`, we need to plant symlinks for `NestedSet<Package>: [A1, C1, [D1]]`,
- To execute actions in `B`, we need to plant symlinks for `NestedSet<Package>: [B1, C1, [D1]]`
In the end, we expect to see symlinks to `A1`, `B1`, `C1` and `D1`.
**What went wrong**
With the current code, there are 2 possible race conditions:
1. Transitive NestedSet level:
- Start to plant symlinks for `A`
- `NestedSet [D1]` added to `handledPackageNestedSets`. _No symlink planted yet_.
- Start to plant symlinks for `B`
- `NestedSet [D1]` seen as "handled" and immediately skipped. Planted `B1` and `C1`. `B` moves on to execution.
=> actions from `B` that requires `D1` would fail (no such file or directory).
2. Individual …
> [7.2.0] Fix a race condition in IncrementalPackageRoots.

- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java
- src/test/java/com/google/devtools/build/lib/buildtool/DirectoryArtifactWarningTest.java
Notably, CoverageReportAction is owned by ActionOwner.SYSTEM_ACTION_OWNER, which doesn't have a label.
Fixes https://github.com/bazelbuild/bazel/issues/22069.
PiperOrigin-RevId: 627373896
Change-Id: Ic69c76079245a343721437df6659584a8f3aa97a
> [7.2.0] Avoid crashing on an action owner without a label when checking for unsound directory inputs or outputs.

- src/main/java/com/google/devtools/build/lib/remote/ExperimentalGrpcRemoteExecutor.java
- src/test/java/com/google/devtools/build/lib/remote/ExperimentalGrpcRemoteExecutorTest.java
- src/test/java/com/google/devtools/build/lib/remote/FakeExecutionService.java
- src/test/java/com/google/devtools/build/lib/remote/GrpcRemoteExecutorTest.java
- src/test/java/com/google/devtools/build/lib/remote/GrpcRemoteExecutorTestBase.java
A literal StatusRuntimeException thrown from a response stream iterator (as an error response to the overall request) should have the same consideration as one thrown from the operation response unwrap.
waitExecution requires an additional check for SRE thrown directly from operation stream pop.
Existing NOT_FOUNDs that do not pass the inner retry check will similarly be passed through.
To detect this NOT_FOUND in test, the actual exception thrown as a result of thenError must be the error response from stream provided by FakeExecutionService. This corrects a number of tests which did not check for explicit exceptions and were relying on UNKNOWN SREs resulting from errors during handling, and removes numerous thenAck()s required to validate tests.
Closes #22067.
PiperOrigin-RevId: …
> [7.2.0] Handle operation stream exception in wrapper

- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java
- src/test/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloaderTest.java
- third_party/remoteapis/build/bazel/remote/asset/v1/remote_asset.proto
A follow up from https://github.com/bazelbuild/remote-apis/pull/286
Closes #21996.
PiperOrigin-RevId: 628100606
Change-Id: Ib37a013d704dcfd14556f7914d90c1393ef73d38
Commit https://github.com/bazelbuild/bazel/commit/618c0abbfe518f4e29de523a2e63ca9179050e94
Commit https://github.com/bazelbuild/bazel/commit/dcfefd9f894b0162da3781a5eeb4747dd75ffa29 (Third party changes)
> [7.2.0] Add digest func to Remote Asset Downloader

- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java
- src/test/shell/bazel/runfiles_test.sh
`SymlinkTreeUpdater` now correctly replaces symlinks with directories and vice versa in runfiles trees.
Fixes #20266
Closes #22087.
PiperOrigin-RevId: 628028591
Change-Id: Id94cea42f9cdfab001e56242a329b8d6d253ba29
Commit https://github.com/bazelbuild/bazel/commit/4b18dbe8fa1ac601bf3b85c7150d9e537a39084b
> [7.2.0] Handle file type changes with in-process symlink creation

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
`SkyframeLookupResult#get` can return `null` even if `env.valuesMissing()` is `false`.
Closes #22152.
PiperOrigin-RevId: 629099024
Change-Id: I54e675ce7bdf012d966308fb60d99e9b04e2d75f
Commit https://github.com/bazelbuild/bazel/commit/dacfd9c01b9b0376c8009bed74656755daf16905
> [7.2.0] Fix potential NPE in ModuleFileFunction

- src/tools/android/java/com/google/devtools/build/android/r8/BUILD.tools
We are migrating Android functionality out of Bazel into rules_android. Currently rules_android depends on
@bazel_tools//tools/android:desugar_java8 for a sh_binary that calls the R8 desugar binary. Going forward, we'll maintain the sh_binary directly in rules_android, and therefore will require public visibility on [...]/r8:desugar. Eventually the source code for the Bazel R8 desugar wrapper will also move into rules_android.
Part of https://github.com/bazelbuild/rules_android/issues/122.
Closes #21775.
PiperOrigin-RevId: 618272641
Change-Id: I09d9ca19b742049c2d29a75336d1b0680b0005b1
Commit https://github.com/bazelbuild/bazel/commit/32fd6e9c2e7e4907c263ba8de2e55abd1484389b
> [7.2.0] Set public visibility for R8 desugar binary

- src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library4/BUILD.builtin_test
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library4/bar.cc
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library4/bar.h
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library4/main.cc
Previously, this failed with
```
Error in extend: type 'select' is not iterable
```
Fixes #21875
Closes #21878.
PiperOrigin-RevId: 629183138
Change-Id: I98603ab94261b4f8299e1cc89fc3eaa635661964
Commit https://github.com/bazelbuild/bazel/commit/cd1ef04a064be024280e58275e8b46d22aaf48ab
> [7.2.0] Support `select` in deps of a `cc_binary` with `dynamic_deps`

- src/main/java/com/google/devtools/build/lib/skyframe/FilesystemValueChecker.java
- src/main/java/com/google/devtools/build/lib/skyframe/SequencedSkyframeExecutor.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java
- src/test/java/com/google/devtools/build/lib/skyframe/FilesystemValueCheckerTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/SequencedSkyframeExecutorTest.java
If `--experimental_remote_output_service` is set, a `XattrProvider` which uses `BatchStat` RPC to get the digest of a file will be used for Bazel to invalidate stale output files during the start of incremental builds.
Working towards https://github.com/bazelbuild/bazel/issues/21630.
Closes #21840.
PiperOrigin-RevId: 619920334
Change-Id: I5aa0b482dc97db62f1c52867796f913df15974b7
Commit https://github.com/bazelbuild/bazel/commit/e03de754ec15096fcd1f701ea0b2d4c09c4b97a1
> [7.2.0] Use XattrProvider from OutputService to check filesystem values

- src/main/java/com/google/devtools/build/lib/remote/disk/Sqlite.java
- src/test/java/com/google/devtools/build/lib/remote/disk/SqliteTest.java
This is useful when initially setting up a database, as the statements won't be used again.
PiperOrigin-RevId: 628480119
Change-Id: I87d746bc754663147fbb36e27a2afdb586c57cc0
> [7.2.0] Add a convenience method to Connection to prepare and execute a Statement only once.

- MODULE.bazel.lock
- src/test/shell/bazel/starlark_repository_test.sh
- src/test/tools/bzlmod/MODULE.bazel.lock
- tools/build_defs/repo/utils.bzl
Modifying auth information should not result in a repo rule being reevaluated after a successful evaluation. This regressed in a5376aa3e11ea2ecfbd52068794ed3e652d9c179.
Fixes #22118
Closes #22125.
PiperOrigin-RevId: 629182408
Change-Id: I0c553e9ded72230b647a37203d51ba779976d7fc
Commit https://github.com/bazelbuild/bazel/commit/3fc76bea04a1859d4f61f079aca28c052df22550
> [7.2.0] Do not watch `.netrc` in `read_netrc`

- src/main/java/com/google/devtools/build/lib/runtime/StarlarkOptionsParser.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkOptionsParsingTest.java
Fixes #20582
RELNOTES: Starlark command-line flags can now be referred to through `alias` targets.
Closes #22192.
PiperOrigin-RevId: 629865954
Change-Id: I6215c8484ddc08e75507191bfa1eb5bc709c5fc6
Commit https://github.com/bazelbuild/bazel/commit/43fdcd36f88a3f3a549cecc3f69627537734bb14
> [7.2.0] Follow unconfigured `alias`es during options parsing

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
Closes #22180.
PiperOrigin-RevId: 629983939
Change-Id: Ie4bb781f085a3505264dbcde50dbf7b188b5ce32
Commit https://github.com/bazelbuild/bazel/commit/79b6c9531ecb98642f1eb42d977c6f75850d96e8
> [7.2.0] Add profile spans to BazelOutputService RPC calls

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteModuleTest.java
Closes #22245.
PiperOrigin-RevId: 631015801
Change-Id: I1a20c2ea034f429443b0fd37fe4924786e0dc7a0
Commit https://github.com/bazelbuild/bazel/commit/3c5b1ca5ae8ab51693feab633228695197a61974
> [7.2.0] Exit if `--experimental_remote_output_service` is set, but not `--remote_cache` nor `--remote_executor`

- src/main/java/com/google/devtools/build/lib/exec/SpawnLogContext.java
- src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java
A ParamFileActionInput isn't present in the InputMetadataProvider and doesn't exist in the filesystem if the respective action is running remotely. Therefore, the isInputDirectory call as previously written would always crash on these inputs (which is reported as a warning, not an error; this is arguably a bad idea and will be fixed in a followup).
Fixes #21820.
PiperOrigin-RevId: 631012628
Change-Id: Ie7eb039d51b2c1465f04a18a432623b3df8e25a4
> [7.2.0] Correctly handle ParamFileActionInput when writing to the compact execution log.

- src/main/java/com/google/devtools/build/lib/exec/AbstractSpawnStrategy.java
- src/main/protobuf/failure_details.proto
Although failing to write a log does not in principle affect the ability to build successfully, treating it as a warning hides problems and makes debugging them difficult (see e.g. https://github.com/bazelbuild/bazel/issues/21820). Spawn log implementations must be able to inspect the spawn inputs even if they're not present on disk (when building without the bytes) by using in-memory data.
PiperOrigin-RevId: 631042310
Change-Id: Iabe48e524dcd77bc434037c3396956f30174f57f
> [7.2.0] Treat an IOException while logging a spawn as an error instead of a warning.

- MODULE.bazel.lock
- src/test/shell/bazel/starlark_repository_test.sh
- src/test/tools/bzlmod/MODULE.bazel.lock
- tools/build_defs/repo/utils.bzl
Modifying auth information should not result in a repo rule being reevaluated after a successful evaluation. This regressed in a5376aa3e11ea2ecfbd52068794ed3e652d9c179.
Fixes #22118
Closes #22125.
PiperOrigin-RevId: 629182408
Change-Id: I0c553e9ded72230b647a37203d51ba779976d7fc
Commit https://github.com/bazelbuild/bazel/commit/3fc76bea04a1859d4f61f079aca28c052df22550
> [7.1.2] Do not watch `.netrc` in `read_netrc`

- src/test/py/bazel/bazel_workspace_test.py
- src/test/py/bazel/test_base.py
To prevent python tests from accessing BCR, this was missed in https://github.com/bazelbuild/bazel/commit/055e25b75c74d1e2c4c71694a938b6456323facc
Closes #22089.
PiperOrigin-RevId: 627384354
Change-Id: Ic4545616fad88f479b24553eb7ffe81004d41090
Commit https://github.com/bazelbuild/bazel/commit/c900865bbb3c38b589d6e5fbc422d61d3bba4681
> [7.2.0] Always create an empty MODULE.bazel for python tests

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/RepoFetchingSkyKeyComputeState.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
- src/test/shell/bazel/starlark_repository_test.sh
RELNOTES: Fixed certain deadlocks in repo fetching with worker threads (`--experimental_worker_for_repo_fetching=auto`).
> [7.2.0] Fix certain deadlocks in repo fetching with worker threads

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/InterimModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java
This effectively reverts most of 2a2a4743ad624f7f238b7771b8ceedb7649e8f5c: Module files of yanked versions are evaluated just like those of any other versions and "yankedness" is only checked for the final dep graph after selection.
This greatly simplifies incremental fetching of (inherently mutable) yanked version information with the new lockfile format.
Work towards #20369
RELNOTES: `print` statements in module files are now only executed for the root module and modules subject to non-registry overrides (e.g. `local_path_override`).
Closes #22083.
PiperOrigin-RevId: 627953972
Change-Id: Ie0aba02d187e000450a89ad2cd281c173582880a
Commit https://github.com/bazelbuild/bazel/commit/45982b4040096bdd76329c7034d72f2bae673e4e
> [7.2.0] Revert special handling of yanked module files

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
So we don't use stale `StartBuildResponse` from the output service.
Closes #22252.
PiperOrigin-RevId: 631086641
Change-Id: I8924ceae8a489b156a9ac7d2258193b0f0252d94
Commit https://github.com/bazelbuild/bazel/commit/a5bb1f0510b5aecec1295d31100aec4db6c7e817
> [7.2.0] Store lastBuildId and compare it with the one in StartBuildResponse

- src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationHelper.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CompileBuildVariables.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkstampCompileHelper.java
When using `--experimental_use_llvm_covmap`, no `.gcno` files are output. By listing them as outputs there is a mismatch between expected and actual outputs. Bazel will create these empty files after the action is run, but they non-deterministically get counted in the `Action` outputs, which can lead to cache misses on subsequent runs.
Closes #22132.
PiperOrigin-RevId: 630996820
Change-Id: Ia7de7a05305095c8befee4f86181cf84d9737814
> [7.2.0] Stop listing `.gcno` files as outputs when using LLVM coverage map format

- src/main/java/com/google/devtools/build/lib/packages/RuleVisibility.java
- src/test/java/com/google/devtools/build/lib/packages/RuleTest.java
- src/test/shell/bazel/bazel_rules_test.sh
Fixes https://github.com/bazelbuild/bazel/issues/22279
PiperOrigin-RevId: 631778635
Change-Id: I56e6caa3c1e8eb2d00467f5173564d30146bba4a
Commit https://github.com/bazelbuild/bazel/commit/772f10346e9c847402fde973b59f17b632e3ac22
> [7.2.0] Improve error message when parsing an invalid visibility label, e.g. //visibility:none

- src/tools/android/java/com/google/devtools/build/android/r8/BUILD.tools
We are migrating Android functionality out of Bazel into rules_android. Currently rules_android depends on
@bazel_tools//tools/android:desugar_java8 for a sh_binary that calls the R8 desugar binary. Going forward, we'll maintain the sh_binary directly in rules_android, and therefore will require public visibility on [...]/r8:desugar. Eventually the source code for the Bazel R8 desugar wrapper will also move into rules_android.
Part of https://github.com/bazelbuild/rules_android/issues/122.
Closes #21775.
PiperOrigin-RevId: 618272641
Change-Id: I09d9ca19b742049c2d29a75336d1b0680b0005b1
Commit https://github.com/bazelbuild/bazel/commit/32fd6e9c2e7e4907c263ba8de2e55abd1484389b
> [7.1.2] Set public visibility for R8 desugar binary

- src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
Closes #22172.
PiperOrigin-RevId: 629494462
Change-Id: Ib1febd4244c2a919969c125a96512d13cf6d6a6b
Commit https://github.com/bazelbuild/bazel/commit/0e7c0fb91eb6d6fd0f7a4e4bddf734569a9dd3b3
> [7.2.0] Rename the compact execution log to better reflect the file format.

- src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
If a test fails, the failure is going to be informative than a generic exec error and the failure may have interrupted or prevented the test runner from touching the status file.
Speculatively fixes #22028
Closes #22098.
PiperOrigin-RevId: 628355694
Change-Id: I370c7aba331f2a7a89cb9a9ff99d32b1694fd03a
Commit https://github.com/bazelbuild/bazel/commit/874a050aa7ab3f2034bbd4afb3a5fbf4ed5109d1
> [7.2.0] Only check for shard status file if a test passed

- src/main/java/com/google/devtools/build/lib/rules/android/AndroidBinary.java
- src/main/java/com/google/devtools/build/lib/rules/android/AndroidStarlarkCommon.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/android/AndroidStarlarkCommonApi.java
We call DexMerger via SpawnActionTemplate which is only available in native Blaze. So we must expose the parameter to the Starlark API.
PiperOrigin-RevId: 604482423
Change-Id: I2c9c165373d35cb1f7a6f928c11839b201973bed
Commit https://github.com/bazelbuild/bazel/commit/84861027d3f94ce6fc0bcf25ebbb787d6be8567a
> [7.2.0] Forward min_sdk_version to dexmerger actions

- src/main/java/com/google/devtools/build/lib/analysis/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfigurationValue.java
- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java
- src/main/java/com/google/devtools/build/lib/analysis/config/ExecutionInfoModifier.java
- src/test/java/com/google/devtools/build/lib/analysis/config/ExecutionInfoModifierTest.java
Calling --modify_execution_info multiple times used to result in the last version being used. With this change, options are amended additively if --incompatible_modify_execution_info_additive is set.
Fixes #13342
Closes #16262.
PiperOrigin-RevId: 631803759
Change-Id: I5386cbb0d02ef19a6b2ddf2f818cbab660b17c31
Closes #22288.
> [7.2.0] Make --modify_execution_info additive

- src/main/java/com/google/devtools/build/lib/shell/Command.java
- src/main/java/com/google/devtools/build/lib/shell/SubprocessBuilder.java
- src/main/java/com/google/devtools/build/lib/shell/WindowsSubprocessFactory.java
- src/test/java/com/google/devtools/build/lib/shell/CommandTest.java
- src/test/java/com/google/devtools/build/lib/windows/BUILD
- src/test/java/com/google/devtools/build/lib/windows/MockSubprocess.java
- src/test/java/com/google/devtools/build/lib/windows/WindowsSubprocessTest.java
JavaSubprocessFactory causes the environment to be inherited if SubprocessBuilder#setEnv is never called or called with null. WindowsSubprocessFactory currently interprets it as an empty environment (other than the unconditionally inherited SYSTEMROOT and SYSTEMDRIVE). This CL makes the behavior on Windows the same as elsewhere.
Fixes #22190. The test failures were due to the //src/tools/remote:worker binary spawned by the test being unable to locate the runfiles directory, as the RUNFILES_MANIFEST_FILE environment variable wasn't inherited. It's unclear why the tests used to work, although I suspect it has to do with one of the many runfiles-related changes submitted to the 8.x tree.
These tests are the only uses of SubprocessBuilder without an explicit setEnv call, so other callsites …
> [7.2.0] Fix inheritance of environment variables in WindowsSubprocessFactory.

- src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
I accidentally added a 'd'.
Closes #22280.
PiperOrigin-RevId: 632109445
Change-Id: I1cacbb1f05040d97c2e0418e307bb9883d3d426f
Commit https://github.com/bazelbuild/bazel/commit/b8eb437521374acd1f0047fac1b7ca980cc7e179
> [7.2.0] Fix wrong zstd extension in SpawnLogModule.

- MODULE.bazel
- MODULE.bazel.lock
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/main/java/com/google/devtools/build/lib/packages/StarlarkNativeModule.java
- src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/BUILD.builtin_test
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/starlark_tests.bzl
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleClassFunctionsTest.java
- workspace_deps.bzl
Cherry-picks:
* d160b12d9e059059fdf42418ef13840caa1b24c0
* d1df1be024950db7a2ab6cc7706ec5e2dd79ac1a
* 8ee8f797e72898282a81993e012e7502ff1bf656
* f2eb91a959da42b35d304147489892e07e8e9dba
* 8e7ef00ad51c8ca176dfe1c3146735e3762ffb7b
Closes #21986
Closes #22053
Closes #22113
> [7.2.0] Combined cc_shared_library cherry-picks

- MODULE.bazel.lock
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/external_remote_file_test.sh
- src/test/tools/bzlmod/MODULE.bazel.lock
- tools/build_defs/repo/http.bzl
- tools/build_defs/repo/utils.bzl
This issue adds support necessary to tackle
https://github.com/bazelbuild/bazel-central-registry/issues/1566
Add two new attributes to http_archive: remote_file_urls and remote_file_integrity.
The purpose of these two attributes is to allow files to effectively be overlaid ontop of an http_archive. The goal of such functionality would be useful for BCR since the BUILD & WORKSPACE files need no longer be stored as patch files.
This means we could probably deprecate `build_file` since that could be referenced as a file:// url in the remote_file_urls attribute.
Co-authored-by: Mark Williams <markrwilliams@google.com>
CC @fmeum
Closes #22155.
PiperOrigin-RevId: 632594203
Change-Id: I6310093482c5c58537ed6dbe4ff90bafdbd696ff
Commit https://github.com/bazelbuild/bazel/commit/e01509f1a5bbfac96e705 …
> [7.2.0] Add support for remote_files for http_archive

- src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl
- src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl
- src/main/starlark/builtins_bzl/common/cc/cc_test.bzl
- src/main/starlark/tests/builtins_bzl/BUILD
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/BUILD.builtin_test
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/starlark_tests.bzl
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library2/MODULE.bazel
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library2/WORKSPACE
- src/main/starlark/tests/builtins_bzl/cc_builtin_tests.sh
This is required for `exports_filter` to match any external repositories with Bzlmod enabled.
`native.package_relative_label` is used to convert the user-specified filter strings, which are always valid labels, to canonical label literals that are then passed to the actual `cc_shared_library` rule.
Fixes #21872
Closes #21622.
PiperOrigin-RevId: 632624776
Change-Id: I2f80563d8c434b2726f4facb0551b316b2cd2e1c
> [7.2.0] Apply repo mapping to `cc_shared_library`'s `exports_filter`

- src/main/java/com/google/devtools/build/lib/exec/SpawnLogContext.java
- src/main/protobuf/BUILD
- src/main/protobuf/spawn.proto
- src/test/java/com/google/devtools/build/lib/exec/BUILD
- src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java
RELNOTES: The compact and full execution logs now contain start times for spawns (if available).
Closes #22281.
PiperOrigin-RevId: 633108842
Change-Id: I3b7fbf8559b7583dcfe5ed0ff5eaf736de4f1f8d
Commit https://github.com/bazelbuild/bazel/commit/73b0faff39ed435b3cbeb09c93185b155fbd3e09
> [7.2.0] Add start time to execlog `Spawn`

- MODULE.bazel.lock
- src/test/tools/bzlmod/MODULE.bazel.lock
- tools/android/android_extensions.bzl
- tools/cpp/cc_configure.bzl
- tools/osx/xcode_configure.bzl
- tools/sh/sh_configure.bzl
- tools/test/extensions.bzl
Removes unnecessary lockfile entries.
Closes #22335.
PiperOrigin-RevId: 633311588
Change-Id: Ia0ccb2fd14b28123115109db9fa921380319451e
> [7.2.0] Mark bazel_tools extensions as reproducible

- src/main/java/com/google/devtools/build/lib/runtime/UiEventHandler.java
If the cli-update-thread is crashing, it may attempt to interrupt and join on itself. Hopefully no updateThread could be in stopUpdateThread without going through handleCrash() -> Event.FATAL sequence through BlazeRuntime.
Fixes #22051
Closes #22122.
PiperOrigin-RevId: 633653817
Change-Id: Iaef5df56358d74bd7210ad8cb3562b452de9eb6a
Commit https://github.com/bazelbuild/bazel/commit/63062400732c266fe36a5bd54551c356410dfef8
> [7.2.0] Prevent currentThread().join() on cli thread crash

- src/main/java/com/google/devtools/build/lib/bazel/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Registry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryImpl.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
- src/test/py/bazel/bzlmod/bazel_lockfile_test.py
- src/test/py/bazel/bzlmod/bazel_yanked_versions_test.py
RELNOTES: The new `refresh` value for `--lockfile_mode` behaves like the `update` mode, but additionally forces a refresh of mutable registry content (yanked versions and missing module versions) when switched to or from time to time while enabled.
Closes #22333.
PiperOrigin-RevId: 633737372
Change-Id: I2cae552f6adfcd07a5b3263b5e4997e21653f106
Commit https://github.com/bazelbuild/bazel/commit/88a230f4cf28deec1455cb2caed4dc9f81e108c9
> [7.2.0] Add `--lockfile_mode=refresh`

- src/main/java/com/google/devtools/build/lib/remote/disk/Sqlite.java
- src/test/java/com/google/devtools/build/lib/remote/disk/SqliteTest.java
This adds a bit of convenience when executing pragmas that echo back the setting.
PiperOrigin-RevId: 633913983
Change-Id: If2a9f747a1fe73393dfe5608ae17d366d271892e
> [7.2.0] Modify executeUpdate to discard a non-empty result instead of throwing.

- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheClient.java
This will make it easier for garbage collection to identify them.
PiperOrigin-RevId: 634007262
Change-Id: I78b836f4fbae448c2ef408e7c2f8313447cedc22
> [7.2.0] Put temporary files created by the disk cache in a separate subdirectory.

- src/main/java/com/google/devtools/build/lib/remote/ByteStreamBuildEventArtifactUploader.java
- src/test/shell/bazel/remote/remote_build_event_uploader_test.sh
In particular, this ensures that the compact execution log is uploaded (for which a test has been added).
ByteStreamBuildEventArtifactUploader would have benefitted from a refactor, but I'm deliberately making a minimal change that can be cherry-picked into 7.2.0 without risking a regression.
PiperOrigin-RevId: 634033159
Change-Id: I4d3df757f612337b5d2b222278d1171cc8e1aed4
> [7.2.0] Include all LocalFiles of type LOG and PERFORMANCE_LOG in --remote_build_event_upload=MINIMAL.

- src/main/java/com/google/devtools/build/lib/remote/disk/Sqlite.java
- src/main/native/sqlite_jni.cc
- src/test/java/com/google/devtools/build/lib/remote/disk/SqliteTest.java
This will be necessary to implement retry loops when the database is locked by another process (SQLITE_BUSY). However, I'm exporting all of the known error codes for future convenience. They're a stable API, so hardcoding the values should be fine.
PiperOrigin-RevId: 633948990
Change-Id: Ic089d2792ddab28bcba20d583fbdedbaea421c4c
> [7.2.0] Expose SQLite error codes to Java.

- src/main/java/com/google/devtools/build/lib/actions/FileArtifactValue.java
- src/main/java/com/google/devtools/build/lib/sandbox/AbstractContainerizingSandboxedSpawn.java
- src/main/java/com/google/devtools/build/lib/sandbox/AbstractSandboxSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/DockerSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxCommandLineBuilder.java
- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/ProcessWrapperSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java
- src/main/java/com/google/devtools/build/lib/sandbox/WindowsSandboxUtil.java
- src/main/java/com/google/devtools/build/lib/sandbox/WindowsSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStore.java
- src/main/java/com/google/devtools/build/lib/worker/SandboxedWorker.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerExecRoot.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerModule.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnRunner.java
- src/test/java/com/google/devtools/build/lib/sandbox/AbstractContainerizingSandboxedSpawnTest.java
- src/test/java/com/google/devtools/build/lib/sandbox/LinuxSandboxCommandLineBuilderTest.java
- src/test/java/com/google/devtools/build/lib/sandbox/SandboxHelpersTest.java
- src/test/java/com/google/devtools/build/lib/sandbox/SymlinkedSandboxedSpawnTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStoreTest.java
- src/test/java/com/google/devtools/build/lib/worker/SandboxHelper.java
- src/test/java/com/google/devtools/build/lib/worker/WorkerSpawnRunnerTest.java
- src/test/java/com/google/devtools/build/lib/worker/WorkerSpawnStrategyTest.java
- src/test/shell/bazel/bazel_sandboxing_test.sh
The bind mounting scheme used with the Linux sandbox' hermetic `/tmp` feature is modified to preserve all paths as they are outside the sandbox, which removes the need to rewrite paths when staging inputs into and, crucially, moving outputs out of the sandbox.
Source roots and output base paths under `/tmp` are now treated just like any user-specified bind mount under `/tmp`: They are mounted under the hermetic tmp directory with their path relativized against `/tmp` before the hermetic tmp directory is mounted as `/tmp` as the final step.
There is one caveat compared to user-specified mounts: Source roots, which may themselves not lie under `/tmp`, can be symlinks to directories under `/tmp` (e.g., when they arise from a `local_repository`). To handle this situation in the common case, …
> [7.2.0] Preserve paths under hermetic `/tmp` in the sandbox

- src/tools/android/java/com/google/devtools/build/android/dexer/BUILD.tools
Necessary to remove references to `@bazel_tools//tools/android`, which is necessary to remove bind()s from Starlark android_sdk_repository.
PiperOrigin-RevId: 633693304
Change-Id: Ib49fd219847e63135a4b3e771bf67013e12830b4
Commit https://github.com/bazelbuild/bazel/commit/df9f76aa47afbe9c417a4152b01de97df23e0f64
> [7.2.0] Expand visibility of DexFileSplitter

- tools/cpp/unix_cc_toolchain_config.bzl
The external_include_paths feature enables specifying include paths locally with -I and with -isystem when the project is included as an external repo.
This makes it possible to set -Werror against your own headers for development without propagating this to consumers of your libraries.
For some reason this was only previously enabled on linux. I do not see a reason for not also enabling it on macos.
Closes #21949.
PiperOrigin-RevId: 634394452
Change-Id: I0df91b2a2c9b4a5bd52b22e64f99ea0745cb9759
Commit https://github.com/bazelbuild/bazel/commit/d831214a6d3ed7ae6b4c14ce4735f023b1da6e3c
> [7.2.0] feat(cc toolchain): support external_include_paths on macos

- scripts/release/common.sh
Previously the code failed when the repository was in detached HEAD state (e.g. on CI).
Closes #22405.
PiperOrigin-RevId: 634564660
Change-Id: I60d87f1f24a1dceec6b74709a571c9630cf6bcc5
Commit https://github.com/bazelbuild/bazel/commit/2028c473ae5d9f7bd053383a1622bb9678d7ab33
> [7.2.0] Fix git branch detection in release scripts

- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
- src/test/shell/integration/sandboxing_test.sh
The logic for sandboxing hermetic tmp needs to take into account all paths under `/tmp` used during the build. A user may also pass a `sandbox_base` under `/tmp` even when the `output_base` is not. This change adds `sandbox_base` to the list.
Fix suggested by fmeum
Closes #22435.
PiperOrigin-RevId: 635382607
Change-Id: I32497a514ff16e64a0e0d84c307f280d3d37544b
Commit https://github.com/bazelbuild/bazel/commit/eebf5f97e33fa4abad128c029e5d254783d805ca
> [7.2.0] Fix sandboxing hermetic tmp to take into account sandbox_base

- src/main/java/com/google/devtools/build/lib/sandbox/AbstractSandboxSpawnRunner.java
The reverts in 3fddc7f38ace43981d839ed4558b8a457caf41fb accidentally replaced `sandboxExecRoot` with `execRoot` in the function that computes writable directories for sandbox spawn runners.
This issue was observed in https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/3029.
Closes #22443.
PiperOrigin-RevId: 635383877
Change-Id: I3d74bf78cf97ecd267ba90b68cf1b715850aba27
Commit https://github.com/bazelbuild/bazel/commit/b0ed4ca15d3c66fb7a5b19592cefaae709defe63
> [7.2.0] Fix writable sandbox path

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GsonTypeAdapterUtil.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionEvalFactors.java
JSON-based merge conflict resolution for `MODULE.bazel.lock` can end up producing entries with, e.g., both a `general` and an `os:Linux` factor result when the OS/arch dependence of the extension changes. `BazelLockFileModule` now invalidates each factor result individually.
Also sort the extension factors.
Closes #22378.
PiperOrigin-RevId: 635913837
Change-Id: I0064098806c856f16e8f4c0270f609f06cebc945
Commit https://github.com/bazelbuild/bazel/commit/c4092e9c591bf90bd705482e9a889306c28d72f0
> [7.2.0] Remove stale extension factors

- src/main/java/com/google/devtools/build/lib/analysis/actions/PathMappers.java
- src/test/shell/bazel/path_mapping_test.sh
Targets tagged with `local` or `no-sandbox` and `no-remote` can't successfully use path mapping and thus have it disabled implicitly.
Closes #21921.
PiperOrigin-RevId: 635832339
Change-Id: Ib5cac0b202cbcd1704410f06fa3cda645581b849
Commit https://github.com/bazelbuild/bazel/commit/46dce83e62d5142ea588d1f108300dad5da190d7
> [7.2.0] Disable path mapping with `local` or `no-{sandbox,remote}` tags

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ArchiveOverride.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ArchiveRepoSpecBuilder.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GitOverride.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GitRepoSpecBuilder.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleVersionOverride.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
The following validation checks were not enforced due to backwards compatibility concerns, but ended up crashing Bazel when invalid labels made it into the lockfile, which is enabled by default. We might as well enable them now:
* Fail if a label passed to `use_extension` is not valid
* Fail if a label passed to the `patches` attribute of an override is not valid or points to a repo other than the main repo
Work towards #21845
Closes #22487.
PiperOrigin-RevId: 636255834
Change-Id: I55dda374cd1716e514c4d78642479b136fd3ad43
Commit https://github.com/bazelbuild/bazel/commit/cdace8f4d6496fdc3725438a64e952afd63c98d7
> [7.2.0] Fail early on certain invalid labels in module files

- src/main/java/com/google/devtools/common/options/BUILD
- src/main/java/com/google/devtools/common/options/IsolatedOptionsData.java
- src/main/java/com/google/devtools/common/options/OptionsParserImpl.java
- src/test/java/com/google/devtools/common/options/OptionsTest.java
Examples:
```
$ bazel build //src:bazel-dev --experimental_remote_cache_evection_retries=5
ERROR: --experimental_remote_cache_evection_retries=5 :: Unrecognized option: --experimental_remote_cache_evection_retries=5 (did you mean '--experimental_remote_cache_eviction_retries'?)
$ bazel build //src:bazel-dev --notest_kep_going
ERROR: --notest_kep_going :: Unrecognized option: --notest_kep_going (did you mean '--notest_keep_going'?)
```
Closes #22193.
PiperOrigin-RevId: 636258381
Change-Id: Ie81344caa14054e1d328d5a6e9b94da506d6a577
Commit https://github.com/bazelbuild/bazel/commit/0e9287f41ceeea6c980045cbbc126a885a47f42c
> [7.2.0] Provide "did you mean ...?" suggestions for unknown command-line options

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
Fixes #22489
Closes #22493.
PiperOrigin-RevId: 636310898
Change-Id: If2fb41fd8d51f15aa1047cb62d55035e81187e41
Commit https://github.com/bazelbuild/bazel/commit/792d17c223ef5d170814940b28b4a3c69b799a2b
> [7.2.0] Fix a crash on `use_repo_rule` with no repos

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
So that the last task won't try to shutdown the remoteCache, otherwise, might cause deadlocks.
Fixes https://github.com/bazelbuild/bazel/issues/21568.
PiperOrigin-RevId: 635746896
Change-Id: Ic321216dd0bda05ef1ad18367c8ebbcd1a1d272c
Commit https://github.com/bazelbuild/bazel/commit/a804fb1748ce767d98f8b7a40e660ed22576e30e
> [7.2.0] Wait for background tasks finished before releasing remoteCache.

- MODULE.bazel
- MODULE.bazel.lock
- src/MODULE.tools
- src/test/tools/bzlmod/MODULE.bazel.lock
Closes #22513.
PiperOrigin-RevId: 636650432
Change-Id: Ic9af576b7f24af92ff8c3f0fbb1167d6db1687ea
Commit https://github.com/bazelbuild/bazel/commit/9dcec1017c9e127d916930c1b69c4cf01bf99951
> [7.2.0] Update buildozer to 7.1.2

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ArchiveRepoSpecBuilder.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
- src/test/py/bazel/bzlmod/mod_command_test.py
This is a continuation of #22155 that adds the newly added 'remote_files' attribute for http_archive to the bzlmod functionality.
The end goal is to then update BCR to this new functionality to overlay files rather than use patch files when providing MODULE/WORKSPACE/BUILD files.
https://github.com/bazelbuild/bazel-central-registry/issues/1566 has a good discussion of the rationale.
Co-authored-by: Fabian Meumertzheim <fabian@meumertzhe.im>
Closes #22349.
PiperOrigin-RevId: 636682112
Change-Id: Ief070985598a7c0f427a98cd3daeb69a0984f7be
Commit https://github.com/bazelbuild/bazel/commit/c4167e309a29384ee1cf827b4ecf4ff5b0210fc9
> [7.2.0] Add support for overlays in source.json

- src/main/java/com/google/devtools/build/lib/shell/WindowsSubprocess.java
- src/main/java/com/google/devtools/build/lib/windows/WindowsProcesses.java
- src/main/native/windows/processes-jni.cc
- src/test/java/com/google/devtools/build/lib/windows/MockSubprocess.java
- src/test/java/com/google/devtools/build/lib/windows/WindowsProcessesTest.java
Otherwise, a subprocess that consumes the stdin in its entirety can never terminate.
PiperOrigin-RevId: 635774207
Change-Id: I134ddd1fee50faccb8ddb8400dbb11ce6a354c05
Commit https://github.com/bazelbuild/bazel/commit/b3f5c62d675ba9bf200e41cf755925b7242638d9
> [7.2.0] Close the stdin pipe handle when the respective OutputStream is closed

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
Instead of
```
ERROR: An error occurred during the fetch of repository 'mydep~':
Traceback (most recent call last):
File "/private/var/tmp/_bazel_fmeum/7d8a4807d1079f03870ba5776e9ca66b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 45, in _http_archive_impl
download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Bad URL: invalid
ERROR: <builtin>: fetching http_archive rule //:mydep~: Traceback (most recent call last):
File "/private/var/tmp/_bazel_fmeum/7d8a4807d1079f03870ba5776e9ca66b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 45, in _http_archive_impl
download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Bad URL: invalid
ERROR: Error computing the main …
```
> [7.2.0] Do not print repository errors twice

- third_party/grpc/00_disable_layering_check.patch
There were 2 things with the previous implementation that needed to be improved here:
1. Apple Clang has a bug where it doesn't pass module compiler flags to the underlying -cc1 invocation, so we have to manually pass them directly to that invocation with -Xclang
2. The previous search script was too aggressive and slow for macOS. The macOS SDK has tons of files that aren't headers, and tons of symlinks pointing to other files within the SDK. This adds a fork in the script to run a version that works with Apple SDKs. The time difference on my machine is 41s->6s. 6s is still pretty long so if desired we can put this behavior behind an env var for users to opt in with.
I've added a hermetic version of this to the apple_support toolchain, but similar to the Linux setup here the modulemap …
> [7.2.0] Add layering_check support for macOS

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/RepoFetchingSkyKeyComputeState.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/RepoFetchingWorkerSkyFunctionEnvironment.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
- src/main/java/com/google/devtools/build/skyframe/SkyFunction.java
This greatly simplifies the code flow. Instead of using `volatile` and resorting to some very unsavory workarounds, we can simply make sure only one thread is changing `state.workerFuture` using plain old synchronization, and on memory pressure, make absolutely sure that the state object is cleaned up after we remove it from the central state cache.
This goes against the advice introduced in https://github.com/bazelbuild/bazel/commit/8ef0a519f2e468498fa53f4aede871b658890f92; the wording for `SkyKeyComputeState#close()` has been updated.
Also changed the "retry on cancellation" logic from using recursion to using a `while`-loop for better clarity around nested `finally` blocks.
Fixes https://github.com/bazelbuild/bazel/issues/22393.
PiperOrigin-RevId: 637975501
Change-Id: …
> [7.2.0] Block in repo fetching state's `close()` method

- MODULE.bazel.lock
- src/test/tools/bzlmod/MODULE.bazel.lock
- tools/build_defs/repo/http.bzl
- tools/build_defs/repo/utils.bzl
- Fixed the leak of `remote_patches` URLs for downloaded the source archive.
- Compute auth for required URLs only
Fixes https://github.com/bazelbuild/bazel/issues/22201
Closes #22517.
PiperOrigin-RevId: 638300996
Change-Id: Ib76e3284f209d2314844cfd662ac8eadba785fae
Commit https://github.com/bazelbuild/bazel/commit/5986420a3a5ce3493c50d733618649246a7e8651
> [7.2.0] Fix getting authentication for URLs in http repo rules

- tools/cpp/windows_cc_toolchain_config.bzl
MSVC fails if `/external:I <some_path>` is broken into two lines in `.param` files. This is avoided by using the alternative `/external:I<some_path>` form.
Fixes #22614
Closes #22616.
PiperOrigin-RevId: 640055579
Change-Id: I5fda2714dc479fd76f22e2f8562dddbdfcdb9a18
Commit https://github.com/bazelbuild/bazel/commit/759fe7d7f3fdf142490e970457f72180f4d1b59a
> [7.2.0] Keep `/external:I...` on a single param file line

- src/main/java/com/google/devtools/build/lib/skyframe/BUILD
- src/main/java/com/google/devtools/build/lib/skyframe/DiffAwarenessManager.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java
On an incremental build with `--watchfs`, the `handleDiffs` span in the timing profile is now almost fully explained by subspans.
Closes #22622.
PiperOrigin-RevId: 640084976
Change-Id: Iab7c9f22bab5e53cfab1d39dc0b3f2a697453540
Commit https://github.com/bazelbuild/bazel/commit/f4b453722304ffcbe605eb54bc41d2d12a30303a
> [7.2.0] Add more profiler spans to diff handling

- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/RegisteredExecutionPlatformsFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunction.java
- src/test/java/com/google/devtools/build/lib/skyframe/toolchains/RegisteredExecutionPlatformsFunctionTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunctionTest.java
- src/test/shell/integration/toolchain_test.sh
- src/test/shell/testenv.sh.tmpl
Cherrypick of 0938026a159e217953d6798d78aa6516ec0f998b.
Fixes #22608.
> [7.2.0] Update toolchain resolution to fully dereference aliases

- src/main/java/com/google/devtools/build/lib/sandbox/AbstractContainerizingSandboxedSpawn.java
- src/main/java/com/google/devtools/build/lib/sandbox/BUILD
- src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/ProcessWrapperSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java
- src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java
- src/main/java/com/google/devtools/build/lib/sandbox/SandboxOptions.java
- src/main/java/com/google/devtools/build/lib/sandbox/SandboxStash.java
- src/main/java/com/google/devtools/build/lib/sandbox/SymlinkedSandboxedSpawn.java
- src/test/java/com/google/devtools/build/lib/sandbox/SymlinkedSandboxedSpawnTest.java
- src/test/shell/integration/sandboxing_test.sh
This change introduces the flag `--experimental_inmemory_sandbox_stashes` to track in memory the contents of the stashes stored with `--reuse_sandbox_directories=true`
With the old behavior Bazel has to perform a lot of I/O to read the contents of each stash before reusing it in a new action. Essentially, it checks  every directory and subdirectory in the stashed sandbox to find out which files are different to the inputs of the new action about to be executed.
With in-memory stashes we associate each stash to the symlinks that needed to be created for that action. We also store the time at which these symlinks were created. In a background thread after the action has finished executing we stat every directory and for the ones that have changed (this should be rare) we update the …
> [7.2.0] Add option to track sandbox stashes in memory

- src/main/java/com/google/devtools/build/lib/rules/java/JavaOptions.java
- src/main/starlark/builtins_bzl/common/java/java_binary.bzl
- src/main/starlark/builtins_bzl/common/java/java_helper.bzl
- src/test/shell/bazel/bazel_java_test.sh
This is a partial cherry-pick of 417c6b803db1078d20077068471427c86c016190 which excludes the changes to `oneversion` itself, which is built and released for Bazel 7 as part of java_tools:
* Avoid passing --whitelist to one_version if no allowlist is configured in the toolchain as it isn't supported by the Bazel version of oneversion yet.
* Document the one_version flags.
* Clean up tests not updated after recent rules_java releases.
Fixes #22576
> [7.2.0] Make Bazel changes for `oneversion` support

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
Should fix the following crash observed in the wild:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'RepoSpecKey{moduleKey=rules_pkg@0.7.0, registryUrl=https://bcr.bazel.build/}' (requested by nodes 'com.google.devtools.build.lib.bazel.bzlmod.BazelModuleResolutionValue$$Lambda/0x00000008005fd220@38aba3ca')
at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at …
```
> [7.2.0] Fix data race in `IndexRegistry#getBazelRegistryJson`

- MODULE.bazel
- MODULE.bazel.lock
- scripts/BUILD
- scripts/bazel-lockfile-merge.jq
- scripts/bazel_lockfile_merge_test.sh
- site/en/external/lockfile.md
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileFunction.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepoRecordedInput.java
Adds a `jq` script to `scripts/` that merges any number of `MODULE.bazel.lock` files without using Bazel or reading the corresponding `MODULE.bazel` files.
The lockfile docs now have a section explaining the steps needed to set up this script as a custom merger driver for Git, which means that merge conflicts in `MODULE.bazel.lock` files will always be resolved automatically. Note that resolution may emit lockfiles with redundant information that will be dropped by subsequent Bazel invocations.
When Bazel encounters an error during lockfile parsing that could be caused by a merge conflict, it emits a different error message with a link to the docs. This required fixing the following kind of server crash when a conflict marker occurs inside a `recordedFileInputs` object:
```
FATAL: bazel …
```
> [7.2.0] Add a git merge driver for `MODULE.bazel.lock`

- tools/bash/runfiles/runfiles.bash
This piece of code is supposed to be copy-pasted literally, so it is better to already configure shellcheck ignore to help users who apply shellcheck to their scripts.
Closes #22530.
PiperOrigin-RevId: 641178789
Change-Id: I4ea3629f57e66996fca5768cea73497cda29eb16
Commit https://github.com/bazelbuild/bazel/commit/b75ad88d82c1736016a171fe16216f63a1a3faff
> [7.3.0] chore: Ignore shellcheck error in copy-paste code

- site/en/external/module.md
The bullet list in the "Repository names and strict deps" section of https://bazel.build/external/module does not render properly on the website.  However, other bullet lists on this page do render correctly.  The difference is apparently the level of indentation.  This PR attempts to correct the discrepancy.
Closes #22663.
PiperOrigin-RevId: 641904379
Change-Id: I9d97841731ec99bad91796fff3fd3d62426b10ff
Commit https://github.com/bazelbuild/bazel/commit/f6687ad45eccfa7928c9a54f3db2e3c660d9bbce
> [7.3.0] Format "Repository names and strict deps" bullet list

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
Fixes #22688
Closes #22689.
PiperOrigin-RevId: 642286171
Change-Id: I0c872c06c6dcffb5b90520c492bee247970f42d7
Commit https://github.com/bazelbuild/bazel/commit/705cbb18656d3f314583db099d1e221eb0c9c9d7
> [7.2.1] Fix crash on `IOException` in SingleExtensionEvalFunction

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
Fixes #22688
Closes #22689.
PiperOrigin-RevId: 642286171
Change-Id: I0c872c06c6dcffb5b90520c492bee247970f42d7
Commit https://github.com/bazelbuild/bazel/commit/705cbb18656d3f314583db099d1e221eb0c9c9d7
> [7.3.0] Fix crash on `IOException` in SingleExtensionEvalFunction

- src/test/java/com/google/devtools/build/android/r8/BUILD
- src/tools/android/java/com/google/devtools/build/android/r8/BUILD
- src/tools/android/java/com/google/devtools/build/android/r8/BUILD.tools
When android sdk is defined, android_sdk_repository maps //external:android/d8_jar_import to androidsdk//:d8_jar_import, which refers to android_gmaven_r8//jar:jar.
PiperOrigin-RevId: 611144488
Change-Id: I4ee5945ce5a1fdb30e96775396ec3628cefaa2e8
> [7.2.1] Replace //external:android/d8_jar_import with "@android_gmaven_r8//jar"

- src/test/java/com/google/devtools/build/android/r8/BUILD
- src/tools/android/java/com/google/devtools/build/android/r8/BUILD
- src/tools/android/java/com/google/devtools/build/android/r8/BUILD.tools
When android sdk is defined, android_sdk_repository maps //external:android/d8_jar_import to androidsdk//:d8_jar_import, which refers to android_gmaven_r8//jar:jar.
PiperOrigin-RevId: 611144488
Change-Id: I4ee5945ce5a1fdb30e96775396ec3628cefaa2e8
> [7.3.0] Replace //external:android/d8_jar_import with "@android_gmaven_r8//jar"

- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
- src/test/py/bazel/bzlmod/bazel_overrides_test.py
Fixes #22687
Closes #22700.
PiperOrigin-RevId: 642340825
Change-Id: I96f496b309c4740ae561f69098eca54a12a574f0
Commit https://github.com/bazelbuild/bazel/commit/b868a5919d28554dea614800e8fbb8bd9da3b401
> [7.3.0] Treat missing repo boundary files as transient errors

- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
- src/test/py/bazel/bzlmod/bazel_overrides_test.py
Fixes #22687
Closes #22700.
PiperOrigin-RevId: 642340825
Change-Id: I96f496b309c4740ae561f69098eca54a12a574f0
Commit https://github.com/bazelbuild/bazel/commit/b868a5919d28554dea614800e8fbb8bd9da3b401
> [7.2.1] Treat missing repo boundary files as transient errors

- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
Fixes this issue when collecting coverage with the compact execution log:
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.cmdline.Label.getCanonicalForm()" because the return value of "com.google.devtools.build.lib.actions.Spawn.getTargetLabel()" is null
at com.google.devtools.build.lib.exec.CompactSpawnLogContext.logSpawn(CompactSpawnLogContext.java:216)
at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:191)
at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:118)
at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
at com.google.devtools.build.lib.bazel.coverage.CoverageReportActionBuilder$CoverageReportAction.execute(Cov …
```
> [7.2.1] Fix an NPE with the compact execution log and coverage

- src/main/java/com/google/devtools/build/lib/actions/ArtifactFactory.java
- src/main/java/com/google/devtools/build/lib/actions/ArtifactResolver.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/HeaderDiscovery.java
- src/test/java/com/google/devtools/build/lib/actions/util/ActionsTestUtil.java
- src/test/shell/bazel/cc_integration_test.sh
This sounds like a weird corner case, but it happens in one very prominent case, which is protobuf: it contains a `local_repository(path=".")` rule in its WORKSPACE file in order to work around the consequences of the uncomfortable fact that `@bazel_tools` depends on it.
If this was *not* done, when sibling repository layout is in effect, paths in the external repo would be resolved as ones in the main repo, thus causing "undeclared inclusion" errors when running C++ actions in the external repo.
This is not perfect (after all, it's ambiguous which Artifact such paths refer to), but seems to be good enough for protobuf and will go away once the `@bazel_tools -> @com_google_protobuf` dependency is cut or if bzlmod is turned on for good.
PiperOrigin-RevId: 634663132 …
> [7.3.0] Cherry-pick fix to make Protobuf work with sibling repository layout into Bazel 7.3

- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
Fixes this issue when collecting coverage with the compact execution log:
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.cmdline.Label.getCanonicalForm()" because the return value of "com.google.devtools.build.lib.actions.Spawn.getTargetLabel()" is null
at com.google.devtools.build.lib.exec.CompactSpawnLogContext.logSpawn(CompactSpawnLogContext.java:216)
at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:191)
at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:118)
at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
at com.google.devtools.build.lib.bazel.coverage.CoverageReportActionBuilder$CoverageReportAction.execute(Cov …
```
> [7.3.0] Fix an NPE with the compact execution log and coverage

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
When a repository rule is restarted due to memory pressure, all its downloads must be interrupted. While this happened for `repository_ctx.download`, the `download_and_extract` method did not register its `PendingTask`. Since downloads happen on a separate executor, they would continue even through restarts, leading to warnings (see below) or even left over download temp directories.
```
WARNING: Download from https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.26-aarch64-apple-darwin.tar.gz failed: class java.io.FileNotFoundException /private/var/tmp/_bazel_fmeum/0465a0857e26a35c072f48ab751a1794/external/aspect_bazel_lib~~toolchains~coreutils_darwin_arm64/temp2576567839043404337/coreutils-0.0.26-aarch64-apple-darwin.tar.gz (No such file or directory)
```
Closes …
> [7.3.0] Ensure that downloads are cancelled on repo rule restart

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
When a repository rule is restarted due to memory pressure, all its downloads must be interrupted. While this happened for `repository_ctx.download`, the `download_and_extract` method did not register its `PendingTask`. Since downloads happen on a separate executor, they would continue even through restarts, leading to warnings (see below) or even left over download temp directories.
```
WARNING: Download from https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.26-aarch64-apple-darwin.tar.gz failed: class java.io.FileNotFoundException /private/var/tmp/_bazel_fmeum/0465a0857e26a35c072f48ab751a1794/external/aspect_bazel_lib~~toolchains~coreutils_darwin_arm64/temp2576567839043404337/coreutils-0.0.26-aarch64-apple-darwin.tar.gz (No such file or directory)
```
Closes …
> [7.2.1] Ensure that downloads are cancelled on repo rule restart

- tools/cpp/BUILD.tpl
- tools/cpp/unix_cc_configure.bzl
- tools/cpp/unix_cc_toolchain_config.bzl
With `-std=c++20`, Clang defaults to using C++ modules rather than Clang modules, which can result in failures when using `layering_check` and thus `use_module_maps`.
Fixes https://github.com/bazel-contrib/toolchains_llvm/issues/334
Closes #22660.
PiperOrigin-RevId: 642548168
Change-Id: Ie1dd4c482d716635f7b6c53ffd3c5d84b6aa8cc2
Commit https://github.com/bazelbuild/bazel/commit/9e913fbfa2e3930742fc30dfb60ac5e2694c70cf
> [7.3.0] Force use of Clang over C++ modules with `use_module_maps`

- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
- src/test/shell/bazel/bazel_sandboxing_test.sh
This would make the bind mount fail, which would cause the sandbox to be terminated.
Fixes https://github.com/bazelbuild/bazel/issues/4963
PiperOrigin-RevId: 643257634
Change-Id: I19d83ba2413a1d3c6606e7ea381dff2b71922e86
Commit https://github.com/bazelbuild/bazel/commit/b6bb80078633438be4c8b3537a0ec8d7f8ae3825
> [7.3.0] Don't try to bind mount non-existent paths in the sandbox.

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
- src/test/py/bazel/bzlmod/bazel_overrides_test.py
`--override_module=foo=` will discard previous overrides specified by this option.
Closes #22751.
PiperOrigin-RevId: 644253498
Change-Id: If723756433545bfc875d7f877d596f2e3f041464
Commit https://github.com/bazelbuild/bazel/commit/82e31358549f7614497bf9d9fe8d16415a49eece
> [7.3.0] Allow discard previous overrides for --override_repository and --override_module

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
- src/test/py/bazel/bzlmod/bazel_overrides_test.py
`--override_module=foo=` will discard previous overrides specified by this option.
Closes #22751.
PiperOrigin-RevId: 644253498
Change-Id: If723756433545bfc875d7f877d596f2e3f041464
Commit https://github.com/bazelbuild/bazel/commit/82e31358549f7614497bf9d9fe8d16415a49eece
> [7.2.1] Allow discard previous overrides for --override_repository and --override_module

- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
Previously, it only retries when we have error whose message contains "connection reset by peer". In some cases, we could also have message like "Connection reset", e.g. https://buildkite.com/bazel/bazel-bazel-macos-ninja/builds/1827#01902690-f35a-4f3d-9166-7b39c1f885fb.
PiperOrigin-RevId: 644325070
Change-Id: I75500646b35681fda25e584ec5d6ec3348cee9a5
> [7.3.0] Retry on connection reset error for http cache.

- src/main/java/com/google/devtools/build/lib/actions/SpawnResult.java
- src/main/java/com/google/devtools/build/lib/exec/local/LocalSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/AbstractSandboxSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/shell/ExecutionStatistics.java
- src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
This was already the case for "local" spawns. Statistics may be missing if the spawn wrapper exits abnormally.
Fixes #22151.
Closes #22780.
PiperOrigin-RevId: 644378541
Change-Id: Ia3d792f380b78945523f21875c593744b60f0c81
Commit https://github.com/bazelbuild/bazel/commit/ec41dd1fe71380ac724399839f5bf22c3969f24b
> [7.2.1] Do not fail a sandboxed spawn for missing execution statistics

- src/main/cpp/rc_file.cc
- src/test/cpp/rc_file_test.cc
- src/test/cpp/rc_options_test.cc
Fixes #22685.
PiperOrigin-RevId: 644377301
Change-Id: I05e7e01f1b4f79c219aa974871efcbc41966966c
Commit https://github.com/bazelbuild/bazel/commit/7b02eaa837fabf0e3d0e810690e51d55506529ab
> [7.3.0] Use the generic term "config file" instead of the product-specific ".blazerc" in error messages.

- src/main/java/com/google/devtools/build/lib/actions/SpawnResult.java
- src/main/java/com/google/devtools/build/lib/exec/local/LocalSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/sandbox/AbstractSandboxSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/shell/ExecutionStatistics.java
- src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
This was already the case for "local" spawns. Statistics may be missing if the spawn wrapper exits abnormally.
Fixes #22151.
Closes #22780.
PiperOrigin-RevId: 644378541
Change-Id: Ia3d792f380b78945523f21875c593744b60f0c81
Commit https://github.com/bazelbuild/bazel/commit/ec41dd1fe71380ac724399839f5bf22c3969f24b
> [7.3.0] Do not fail a sandboxed spawn for missing execution statistics

- src/main/java/com/google/devtools/build/lib/vfs/FileSystemUtils.java
- src/test/shell/bazel/bazel_sandboxing_test.sh
Similar to https://github.com/bazelbuild/bazel/commit/547f0c6955942e6aafd279adbb2f5368a7a2347e, but also includes the r and x bits.
Fixes #22260.
PiperOrigin-RevId: 644705156
Change-Id: I5354db76dd2c375a6e686fb4808649053b24c500
Commit https://github.com/bazelbuild/bazel/commit/fb05e916ddf18dc06ef1fdde5063de6c49cee5c1
> [7.3.0] Fix permissions on tree artifact subdirectories as needed to move them out of the sandbox.

- src/main/java/com/google/devtools/build/lib/vfs/FileSystemUtils.java
- src/test/shell/bazel/bazel_sandboxing_test.sh
Similar to https://github.com/bazelbuild/bazel/commit/547f0c6955942e6aafd279adbb2f5368a7a2347e, but also includes the r and x bits.
Fixes #22260.
PiperOrigin-RevId: 644705156
Change-Id: I5354db76dd2c375a6e686fb4808649053b24c500
Commit https://github.com/bazelbuild/bazel/commit/fb05e916ddf18dc06ef1fdde5063de6c49cee5c1
> [7.2.1] Fix permissions on tree artifact subdirectories as needed to move them out of the sandbox.

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionContext.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
- src/test/py/bazel/bzlmod/bazel_module_test.py
- src/test/shell/bazel/jdeps_test.sh
`StarlarkBaseExternalContext` now implements `AutoCloseable` and, in `close()`:
1. Cancels all pending async tasks.
2. Awaits their termination.
3. Cleans up the working directory (always for module extensions, on failure for repo rules).
4. Fails if there were pending async tasks in an otherwise successful evaluation.
Previously, module extensions didn't do any of those. Repo rules did 1 and 4 and sometimes 3, but not in all cases.
This change required replacing the fixed-size thread pool in `DownloadManager` with virtual threads, thereby resolving a TODO about not using a fixed-size thread pool for the `GrpcRemoteDownloader`.
Work towards #22680
Work towards #22748
Closes #22772
PiperOrigin-RevId: 644669599
Change-Id: Ib71e5bf346830b92277ac2bd473e11c834cb2624
Closes #22775
> [7.2.1] Enforce and await cleanup in `StarlarkBaseExternalContext`

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
This avoids collisions between overlay files and regular BCR files such as `source.json`.
Overlay support has been released in 7.2.0, but hasn't been used in the BCR yet.
Closes #22811.
PiperOrigin-RevId: 645071272
Change-Id: Ib05855a728ebb09795bf70afb14457e9e6d23bf0
Commit https://github.com/bazelbuild/bazel/commit/36da00463d4b645752d1be7c5b8d41139d3b8811
> [7.2.1] Locate BCR module overlay files under the `overlay` subdirectory

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/UrlRewriter.java
There is an [open issue](https://github.com/bazelbuild/bazel/issues/22104) where bazel will occasionally fail at start up time because it is unable to parse the downloader config. While I've yet to create a reliable reproduction for this issue, the one time I've triggered this error with a build with additional logging, it seemed to be because the current working directory wasn't the root of the workspace. While I'm not sure this will actually fully resolve the problem (since I don't know what's causing it) being clearer about where the config file is meant to be can only be a Good Thing.
Addresses #22104
Closes #22770.
PiperOrigin-RevId: 645115556
Change-Id: I7e9bea1c55a106cd767ebfd6d557a7c59c47cd66
Commit https://github.com/bazelbuild/bazel/commit/0e220f03f154cbb5e52190e1085b01173f301c02 …
> [7.2.1] Be more precise about where to read the URL rewriter config from

- src/main/java/com/google/devtools/build/lib/skyframe/LocalRepositoryLookupFunction.java
- src/test/py/bazel/bzlmod/bazel_module_test.py
This still leaves the question of "what do we do instead?". See issues #22208 and #21515.
Fixes https://github.com/bazelbuild/bazel/issues/22754.
Closes #22774.
PiperOrigin-RevId: 645148811
Change-Id: Ib9d07d2ecbc3a79e3341de6739de1c3349124d6b
Commit https://github.com/bazelbuild/bazel/commit/1246ff498b51acb92776efb9402c40f54d83fdee
> [7.2.1] Do not eval WORKSPACE in LocalRepositoryLookupFunction when `--noenable_workspace`

- src/main/java/com/google/devtools/build/lib/analysis/RepoMappingManifestAction.java
- src/main/java/com/google/devtools/build/lib/analysis/SourceManifestAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/AbstractFileWriteAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/BinaryFileWriteAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/FileWriteAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/LauncherFileWriteAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/LazyWriteNestedSetOfTupleAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/LazyWritePathsFileAction.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/ParameterFileWriteAction.java
- src/main/java/com/google/devtools/build/lib/analysis/extra/ExtraActionInfoFileWriteAction.java
- src/main/java/com/google/devtools/build/lib/analysis/test/BaselineCoverageAction.java
- src/main/java/com/google/devtools/build/lib/analysis/test/InstrumentedFileManifestAction.java
- src/main/java/com/google/devtools/build/lib/rules/android/AndroidDeployInfoAction.java
- src/main/java/com/google/devtools/build/lib/rules/android/WriteAdbArgsAction.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppModuleMapAction.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/UmbrellaHeaderAction.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/WriteBuildInfoHeaderAction.java
- src/main/java/com/google/devtools/build/lib/rules/genquery/GenQuery.java
- src/main/java/com/google/devtools/build/lib/rules/java/WriteBuildInfoPropertiesAction.java
- src/main/java/com/google/devtools/build/lib/rules/python/PyBuiltins.java
- src/test/java/com/google/devtools/build/lib/analysis/actions/AbstractFileWriteActionTest.java
Getting rid of the single boolean field on `AbstractFileWriteAction` reduces padding on each subclass instance and in particular frees up a 4-byte field on `CppModuleMapAction`.
Also use a lambda to define `newDeterministicWriter` if possible for improved readability.
This prepares for future changes that will add fields to `CppModuleMapAction` to support path mapping.
Closes #22609.
PiperOrigin-RevId: 643340715
Change-Id: Id3af26049098e6dfa731f0e7a1be6709bea0d9f2
Closes #22749 
Closes #22750
> [7.3.0] Push `makeExecutable` down into `AbstractFileWriteAction` subclasses

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionContext.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
- src/test/py/bazel/bzlmod/bazel_module_test.py
`StarlarkBaseExternalContext` now implements `AutoCloseable` and, in `close()`:
1. Cancels all pending async tasks.
2. Awaits their termination.
3. Cleans up the working directory (always for module extensions, on failure for repo rules).
4. Fails if there were pending async tasks in an otherwise successful evaluation.
Previously, module extensions didn't do any of those. Repo rules did 1 and 4 and sometimes 3, but not in all cases.
This change required replacing the fixed-size thread pool in `DownloadManager` with virtual threads, thereby resolving a TODO about not using a fixed-size thread pool for the `GrpcRemoteDownloader`.
Work towards #22680
Work towards #22748
Closes #22772.
PiperOrigin-RevId: 644669599
Change-Id: Ib71e5bf346830b92277ac2bd473e11c834cb2624
Closes #22776
> [7.3.0] Enforce and await cleanup in `StarlarkBaseExternalContext`

- src/main/cpp/blaze.cc
- src/main/cpp/util/file_platform.h
- src/main/cpp/util/file_posix.cc
- src/main/cpp/util/file_windows.cc
This is required for UTF-8 to be rendered properly in a terminal (e.g. for `bazel mod graph`).
Closes #22874.
PiperOrigin-RevId: 646592183
Change-Id: I33692986301ea472462ad0e6da9634bd580c8a5f
Commit https://github.com/bazelbuild/bazel/commit/4a5fe6207eb596effc13fe6b8e862727dc03eda6
> [7.3.0] Switch to a UTF-8 codepage in the client on Windows

- src/main/java/com/google/devtools/build/lib/skyframe/LocalRepositoryLookupFunction.java
- src/test/py/bazel/bzlmod/bazel_module_test.py
This still leaves the question of "what do we do instead?". See issues #22208 and #21515.
Fixes https://github.com/bazelbuild/bazel/issues/22754.
Closes #22774.
PiperOrigin-RevId: 645148811
Change-Id: Ib9d07d2ecbc3a79e3341de6739de1c3349124d6b
Commit https://github.com/bazelbuild/bazel/commit/1246ff498b51acb92776efb9402c40f54d83fdee
> [7.3.0] Do not eval WORKSPACE in LocalRepositoryLookupFunction when `--noenable_workspace`

- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/main/java/com/google/devtools/build/lib/remote/http/DownloadTimeoutException.java
Address https://github.com/bazelbuild/bazel/issues/20559#issuecomment-2203999686.
PiperOrigin-RevId: 649360592
Change-Id: I50ac2ed3b54d6cffb5f96d3f8315279786c4f30f
> [7.3.0] Retry HTTP download on timeout.

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
We are moving android tests out of Bazel repo.
PiperOrigin-RevId: 650742822
Change-Id: I2a0363b91420e744cdeeecc82eebfbcd727d306d
> [7.3.0] Disable android tests in Bazel presubmit and postsubmit.

- src/main/java/com/google/devtools/build/lib/rules/genquery/GenQueryConfiguration.java
This is not a cherry-pick, but a dedicated fix for Bazel 7.x. Bazel 8 is not affected as the switch to the Starlarkified exec configuration has already resolved this problem.
Fixes #14169
> Preserve `--experimental_skip_ttvs_for_genquery` in the exec cfg

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
Documenting the default caching behaviour for `rctx.download` and `rctx.download_and_extract`.
 
Related to #22652
Closes #22716.
PiperOrigin-RevId: 653878029
Change-Id: I129f9eede2b841483a98d5335651c1d1198aaf76
Commit https://github.com/bazelbuild/bazel/commit/d4b416f503d9e202dec0b24905366109ace43165
> [7.3.0] Document source of truth for `rctx.download*` cache key

- tools/java/runfiles/Runfiles.java
`Runfiles` insurance are cheap, `Preloaded` instances are costly.
Closes #23006.
PiperOrigin-RevId: 654661845
Change-Id: I46ee31718a2c5753d983b9c741547fe2a1de5d88
Commit https://github.com/bazelbuild/bazel/commit/7d266153af8516cfcd78f9e986a806566b205b27
> [7.3.0] Fix javadocs for Runfiles

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
In the experimental_remote_cache_async mode, the
cache upload steps were not profiled, unlike in the non-async case.
This adds the profiling back.
Fixes #20404.
It'd be great if this could be backported into 7.3.0 once merged.
Closes #23056.
PiperOrigin-RevId: 655466182
Change-Id: Ib450ba4ea88a8ecdad66c6db0728db901e925017
Commit https://github.com/bazelbuild/bazel/commit/54820bde03e5e9330d3ffa063f7a304ce04701fc
> [7.3.0] --experimental_remote_cache_async: Profile upload events.

- src/main/java/com/google/devtools/build/lib/rules/cpp/HeaderDiscovery.java
- src/test/shell/bazel/bazel_layering_check_test.sh
When clang generates dotd files when using `-fmodule-map-file` any `extern module` directives in the modulemap are included in the dotd file if they exist. The result of this was that with sandboxing disabled the dotd file included transitive cppmap files that weren't in its input set, resulting in build failures. This change excludes those instead since they're not required as evidence by the fact that with sandboxing enabled they are not part of the input set.
Fixes https://github.com/bazelbuild/bazel/issues/21592
Closes #21832.
PiperOrigin-RevId: 656382428
Change-Id: I4bc9802884ce1bc66ceda65a602db8dffbd1d9ea
Commit https://github.com/bazelbuild/bazel/commit/ad53147cc4f4d47c064845ec9612876161ff139e
> [7.3.0] Ignore transitive cppmap files from dotd files

- src/main/java/com/google/devtools/build/lib/bazel/rules/sh/ShBinary.java
- src/main/starlark/builtins_bzl/common/python/py_executable_bazel.bzl
- src/test/java/com/google/devtools/build/lib/blackbox/framework/ProcessRunner.java
- src/test/py/bazel/runfiles_test.py
- src/test/shell/bazel/bazel_windows_example_test.sh
- src/test/shell/bazel/python_version_test.sh
- src/tools/launcher/bash_launcher.cc
- src/tools/launcher/launcher.cc
- src/tools/launcher/launcher.h
- src/tools/launcher/python_launcher.cc
When the Windows launcher binary is copied to become the `executable` of another target, it can't expect to find the main file right next to it. Instead, look it up via `Rlocation`, which doesn't require colocation to find the file. This helps with a common pattern in wrapper rules where `ctx.symlink` is used to work around the limitation that the `executable` of a target has to be produced by that target.
For the Python rules, for which the source of truth is not the Bazel repo anymore, the new launch key is checked for in a backwards compatible way.
Closes #23076.
PiperOrigin-RevId: 657116461
Change-Id: I3f966b48e0812668cfa7bd394f2eaf23d66889b6
Closes #23121
> [7.3.0] Make Window launchers relocatable

- src/main/java/com/google/devtools/build/lib/actions/SpawnResult.java
- src/main/java/com/google/devtools/build/lib/exec/AbstractSpawnStrategy.java
- src/main/java/com/google/devtools/build/lib/exec/BUILD
- src/main/java/com/google/devtools/build/lib/exec/SpawnCache.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/remote/common/RemotePathResolver.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteExecutionServiceTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerTest.java
- src/test/shell/bazel/path_mapping_test.sh
When path mapping is enabled, different `Spawn`s in the same build can have identical `RemoteAction.ActionKey`s and can thus provide remote cache hits for each other. However, cache hits are only possible after the first local execution has concluded and uploaded its result to the cache.
To avoid unnecessary duplication of local work, the first `Spawn` for each `RemoteAction.ActionKey` is tracked until its results have been uploaded and all other concurrently scheduled `Spawn`s wait for it and then copy over its local outputs.
Fixes #21043
Closes #22556.
PiperOrigin-RevId: 655097996
Change-Id: I4368f9210c67a306775164d252aae122d8b46f9b
Closes #23060
> [7.3.0] Deduplicate locally executed path mapped spawns

- src/main/java/com/google/devtools/build/lib/actions/Artifact.java
- src/main/java/com/google/devtools/build/lib/actions/BUILD
- src/main/java/com/google/devtools/build/lib/actions/CommandLines.java
- src/main/java/com/google/devtools/build/lib/vfs/BUILD
- src/main/java/com/google/devtools/build/lib/vfs/PathFragment.java
- src/main/java/com/google/devtools/build/lib/vfs/PathStrippable.java
- src/test/java/com/google/devtools/build/lib/analysis/actions/StrippingPathMapperTest.java
In `CommandLines`, the very first argument of the first command line is always a path to an executable. As such, it should be path mapped, even when it is a string. This wasn't the case for `SpawnAction`'s created via `ctx.actions.run(executable = <some string>)`.
Work towards #22366
Closes #22844.
PiperOrigin-RevId: 656258007
Change-Id: Ia046a7cc66aae51aec764e2f1c49e1d4f69e4b37
Closes #23040
> [7.3.0] Path map executable paths

- src/test/shell/bazel/path_mapping_test.sh
Javac actions gained support for multiplex sandboxing with rules_java 7.5.0, which makes it possible to test path mapping in this mode.
Fixes #21091
Closes #21837.
PiperOrigin-RevId: 657111790
Change-Id: Ib08f2c0bc48d210cce013e328da0e871f73278aa
Commit https://github.com/bazelbuild/bazel/commit/8e79fe0329b995ec6db2f63d5cced84f90d158f3
> [7.3.0] Add path mapping test for multiplex sandboxing

- src/main/java/com/google/devtools/build/lib/cmdline/PackageIdentifier.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/HeaderDiscovery.java
- src/main/java/com/google/devtools/build/lib/skyframe/ActionExecutionFunction.java
https://github.com/bazelbuild/bazel/commit/60924fdc2972184494f6382d39e8c786aa14b9a9 changed the canonical repo name separator from `~` to `+`. Older repo names containing `~` now trigger a syntax error. If an action cache entry refers to an exec path from a previous version of Bazel that used `~`, we need to be resilient and treat the cache entry as corrupted, rather than just crash.
Fixes https://github.com/bazelbuild/bazel/issues/23180.
Closes #23227.
PiperOrigin-RevId: 660105601
Change-Id: Iea5d86c635056d12ba20598383da463bdde03ab0
> [7.3.0] Be resilient to outdated exec paths in action cache entries

- src/main/java/com/google/devtools/build/lib/cmdline/PackageIdentifier.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/HeaderDiscovery.java
- src/main/java/com/google/devtools/build/lib/skyframe/ActionExecutionFunction.java
https://github.com/bazelbuild/bazel/commit/60924fdc2972184494f6382d39e8c786aa14b9a9 changed the canonical repo name separator from `~` to `+`. Older repo names containing `~` now trigger a syntax error. If an action cache entry refers to an exec path from a previous version of Bazel that used `~`, we need to be resilient and treat the cache entry as corrupted, rather than just crash.
Fixes https://github.com/bazelbuild/bazel/issues/23180.
Closes #23227.
PiperOrigin-RevId: 660105601
Change-Id: Iea5d86c635056d12ba20598383da463bdde03ab0
> [8.0.0-pre.20240805.3] Be resilient to outdated exec paths in action cache entries

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileFunction.java
- src/test/py/bazel/bzlmod/bazel_lockfile_test.py
We write a different lockfile version based on `--incompatible_use_plus_in_repo_names` (see HACK in `BazelLockFileModule.java`). But we don't _expect_ a different lockfile version based on that flag; this causes us to consider the lockfile _always_ out-of-date when that flag is set.
Fixes https://github.com/bazelbuild/bazel/issues/23279.
> [7.3.1] Fix expected lockfile version to change based on `--incompatible_use_plus_in_repo_names`

- scripts/docs/BUILD
- scripts/docs/create_release_docs.py
- scripts/docs/rewriter.py
- scripts/docs/rewriter_test.py
- scripts/docs/testdata/expected_output/doc.md
- scripts/docs/testdata/expected_output/markdown_with_html.md
- scripts/docs/testdata/input/doc.md
- scripts/docs/testdata/input/markdown_with_html.md
- site/en/BUILD.bazel
- site/en/_buttons.html
- src/main/java/com/google/devtools/build/docgen/release/TableOfContentsOptions.java
- src/main/java/com/google/devtools/build/docgen/release/TableOfContentsUpdater.java
The header of each docs page now indicates the current version in bold and contains links to the same page for each other release with versioned docs.
The template language usage in this change is based on publicly available information: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/97f69c065e9a049f43a5676b633d181ed0ac8448/plugins/core-plugin/src/main/resources/site-template.md?plain=1
Closes #22725.
PiperOrigin-RevId: 644354576
Change-Id: I7c4e9208a79430d3c56c94674b70296a2a778a5f
Commit https://github.com/bazelbuild/bazel/commit/2562707390fed314e2fb56eb6f92afa964117d25
> [7.3.1] Add a version indicator and selector to all docs pages

- src/main/java/com/google/devtools/build/lib/buildeventservice/BuildEventServiceModule.java
- src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
- src/main/java/com/google/devtools/build/lib/runtime/BuildEventStreamer.java
- src/main/java/com/google/devtools/build/lib/runtime/SynchronizedOutputStream.java
- src/test/java/com/google/devtools/build/lib/runtime/BuildEventStreamerTest.java
- src/test/java/com/google/devtools/build/lib/runtime/SynchronizedOutputStreamTest.java
BES consumers may want to turn the stream of progress events into a view that resembles the terminal output by combining stdout and stderr. In particular in `--curses=on` mode, this resulted in garbled output such as the following due to stdout and stderr being buffered separately:
```
[0 / 3] 3 actions running
INFO: From Executing genrule //:1:
Hello from genrule //:1 on stderr
[1 / 3] 2 actions running
INFO: From Executing genrule //:2:
Hello from genrule //:2 on stdout
[2 / 3] 1 actions running
INFO: From Executing genrule //:3:
Hello from genrule //:3 on stderr
INFO: Build completed successfully, 3 total actions
Hello from genrule //:1 on stdout
Hello from genrule //:2 on stderr
Hello from genrule //:3 on stdout
Hello again from genrule //:3 on stdout
```
when the original output was: …
> [7.4.0] Preserve order between stdout and stderr in BES on a best-effort basis

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodRepoRuleValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GitRepoSpecBuilder.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/InterimModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/LockFileModuleExtension.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Module.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionUsage.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Selection.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/TagClass.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/repository/RepositoryModuleApi.java
- src/main/java/com/google/devtools/build/skydoc/fakebuildapi/repository/FakeRepositoryModule.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodTestUtil.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/StarlarkBazelModuleTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/ModExecutorTest.java
- src/test/tools/bzlmod/MODULE.bazel.lock
Also avoids a pattern that could result in a class initialization deadlock.
Closes #23229.
PiperOrigin-RevId: 660673482
Change-Id: Ie89ffc2e956b6e14b81cfe4462cd97241bf78be3
Closes #23346
> [7.4.0] Remove unused code from Bzlmod package

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryImpl.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/VendorCommand.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloader.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/main/java/com/google/devtools/build/lib/runtime/BlazeRuntime.java
- src/main/java/com/google/devtools/build/lib/runtime/CommandEnvironment.java
- src/main/java/com/google/devtools/build/lib/runtime/CommonCommandOptions.java
- src/main/java/com/google/devtools/build/lib/runtime/ServerBuilder.java
- src/main/java/com/google/devtools/build/lib/skyframe/packages/BazelPackageLoader.java
- src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisMock.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteModuleTest.java
- src/test/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorTest.java
This option sets the global limit for how many parallel HTTP connections bazel will initiate to download files.
Working towards https://github.com/bazelbuild/bazel/issues/19315.
Note: The first four commits of the PR are a refactoring from  #23080. The last commit is a bigger refactoring, moving `HttpDownloader` around further. Commit-by-commit review is encouraged. The hope is to get this PR in before 7.3.0rc1 is cut on Monday.
Closes #23106.
PiperOrigin-RevId: 657111369
Change-Id: I9a848758517cd78cd5a0e1b380bf39625045b77a
Commit https://github.com/bazelbuild/bazel/commit/01d477dc424cf4c61ca828252f3e747c2c5c185e
> [7.4.0] Introduce `--http_max_parallel_downloads`.

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
Lockfile entries that record repo mapping usages for invalid repo names are always invalid. They can lead to confusing situations where updating the lockfile doesn't result in changes, yet running in `error` mode fails with an error saying that the lockfile is not up to date.
Instead, show a warning such as the following that users can forward to the extensions maintainers:
```
WARNING: The module extension @@rules_rust+//rust/private:extensions.bzl%i produced an invalid lockfile entry because it referenced @@[unknown repo 'cui__url-2.5.2' requested from @@rules_rust+]. Please report this issue to its maintainers.
```
Context: https://bazelbuild.slack.com/archives/C014RARENH0/p1723132195268549
Closes #23244.
PiperOrigin-RevId: 661334265
Change-Id: Ib6415cc9911b30d1f9ce493033cd25a347734b7e …
> [7.4.0] Warn if a module extension produces an invalid lockfile entry

- src/main/java/com/google/devtools/build/lib/util/DependencySet.java
PiperOrigin-RevId: 658725449
Change-Id: I09edfa9af8a4956d661174bef76a7f8776891a8b
Commit https://github.com/bazelbuild/bazel/commit/638f293a0f608db0ea6de4e0b58cd61870086db6
> [7.4.0] Apply a workaround for absolute paths in .d files which can lead to cache issues with the Android NDK on Windows.

- src/main/java/com/google/devtools/build/lib/cmdline/BUILD
- src/main/java/com/google/devtools/build/lib/cmdline/RepositoryMapping.java
- src/main/java/com/google/devtools/build/lib/cmdline/RepositoryName.java
- src/test/java/com/google/devtools/build/lib/cmdline/RepositoryMappingTest.java
If `@boo` is parsed in a context in which only `@foo` is visible, the resulting `RepositoryName` object will show as follows in error messages:
```
@@[unknown repo 'boo' requested from @@ (did you mean 'foo'?)]
```
Closes #23184.
PiperOrigin-RevId: 660678414
Change-Id: Iecb5b1d211ff9e1f04ff0f2189376a98b7b261a9
Closes #23189
Closes #23239
> [7.4.0] Show "did you mean" suggestion for unknown repo names

- src/main/java/com/google/devtools/build/lib/buildtool/ExecutionProgressReceiver.java
- src/main/java/com/google/devtools/build/lib/runtime/UiStateTracker.java
While we delay the execution phase progress until we execution real actions (see unknown commit), with Skymeld we could still see the following scenario:
- Bazel completes the analysis for the first top-level target
- Bazel starts execution for the first top-level target, still analyzing other top-level targets
- Bazel completes execution for the first top-level target, still running analysis for other top-level targets
Prior to this CL, we would have reported something like `[42 / 42] checking cached actions` until we continue with execution (after the next top-level target finishes analysis). Now, we do report `[42 / 42] no actions running`.
RELNOTES: Improve progress message in case there are no actions in flight, and display explicitly "no actions running" in that case. …
> [7.4.0] Replace "checking cached actions" message when no action is running.

- src/main/java/com/google/devtools/build/lib/remote/grpc/BUILD
- src/main/java/com/google/devtools/build/lib/remote/grpc/SharedConnectionFactory.java
- src/test/java/com/google/devtools/build/lib/remote/grpc/BUILD
- src/test/java/com/google/devtools/build/lib/remote/grpc/SharedConnectionFactoryTest.java
Such connections are usually not in a recoverable state and should not be used for retries, which would otherwise likely fail in the same way.
Fixes #20868
Closes #23150.
PiperOrigin-RevId: 662091153
Change-Id: Iaf160b11a13af013b9969c7fdaa966bca8ab6be2
Commit https://github.com/bazelbuild/bazel/commit/06691b3073590f68118132017ff30874c533ca6d
> [7.4.0] Do not reuse gRPC connections that fail with native Netty errors

- src/main/java/com/google/devtools/build/lib/sandbox/AbstractSandboxSpawnRunner.java
- src/main/protobuf/failure_details.proto
- src/test/shell/integration/sandboxing_test.sh
Also wrap it in an EnvironmentalExecException, as it seems more appropriate than a UserExecException; introduce separate failure codes while at it.
(We should probably rethink whether SpawnRunner#exec should even be allowed to return a naked IOException, but that's a much larger change.)
Fixes #23283.
PiperOrigin-RevId: 665790329
Change-Id: Ibf12481c19d155dc3d4f95e21df3e8ee305f3512
Commit https://github.com/bazelbuild/bazel/commit/f5df0e759f3d3b69092eae8266e919f29a67529b
> [7.4.0] Improve user-visible error message when an IOException occurs while copying sandbox inputs/outputs.

- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java
- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java
- src/test/shell/bazel/bazel_symlink_test.sh
Unresolved symlinks, when consumed as runfiles with `--experimental_inprocess_symlink_creation`, are now created as symlinks directly pointing to their target path instead of to the absolute path of the unresolved symlink artifact under the execroot, just like with out-of-process symlink creation.
Along the way, fix the propagation of `--experimental_inprocess_symlink_creation` to the exec configuration, which previously would have caused the new test cases to fail open.
Fixes #23327
Closes #23328.
PiperOrigin-RevId: 665754549
Change-Id: I6b240ca27dac513738056b015c97baec91677c4e
Closes #23329
> [7.4.0] Fix in-process materialization of unresolved symlinks in runfiles

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodRepoRuleCreator.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionEvalStarlarkThreadContext.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/BzlmodRepoRuleFunction.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/py/bazel/bzlmod/bazel_module_test.py
Since `Rule` logic drops a call stack entry, errors during repo rule instantiation in a module extension weren't reported with a useful `Location`.
Work towards #19055
Closes #23363.
PiperOrigin-RevId: 665468188
Change-Id: If67b5b6f290ac4e33b5743e9c1c361a93e1217ef
Closes #23364
> [7.4.0] Fix locations reported in repo rule instantiation errors for extensions

- src/main/tools/linux-sandbox-pid1.cc
Without a remount, sys still refers to the parent namespace, so a device created inside the namespace (e.g. tun) won't be shown under /sys/class/net.
Closes #23274.
PiperOrigin-RevId: 666303783
Change-Id: I3e0ddd9a150eb10b581abbf0d165babde7fe28ee
Commit https://github.com/bazelbuild/bazel/commit/448fd0bb11982139a158ea77b845589efbf1236e
> [7.4.0] Remount sys to make /sys/class/net consistent with network namespace.

- src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
- src/main/java/com/google/devtools/build/lib/buildtool/ExecutionTool.java
- src/main/java/com/google/devtools/build/lib/runtime/SkymeldUiStateTracker.java
- src/main/java/com/google/devtools/build/lib/runtime/UiEventHandler.java
- src/main/java/com/google/devtools/build/lib/runtime/UiStateTracker.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java
- src/main/java/com/google/devtools/build/lib/skyframe/TopLevelStatusEvents.java
- src/test/java/com/google/devtools/build/lib/runtime/SkymeldUiStateTrackerTest.java
- src/test/java/com/google/devtools/build/lib/runtime/UiStateTrackerTest.java
- src/test/shell/integration/ui_test.sh
Cherry-pick of the following commits:
* Exclude WorkspaceStatusActions `from execution_phase_time_in_ms` (8a413983fc1c053d1f24b09cb72697d24397ba59)
* Delay execution phase reporting in Skymeld (5744abd7831fec791067ec8e182cd47f82aaaf3e)
Closes #23354
> [7.4.0] Delay execution phase reporting in Skymeld

- src/main/java/com/google/devtools/build/lib/bazel/rules/CcRules.java
- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcStaticLibraryRule.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/cpp/CcModuleApi.java
- src/main/starlark/builtins_bzl/common/cc/action_names.bzl
- src/main/starlark/builtins_bzl/common/cc/cc_common.bzl
- src/main/starlark/builtins_bzl/common/cc/experimental_cc_static_library.bzl
- src/main/starlark/builtins_bzl/common/exports.bzl
- src/main/starlark/tests/builtins_bzl/BUILD
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/BUILD.builtin_test
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/bar.cc
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/bar.h
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/cc_static_library_integration_test.sh
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/foo.cc
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/foo.h
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/lib_only.cc
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/mock_toolchain.bzl
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/starlark_tests.bzl
- src/main/starlark/tests/builtins_bzl/cc/cc_static_library/test_cc_static_library/test.cc
- src/main/starlark/tests/builtins_bzl/cc_builtin_tests.sh
- tools/build_defs/cc/action_names.bzl
- tools/cpp/BUILD.tpl
- tools/cpp/unix_cc_configure.bzl
- tools/cpp/unix_cc_toolchain_config.bzl
- tools/cpp/validate_static_library.sh.tpl
- tools/cpp/windows_cc_toolchain_config.bzl
RELNOTES: The new `cc_static_library` rule produces a static library that bundles given targets and all their transitive dependencies. It has to be enabled via `--experimental_cc_static_library`.
Implements https://docs.google.com/document/d/1jN0LUmp6_-rV9_f-Chx-Cs6t_5iOm3fziOklzBGjGIg/edit
Fixes #1920
Closes #16954.
PiperOrigin-RevId: 661382285
Change-Id: I972afd1a38d50ab4e48d9b3c189f1662b0096bbf
Closes #23192
> [7.4.0] Add experimental `cc_static_library` rule

- src/main/java/com/google/devtools/build/lib/runtime/CommandLinePathFactory.java
- src/test/java/com/google/devtools/build/lib/runtime/CommandLinePathFactoryTest.java
Fixes #23305
Closes #23310.
PiperOrigin-RevId: 665745084
Change-Id: Ib22290e08f62c52c5a596eeabd31b1b910fcf421
Commit https://github.com/bazelbuild/bazel/commit/8b2057e774854fa0a917d3bfdec3a35278e6ee11
> [7.4.0] CommandLinePathFactory: skip empty or relative path elements

- src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainVariables.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileActionTemplate.java
- src/test/java/com/google/devtools/build/lib/remote/util/IntegrationTestUtils.java
- src/test/py/bazel/test_base.py
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/path_mapping_test.sh
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/BUILD
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/ExecutionServer.java
- tools/java/runfiles/BUILD
C++ action templates are now properly path mapped.
Since the default Unix toolchain doesn't support object file groups on macOS, `apple_support` is needed in the test. This requires wiring up `LocalEnvProvider` in the remote worker to get `DEVELOPER_DIR` to be set, which in turn requires improving the runfiles handling for the the worker.
Closes #22890.
PiperOrigin-RevId: 657733074
Change-Id: I132e338d7a44964a8a1aad3062a5c9a4c8e79e57
Commit https://github.com/bazelbuild/bazel/commit/23f3be03262c89e7c2d18a110c187ee5c760af31
> [7.4.0] Add path mapping support for C++ compile action templates

- src/main/java/com/google/devtools/build/lib/runtime/CommonCommandOptions.java
This flag is widely used to integrate Bazel with existing CI and a BES
service. Let's make sure that it's documented.
Closes #19703.
PiperOrigin-RevId: 661331479
Change-Id: Ifae2cfacb734170ebdd898f0c4ef30a80dcae94a
Commit https://github.com/bazelbuild/bazel/commit/bfe268399a08e8873ef66f6512794fcbb2569910
> [7.4.0] document --invocation_id

- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/Checksum.java
- src/test/shell/bazel/external_integration_test.sh
Previously, invalid base64 would crash the Bazel server.
Closes #23410.
PiperOrigin-RevId: 667624565
Change-Id: I7b6b834fd291e9a3dae59df88b29bb378e7663a3
Commit https://github.com/bazelbuild/bazel/commit/1b0ed28013e99fc9b0c99dedbef09537cbf07c6b
> [7.4.0] Handle invalid base64 in SRI

- src/main/java/com/google/devtools/build/lib/skyframe/BUILD
- src/main/java/com/google/devtools/build/lib/skyframe/BuildDriverFunction.java
Prevent an NPE encountered when transitive packages are pruned before planting in BuildDriverFunction.
```
(13:13:58) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'BuildDriverKey of ActionLookupKey: ConfiguredTargetKey{label=//autonomy/planning/corridor_map_generator:extended_corridor_location.orin, config=BuildConfigurationKey[eb69cd8e663e6b9c29ef248d6832d55cd81adb9501937e1bba8017d095e8d982]}' (requested by nodes )
at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
at …
```
> Use retrieved nestedSet for symlink planting

- src/main/tools/linux-sandbox-pid1.cc
See discussion in https://github.com/bazelbuild/bazel/issues/23275.
Fixes #23275.
Fixes #23411.
PiperOrigin-RevId: 667906233
Change-Id: Id6dbaeca015297d1c70339f1e2ccdf2db20e0de7
Commit https://github.com/bazelbuild/bazel/commit/e88a7d982411e3d6bbfb658b88e76944ea5ed720
> [7.4.0] Allow ICMP sockets inside a sandbox.

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkSubrule.java
- src/test/java/com/google/devtools/build/lib/analysis/starlark/StarlarkSubruleTest.java
Fixes https://github.com/bazelbuild/bazel/issues/23282
PiperOrigin-RevId: 667946340
Change-Id: Icac6c4e4c695e5b580c13e9aa9cd7cee608b8e3b
Commit https://github.com/bazelbuild/bazel/commit/1f216b1940c4473b991d7da1c799db057c86fe02
> [7.4.0] Fix attribute lookup for subrules used in aspects

- src/main/java/com/google/devtools/build/lib/analysis/AspectCompleteEvent.java
- src/main/java/com/google/devtools/build/lib/analysis/TargetCompleteEvent.java
- src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java
Note that I have slightly modified the code to make it work with `release-7.4.0` source tree because of missing other commits. More specifically, instead of using `inputMap.getRunfilesTrees()` to get runfiles, it uses `TargetCompleteEvent`.
Working towards #23434.
Original Description:
Previously, we download outputs of toplevel artifacts in CompletionFunction because intermediate targets might be promoted to toplevel by skymeld in the middle of the build. However, it didn't handle runfiles of the target. This CL fixes that.
A test case will be added in a followup CL because it requires changes to skymeld & BwoB to unveil the bug.
Working towards #22367.
PiperOrigin-RevId: 667532830
Change-Id: Idfe2a0b693f103d501c9b24a454c16186468667a
> [7.4.0] Download runfiles in CompletionFunction.

- src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java
- src/main/java/com/google/devtools/build/lib/vfs/JavaIoFileSystem.java
`File#list` is documented to never return `"."` and `".."`.
Closes #23435.
PiperOrigin-RevId: 668327754
Change-Id: I0beb70a82232990a83671485dcd97208ea4bd147
Commit https://github.com/bazelbuild/bazel/commit/bf2eff89d514a4416f8203c2c676d043104fcf37
> [7.4.0] Avoid unnecessary copying in `getDirectoryEntries` implementations

- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialCacheExpiry.java
Also use the supplied current time instead of calling Instant.now().
I don't know how to meaningfully test this; there's so little going on that the test would essentially mirror the implementation.
Fixes #23429.
PiperOrigin-RevId: 668351088
Change-Id: I12f1575e5280330c61361e4cf1b7d9f9231f16eb
Commit https://github.com/bazelbuild/bazel/commit/5209ce7587d4f8da37d7492d91d0aac1b91ab249
> [7.4.0] Fix cache duration computation in CredentialCacheExpiry.

- src/main/java/com/google/devtools/build/lib/packages/SelectorValue.java
- src/test/java/com/google/devtools/build/lib/packages/BuildTypeTest.java
This allows Starlark unit tests to verify that certain `select` expressions are equal.
Closes #19702.
PiperOrigin-RevId: 658825855
Change-Id: I06b52ad10b42b30bbb1506f06bafd336abfc21d7
Commit https://github.com/bazelbuild/bazel/commit/59a2977e3bdfe7d4cf1abda9cf6969722dc953c2
> [7.4.0] Implement `SelectorValue#{equals,hashCode}`

- src/main/java/com/google/devtools/build/lib/runtime/SkymeldUiStateTracker.java
- src/main/java/com/google/devtools/build/lib/runtime/UiStateTracker.java
- src/test/java/com/google/devtools/build/lib/runtime/SkymeldUiStateTrackerTest.java
- src/test/java/com/google/devtools/build/lib/runtime/UiStateTrackerTest.java
A race condition can happen:
- Thread 1: `#writeProgressBar` is called due to `LoadingPhaseStartedEvent`, expecting `buildStatus` to be `TARGET_PATTERN_PARSING`
- Main thread: `LoadingPhaseCompleteEvent` arrives. **`buildStatus` is set to `LOADING_COMPLETE`**. additionalMessage is not yet updated and is still null.
- Thread 1: Seeing that `buildStatus` is now `LOADING_COMPLETE`, it moves forward with that code path => NPE when `additionMessage` is checked.
To fix this NPE, the CL made 2 changes:
1. Synchronize methods that touch `buildStatus`
2. Default `additionalMessage` to an empty string to make the code more robust.
PiperOrigin-RevId: 640061798
Change-Id: I5034fe7692e0641559fb7666eec09cb554e09545
#23484
> [7.4.0] Fix an NPE with the SkymeldUiStateTracker.

- tools/test/test-setup.sh
Fixes #23479.
PiperOrigin-RevId: 670894294
Change-Id: I40319db72123358770a56d217dafb4fc7fd0d467
Commit https://github.com/bazelbuild/bazel/commit/24d165e958fc32d222409a890cc5def7d0fbc9f4
> [7.4.0] Exit if it wasn't possible to zip undeclared outputs because `zip` failed.

- third_party/remoteapis/build/bazel/remote/execution/v2/remote_execution.proto
Updates the file to the state of bazelbuild/remote-apis@0d21f29acdb90e1b67db5873e227051af0c80cdd.
Partial commit for third_party/*, see #23458.
Change-Id: I23a9acf02a6616a89c010cfd415ffa5618382e0e
Commit https://github.com/bazelbuild/bazel/commit/2af3658fda7a8401ea08038df20639ef04daba52
> [7.4.0] Update `remote_execution.proto`

- src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java
- src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
- src/main/native/unix_jni.cc
This is a revert (in spirit) of unknown commit and unknown commit. It restores the ability to use umask(2) to control the effective permissions for created directories, which was present before those changes.
Fixes #23405.
PiperOrigin-RevId: 667972097
Change-Id: I6b154d351d68d27a2470cc2b1c24293722625580
> [7.4.0] Always use 0777 when creating directories, and leave group/other permission bits alone when making an already existing directory writable.

- src/main/java/com/google/devtools/build/lib/remote/LeaseService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
At construction time, the action cache is not loaded so it's always `null`. Change it to lazily get the action cache when cleaning up it.
Fixes #22220.
PiperOrigin-RevId: 672522144
Change-Id: I2de8b33ab78c04a690b17cd261d18d17f8b292ab
Commit https://github.com/bazelbuild/bazel/commit/9187a7ec011504befba2fea98481e37558d7998c
> [7.4.0] Lazily get action cache in lease service.

- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheClient.java
- src/test/java/com/google/devtools/build/lib/remote/http/HttpCacheClientTest.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/OnDiskBlobStoreCache.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/OnDiskHttpCacheServerHandler.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/RemoteWorker.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/http/AbstractHttpCacheServerHandler.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/http/BUILD
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/http/HttpCacheServerInitializer.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/http/InMemoryHttpCacheServerHandler.java
- src/tools/remote/src/test/java/com/google/devtools/build/remote/worker/http/AbstractHttpCacheServerHandlerTest.java
- src/tools/remote/src/test/java/com/google/devtools/build/remote/worker/http/BUILD
So that we can have proper cache eviction integration tests for HTTP cache later.
PiperOrigin-RevId: 672501366
Change-Id: I52048a4498601cfa98cc9695d5ddddc5b93f56b9
> [7.4.0] Use disk cache for HTTP cache server.

- site/en/external/migration.md
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
This makes it easier to realistically test how the root module would behave as a non-root module.
RELNOTES: Overrides in the root MODULE.bazel file are now ignored with `--ignore_dev_dependency`. (Overrides in non-root modules are already ignored.)
Closes #23520.
PiperOrigin-RevId: 672480499
Change-Id: Ifd3a99f4ed462061101fecf918d61989c9f60401
Commit https://github.com/bazelbuild/bazel/commit/bb7a54ceea34f901d415b096767070b0bd35a281
> [7.4.0] Ignore overrides with `--ignore_dev_dependency`

- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteActionContextProvider.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionCache.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java
- src/main/java/com/google/devtools/build/lib/remote/common/BUILD
- src/main/java/com/google/devtools/build/lib/remote/common/LostInputsEvent.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteExecutionServiceTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerWithGrpcRemoteExecutorTest.java
- src/test/shell/bazel/remote/remote_execution_http_test.sh
- src/test/shell/bazel/remote/remote_utils.sh
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/OnDiskHttpCacheServerHandler.java
Previously, it's possible for an HTTP cache to delete CAS entries referenced by AC without deleting the AC itself because HTTP cache doesn't understand the relationship between AC and CAS. This could result in permanent build errors because Bazel always trust the AC from remote cache assuming all referenced CAS entries exist.
Now, we record the digest of lost blobs before build rewinding, so that during the next build, we can ignore the stale AC and continue with execution.
Fixes #18696.
RELNOTES: Added support for using a remote cache that evicts blobs and doesn't have AC integrity check (e.g. HTTP cache).
PiperOrigin-RevId: 672536163
Change-Id: Ic1271431d28333f6d86e5963542d15a133075157
Commit https://github.com/bazelbuild/bazel/commit/5d815790a0f5007068ed87a757e0f20aa80020ad
> [7.4.0] Make HTTP cache works with cache eviction.

- src/main/java/com/google/devtools/build/lib/query2/cquery/CqueryTransitionResolver.java
- src/main/java/com/google/devtools/build/lib/query2/cquery/TransitionsOutputFormatterCallback.java
- src/test/shell/integration/configured_query_test.sh
All errors used to be wrapped in an `InterruptedException` instead of being reported with a message. Also show a warning when an incompatible target is skipped instead of failing the build.
Work towards #21010
Closes #23210.
PiperOrigin-RevId: 660116656
Change-Id: I22651110984e471a6b31dcc59a387f3f85ad49bc
https://github.com/bazelbuild/bazel/commit/300c5867b7d2da1ba32abc20e95662096c2a7a08
> [7.4.0] Don't mask error in `cquery` transitions output formatter

- src/main/java/com/google/devtools/build/lib/packages/Type.java
- src/test/java/com/google/devtools/build/lib/analysis/ConfigurableAttributesTest.java
- src/test/java/com/google/devtools/build/lib/packages/TypeTest.java
Convert values to Starlark values when concating string_list_dict type.
This is because Dict checks that all the values put in it are Starlark valid values. But string_list_dict value is of type List<String>, when Java's List isn't a Starlark value.
Fixes #23065
My first PR to bazel :star_struck: Would love you to review the PR.
Checked that the test didn't pass before the change and did after it.
Closes #23424.
PiperOrigin-RevId: 673463108
Change-Id: Ib2cdce7d94243f4e3bda23203a196fee4e766189
Commit https://github.com/bazelbuild/bazel/commit/f1f8d5829a987854d49913058087765db68fc92c
> [7.4.0] Convert values to Starlark values when concating string_list_dict type

- src/main/java/com/google/devtools/build/lib/actions/ActionOutputDirectoryHelper.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTestBase.java
Fixes #23462.
Closes #23555.
PiperOrigin-RevId: 672863567
Change-Id: I50af46f2ae637fb478e81ae31bd16ac4e306fe40
Commit https://github.com/bazelbuild/bazel/commit/885a6ba3b27366a56e776f8665704eebaeb5199d
> [7.4.0] Ensure parent directories of action outputs are made writable when building without the bytes.

- src/main/java/com/google/devtools/build/lib/packages/BuiltinRestriction.java
- src/main/starlark/builtins_bzl/common/cc/cc_common.bzl
PiperOrigin-RevId: 673946235
Change-Id: If20c63df2877aa948032d97795d88d960d9fa6bc (cherry picked from commit ff2e950b7a8cb763f36d2a679978c5f668160c78)
> [7.4.0] Add `@rules_cc` to the default API allowlist

- src/main/java/com/google/devtools/build/lib/bazel/commands/FetchCommand.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/VendorCommand.java
- src/main/java/com/google/devtools/build/lib/runtime/commands/TargetPatternsHelper.java
- src/test/py/bazel/bzlmod/bazel_fetch_test.py
- src/test/py/bazel/bzlmod/bazel_vendor_test.py
Fixes: https://github.com/bazelbuild/bazel/issues/23628
RELNOTES: Bazel fetch and vendor command now supports --target_pattern_file for specifying target patterns.
Closes #23640.
PiperOrigin-RevId: 676063442
Change-Id: Ibbbf7879dfec4ec10093631fb002f87c9dddc8ef
Commit https://github.com/bazelbuild/bazel/commit/3120d35eed1e9492fb848a2c4ffc7c85e7127a6a
> [7.4.0] Support --target_pattern_file for fetch and vendor command

- src/main/java/com/google/devtools/build/lib/rules/cpp/CcStarlarkInternal.java
- src/main/starlark/builtins_bzl/common/cc/cc_compilation_helper.bzl
- src/test/java/com/google/devtools/build/lib/rules/cpp/StarlarkCcCommonTest.java
So far only the generated header in the virtual includes is tested but the Include path pointing to that directory isnt
This is a testcase to reproduce the suspected error reported here:
- https://github.com/bazelbuild/bazel/issues/23061
Assuming that the location of the file is asserted:
```Java
assertThat(artifactsToStrings(ccInfo.getCcCompilationContext().getDirectPublicHdrs()))
.contains("bin third_party/bar/_virtual_includes/starlark_lib_suffix/starlark_lib.h");
```
Adding a testcase for the include path seems reasonable.
A local run of the testcase shows the error:
```
1) testStripIncludePrefixIncludePath(com.google.devtools.build.lib.rules.cpp.StarlarkCcCommonTest)
value of: getIncludeDirs().onlyElement()
expected: bazel-out/k8-fastbuild/bin/third_party/bar/_virtual_includes/starlar …
```
> [7.4.0] Fix inconsistent virtual include paths

- src/main/java/com/google/devtools/build/lib/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/AspectCollection.java
- src/main/java/com/google/devtools/build/lib/analysis/OutputGroupInfo.java
- src/main/java/com/google/devtools/build/lib/buildtool/BuildRequest.java
- src/main/java/com/google/devtools/build/lib/buildtool/BuildResultPrinter.java
- src/main/java/com/google/devtools/build/lib/runtime/commands/BUILD
- src/main/java/com/google/devtools/build/lib/runtime/commands/TestCommand.java
- src/test/shell/integration/validation_actions_test.sh
While https://github.com/bazelbuild/bazel/commit/cd725834eba3edb53b7a7dd9867363ef1fe00e57 made it so that a rule and an aspect can both specify validation outputs, it accidentally didn't actually merge the `_validation` output groups.
By adding the missing merge logic and having the `ValidateTarget` aspect depend on all other aspects, both a rule and an aspect returning a validation output is now fully supported with `--experimental_use_validation_aspect`.
Closes #23589.
PiperOrigin-RevId: 675294550
Change-Id: I581417bee223f0b6aedbc0ce71cae75cd6609ef7 
(cherry picked from commit 750f0a1c05f56403e3b4a3d08b6d7de6ce3ed7f7)
Fixes #23664
> Fix `_validation` output group merging

- src/main/java/com/google/devtools/build/lib/analysis/PlatformOptions.java
- src/main/java/com/google/devtools/build/lib/analysis/config/FragmentOptions.java
- src/test/java/com/google/devtools/build/lib/analysis/PlatformOptionsTest.java
- src/test/shell/integration/toolchain_test.sh
Because the semantics of `--extra_toolchains` are that the last entry has highest priority, when deduping we need to keep the **last** entry, not the first.
Since nothing else used `dedupeOnly`, remove that entirely.
Fixes #22912.
Closes #23093.
PiperOrigin-RevId: 655696234
Change-Id: Icb5f70c47814803a1455d6b8512d977fa5f13469
Fixes #23095
> [7.4.0] Fix deduping for `--extra_toolchains`.

- src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java
- src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
- src/test/shell/bazel/disk_cache_test.sh
A source edit might have occurred in the interim, putting the test back into a passing state that has been previously stored in the cache. The current logic disables disk/remote caching when rerunning a test following a failure, which causes spurious reexecutions (see issue #11057).
Although this code has been around for a very long time, it seems that it was originally added to ensure that a flaky test failure doesn't become sticky. However, for this purpose it suffices to bust the local cache, as a disk/remote cache should never store failures (if it did, this would not be a complete fix, and we'd have much bigger problems elsewhere). Note that Bazel itself never uploads local failures to a disk/remote cache, but can't control whether a remote executor does.
The fix is to split the …
> [7.4.0] Make it possible to get a disk/remote cache hit for a test following a failure of the same test.

- src/main/java/com/google/devtools/build/lib/actions/ActionExecutionMetadata.java
- src/main/java/com/google/devtools/build/lib/actions/SpawnResult.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/StarlarkAction.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java
- src/main/java/com/google/devtools/build/lib/exec/AbstractSpawnStrategy.java
- src/main/java/com/google/devtools/build/lib/exec/BUILD
- src/main/java/com/google/devtools/build/lib/exec/SpawnCache.java
- src/main/java/com/google/devtools/build/lib/includescanning/SpawnIncludeScanner.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/remote/common/RemotePathResolver.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileAction.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileAction.java
- src/test/java/com/google/devtools/build/lib/actions/SpawnResultTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteExecutionServiceTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerTest.java
- src/test/shell/bazel/path_mapping_test.sh
Cherry-picks the following changes to implement output reuse:
* Deduplicate locally executed path mapped spawns (#22556)
* Fix local execution deduplication to work with optional outputs (#23296)
* Force synchronous upload and reuse of possibly modified spawn outputs (#23382)
* Add support for in-memory outputs to output reuse (#23422)
Fixes #23377
Fixes #23444
Fixes #23457
> [7.4.0] Output reuse

- src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java
- src/main/java/com/google/devtools/build/lib/runtime/ConfigExpander.java
- src/main/java/com/google/devtools/common/options/ArgsPreProcessor.java
- src/main/java/com/google/devtools/common/options/OptionsParser.java
- src/main/java/com/google/devtools/common/options/OptionsParserImpl.java
- src/main/java/com/google/devtools/common/options/ParamsFilePreProcessor.java
- src/test/java/com/google/devtools/common/options/OptionsParserTest.java
- src/test/java/com/google/devtools/common/options/ParamsFilePreProcessorTest.java
- src/test/java/com/google/devtools/common/options/ShellQuotedParamsFilePreProcessorTest.java
- src/test/java/com/google/devtools/common/options/UnquotedParamsFilePreProcessorTest.java
- src/test/py/bazel/options_test.py
This regressed in https://github.com/bazelbuild/bazel/commit/44d395338ab9a27596b0796c14076641f4cb2093.
Fixes #22980
Closes #23105.
PiperOrigin-RevId: 657276908
Change-Id: If2e88455a344082bfbec405c30c148c0d044adb6
Commit https://github.com/bazelbuild/bazel/commit/9fbf427d3c9943f0efa659f9934e77358c64e9a7
> [7.4.0] Fail on inapplicable flags on non-common commands expanded from configs

- site/en/query/language.md
- src/main/java/com/google/devtools/build/lib/query2/engine/Lexer.java
- src/test/java/com/google/devtools/build/lib/query2/engine/LexerTest.java
Unquoted `query` words that start with `@@` are no longer broken on `+`, which allows the usage of unquoted canonical labels in expressions. In the very rare case of a shorthand form of a canonical label referring to a WORKSPACE repo (which contains no `+`), the `+` can be separated by a space to get the original behavior (e.g. `@@foo+bar` no longer means `@@foo//:foo + //bar:bar`,  but `@@foo +bar` does.
Closes #23600.
PiperOrigin-RevId: 673763980
Change-Id: Ie5509647b4e04e2f72b908d609781c79cf7b06d4
Fixes #23601
> [7.4.0] Allow unquoted canonical repository names with `query`

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelFetchAllFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelFetchAllValue.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/FetchCommand.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/FetchOptions.java
- src/test/py/bazel/bzlmod/bazel_fetch_test.py
Also cleans up an unused field on `BazelFetchAllValue`.
Closes #23644.
PiperOrigin-RevId: 676333873
Change-Id: Ida7149a1c5642facaeed7fb68bf9f451016c359c
Commit https://github.com/bazelbuild/bazel/commit/55346791e0a0711ef205c20bc022271c02e0c1c9
> [7.4.0] Only invalidate `configure` repos with `fetch --configure --force`

- MODULE.bazel
- third_party/BUILD
- third_party/upb/01_remove_werror.patch
- third_party/upb/BUILD
With Xcode 16, `upb` fails its own `-Werror` check due to using Clang extensions.
Closes #23667.
PiperOrigin-RevId: 676957876
Change-Id: I8e038b5f879077fefdb5811aff6ae5f56fb4f762
Closes #23668
> [7.4.0] Fix upb build with Clang 16

- src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationContext.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcStarlarkInternal.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainVariables.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CompileBuildVariables.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppModuleMapAction.java
- src/test/java/com/google/devtools/build/lib/rules/cpp/BUILD
- src/test/java/com/google/devtools/build/lib/rules/cpp/CppModuleMapActionTest.java
- src/test/shell/bazel/path_mapping_test.sh
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/ExecutionServer.java
Users can opt into path mapping for C++ module map actions via `--modify_execution_info=CppModuleMap=+supports-path-mapping`. This is achieved by mapping paths in the module map files as well as converting the sequence variable for module map paths to a new structured `ArtifactSequenceVariable`.
Also makes it so that `ExecutionServer` gracefully handles failing commands instead of crashing.
Closes #22957.
PiperOrigin-RevId: 675073116
Change-Id: I13835c7fb01354a89ec5fd141cf892c6b733efe4
Fixes #23178
> [7.4.0] Support `layering_check` with C++ path mapping

- src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionBuilder.java
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/cpp_darwin_integration_test.sh
The `runtime_solib_name` link variable had an incorrect value in the case of a transitive dynamic library. Since non-transitive ("nodeps") dynamic libraries are no longer used on macOS, the `--incompatible_macos_set_install_name` flag didn't have any positive effect.
This PR is intentionally limited to the fix so that it can be cherry-picked into Bazel 7, where it can make the incompatible flag work with the `apple_support` toolchain. A follow-up PR will add the feature to the Unix toolchain and flip the incompatible flag for Bazel 8.
Work towards #12370
Closes #23089.
PiperOrigin-RevId: 668228562
Change-Id: I7524679bfe8c6b8b28c0cb04f46c0d22d0adbe99
Fixes #23185
> [7.4.0] Fix `runtime_solib_name` for `--incompatible_macos_set_install_name`

- src/main/java/com/google/devtools/build/lib/remote/GrpcCacheClient.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteRepositoryRemoteExecutor.java
- src/main/java/com/google/devtools/build/lib/remote/common/RemoteCacheClient.java
- src/main/java/com/google/devtools/build/lib/remote/disk/DiskAndRemoteCacheClient.java
- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheClient.java
- src/main/java/com/google/devtools/build/lib/remote/http/HttpCacheClient.java
- src/test/java/com/google/devtools/build/lib/remote/GrpcCacheClientTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteRepositoryRemoteExecutorTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerTest.java
- src/test/java/com/google/devtools/build/lib/remote/UploadManifestTest.java
- src/test/java/com/google/devtools/build/lib/remote/disk/DiskCacheClientTest.java
- src/test/java/com/google/devtools/build/lib/remote/http/HttpCacheClientTest.java
- src/test/java/com/google/devtools/build/lib/remote/util/InMemoryCacheClient.java
- src/test/shell/bazel/remote/remote_execution_test.sh
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/ActionCacheServer.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/ExecutionServer.java
In-memory outputs marked with the `internal-inline-outputs` execution requirement are now added to the `inline_output_files` hint field of the remote execution and remote cache API, potentially saving a round trip on files that are unconditionally read by Bazel client after spawn execution.
Support for output file inlining has been added to the remote worker implementation.
Fixes #8421.
Closes #23428.
PiperOrigin-RevId: 673938116
Change-Id: Ieaea53502c43f9fc90b99f72dd4cdb4711239dd3 
(cherry picked from commit 56ad5d2551b37bf7ed2bd56c98ec1ce751685c38)
Closes #23511
> [7.4.0] Wire up `internal-inline-outputs` requirement with RE API

- src/test/shell/bazel/cc_integration_test.sh
- tools/cpp/unix_cc_toolchain_config.bzl
When linking a nodeps dynamic library that contains object files produced from tree artifact sources, the library may not contain any references to the symbols in those files. In this case, when wrapping the files in `--start-lib/--end-lib`, they may end up being dropped by the linker, which results in missing symbols compared to a build with `--dynamic_mode=off`.
This is fixed by not wrapping object files into `--start-lib/--end-lib` for the nodeps dynamic library link action.
Fixes bazelbuild/rules_cc#230
Closes #23084.
PiperOrigin-RevId: 667945814
Change-Id: Iec148ad1b86626bb5263fecc9b98b0db89f81ad6
Commit https://github.com/bazelbuild/bazel/commit/164ffa56dfc68151ec7f33701c304fb86a7bebda
> [7.4.0] Do not wrap object files in `--start-lib/--end-lib` for nodeps libraries

- src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java
- src/main/java/com/google/devtools/build/lib/query2/aquery/ActionGraphQueryEnvironment.java
- src/main/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryEnvironment.java
- src/test/shell/integration/configured_query_test.sh
Previously this code was assuming that all cquery target patterns should use the root repository's .bazelignore contents which was incorrect.
Because the way this manifested itself was that when cquery drives populating the graph and when it queries it, it would use different keys, this led to misleading messages about packages not being in scope.
Closes #22142.
PiperOrigin-RevId: 628477138
Change-Id: I84e3381848b843ca9813acdd0762a3b3e4711a90
> [7.4.0] cquery: Factor RepositoryName into fetching ignored packages

- src/main/java/com/google/devtools/build/lib/unix/NativePosixFiles.java
- src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java
- src/main/java/com/google/devtools/build/lib/vfs/JavaIoFileSystem.java
- src/main/native/unix_jni.cc
- src/test/java/com/google/devtools/build/lib/vfs/FileSystemTest.java
- src/test/java/com/google/devtools/build/lib/vfs/JavaIoFileSystemTest.java
Currently, we truncate to second precision. Instead, make use of utimensat(2), which can accommodate up to nanosecond precision, is part of POSIX, and is widely available (Linux, Darwin, OpenBSD, FreeBSD and NetBSD).
PiperOrigin-RevId: 678185275
Change-Id: I307dbc75c8f594e6d70b43ee0bde2226b3015611
> [7.4.0] Use millisecond precision when setting the last modified time on Unix.

- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheClient.java
Fixes #23512.
PiperOrigin-RevId: 678162004
Change-Id: If94854fa02a4ae457507e3d2b20227871f88b068
> [7.4.0] Use NOW_SENTINEL_TIME when refreshing the mtime on a disk cache entry.

- repositories.bzl
- site/en/concepts/build-ref.md
- site/en/concepts/platforms.md
- site/en/configure/attributes.md
- site/en/configure/windows.md
- site/en/contribute/codebase.md
- site/en/docs/configurable-attributes.md
- site/en/extending/macros.md
- site/en/extending/repo.md
- site/en/extending/toolchains.md
- site/en/external/module.md
- site/en/external/overview.md
- site/en/external/registry.md
- site/en/query/language.md
- site/en/query/quickstart.md
- site/en/remote/output-directories.md
- site/en/start/java.md
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/repository/RepositoryModuleApi.java
- src/test/tools/bzlmod/MODULE.bazel.lock
- tools/build_defs/repo/http.bzl
original commits:
* 13ecdf583301a94484a1ae0eb27c56fcf3248dc5
* 114c0c641d128429df32999012f7a1207c3bee02
* 970120f7e3590354191ac4ec4f09e28a3608f813
* 1ab2c824e54fd27896f14c5257ab737815463dc1
* c04a5617d2c960e19177d6299f00a81624857925
> [7.4.0] external dependency doc updates

- .bazelci/build_bazel_binaries.yml
Working towards: https://github.com/bazelbuild/continuous-integration/issues/1402
PiperOrigin-RevId: 665794401
Change-Id: Iee2445c522d5e8e4f78f90703520e4baef0d17b4
Cherry pick of eee5ab3bc1
> [7.4.0] Add ubuntu2004_arm64 to .bazelci/build_bazel_binaries.yml

- BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/PatchUtil.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
- third_party/upb/BUILD
Work towards #19301
RELNOTES: Patches to the module file in `single_version_override` are now effective as long as the patch file lies in the root module.
Closes #23536.
PiperOrigin-RevId: 678347809
Change-Id: I6a3c4664e55cff90c8e42795f95d8ef211348ca9
Closes #23605
> [7.4.0] Apply `single_version_override` patches to module files

- src/main/java/com/google/devtools/build/lib/skyframe/BzlmodRepoRuleFunction.java
- src/test/py/bazel/bzlmod/mod_command_test.py
Fixes #22587
Closes #23125.
PiperOrigin-RevId: 657871750
Change-Id: Iab295f330d0b9fcc30207d04a57ad87dacf480b5
Commit https://github.com/bazelbuild/bazel/commit/86159f17831715d0eb356e5619b939bc11cae287
> [7.4.0] Fix NPE in mod show_repo

- src/main/starlark/builtins_bzl/common/cc/cc_compilation_helper.bzl
This showed up in Starlark CPU profiles and is not negligible as it repeatedly checks allowlists.
Closes #23256.
PiperOrigin-RevId: 671444687
Change-Id: I6e64b0c94332a54fcc5d531ff0e3aab176b7bd0a
Commit https://github.com/bazelbuild/bazel/commit/b85db78de3b25cb7f5c9cb0c7afe388f75e040e3
> [7.4.0] Deduplicate calls to `config.is_sibling_repository_layout()`

- src/main/java/com/google/devtools/build/lib/buildeventservice/BazelBuildEventServiceModule.java
- src/test/java/com/google/devtools/build/lib/buildeventservice/BazelBuildEventServiceModuleTest.java
Fixes https://github.com/bazelbuild/bazel/issues/20681
Closes #20684.
PiperOrigin-RevId: 595228741
Change-Id: I06bab1efa25deaa4085acfffd350dc62f9f73aa3
> [7.4.0] Gracefully handle setting the same header with --bes_header twice.

- src/main/java/com/google/devtools/build/lib/remote/BUILD
- src/main/java/com/google/devtools/build/lib/remote/RemoteOutputChecker.java
This allows Kythe extraction to work with BwoB.
Closes #23669.
PiperOrigin-RevId: 676371827
Change-Id: I354cb9b9c0ec3511c6d866956fca1ff06a27cfab
Commit https://github.com/bazelbuild/bazel/commit/055314eb8694c827931340583aa125b40f0673bb
> [7.4.0] Fetch extra action outputs with `--remote_download_toplevel`

- src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainVariables.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppActionConfigs.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/LibrariesToLinkCollector.java
- src/test/java/com/google/devtools/build/lib/packages/util/mock/osx_cc_toolchain_config.bzl
- src/test/java/com/google/devtools/build/lib/rules/cpp/LibraryToLinkValueTest.java
- tools/cpp/osx_cc_wrapper.sh.tpl
The toolchain was passing -l:name. This mechanism doesn' t exist on macOS,
instead the full path to the shared library should be passed.
This is a cherry pick of f0ade80ce920be0719b1a43a40258397f68a944d and eb50e5b83bc0f54e7409f553b67a33b8793b7508
> [7.4.0] Fix versioned shared libraries for macOS toolchain

- src/tools/launcher/BUILD
- src/tools/launcher/launcher_maker.cc
`//tools/launcher:launcher_maker` produces launchers *for* Windows, but there is no reason why it must *run on* Windows. By making it runnable on all platforms, `*_binary` targets can be built *for* Windows from any platform assuming that a suitable cross-compiling C++ toolchain is available.
Closes #23731.
PiperOrigin-RevId: 679251350
Change-Id: I1b380d5b28a616ace88a3b049a2b4554aa209ae3
Commit https://github.com/bazelbuild/bazel/commit/108f1171c18387f80596e8709c7b7552c47fe457
> [7.4.0] Make `launcher_maker` cross-platform

- src/main/java/com/google/devtools/build/lib/bazel/repository/DecompressorValue.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/DecompressorValueTest.java
In some (legacy) projects, nuget is used to handle C++ packages.
Nuget packages are working fine with WORKSPACE `http_archive` directives when explicitly specifying `type = "zip"`.
However, when migrating to bzlmod, we ran into issues when the url in source.json is a nupkg file.
This PR resolves that issue and allows consumption of nupkg archives as Bazel modules.
Closes #23645.
PiperOrigin-RevId: 680636414
Change-Id: Ia7fd3fc738a2dd68b1063dba0dc847c5b0668401
Commit https://github.com/bazelbuild/bazel/commit/b38703665f1324b04ce12d4a84443077510f8ee4
> [7.4.0] Allow decompression of nupkg

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/JsonOutputFormatter.java
Otherwise `"<root>"` ends up being escaped with Unicode escape sequences, which is unnecessarily complex.
Work towards #22691
Closes #23785.
PiperOrigin-RevId: 680633877
Change-Id: Ic3c90c33bbf1209efa90be78b432e2132f0a1f05
Commit https://github.com/bazelbuild/bazel/commit/e959d78517abc0f50b2251e8225355a96e4c59d1
> [7.4.0] Don't HTML escape `bazel mod` JSON output

- .bazelrc
Mitigating #23726
PiperOrigin-RevId: 678213406
Change-Id: I99ea19f3dcf56a359e39274ce9043a6b4f64b6a4
Backporting https://github.com/bazelbuild/bazel/commit/355b000accfff4ea29876a46321308fe9422a9d1#diff-544556920c45b42cbfe40159b082ce8af6bd929e492d076769226265f215832fR85
> [7.4.0] Temporarily allow network access in sandbox for macos

- src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
- src/main/java/com/google/devtools/build/lib/exec/ExecutionOptions.java
Fixes #18643.
PiperOrigin-RevId: 678723961
Change-Id: I3da378d2009de2632228d1e914ae451c96cf5b75
> [7.4.0] Declare the compact execution log format to be stable.

- site/en/remote/cache-remote.md
* Recommend the compact format over the binary and JSON formats.
* Note that `//src/tools/execlog:parser` can be used with any format.
* Note that `//src/tools/execlog:converter` can be used to convert between formats.
PiperOrigin-RevId: 680941049
Change-Id: I81caf27a4ff6aef0ea97667df5ccbba1c3f10d58
> [7.4.0] Update https://bazel.build/remote/cache-remote in light of recent improvements.

- src/main/java/com/google/devtools/build/lib/bazel/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
- src/test/shell/bazel/bazel_execlog_test.sh
Previously the execution logs were always written to relative paths.
This caused an issue if you put this flag in your `.bazelrc` and
expected the log to be produced in a relative directory. You can now use
`%workspace%` to handle writing to the root of your workspace.
Fixes https://github.com/bazelbuild/bazel/issues/22267
Closes #23813.
PiperOrigin-RevId: 682196916
Change-Id: I5f6fe3c72cfc3fe9a891e0d44440cb49bbc787d8
Commit https://github.com/bazelbuild/bazel/commit/9aaeb9fe2c1edaca38f91c53a5620a2df2220302
> [7.4.0] Support %workspace% in execution log paths

- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
- src/test/java/com/google/devtools/build/lib/exec/CompactSpawnLogContextTest.java
- src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java
The cherry-pick of the compact execlog runfiles changes assumed that runfiles only appear in the top-level tool nested set, but this isn't true for genrules. Instead, as in Bazel 8, it can be assumed that all middleman are also contained in inputs, which makes it possible to remove the extra middleman parameter and pass all runfiles tree information down to transitive log calls.
Fixes #23884
> [7.4.0] Fix NPE in execlog when runfiles middleman are not top-level

- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
- src/test/shell/integration/sandboxing_test.sh
Fixes #23754
Closes #23755.
PiperOrigin-RevId: 679472028
Change-Id: I0ea922ee6edf28c5643c6f2b524371f1d5405c9c
Commit https://github.com/bazelbuild/bazel/commit/765d5e0a64926517d686ff567d280914df08e7dc
> [7.4.0] Create writable dirs under hermetic tmp in the sandbox

- bazel_downloader.cfg
- src/main/java/com/google/devtools/build/lib/skyframe/BUILD
- src/main/java/com/google/devtools/build/lib/skyframe/IgnoredPackagePrefixesFunction.java
- src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewTestCase.java
- src/test/java/com/google/devtools/build/lib/packages/util/PackageLoadingTestCase.java
- src/test/java/com/google/devtools/build/lib/pkgcache/IncrementalLoadingTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/GlobFunctionTest.java
- src/test/py/bazel/bzlmod/bazel_vendor_test.py
- Adding `--vendor_dir` to ignored package prefixes as if it's added in the `.bazelignore` file.
- This allows users to do `bazel build //...` after vendoring external deps in the source root without manually adding the vendor dir in `.bazelignore`.
Fixes https://github.com/bazelbuild/bazel/issues/23521
Closes #23771.
PiperOrigin-RevId: 680994986
Change-Id: I9c8b76ca20b9060232dfe05460a8fc857c92e93f
Backporting https://github.com/bazelbuild/bazel/commit/d42301b0714ab80aa376715995bc73849a451638
> [7.4.0] Automatically ignore vendor dir for finding packages

- src/main/java/com/google/devtools/build/lib/packages/BuiltinRestriction.java
Closes #23873.
PiperOrigin-RevId: 682416574
Change-Id: I531cbdadac035bb14585eafe5be093823bca2214
(cherry picked from commit cab7d45d39b01f5b3d668ecc747cc2c456330b18)
Closes #23874
> [7.4.0] Allow `rules_shell` to use private APIs

- src/main/java/com/google/devtools/build/lib/actions/BUILD
- src/main/java/com/google/devtools/build/lib/actions/ResourceManager.java
- src/main/protobuf/failure_details.proto
- src/test/java/com/google/devtools/build/lib/actions/ResourceManagerTest.java
Before:
```
Caused by: java.util.NoSuchElementException: Resource foo is not tracked in this resource set.
at com.google.devtools.build.lib.actions.ResourceManager.assertExtraResourcesTracked(ResourceManager.java:499)
at com.google.devtools.build.lib.actions.ResourceManager.areResourcesAvailable(ResourceManager.java:540)
```
After:
```
ERROR: src/test/java/com/google/devtools/build/lib/actions/BUILD:102:10: Testing //src/test/java/com/google/devtools/build/lib/actions:ActionsTests failed: Resource foo is not being tracked by the resource manager. Available resources are: cpu, memory
```
Fixes #19572
Closes #23541.
PiperOrigin-RevId: 682282327
Change-Id: Ifdff5f85de9e45ac119c2a2cfd161c054a722546 
(cherry picked from commit e5ab94bfdebb4a08b8849befbb40d7592485e4ee)
Closes #23868
> [7.4.0] Do no crash if a requested resource is not available

- src/main/java/com/google/devtools/build/lib/analysis/SourceManifestAction.java
- src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java
- src/main/protobuf/failure_details.proto
- src/main/tools/build-runfiles-windows.cc
- src/main/tools/build-runfiles.cc
- src/test/java/com/google/devtools/build/lib/analysis/BUILD
- src/test/java/com/google/devtools/build/lib/analysis/SourceManifestActionTest.java
- src/test/shell/bazel/bazel_determinism_test.sh
- src/test/shell/bazel/workspace_test.sh
- src/test/shell/integration/runfiles_test.sh
- tools/bash/runfiles/runfiles.bash
- tools/bash/runfiles/runfiles_test.bash
- tools/cpp/runfiles/runfiles_src.cc
- tools/cpp/runfiles/runfiles_test.cc
- tools/java/runfiles/Runfiles.java
- tools/java/runfiles/testing/RunfilesTest.java
(contains the refactor in f311efc565c8e0eeddd5283834df69f69c860601 to reduce merge conflicts)
Adds support for spaces and newlines in source and target paths of runfiles symlinks to `build-runfiles` as well as to the Bash, C++, and Java runfiles libraries (the Python runfiles library has moved out of the repo).
If a symlink has spaces or newlines in its source path, it is prefixed with a space in the manifest and spaces, newlines, and backslashes in the source path are escaped with `\s`, `\n`, and `\b` respectively. This scheme has been chosen as it has the following properties:
1. There is no change to the format of manifest lines for entries whose source and target paths don't contain a space. This ensures compatibility with existing runfiles libraries.
2. There is even no change to the …
> [7.4.0] Allow all characters in runfile source and target paths

- src/main/java/com/google/devtools/build/lib/actions/PathMapper.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/StrippingPathMapper.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainVariables.java
- src/test/shell/bazel/path_mapping_test.sh
This allows path mapping to apply to actions that reference execpaths in custom compiler options via location expansion.
Closes #23630.
PiperOrigin-RevId: 680941133
Change-Id: Ia10e2df481dcfe4480cbf9dfb1e12ec3b07d8ab2
Commit https://github.com/bazelbuild/bazel/commit/b4b35af91283709689ffca37c4d1eb4f5eee0c30
> [7.4.0] Heuristically path map copts and defines

- tools/cpp/unix_cc_toolchain_config.bzl
This cherry picks 62dc3b5b3b31fe53e25d253f501eeed21ab4ae48 and 0b0d90844a82908a436c21ad388a8e7a4e809d90 which allows setting install_name and soname on shared libraries. No defaults changed here.
Fixes https://github.com/bazelbuild/bazel/issues/23842
> [7.4.0] Cherry pick install_name and soname features

- src/main/java/com/google/devtools/build/lib/bazel/BazelWorkspaceStatusModule.java
On windows, bazel will run the workspace_status_command, and receive carriage return characters \r even if the workspace_status_command did not include them.
Fixes https://github.com/bazelbuild/bazel/issues/13442
PiperOrigin-RevId: 684055158
Change-Id: Idd3bd9c954d64b0a2d674dd7d90cf61c00955917
> Trim Workspace Status values

- src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl
- src/test/java/com/google/devtools/build/lib/rules/cpp/CcLibraryConfiguredTargetTest.java
Fixes https://github.com/bazelbuild/bazel/issues/23885
Closes #23102.
PiperOrigin-RevId: 684433748
Change-Id: I12cdb9a04f930a52e57bbd8551c8f2559a15932a
Commit https://github.com/bazelbuild/bazel/commit/c2d316b4d3f832d0c5677f0abc63c27d059873b8
> [8.0.0] Add additional_compiler_inputs support to local_defines/defines

- src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java
The logic picked the first instead of the highest version due to a typo.
Closes #23936.
PiperOrigin-RevId: 684528776
Change-Id: Ic61c84ca2f3489e43fc71944824e7e2311543ab9
Commit https://github.com/bazelbuild/bazel/commit/4e6a28acbe11e50e2c3336d42c8075293e26b0af
> [8.0.0] Fix version resolution in `AutoloadSymbols`

- src/main/starlark/builtins_bzl/common/java/java_common.bzl
PiperOrigin-RevId: 685675470
Change-Id: I1194e08ab32f881b84cf7324fdb954dd3f0ce22c (cherry picked from commit 0d5673a6cdb232238567f491dc94a0b5ca07258e)
> [8.0.0] Expose required symbols for migrating the remaining java rules code out of Bazel

- src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java
The logic picked the first instead of the highest version due to a typo.
Closes #23936.
PiperOrigin-RevId: 684528776
Change-Id: Ic61c84ca2f3489e43fc71944824e7e2311543ab9
> [7.4.0] Fix version resolution in AutoloadSymbols

- src/main/starlark/builtins_bzl/common/java/java_common.bzl
PiperOrigin-RevId: 685675470
Change-Id: I1194e08ab32f881b84cf7324fdb954dd3f0ce22c (cherry picked from commit 0d5673a6cdb232238567f491dc94a0b5ca07258e)
> [7.4.0] Expose required symbols for migrating the remaining java rules code out of Bazel

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkAttrModule.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkAttributesCollection.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleContext.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkAttrModuleApi.java
- src/main/java/com/google/devtools/build/skydoc/fakebuildapi/FakeStarlarkAttrModuleApi.java
- src/main/java/com/google/devtools/build/skydoc/rendering/proto/stardoc_output.proto
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleClassFunctionsTest.java
This really just exposes the existing LABEL_DICT_UNARY type that already exists in Java.
Other than writing some boring conversion logic, all pieces fell together pretty pleasantly.
Work towards #7989. That one calls for a string-to-label-list-dict type, but I'm planning to resolve that as WAI, since string-to-label-dict is close enough.
PiperOrigin-RevId: 686415025
Change-Id: Ib07ada7ab2ede95220ed1cc2d3569996fc4afb88
> Add a string-to-label-dict attribute type.

- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
When cancelling an asynchronous repository download task, an interrupt signal is sent to the download thread. This doesn't mean that the download stops immediately. Avoid restarting a download until the previous download has actually stopped, so that the new download is able to clean old data without crashing (on Windows).
Fixes #21773
Closes #23837.
PiperOrigin-RevId: 686175953
Change-Id: I8d75f905b739d38b6cb430d5b5e84fda9a2d14e3
Commit https://github.com/bazelbuild/bazel/commit/48338d2ff33586a0d053e358da6b94e23fe0e2eb
> [8.0.0] Properly cancel repository downloads

- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
When cancelling an asynchronous repository download task, an interrupt signal is sent to the download thread. This doesn't mean that the download stops immediately. Avoid restarting a download until the previous download has actually stopped, so that the new download is able to clean old data without crashing (on Windows).
Fixes #21773
Closes #23837.
PiperOrigin-RevId: 686175953
Change-Id: I8d75f905b739d38b6cb430d5b5e84fda9a2d14e3
Commit https://github.com/bazelbuild/bazel/commit/48338d2ff33586a0d053e358da6b94e23fe0e2eb
> [7.4.0] Properly cancel repository downloads

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java
Fixes #23981
Closes #23982.
PiperOrigin-RevId: 686486627
Change-Id: I5f03b63601a535f8d551c005b00bf040846a324d
Commit https://github.com/bazelbuild/bazel/commit/b0f1430f0e9b7608b9ecc64b20c3b0fe40ac4a43
> [8.0.0] Show "did you mean" suggestion for `{override,inject}_repo`

- src/main/cpp/blaze.cc
- src/main/cpp/blaze_util.cc
- src/main/cpp/blaze_util.h
- src/main/cpp/option_processor.cc
- src/main/cpp/startup_options.cc
- src/main/cpp/startup_options.h
- src/main/cpp/util/bazel_log_handler.cc
- src/main/cpp/util/bazel_log_handler.h
- src/main/cpp/util/logging.cc
- src/main/cpp/util/logging.h
- src/main/java/com/google/devtools/build/lib/runtime/BlazeServerStartupOptions.java
- src/main/java/com/google/devtools/build/lib/runtime/UiEventHandler.java
- src/main/java/com/google/devtools/build/lib/runtime/UiOptions.java
- src/test/cpp/util/logging_test.cc
- src/test/shell/integration/ui_test.sh
Implement "quiet mode"
This change adds a "--quiet" startup option, which causes Blaze not to print any status messages, progress messages, info messages or warnings of any kind. Error messages are still emitted as usual.
Fixes https://github.com/bazelbuild/bazel/issues/4867.
RELNOTES[NEW]: The "blaze --quiet" command line option can now be used to make Blaze emit much less output.
PiperOrigin-RevId: 686784300
Change-Id: Ibaa0b6a1788b43863337dce6fc16da09defb6724
> Cherry-pick quiet mode (fix for #4867) to 8.0.0

- src/main/java/com/google/devtools/build/lib/packages/Package.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
- src/test/java/com/google/devtools/build/lib/packages/PackageFactoryTest.java
Previously we weren't creating input files for labels used in the attribute of a top-level symbolic macro. This meant that if you wrote
```
my_macro(
name = "foo",
srcs = ["input.txt"],
)
```
you'd get an error message claiming that input.txt is not declared and requires an `exports_files()`. (The usages of input.txt by targets declared inside of foo don't count, because implicit input file creation only works for usages of labels outside of symbolic macro bodies.)
This CL fixes this behavior, refactors the relevant logic in Package.java, and adds more test coverage.
Package.java:
- Factor the big for loop from `beforeBuild()` to `createAssumedInputFiles()`. Leave the original for loop in place for test suite accumulation, and pull the `if (discover...)` out of the new call.
- Factor the …
> [8.0.0] Fix implicit input file creation for symbolic macros

- src/main/java/com/google/devtools/build/lib/rules/android/AndroidBinary.java
- src/main/java/com/google/devtools/build/lib/rules/android/AndroidStarlarkCommon.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/android/AndroidStarlarkCommonApi.java
createDexMergerActions continues to be exposed to Starlark due to it's use for SpawnActionTemplate which is not exposed to Starlark. We must pass a file containing global information to the final dexmerging step in order to support Java 17 Record desugaring. This change adds an optional parameter to the Starlark interface to forward the globals file to the Dex Merger.
PiperOrigin-RevId: 660045021
Change-Id: Ie3b961ff2687f48ca29a94e67180c0e5875ddbe3
Commit https://github.com/bazelbuild/bazel/commit/2daa0a3d893a3c18021e7c1191d4cacc270dd062
> [7.4.0] Blaze/Bazel changes for Java 17 Record desugaring

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/test/shell/bazel/external_integration_test.sh
Fixes https://github.com/bazelbuild/bazel/issues/16496
Closes #24019.
RELNOTES: The stripPrefix parameter of repository_ctx.download_and_extract()
and repository_ctx.extract() has been renamed to strip_prefix; the deprecated
stripPrefix name remains usable for compatibility.
PiperOrigin-RevId: 687224164
Change-Id: Iffaba2e65c049a2ff8bb98d1fba52e0bba9e5a02
Commit https://github.com/bazelbuild/bazel/commit/49d7bb661296c6e494d502ee7c3ab43f3df17fe1
> [8.0.0] Rename `stripPrefix=` to `strip_prefix=`

- src/main/cpp/blaze.cc
- src/main/cpp/option_processor.cc
- src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java
- src/main/java/com/google/devtools/build/lib/runtime/BlazeRuntime.java
- src/main/java/com/google/devtools/build/lib/runtime/CommandDispatcher.java
- src/main/java/com/google/devtools/build/lib/runtime/UiEventHandler.java
- src/main/java/com/google/devtools/build/lib/runtime/UiOptions.java
- src/main/java/com/google/devtools/build/lib/server/GrpcServerImpl.java
- src/main/protobuf/command_server.proto
- src/test/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcherTest.java
- src/test/java/com/google/devtools/build/lib/runtime/UiEventHandlerStdOutAndStdErrTest.java
- src/test/java/com/google/devtools/build/lib/server/GrpcServerTest.java
Rearguard fighting for #4867.
PiperOrigin-RevId: 688453143
Change-Id: I3f5a2f3f69676b5c5d6941b25b0d4c35a06e6056
> Reimplement --quiet using a field in the command server proto.

- src/main/starlark/builtins_bzl/common/java/java_common.bzl
PiperOrigin-RevId: 688955616
Change-Id: I408da72cfe409db7feb1978762fc6848f8fe118f (cherry picked from commit 38833e15f5795d493c50f1030dd5a7724f70a2b2)
> [8.0.0] Expose last remaining private APIs for java rules migration

- src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRulesModule.java
- src/main/java/com/google/devtools/build/lib/rules/android/AndroidConfiguration.java
- src/main/starlark/builtins_bzl/common/builtin_exec_platforms.bzl
- src/test/java/com/google/devtools/build/lib/analysis/starlark/BUILD
- src/test/java/com/google/devtools/build/lib/analysis/starlark/StarlarkAttrTransitionProviderTest.java
- src/test/java/com/google/devtools/build/lib/rules/cpp/CcCommonTest.java
The flag is a no-op and has been removed from Bazel.
> [8.0.0] Move `--fat_apk_cpu` to the flag graveyard

- src/main/starlark/builtins_bzl/common/java/java_common.bzl
PiperOrigin-RevId: 688955616
Change-Id: I408da72cfe409db7feb1978762fc6848f8fe118f (cherry picked from commit 38833e15f5795d493c50f1030dd5a7724f70a2b2)
> [7.4.1] Expose last remaining private APIs for java rules migration

- src/main/starlark/builtins_bzl/common/cc/experimental_cc_static_library.bzl
Closes #23800.
PiperOrigin-RevId: 684529045
Change-Id: I14dc53b6f2e39c7a05ee3a8b872eb220af45cef9
Commit https://github.com/bazelbuild/bazel/commit/ed37f39206f2981ade87897eec4bfdab3db055a1
> [8.0.0] Mark `cc_static_library` as experimental in docs

- src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java
- src/main/native/windows/file.cc
This is a partial fix for issue #21747 for the `--windows_enable_symlinks` case.
The fix was suggested in discussion of this issue. This resolves the problem with creating a junction if the target path doesn't exist for those who have Windows symlinks enabled, until a complete solution is provided.
Closes #24051.
PiperOrigin-RevId: 688724224
Change-Id: Ie44f7834af5fd35ab57961e6012b9f336c25d606
Commit https://github.com/bazelbuild/bazel/commit/3e5514d97342421ac285c5b5edcf76ba743fda8e
> [8.0.0] Partial fix for bug with creating a junction to file instead of symlink

- src/main/java/com/google/devtools/build/lib/packages/Package.java
- src/main/java/com/google/devtools/build/lib/packages/TargetRecorder.java
- src/test/java/com/google/devtools/build/lib/packages/PackageFactoryTest.java
Recent experience with symbolic macro migration showed that we need to relax the restrictions on the implicit creation of input files.
Previously it was an error to refer to a non-existent target `"foo_input"` if there happened to be a symbolic macro named `"foo"` in the package. The rationale was that we don't want to have to evaluate `foo` just to decide whether or not `foo_input` is in fact an `InputFile`.
But this restriction means that the common idiom:
```starlark
bzl_library(
name = "foo",
srcs = ["foo.bzl"],
)
```
blocks `bzl_library` from being a symbolic macro (e.g. wrapping the underlying rule). We believe this will be a common blocker well beyond this one example.
Therefore, we will now only block the implicit creation of input files when they collide exactly with a target or …
> [8.0.0] Allow implicit creation of input files within a macro's namespace

- .bazelci/presubmit.yml
- src/test/shell/bazel/BUILD
Tests on macOS arm64 should be much more stable after bumping VM specs.
Also bumped the size of disk_cache_test as it sometimes timeout on Linux.
Closes https://github.com/bazelbuild/bazel/issues/23726
PiperOrigin-RevId: 684412631
Change-Id: I5485f839aee0c3a1012196c6628eda9535985b82
Commit https://github.com/bazelbuild/bazel/commit/efa030314ec5f7340d770b6ae9736a9e24d29ee3
> [8.0.0] Re-enable tests that were disabled due CI infra flake

- src/tools/diskcache/Gc.java
We want a lower bound, not an upper one.
PiperOrigin-RevId: 690593852
Change-Id: If391e695593c9d445b4968be98d05e6169a06b3a
> [7.4.1] Correctly compute the number of threads to use for garbage collection.

- src/tools/diskcache/Gc.java
We want a lower bound, not an upper one.
PiperOrigin-RevId: 690593852
Change-Id: If391e695593c9d445b4968be98d05e6169a06b3a
> [8.0.0] Correctly compute the number of threads to use for garbage collection.

- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheGarbageCollector.java
- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheGarbageCollectorIdleTask.java
- src/test/java/com/google/devtools/build/lib/remote/disk/DiskCacheGarbageCollectorTest.java
Fixes https://github.com/bazelbuild/bazel/issues/24098
With this change the disk cache garbage collection works correctly:
```
241027 09:06:34.732:I 681 [com.google.devtools.build.lib.remote.disk.DiskCacheGarbageCollectorIdleTask.run] Disk cache garbage collection started
241027 09:07:06.123:I 681 [com.google.devtools.build.lib.remote.disk.DiskCacheGarbageCollectorIdleTask.run] Deleted 190243 of 446229 files, reclaimed 5.4 GiB of 15.4 GiB
```
Closes #24099.
PiperOrigin-RevId: 690652512
Change-Id: Ie8d1fa6b2afb0bd5bd85fdb6835871023a64ad24
Commit https://github.com/bazelbuild/bazel/commit/374658377f662701f1e92f757090949fdd0da1ab
> [7.4.1] Prevent excessive thread creation in disk cache garbage collection

- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheGarbageCollector.java
- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheGarbageCollectorIdleTask.java
- src/test/java/com/google/devtools/build/lib/remote/disk/DiskCacheGarbageCollectorTest.java
Fixes https://github.com/bazelbuild/bazel/issues/24098
With this change the disk cache garbage collection works correctly:
```
241027 09:06:34.732:I 681 [com.google.devtools.build.lib.remote.disk.DiskCacheGarbageCollectorIdleTask.run] Disk cache garbage collection started
241027 09:07:06.123:I 681 [com.google.devtools.build.lib.remote.disk.DiskCacheGarbageCollectorIdleTask.run] Deleted 190243 of 446229 files, reclaimed 5.4 GiB of 15.4 GiB
```
Closes #24099.
PiperOrigin-RevId: 690652512
Change-Id: Ie8d1fa6b2afb0bd5bd85fdb6835871023a64ad24
Commit https://github.com/bazelbuild/bazel/commit/374658377f662701f1e92f757090949fdd0da1ab
> [8.0.0] Prevent excessive thread creation in disk cache garbage collection

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/FileApi.java
For symmetry with File.is_directory.
Fixes #11209.
PiperOrigin-RevId: 690652872
Change-Id: I4e93cb18e2469819cfa46f3c0685376093fc455e
Commit https://github.com/bazelbuild/bazel/commit/66a1038a128fbde9331598580f57afb513e4fa36
> [8.0.0] Implement File.is_symlink.

- tools/bash/runfiles/runfiles.bash
`wc -c` has leading spaces that needs to be removed, otherwise trim_length would become `      29` for example.
~I'm not very sure how test cases could work but this fails in our repo.~ I understand it now. We set `IFS=$'\\n\\t'` in our script, which makes this trick stops working `cut -b ${trim_length}-` (note that there are no quotes around `${trim_length}`. Although we could fix our `IFS`, this still seems to be a bug because it is not "portable".
Closes #24076.
PiperOrigin-RevId: 690707015
Change-Id: I728b7462994a6ffdb9b88c3cbea3ec044a8b0134
Commit https://github.com/bazelbuild/bazel/commit/bf666fb0cb7d74a1005e49cd48bfc790cf46d3a4
> [7.4.1] fix: Fix trim_length in runfiles.bash

- tools/bash/runfiles/runfiles.bash
`wc -c` has leading spaces that needs to be removed, otherwise trim_length would become `      29` for example.
~I'm not very sure how test cases could work but this fails in our repo.~ I understand it now. We set `IFS=$'\\n\\t'` in our script, which makes this trick stops working `cut -b ${trim_length}-` (note that there are no quotes around `${trim_length}`. Although we could fix our `IFS`, this still seems to be a bug because it is not "portable".
Closes #24076.
PiperOrigin-RevId: 690707015
Change-Id: I728b7462994a6ffdb9b88c3cbea3ec044a8b0134
Commit https://github.com/bazelbuild/bazel/commit/bf666fb0cb7d74a1005e49cd48bfc790cf46d3a4
> [8.0.0] fix: Fix trim_length in runfiles.bash

- src/main/java/com/google/devtools/build/lib/analysis/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/config/transitions/NoConfigTransition.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkConfig.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/config/StarlarkConfigApi.java
- src/test/java/com/google/devtools/build/lib/starlark/BUILD
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleClassFunctionsTest.java
RELNOTES: A transition that removes all configuration is now available as `config.none()`.
> [8.0.0] Expose config.none to Starlark.

- src/test/shell/bazel/bazel_execlog_test.sh
Related to #24061, which doesn't affect Bazel 8
Closes #24083.
PiperOrigin-RevId: 690535547
Change-Id: I25644d798a33ff0d6c90510fbcebf1bbbc332d40
Commit https://github.com/bazelbuild/bazel/commit/fc27990feb62d9e64f6ce41955dc3245dc26ef2d
> [8.0.0] Verify that the compact execlog supports `bazel coverage`

- src/main/java/com/google/devtools/build/lib/worker/BUILD
- src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnRunner.java
Since `WorkRequest` encodes strings as UTF-8, Bazel's internal string encoding of file paths needs to be undone before passing them to the protobuf builder.
Closes #23924.
PiperOrigin-RevId: 690737819
Change-Id: I3eb341c05e045c75ac004da57e1f46f3587a6810
Commit https://github.com/bazelbuild/bazel/commit/89f798effcec161c99164f08f58d5565e66c7602
> [7.4.1] Fix double encoding of inputs in worker request

- site/en/external/module.md
Looks like f6687ad45eccfa7928c9a54f3db2e3c660d9bbce didn't fully fix things, based on looking at https://bazel.build/external/module today:
Closes #23985.
PiperOrigin-RevId: 691071540
Change-Id: Ic474af8308843314aaeaaa85a40dfc487cf7efca
Commit https://github.com/bazelbuild/bazel/commit/4e4b88fd8385471b783c36f3d9835ba177470fc7
> [7.4.1] docs(module): fix list of bullet points not rendering

- src/main/java/com/google/devtools/build/lib/worker/BUILD
- src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnRunner.java
Since `WorkRequest` encodes strings as UTF-8, Bazel's internal string encoding of file paths needs to be undone before passing them to the protobuf builder.
Closes #23924.
PiperOrigin-RevId: 690737819
Change-Id: I3eb341c05e045c75ac004da57e1f46f3587a6810
Commit https://github.com/bazelbuild/bazel/commit/89f798effcec161c99164f08f58d5565e66c7602
> [8.0.0] Fix double encoding of inputs in worker request

- site/en/external/module.md
Looks like f6687ad45eccfa7928c9a54f3db2e3c660d9bbce didn't fully fix things, based on looking at https://bazel.build/external/module today:
Closes #23985.
PiperOrigin-RevId: 691071540
Change-Id: Ic474af8308843314aaeaaa85a40dfc487cf7efca
Commit https://github.com/bazelbuild/bazel/commit/4e4b88fd8385471b783c36f3d9835ba177470fc7
> [8.0.0] docs(module): fix list of bullet points not rendering

- src/main/java/com/google/devtools/build/lib/cmdline/Label.java
- src/main/java/com/google/devtools/build/lib/cmdline/RepositoryName.java
- src/main/java/com/google/devtools/build/lib/skyframe/ProcessPackageDirectory.java
- src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewTestCase.java
- src/test/shell/bazel/external_integration_test.sh
Also remove an unused method.
RELNOTES: External repositories that are managed by Bzlmod can now contain a top-level `external` directory or package.
Closes #24126.
PiperOrigin-RevId: 691521324
Change-Id: I84d11f2163ce5a6e34578afb6a2cc9793d78f0b1
Commit https://github.com/bazelbuild/bazel/commit/0e2bcda6c3b97c7ecc9b1359157360ace8b40d89
> [8.0.0] Allow `external` top-level dir in Bzlmod-managed non-main repos

- src/main/java/com/google/devtools/build/lib/rules/java/JavaStarlarkCommon.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaCommonApi.java
- src/test/java/com/google/devtools/build/lib/rules/java/JavaStarlarkApiTest.java
PiperOrigin-RevId: 587638256
Change-Id: I4aa6b9c2009323e9c4adc7f6e8b5e335a637ed1c
(cherry picked from commit fb446e6366b50a93f794118cb3b77bb55f189325)
> [7.4.1] Add missing private API for tokenizing javacopts

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/InnateRunnableExtension.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionId.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/blackbox/tests/workspace/BazelEmbeddedStarlarkBlackBoxTest.java
- src/test/shell/bazel/starlark_repository_test.sh
Generate one synthetic "innate" module extension per repo rule class instead of a single one for all `use_repo_rule` usages in a given module. This avoids load cycles if one repo rule definition loads another one.
Closes #24104.
PiperOrigin-RevId: 691954099
Change-Id: Ia2eae6b6f45b169f364f1e83b76e8d907378329f
Commit https://github.com/bazelbuild/bazel/commit/aa7317f8ad3a324831696e2fca8c88d87a26b88c
> [8.0.0] Allow `use_repo_rule` repos to load from each other

- tools/java/runfiles/AutoBazelRepositoryProcessor.java
Add support for when the AutoBazelRepository annotation is placed on a file in a root package (ie. one where there is no package)
fixes #24150
Closes #24161.
PiperOrigin-RevId: 692888334
Change-Id: Idd85e79250f64cf50ca709cf6ad8d025a0db032c
Commit https://github.com/bazelbuild/bazel/commit/156004739c1298fa37f844dc7ccef9c8ee330416
> [8.0.0] Fix empty package in AutoBazelRepositoryProcessor

- tools/cpp/unix_cc_toolchain_config.bzl
This unbreaks `toolchains_llvm`, which depends on this symbol. In the future, the new modular C++ toolchain API should make the symbol obsolete.
Closes #24154.
PiperOrigin-RevId: 693084632
Change-Id: Ica26f547c548fe3d25b3d57bdf2d432fd8f239ad
Commit https://github.com/bazelbuild/bazel/commit/e14d524c8f5d6d79cd0f23ff472b9a0839dd86db
> [8.0.0] Export Unix `cc_toolchain_config` for backwards compatibility

- src/test/py/bazel/bazel_windows_cpp_test.py
- tools/cpp/windows_cc_configure.bzl
This reverts commit cb1bc28f3731b07380a37be600f6ba8108b2a7a7.
Closes https://github.com/bazelbuild/bazel/issues/24158
Related https://github.com/bazelbuild/bazel/issues/24152
> Revert "[7.4.0] Fix ml path for Windows clang-cl cc toolchain (#23406)"

- src/main/cpp/blaze_util_windows.cc
Currently, we rely on CreateFile to effectively obtain an exclusive (write) lock on the entire file, which makes the later call to LockFileEx redundant. This CL makes it so that we open the file in shared mode, and actually use LockFileEx to lock it.
This makes a client-side lock compatible with a server-side one obtained through the JVM (which defaults to opening files in shared mode and uses LockFileEx for locking). Even though this doesn't matter for the output base lock, which is only ever obtained from the client side (the server side doesn't use filesystem-based locks), it will be necessary to implement install base locking (as part of fixing #2109).
Note that this means an older Bazel might immediately exit instead of blocking for the lock, if the latter was previously acquired by …
> [8.0.0] Make the Windows implementation of AcquireLock compatible with JVM locks.

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Registry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryImpl.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RepoSpecFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/YankedVersionsFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/packages/BazelPackageLoader.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/FakeRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
This PR removes the DownloadManager from the registry factory implementation. As the registry created by the factory is cached by the SkyFunction mechanism, the DownloadManager instance was living too long - it is supposed to be re-created for every command instantiation to respect changes in command line options, but for the registry, it ignored those changes.
Instead, the DownloadManager is set directly into the affected SkyFunctions that require access to it. This way, the per-command DownloadManager instance is correctly used.
This fixes https://github.com/bazelbuild/bazel/issues/24166.
Note for reviewers: This is my first time touching code with SkyFunctions, so I don't really know what I'm doing.
Closes #24212.
PiperOrigin-RevId: 693644409
Change-Id: …
> [7.4.1] Remove DownloadManager instance from RegistryFactoryImpl.

- src/main/java/com/google/devtools/build/lib/buildtool/ExecutionTool.java
This reverts the functional changes introduced by https://github.com/bazelbuild/bazel/commit/2f899ef8b39935d9ca131b71a24e67ef286bc378. They're no longer required because https://github.com/bazelbuild/bazel/commit/4c42edb2e8b2e8169da294591f3b45d369432f14 also happened to fix incremental fetching of top-level outputs for `run` commands. The integration test added by the former CL remains in place.
Fixes #20843.
PiperOrigin-RevId: 693664834
Change-Id: I64c1b0d14ae54f3906b9f7d916dbbb4f0204a1b9
> [8.0.0] Observe --noexperimental_check_output_files even for `run` commands.

- src/main/cpp/blaze.cc
- src/main/cpp/blaze_util_platform.h
- src/main/cpp/blaze_util_posix.cc
- src/main/cpp/blaze_util_windows.cc
They are currently only used to acquire a lock on the output base, but a future change will use them to lock the install base as well.
Human-readable output is also amended to refer to the "output base lock" instead of the "client lock", as the latter term becomes ambiguous once multiple locks exist.
Progress on #2109.
PiperOrigin-RevId: 693354279
Change-Id: I2b39e6f5ddb83bbc2be15a31d7de9655358776c5
> [8.0.0] Extract methods to acquire and release a filesystem lock.

- src/BUILD
- src/minimize_jdk.sh
- src/patch_java_manifest_for_utf8.cc
- src/test/shell/bazel/BUILD
This change patches the app manifest of the `java.exe` launcher in the embedded JDK to always use the UTF-8 codepage on Windows 1903 and later.
This is necessary because the launcher sets sun.jnu.encoding to the system code page, which by default is a legacy code page such as Cp1252 on Windows. This causes the JVM to be unable to interact with files whose paths contain Unicode characters not representable in the system code page, as well as command-line arguments and environment variables containing such characters.
The Windows VMs in CI are not running Windows 1903 or later yet, so this change can currently only be tested locally by running `bazel info character-encoding` and verifying that it prints `sun.jnu.encoding = UTF-8`.
Work towards https://github.com/bazelbuild/bazel/issues/374 …
> [8.0.0] Force the JVM to use UTF-8 on Windows

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Registry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryImpl.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RepoSpecFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/YankedVersionsFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/packages/BazelPackageLoader.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/FakeRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
This PR removes the DownloadManager from the registry factory implementation. As the registry created by the factory is cached by the SkyFunction mechanism, the DownloadManager instance was living too long - it is supposed to be re-created for every command instantiation to respect changes in command line options, but for the registry, it ignored those changes.
Instead, the DownloadManager is set directly into the affected SkyFunctions that require access to it. This way, the per-command DownloadManager instance is correctly used.
This fixes https://github.com/bazelbuild/bazel/issues/24166.
Note for reviewers: This is my first time touching code with SkyFunctions, so I don't really know what I'm doing.
Closes #24212.
PiperOrigin-RevId: 693644409
Change-Id: …
> [8.0.0] Remove DownloadManager instance from RegistryFactoryImpl.

- src/main/java/com/google/devtools/build/lib/skyframe/StarlarkBuiltinsFunction.java
PiperOrigin-RevId: 693692713
Change-Id: I65db496e79b30952525dd7995080109fcfc4f9f5
Commit https://github.com/bazelbuild/bazel/commit/764ba19ea5b935d7dd8b112a02dcbe05e4d9a5d5
> [8.0.0] Don't check main repo name for auto-load when bzlmod is disabled.

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkExecutionResult.java
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/starlark_repository_test.sh
RELNOTES: `repository_ctx.execute` can now remove an environment variable when executing a process by associating it with the value `None` in the `environment` argument.
Closes #24221.
PiperOrigin-RevId: 694048622
Change-Id: Ia779e9133411745c9cfe93845c13839d05731c7c
Commit https://github.com/bazelbuild/bazel/commit/21a12c72d84e9108142421d9a8526edf8dceb78c
> [8.0.0] Let repo rules remove env vars for subprocesses

- src/main/java/com/google/devtools/build/lib/bazel/debug/WorkspaceRuleEvent.java
- src/main/java/com/google/devtools/build/lib/bazel/debug/workspace_log.proto
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContextTest.java
This allows the directory structure of third-party archives to be rearranged without platform-specific commands, and without requiring symlink support from the platform.
Closes #24020.
PiperOrigin-RevId: 694246834
Change-Id: I4831d610c5fb841640af1b1b864172ee38319a6b
Commit https://github.com/bazelbuild/bazel/commit/467ea0cd6e6189e73991f3344d108883e0cf5dd3
> [8.0.0] Add `repository_ctx.rename()` for renaming files or directories

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/JsonOutputFormatter.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodTestUtil.java
This allows IDEs to query for the direct dependencies of the root module as well as how they can refer to them from the point of view of the root module.
Also always emit `name` and `version` so that consumers don't have to know how to parse module keys.
Work towards #22691
Closes #23787.
PiperOrigin-RevId: 693453084
Change-Id: Ie3fd5e89301d8e83d0eaa686188634923853f01a
Commit https://github.com/bazelbuild/bazel/commit/1003d2c31bf4f90ded7015b1b7ed570d50ed6a63
> [8.0.0] Include apparent names of deps in `bazel mod` JSON output

- src/main/java/com/google/devtools/build/lib/worker/WorkerParser.java
- src/test/java/com/google/devtools/build/lib/worker/ExampleWorker.java
- src/test/java/com/google/devtools/build/lib/worker/ExampleWorkerMultiplexer.java
- src/test/java/com/google/devtools/build/lib/worker/ExampleWorkerOptions.java
- src/test/shell/integration/bazel_worker_test.sh
Fixes #24237.
RELNOTES[INC]: The mnemonic passed to --worker_extra_flag is now matched against the worker key mnemonic when one is available, instead of the action mnemonic. This makes it consistent with other worker flags taking a mnemonic.
PiperOrigin-RevId: 694436563
Change-Id: I7c6e6ede5e3ef2f53aeb847bbfe173042c528d68
Commit https://github.com/bazelbuild/bazel/commit/8357fbab5c8e5a1125b68fce6dc790c73dbf31ce
> [8.0.0] Match --worker_extra_flag against the worker key mnemonic, not the action mnemonic, as is the case for other worker flags taking a mnemonic.

- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java
Fixes #24239.
Closes #24241.
PiperOrigin-RevId: 694176406
Change-Id: I7d0a9c129c34725d0843eb7ec87b46c657d168d8
Commit https://github.com/bazelbuild/bazel/commit/f651450ba69c21966da7fed3a415989a0d4666aa
> [8.0.0] Add better error handling for skyframe cycles while creating configurations.

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModTidyFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModTidyValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorValue.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/ModCommand.java
- src/main/protobuf/failure_details.proto
- src/test/py/bazel/bzlmod/mod_command_test.py
RELNOTES: `bazel mod` now tries to evaluate all module extensions, even when some have failed to evaluate.
Closes #23828.
PiperOrigin-RevId: 694448503
Change-Id: I1e4f7a36384c7dfdc16d13cdfcd0b4b3aeb41834
Commit https://github.com/bazelbuild/bazel/commit/a0471c703bd0414867ed50180d5024c593326e0a
> [8.0.0] Add support for `--keep_going` to `bazel mod`

- src/main/java/com/google/devtools/build/lib/exec/RunfilesTreeUpdater.java
- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java
- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeStrategy.java
- src/main/java/com/google/devtools/build/lib/runtime/BlazeModule.java
- src/main/java/com/google/devtools/build/lib/vfs/SnapshottingFileSystem.java
- src/test/java/com/google/devtools/build/lib/exec/SymlinkTreeHelperTest.java
- src/test/java/com/google/devtools/build/lib/exec/SymlinkTreeStrategyTest.java
It has been a long-standing feature of runfiles symlink trees that they reflect changes made to files referenced in them after the tree has been built. In certain scenarios (currently only at Google), the FileSystem implementation may rewrite symlink target paths to point to read-only snapshots, which breaks this feature when using in-process symlink creation. With this change, the rewriting is bypassed in this case.
Also improve the documentation for the BlazeModule getFileSystem() and getFileSystemForBuildArtifacts() methods.
PiperOrigin-RevId: 690541050
Change-Id: I140cc68ca1b9236e9fb4049830cc3b5629eaf770
> [8.0.0] Use non-snapshotted paths when creating a runfiles symlink tree.

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/main/java/com/google/devtools/build/lib/packages/BUILD
- src/main/java/com/google/devtools/build/lib/packages/MacroClass.java
- src/main/java/com/google/devtools/build/lib/packages/RuleClass.java
- src/main/java/com/google/devtools/build/lib/packages/RuleClassUtils.java
- src/main/java/com/google/devtools/build/lib/packages/RuleFunction.java
- src/main/java/com/google/devtools/build/lib/runtime/commands/info/BUILD
- src/main/java/com/google/devtools/build/lib/runtime/commands/info/BuildLanguageInfoItem.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/MacroFunctionApi.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/RuleFunctionApi.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkRuleFunctionsApi.java
- src/test/java/com/google/devtools/build/docgen/StarlarkDocumentationTest.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
- src/test/java/com/google/devtools/build/lib/analysis/util/BUILD
- src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewTestCase.java
Allows the following syntax:
```
my_cc_library = macro(
inherit_attrs = native.cc_library,
attrs = {
"cxxopts": None,
"copts": attr.string_list(default = ["-D_FOO"]),
},
...
)
```
Fixes https://github.com/bazelbuild/bazel/issues/24066
Tricky parts:
* Some common rule attributes ("testonly", "size", etc.) have computed defaults;
native rule "license" and "distribs" attrs have defaults which fail type check if
lifted. The only sane way of handling such attrs, if the attribute is unset in
the macro function call, to pass the value as None to the implementation function
so that the implementation function will pass None to the rule function, which
will thus set the default appropriately.
* We need RuleFunctionApi and MacroFunctionApi interfaces (yet more interfaces,
alas, or we get a circular …
> [8.0.0] Symbolic macro attribute inheritance

- tools/test/test-setup.sh
The `rlocation` implementation lacks many of the features of the shell runfiles library, which should be dependend on explicitly instead.
When called, `rlocation` will now fail with an error message.
Closes #24256.
PiperOrigin-RevId: 695241586
Change-Id: I7059c329fd6ca518623d7be8ad3514082097c191
Commit https://github.com/bazelbuild/bazel/commit/1312007fa7e439fa45407d9757066d96e01866b6
> [8.0.0] Do not export `rlocation` from test setup

- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java
- src/test/java/com/google/devtools/build/lib/exec/SymlinkTreeHelperTest.java
This edge case was missing from https://github.com/bazelbuild/bazel/commit/51d7a3c7e549780a7f162bfe6525fffc4c529ae0.
Also add minimal unit test coverage for in-process symlink creation.
PiperOrigin-RevId: 694504600
Change-Id: Ida73afa1ce5730e885bc970eafd07211d1816e93
> [8.0.0] Handle unresolved symlinks correctly when replacing an existing entry in a runfiles tree.

- MODULE.bazel
- MODULE.bazel.lock
- scripts/bootstrap/buildenv.sh
This is more reliable than parsing CHANGELOG.md, which is not always the latest.
This requires us to maintain the Bazel version number in MODULE.bazel, which should be updated once a year on the master branch, but every time we do a minor/patch release.
PiperOrigin-RevId: 695747413
Change-Id: I63d572445d8cb6a76a3e079c2ea6f083257216b0
> [8.0.0] Bazel bootstrap: use MODULE.bazel to get the version

- tools/build_defs/repo/git_worker.bzl
This ensures that this repository rule cannot be influenced by these environment variables, particularly `GIT_DIR`, keeping the operation limited to the directory specified by the `repository_ctx`.
In particular, this ensures that calling Bazel (e.g. `bazel test`) from within a Git hook will work reliably. Git hooks set `GIT_DIR` (among others), which can cause the repository rule's invocations of `git` to misbehave. https://git-scm.com/docs/githooks
When using Git worktrees and calling Bazel from a Git hook, it has been observed that `git_repository()` will not only fail, but will also set `core.bare = true`, breaking the user's clone.
Fixes #24199.
Closes #24204.
PiperOrigin-RevId: 695642299
Change-Id: Id81e32194117cd8996408b236a6a88a20b14910b
Commit …
> [8.0.0] Make `git_repository()` ignore `GIT_` env vars

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegularRunnableExtension.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java
Should fix a server crash due to `unexpected exception type: java.lang.InterruptedException` when interrupting a repo rule fetch.
Closes #24278.
PiperOrigin-RevId: 696043083
Change-Id: I44c95fb6b0043c89de8aa526c2ff9cf014ce9447
Commit https://github.com/bazelbuild/bazel/commit/21d8b02fb26f89ec7bf3e7dd978c6ecf1d258ad0
> [8.0.0] Don't crash when repo rule throws `InterruptedException`

- src/main/java/com/google/devtools/build/lib/packages/MacroClass.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
Previously, it was a no-op for a symbolic macro implementation function to return a value. This CL makes it an evaluation error. (An explicit `return` or `return <expr that evals to None>` statement is still permitted.)
This is useful to enforce code clarity for symbolic macros. It may also help catch errors sooner when migrating legacy macros to symbolic macros. It also leaves the door open to having Bazel interpret the return values of macros in specific ways in the future.
Fixes #24312.
PiperOrigin-RevId: 696153298
Change-Id: Ib317871664c2036cc24ea31bc0033ec691fd07c8
Commit https://github.com/bazelbuild/bazel/commit/9e15ca3ca83120869b08bd5f45b27f110059e7e5
> [8.0.0] Disallow symbolic macros from returning a non-None value

- src/main/java/com/google/devtools/build/lib/bazel/BazelWorkspaceStatusModule.java
On windows, bazel will run the workspace_status_command, and receive carriage return characters \r even if the workspace_status_command did not include them.
Fixes https://github.com/bazelbuild/bazel/issues/13442
PiperOrigin-RevId: 684055158
Change-Id: Idd3bd9c954d64b0a2d674dd7d90cf61c00955917
> [8.0.0] Trim Workspace Status values

- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkRuleFunctionsApi.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
We still have open questions about how macro attribute inheritance ought to interact with the tracking of whether rule attributes were or were not explicitly provided.
In effect, this re-opens https://github.com/bazelbuild/bazel/issues/24066 Part of addressing https://github.com/bazelbuild/bazel/issues/24319
RELNOTES: symbolic macro attribute inheritance is now marked experimental; set --experimental_enable_macro_inherit_attrs flag to enable it.
Commit
https://github.com/bazelbuild/bazel/commit/08beb210eddd35b703857e005d99c60b963e8e10
PiperOrigin-RevId: 696582223
Change-Id: I3d7cb434bf8fe2da9cd10019e6075990205e7153
Working towards #24335
> [8.0.0] Put macro attribute inheritance behind an off-by-default --experimental_enable_macro_inherit_attrs flag

- src/test/shell/integration/run_test.sh
CI runners have been updated in https://github.com/bazelbuild/continuous-integration/commit/bd271932189c4b5e14ab17f1ff004c84b386e4be to a Windows version that supports the approach taken in 7bb8d2b648d533c4352452f2c4dbe9ddb1374434 to start the JVM with UTF-8 as the system encoding.
Closes #24270.
PiperOrigin-RevId: 697541108
Change-Id: I175a52b917667afe4129ad23ccb50171be1d2a59
Commit https://github.com/bazelbuild/bazel/commit/27ab1ef1a2f1f78ecd81f56a113a1a69dec70648
> [8.0.0] Test with non-Latin-1 Unicode characters on Windows

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/CompiledModuleFile.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/VendorFileFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/RepoFileFunction.java
- src/test/py/bazel/bzlmod/bazel_module_test.py
- src/test/py/bazel/bzlmod/test_utils.py
- src/test/py/bazel/test_base.py
As long as Bazel internally represents strings as raw bytes "encoded" in Latin-1, the same must be true for all Starlark files that may contain file system paths.
Also includes changes to the Python test setup:
* `ScratchFile` now always writes files as UTF-8
* `RunProgram` encodes and decodes stdin/stderr/stdout as UTF-8
* `download` no longer leaks a file
Closes #24217.
PiperOrigin-RevId: 697550082
Change-Id: If7f3fc7ddace2cda5e1f8e48a65406aa54f2a6d8
Commit https://github.com/bazelbuild/bazel/commit/fba8603cf571545b5e5948af20434ee6eb9ecfab
> [8.0.0] Parse Starlark files as raw bytes for Bzlmod

- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/objc/AppleBootstrap.java
- src/test/java/com/google/devtools/build/lib/rules/apple/XcodeVersionTest.java
- src/test/java/com/google/devtools/build/lib/rules/objc/ObjcStarlarkTest.java
- src/test/java/com/google/devtools/build/lib/rules/objc/XcodeConfigTest.java
In AppleBootstrap.java give several rule repos access to apple_common that need it, and activate the access restriction independent of INCOMPATIBLE_STOP_EXPORTING_LANGUAGE_MODULES.
PiperOrigin-RevId: 696999389
Change-Id: I000911fbef3b48039beb423e5ba1ab48059b8eeb
> Restrict access to private API apple_common to the repos and tests that need it.

- src/main/java/com/google/devtools/build/lib/packages/MacroClass.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
Merge fix for #24066 into 8.0.0.
Closes tracking issue #24320.
I'm not sure why the automatic merge failed but it works locally, so here goes.
> Don't select()-promote None values

- src/main/java/net/starlark/java/eval/StringModule.java
Since Java 21, the internal `indexOf` method on String that accepts start and end position is available as public API.
Closes #24333.
PiperOrigin-RevId: 697001722
Change-Id: I274b2ffd7a6d925531e1261f04bec5942d70fdf2
Commit https://github.com/bazelbuild/bazel/commit/1c9f1dd19ccd26998cd0a8b000e3c6cd1f1066bb
> [8.0.0] Use new `String#indexOf` overload for Starlark's `stringFind`

- site/en/extending/macros.md
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/main/java/com/google/devtools/build/lib/packages/Attribute.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkRuleFunctionsApi.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
- src/test/java/com/google/devtools/build/lib/starlarkdocextract/ModuleInfoExtractorTest.java
This contains the following 3 cherry picks, which I'm providing in one PR because they must be applied in order:
1. Explicitly ban attribute inheritance from unexported rules/macros
Cherry-pick of
https://github.com/bazelbuild/bazel/commit/372980c4a7e68cfd0b6593172249b7c19c3fe3cb
PiperOrigin-RevId: 696954211
Change-Id: Ia205fe4e6686d51248c1389e1cf7b826650908e8
2. Force the default value of symbolic macro's optional inherited attributes to None
Cherry-pick of
https://github.com/bazelbuild/bazel/commit/a2f1f58cdff07d240c9f715d5091672bd9abd03f
PiperOrigin-RevId: 697301269
Change-Id: I47563898c511a1f065d117f51a7a3a227e23260e
3. Update symbolic macro docs
Cherry-pick of
https://github.com/bazelbuild/bazel/commit/ebeab8ce6607f0ea8448178219c61a935535be6a
PiperOrigin-RevId: 697741975
Change-Id: …
> [8.0.0] Symbolic macro documentation & attribute inheritance cherry picks

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileValue.java
- src/test/tools/bzlmod/MODULE.bazel.lock
aa7317f changed the canonical name of repositories generated by `use_repo_rule`, which should have been accompanied by a bump of the lockfile version.
Should fix https://github.com/bazelbuild/bazel/pull/24171#issuecomment-2482949080
Closes #24363.
PiperOrigin-RevId: 697924369
Change-Id: I3b2876ea3fab86d5ab9c7e08f8c9ce607573c56c
Commit https://github.com/bazelbuild/bazel/commit/71227bf00cf803f931f126ed5ad6df5b2a073a27
> [8.0.0] Bump lockfile version after changes to canonical names

- src/main/java/com/google/devtools/build/lib/query2/common/CommonQueryOptions.java
- src/main/java/com/google/devtools/build/lib/rules/genquery/BUILD
- src/main/java/com/google/devtools/build/lib/rules/genquery/GenQuery.java
- src/test/java/com/google/devtools/build/lib/buildtool/GenQueryIntegrationTest.java
Fixes #24325
Closes #24326.
PiperOrigin-RevId: 697842646
Change-Id: Ied25448861c5133aae6f266000fe983625f48963
Commit https://github.com/bazelbuild/bazel/commit/5141c06f62ed1e435dec40aaed1dfb98f2f9b399
> [8.0.0] Let `genquery` honor `--consistent_labels`

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
Order doesn't matter for these inputs and sorting them can only help decrease merge conflicts in the lockfile.
Closes #24367.
PiperOrigin-RevId: 697924458
Change-Id: Ie29e4c05204b974f10db571d61f38969411da03b
Commit https://github.com/bazelbuild/bazel/commit/34cc02ae8e73a9a1d2f00277da09c27924dd626b
> [8.0.0] Sort recorded inputs in lockfile entries of module extensions

- src/main/java/com/google/devtools/build/lib/profiler/CollectLocalResourceUsage.java
- src/test/java/com/google/devtools/build/lib/profiler/BUILD
- src/test/java/com/google/devtools/build/lib/profiler/ProfilerTest.java
This metric shouldn't be collected on Windows.
Fixes https://github.com/bazelbuild/bazel/issues/23952
PiperOrigin-RevId: 698007958
Change-Id: I4d05e81e180467488a87a7839d879f916f9494b1
Commit https://github.com/bazelbuild/bazel/commit/8f9a5038dd9dbaffffdde38e4f61d5afa0bd76ac
> [8.0.0] Check the current OS and only collect worker metrics on Linux and MacOS.

- src/main/cpp/archive_utils.cc
- src/main/cpp/archive_utils.h
- src/main/cpp/blaze.cc
- src/main/cpp/blaze_util.h
- src/main/cpp/blaze_util_platform.h
- src/main/cpp/blaze_util_posix.cc
- src/main/cpp/blaze_util_windows.cc
- src/test/cpp/blaze_archive_test.cc
Even with `CLOCK_MONOTONIC`, we are still seeing Bazel servers fail to start up occasionally due to start time being larger than end time. Make this non-fatal by truncating to 0 and emitting a warning with start and end time to facilitate further investigation.
Also flip the conditions for command and extraction wait time, which previously were only included if *not* known.
Closes #24344.
PiperOrigin-RevId: 697932531
Change-Id: Ia124a1e10640fde909ec377ab493f1654b5933e7
Fixes #24395
> [8.0.0] Fix duration measurement issues in the client

- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/objc/AppleBootstrap.java
- src/test/java/com/google/devtools/build/lib/rules/apple/XcodeVersionTest.java
- src/test/java/com/google/devtools/build/lib/rules/objc/ObjcStarlarkTest.java
- src/test/java/com/google/devtools/build/lib/rules/objc/XcodeConfigTest.java
This breaks rules_go and rules_swift because they refer to themselves by alias depot names: https://github.com/bazelbuild/bazel/issues/24375
*** Original change description ***
In AppleBootstrap.java give several rule repos access to apple_common that need it, and activate the access restriction independent of INCOMPATIBLE_STOP_EXPORTING_LANGUAGE_MODULES
PiperOrigin-RevId: 698310431
Change-Id: I88973163cadca29021af9575d410fcae1eb6c066
Rollback of https://github.com/bazelbuild/bazel/pull/24360 on release-8.0.0
> [8.0.0] Automated rollback of commit b406bdcbe95dd23ca623f807d5113f18b724611a.

- src/test/java/com/google/devtools/build/lib/buildtool/util/BUILD
- src/test/java/com/google/devtools/build/lib/buildtool/util/BuildIntegrationTestCase.java
Some `get*` methods worked with apparent repo names, others didn't, which is a hurdle to contributions in this area (as observed while working on #24328).
Closes #24329.
PiperOrigin-RevId: 697548136
Change-Id: I24c3624875d1d1110ee8685656b88fffe3be6d95 
(cherry picked from commit 9534199d79c0089123bc8f46a0268432f8e0f3b8)
Closes #24347
> [8.0.0] Apply the main repo mapping in `BuildIntegrationTestCase`

- .bazelrc
Make the buildkite log viewable again
Addressing https://buildkite.com/bazel/bazel-bazel/builds/30048#01930c44-35d3-4c13-aa34-c7d610643e8d
PiperOrigin-RevId: 694528361
Change-Id: I17bde53d954e4a6991fd4af9b563736c5c813011
> [8.0.0] Suppress warnings for all external repos

- src/main/java/com/google/devtools/build/lib/packages/semantics/FlagConstants.java
Enable autoloading of `java_common`
PiperOrigin-RevId: 698696053
Change-Id: Id64c3b024294d97ebc9aed808d6e210065f79825 (cherry picked from commit 06c1ae9f5298e312906366464022551f5d17f648)
> [8.0.0] Fix `@rules_java` autoload configs

- src/main/java/com/google/devtools/build/lib/runtime/CommandEnvironment.java
Fixes issue where server process would "cache" environment variables. Broken since 3ebf658cba43bbab1efc36518f0795a7d65e2d46 (v5).
Closes #24433.
PiperOrigin-RevId: 698847238
Change-Id: I51d4ec811ee9d78717ff816d9988b4ad0f533265
Commit https://github.com/bazelbuild/bazel/commit/a590cfcc93f5ec1f9498e4b100f10172da537a1f
> [8.0.0] Get `--repo_env=NAME` value from client environment (not server).

- site/en/extending/macros.md
- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkRuleFunctionsApi.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
- src/test/java/com/google/devtools/build/lib/starlarkdocextract/ModuleInfoExtractorTest.java
After https://github.com/bazelbuild/bazel/commit/a2f1f58cdff07d240c9f715d5091672bd9abd03f, macro inheritance API is in a good shape - and without macro inheritance, we wouldn't have any good way for symbolic macros in Bazel 8 to use `testonly`.
Considering for how little time the --experimental_enable_macro_inherit_attrs existed, and that no references to it was marked experimental, it seems safe to remove it directly without graveyarding.
Cherry-pick of
https://github.com/bazelbuild/bazel/commit/a39d18122ae824697691813a103ccb65871ff033
RELNOTES: Re-enable symbolic macro attribute inheritance.
PiperOrigin-RevId: 698884636
Change-Id: I7f682949e96b6739e12d8f569a87ef2daf0ea41c
> [8.0.0] Re-enable symbolic macro attribute inheritance and remove --experimental_enable_macro_inherit_attrs flag

- src/main/cpp/option_processor_windows.cc
This fixes startup failures such as:
```
ERROR: While parsing option --client_env==C:=C:\Users\wyv: Variable definitions must be in the form of a 'name=value' assignment
```
Fixes #24448
Closes #24451.
PiperOrigin-RevId: 699115724
Change-Id: Id7a2445e82b24384e9ade0c92ddb343f00e9ab2b
Commit https://github.com/bazelbuild/bazel/commit/59eb5192bc06f50192a3bd442ba170001b7127c2
> [8.0.0] Do not forward legacy `cmd.exe` variables to the server

- src/main/java/net/starlark/java/eval/StarlarkThread.java
- src/test/java/com/google/devtools/build/lib/starlarkdebug/server/StarlarkDebugServerTest.java
If we breakpoint at a line before a local (that is a cell) has been intialized, cell.x is null, which we shouldn't attempt to add to the returned map of locals.
Fixes https://github.com/bazelbuild/bazel/issues/24339
PiperOrigin-RevId: 698316990
Change-Id: Ifb45650fb41471c47605292af9873e9f66b7f7d7
Commit https://github.com/bazelbuild/bazel/commit/ae330a2d1efa3e4eda0b518492d7215a549cc032
> [8.0.0] Fix NPE in the Starlark debugger

- src/main/cpp/option_processor_windows.cc
- src/test/shell/integration/run_test.sh
This fixes startup failures such as:
```
ERROR: While parsing option --client_env==C:=C:\Users\wyv: Variable definitions must be in the form of a 'name=value' assignment
```
Fixes #24448
Closes #24451.
PiperOrigin-RevId: 699115724
Change-Id: Id7a2445e82b24384e9ade0c92ddb343f00e9ab2b
> [Rolling release] Do not forward legacy `cmd.exe` variables to the server

- src/main/java/com/google/devtools/build/lib/dynamic/LocalBranch.java
- src/main/java/com/google/devtools/build/lib/dynamic/RemoteBranch.java
RELNOTE: None
PiperOrigin-RevId: 700286030
Change-Id: I9c9f32f2d3e35b3cf6563a162d31ec35b8ea7e64
Commit https://github.com/bazelbuild/bazel/commit/6f8f372b6ce305b99952cff4bec5c3e41f30748f
> [8.0.0] Cherry-pick two new logs to provide more information in dynamic execution.

- site/en/_book.yaml
- site/en/extending/_index.yaml
- site/en/extending/concepts.md
- site/en/reference/glossary.md
- site/en/rules/legacy-macro-tutorial.md
- site/en/rules/macro-tutorial.md
- site/en/rules/verbs-tutorial.md
Cherry-pick of
https://github.com/bazelbuild/bazel/commit/634f4ec3a1c82d729e789723ee55bcea200417e8
PiperOrigin-RevId: 700733747
Change-Id: Idab23068f679ce5b881c94c05b202b4526d59cca
> [8.0.0] Update macro tutorial, glossary, and related docs for symbolic macros

- src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java
- src/test/shell/integration/run_test.sh
This allows passing through env in a similar way to doing `FOO=bar bazel
run` but also allows you to put this in a `.bazelrc`, and allows you to
bypass any environment filtering done when launching bazel.
Closes #24068.
PiperOrigin-RevId: 692853922
Change-Id: I802c31f2e0b30a738a41f24395dedbaf0b7caef1
Commit https://github.com/bazelbuild/bazel/commit/e60d88672cc4999e057f1c12bac2a1380d7e0a50
> [8.0.0] Add --run_env to bazel run

- site/en/concepts/visibility.md
- site/en/extending/macros.md
- src/main/java/com/google/devtools/build/docgen/templates/attributes/common/visibility.html
- src/main/java/com/google/devtools/build/docgen/templates/be/functions.vm
These were meant to be included with #23857 (forked in #23945).
> [8.0.0] Update concept docs for symbolic macros and visibility

- src/main/starlark/builtins_bzl/bazel/exports.bzl
- src/main/starlark/builtins_bzl/common/exports.bzl
- src/main/starlark/builtins_bzl/common/java/java_common.bzl
Fixes https://github.com/bazelbuild/bazel/issues/24551
Context: https://github.com/bazelbuild/rules_scala/issues/1652#issuecomment-2507453047
This will fix the issue in Bazel@HEAD, and the primary motivation is to turn downstream CI green.
On the off-chance we are making a new Bazel 8 RC, we can include this. Otherwise, maybe this can go in 8.1.0
PiperOrigin-RevId: 701260369
Change-Id: If62eb015b5220b574ce34a26a194d2722021082f (cherry picked from commit 15b8e3f7e07e1d286fa73e73c55da45e7508d73d)
> [8.0.0] Make the removed java symbols compatible with `WORKSPACE` loading

- src/main/starlark/builtins_bzl/common/builtin_exec_platforms.bzl
- src/test/py/bazel/bazel_windows_cpp_test.py
Workaround https://github.com/bazelbuild/bazel/issues/24545
RELNOTES: None
PiperOrigin-RevId: 702651276
Change-Id: Ic2e6f8f215798d202603e1771bd228bcd6b21bed
> [8.0.0] Don't leak `-g0` to the MSVC compiler on Windows

- site/en/docs/bazel-and-java.md
- src/main/java/com/google/devtools/build/docgen/templates/attributes/common/toolchains.html
- src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm
The targets being referenced in `@bazel_tools` were just aliases to `@rules_java`.
PiperOrigin-RevId: 700949569
Change-Id: Ief4bb0e4e3a66a337d4a949587e2a391115a76c5
(cherry-picked from f001ef1a8a2af31abd879598a6def9eb22d3433f)
> [8.0.0] Change `@bazel_tools//tools/jdk` references to `@rules_java//toolchains` in docs

- MODULE.bazel
Our CI fails to build Bazel, producing this error: "The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713."
The workaround was suggested at https://github.com/bazelbuild/rules_python/issues/1169#issuecomment-1513804247
Closes #24549.
PiperOrigin-RevId: 702362811
Change-Id: Ib6d4da1e09fd2b7dfd68af02bbb0eb997e8f427c
> [8.0.0] Enable ignore_root_user_error for Python toolchain

- src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
- src/test/shell/bazel/bazel_test_test.sh
Fixes #24578.
PiperOrigin-RevId: 703513880
Change-Id: I3f95a92ead3e64007974e45362185738b5927cee
Commit https://github.com/bazelbuild/bazel/commit/d93c1cb3b804e012ca8b27c905a99fa7c0ea431c
> [8.0.0] Create intermediate directories when moving deeply nested undeclared outputs.

- scripts/docs/rewriter.py
- site/command-line-reference-prefix.html
- Ensure that rewriter.py also processes generated docs in order to set metadata required by the version selector
- Enable version selector for the command line reference
PiperOrigin-RevId: 703532562
Change-Id: I77664bd6e14b59d2ef0b749f85a52a09c291f6e8
Commit https://github.com/bazelbuild/bazel/commit/19047be2a9294b001e16cb10ec811414aac0eff2
> [8.0.0] Bazel Docs: Fix version selector in release docs

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
This helps the HTTP downloader better cope with filesystems where unlink is non-atomic.
Closes #24295.
PiperOrigin-RevId: 697920434
Change-Id: I91b4dbf07a2efdca07c0310e15aac5f4d89c4091
Commit https://github.com/bazelbuild/bazel/commit/99a27f6d4709516b6210ea4457259f12dd3666ee
> [8.0.1] Retry the cleanup of downloadAndExtract

- site/en/extending/macros.md
Closes #24585.
PiperOrigin-RevId: 704366607
Change-Id: Ibdc89e1ad30ded6f3b69edc2877fcac78c622ea9
Commit https://github.com/bazelbuild/bazel/commit/baa01598cc8e2747d65c0fedcde276e6c9690adf
> [8.0.1] Fix invalid `dict` syntax in macro docs

- src/main/cpp/blaze.cc
- src/test/shell/integration/bazel_command_log_test.sh
- src/test/shell/integration/client_test.sh
PiperOrigin-RevId: 697623665
Change-Id: I5553240373da5cccb405aba7524b3930fcd961c2 (cherry picked from commit 56329b904b8adc284adb3a06b36ef061521e60f0)
Fixes #24626
> [8.0.1] Print embedded label / version when starting Bazel.

- src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
`TEST_PREMATURE_EXIT_FILE` was not cleaned up between test attempts (--flaky_test_attempts).
Fixes https://github.com/bazelbuild/bazel/issues/24655
Closes #24657.
PiperOrigin-RevId: 705495967
Change-Id: Ic4d4be1e72230c3a6bc45c9f372d1188fefad201
Commit https://github.com/bazelbuild/bazel/commit/b33d51f250499b6e51ff9d82371d053fff8e3f55
> [8.0.1] Fix checking TEST_PREMATURE_EXIT_FILE

- src/test/py/bazel/bzlmod/bazel_overrides_test.py
- src/test/py/bazel/py_test.py
- src/test/py/bazel/test_base.py
python: fix bazel py_test testSmoke for Python 3.11+
The test was failing because the `b.py` file couldn't be imported because, starting with Python 3.11, the `PYTHONSAFEPATH` environment variable (set by the bootstrap startup) is respected. This setting inhibits the default Python behavior of adding the main script's directory to sys.path.
To fix, use `py_library.imports` to explicitly add the necessary directory to `sys.path`.
Fixes https://github.com/bazelbuild/bazel/issues/20660
Closes https://github.com/bazelbuild/bazel/pull/20738.
PiperOrigin-RevId: 595498775
Change-Id: I0c9521b210fe9e2c40692727fc87d41995e0968a
Commit https://github.com/bazelbuild/bazel/commit/9b027c88051797ada7350098ef190191b953014a
No public description
PiperOrigin-RevId: 694487395
Change-Id: …
> [7.5.0] Backport 9b027c8 and be2186f to fix windows CI failures

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
This helps the HTTP downloader better cope with filesystems where unlink is non-atomic.
Closes #24295.
PiperOrigin-RevId: 697920434
Change-Id: I91b4dbf07a2efdca07c0310e15aac5f4d89c4091
Commit https://github.com/bazelbuild/bazel/commit/99a27f6d4709516b6210ea4457259f12dd3666ee
> [7.5.0] Retry the cleanup of downloadAndExtract

- tools/build_defs/pkg/path_test.py
No longer works with python 3.12 or later.
PiperOrigin-RevId: 694480477
Change-Id: Ia662c8fb5511e9c551448730800240ab627463be
Commit https://github.com/bazelbuild/bazel/commit/5b54c7412cfb251d9ab83e23b37f06504b893331
> [7.5.0] Cherry-pick "Migrate imp to importlib in path_test.py"

- src/main/starlark/builtins_bzl/common/objc/compilation_support.bzl
- src/test/java/com/google/devtools/build/lib/rules/objc/ObjcStarlarkTest.java
Fixes https://github.com/bazelbuild/bazel/issues/24625
Closes #24698.
PiperOrigin-RevId: 707183228
Change-Id: I369a37e8e652545274ec4949b1c3ac1d2fab38cb
Commit https://github.com/bazelbuild/bazel/commit/2864f2afd948825571761e15dcb5aff517005342
> [8.0.1] Fix linking objc binaries in the root package

- src/tools/launcher/java_launcher.cc
wofstream cannot be constructed from wstring according to the standard https://en.cppreference.com/w/cpp/io/basic_ofstream/basic_ofstream.
Closes #24703.
PiperOrigin-RevId: 707172911
Change-Id: I973f9560c5b20748e4635cd757f53fff9c8ef0c5
Commit https://github.com/bazelbuild/bazel/commit/5b35276f57271bf1d81edade231abd667f1d034b
> [7.5.0] java_launcher: Fix non-portable ofstream usage

- src/main/java/com/google/devtools/build/lib/skyframe/BuildDriverFunction.java
When Skymeld is enabled, symlinks for external repositories are planted lazily in response to an event sent in `BuildDriverFunction`. For top-level aspects, this event needs to be sent individually for each aspect as the transitive packages required can differ per aspect. `BuildDriverFunction` deduplicated all events, including the one for symlink planting, by type, which resulted in missing symlinks for actions registered by the second (and later) aspects.
Fixes #24619
Closes #24676.
PiperOrigin-RevId: 707458188
Change-Id: I9fe523bc746d29e6c6ddb6367e08ce2c6c48c69b
Commit https://github.com/bazelbuild/bazel/commit/f4b071c699dfd8cd324f58eab923e36a3907b33b
> [8.0.1] Fix symlink planting for multiple aspects

- src/main/java/com/google/devtools/build/lib/sandbox/cgroups/controller/v2/UnifiedCpu.java
- src/test/java/com/google/devtools/build/lib/sandbox/cgroups/CpuTest.java
Fixes https://github.com/bazelbuild/bazel/issues/24680
Closes #24714.
PiperOrigin-RevId: 707775390
Change-Id: I1a34c0917174aca3bbcfdec8668aef2d7e68ae6e
Commit https://github.com/bazelbuild/bazel/commit/1c6aa500db5c3c8cc554088154be510c78dd7aee
> [8.0.1] Fix parsing cpu.max file in cgroup v2 implementation

- src/main/java/com/google/devtools/build/lib/analysis/BlazeVersionInfo.java
This is necessary to allow for accurate bisects of Bazel issues when rules rely on `bazel_features` for feature detection. The variable can be used to force the lowest version relevant to the bisect or, in the future, `bazelisk --bisect` could extrapolate the release version from tags.
Closes #24669.
PiperOrigin-RevId: 708009535
Change-Id: I89fad7db4e5443558815ff2351247786558a8ab6
Commit https://github.com/bazelbuild/bazel/commit/b77fe106fc51bf33449c410cf3f909a832d72411
> [8.0.1] Allow `native.bazel_version` to be overridden for dev builds

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionMetadata.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RootModuleFileFixup.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionFunction.java
- src/test/py/bazel/bzlmod/mod_command_test.py
The warnings tell the user to run `bazel mod tidy`, which is very confusing.
Fixes #24495
Closes #24729.
PiperOrigin-RevId: 708007222
Change-Id: I60dc889281a776bbf08a7f9537272d7692cce1d8
Commit https://github.com/bazelbuild/bazel/commit/455ddb74f79a5eb9b47ad212a8d439f56fd58a5f
> [8.0.1] Don't show fixup warnings during `bazel mod tidy`

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryFunction.java
- src/test/shell/bazel/starlark_repository_test.sh
Fixes #24621
Closes #24666.
PiperOrigin-RevId: 708009380
Change-Id: I8706f1fdfba2282a27e84dff610e6511c1060e23
Commit https://github.com/bazelbuild/bazel/commit/7e7ae8c1b4adcaf2ac11bc76231a10f7f88a9eb4
> [8.0.1] Handle access to files under invalid repo names gracefully

- src/main/native/windows/file.cc
- src/main/native/windows/process.cc
- src/tools/launcher/java_launcher.cc
- src/tools/launcher/launcher_main.cc
TEST: bazel build --platforms=//:windows_x86_64  --extra_toolchains=@llvm_mingw_linux_x86_64//:cc-toolchain-linux_x86_64-windows_x86_64 //src/tools/launcher:launcher
Closes #24752.
PiperOrigin-RevId: 711358608
Change-Id: Iedacad9b959427ed5d4598e0ea594cb25b8845c8
Commit https://github.com/bazelbuild/bazel/commit/a4bb2543bd2e796b472a5c33c1b68b4b9866d977
> [7.5.0] windows launcher: Make the launcher compile under mingw

- site/en/docs/user-manual.md
auto does not exist in Bazel 4, 5, 6 or 7. I'm not sure if was there before but in any of these versions when trying it the following error appears
ERROR: While parsing option --dynamic_mode=auto: Not a valid dynamic mode: 'auto' (should be off, default or fully)
Fixes: https://github.com/bazelbuild/bazel/issues/20707
Closes #20705.
PiperOrigin-RevId: 630063050
Change-Id: Ib0b0427268a885d6ffc62c81183b6dd24a6dc517 (cherry picked from commit a70a28f22b18122a52a90e50ecf1360fbd45736c)
> [7.5.0] Fix error in dynamic_mode documentation

- src/main/java/com/google/devtools/build/lib/vfs/FileSystemUtils.java
- src/test/java/com/google/devtools/build/lib/vfs/FileSystemUtilsTest.java
When Bazel knows the size of a file, it can also detect whether it would go past this size while reading the file. This is virtually free due to using a buffered stream and can catch cases of concurrent modifications or even bugs in Bazel.
Work towards #24694
Closes #24708.
PiperOrigin-RevId: 711678485
Change-Id: I85093c0d54dd365b1c301b6036f150dae3552c2a
Commit https://github.com/bazelbuild/bazel/commit/57ef120efad58cf5025dfb44c73beb45713a2d91
> [8.0.1] Detect file reads that are longer than expected

- scripts/bootstrap/bootstrap.sh
- scripts/bootstrap/compile.sh
- src/test/shell/bazel/bazel_bootstrap_distfile_test.sh
In https://github.com/bazelbuild/bazel/issues/24747, users reported errors during bootstrapping about `function_transition_allowlist` missing. This is likely because the version of rules_java used by Bazel itself started using a Starlark rule with a Starlark transition somewhere between Bazel 7 and 8. The bootstrap script never properly set up the `tools/allowlists/function_transition_allowlist` package, so we do that in this CL.
Similarly, we never properly switched to Java 21 in the script; this CL updates that.
It's still a mystery why our bootstrap tests never failed on CI. The only explanation I can think of is that our CI environment somehow detects local JDKs different, resulting in a code path that does _not_ require the `function_transition_allowlist` target to exist. More …
> [8.0.1] Partially fix the bootstrap build

- src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl
- src/test/java/com/google/devtools/build/lib/rules/cpp/CcToolchainProviderTest.java
Fixes https://github.com/bazelbuild/bazel/issues/23247
Closes https://github.com/bazelbuild/bazel/issues/24768
PiperOrigin-RevId: 707176116
Change-Id: I71ef3c630f8130467cc6a0c730c1278ae6b0817f
(cherry picked from commit 03eae37f24dbaaacf8a0fa4299bd452b643014b8)
> [7.5.0] Remove empty coverage environment

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionMetadata.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RootModuleFileFixup.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionFunction.java
- src/test/py/bazel/bzlmod/mod_command_test.py
The warnings tell the user to run `bazel mod tidy`, which is very confusing.
Fixes #24495
Closes #24729.
PiperOrigin-RevId: 708007222
Change-Id: I60dc889281a776bbf08a7f9537272d7692cce1d8 
(cherry picked from commit 455ddb74f79a5eb9b47ad212a8d439f56fd58a5f)
Fixes #24740
> [7.5.0] Don't show fixup warnings during `bazel mod tidy`

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/test/shell/bazel/cc_integration_test.sh
`cc_binary` has an initializer that may set a private attribute, which is only permitted for built-in rules. The allowlist check always used the outermost rule class, thus failing if `cc_binary` is extended by a non-built-in rule. This is fixed by checking the rule class that actually declares the initializer.
Work towards https://github.com/bazelbuild/bazel/issues/19507#issuecomment-1933572248
Closes #24778.
PiperOrigin-RevId: 711361632
Change-Id: I3c0b6e1e6c50fd1af9f1dc635052d0054114ee2d
Commit https://github.com/bazelbuild/bazel/commit/7093088c5427b016e62bed70852b010fc308ad4a
> [8.0.1] Allow `cc_binary` with `dynamic_deps` to be extended

- src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java
- src/test/shell/integration/incompatible_autoload_externally_test.sh
This reduces noise while giving users more actionable information when they actually use a symbol that failed to autoload.
Also ensures that modules with legacy repo names (`com_google_protobuf` and `build_bazel_apple_support`) are handled correctly.
Fixes #23929
Fixes #24597
Closes #24601.
PiperOrigin-RevId: 713208045
Change-Id: I81ae8e9e09dd3a935dca2897fe9fc58d52189a07
Commit https://github.com/bazelbuild/bazel/commit/eba205433aedcd55185f105adbf998ce501b84c8
> [8.0.1] Remove autoload warnings, improve errors and fix legacy repo name support

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/JsonOutputFormatter.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodTestUtil.java
This allows IDEs to query for the direct dependencies of the root module as well as how they can refer to them from the point of view of the root module.
Also always emit `name` and `version` so that consumers don't have to know how to parse module keys.
Work towards #22691
Closes #23787.
PiperOrigin-RevId: 693453084
Change-Id: Ie3fd5e89301d8e83d0eaa686188634923853f01a (cherry picked from commit 1003d2c31bf4f90ded7015b1b7ed570d50ed6a63)
Fixes #24678
> [7.5.0] Include apparent names of deps in `bazel mod` JSON output

- src/main/java/com/google/devtools/build/skyframe/InvalidatingNodeVisitor.java
This protects against an integer overflow which could occur for large key list size and large thread counts.
Regrettably, it's difficult to write a regression test for this scenario, as exercising this overflow requires lots of time and heap, so it would be a performance regression to our test suites.
Fixes https://github.com/bazelbuild/bazel/issues/19445
PiperOrigin-RevId: 595420516
Change-Id: Ic0a475a6a273c50fe9895dd0852fa5b062859cb2
Commit https://github.com/bazelbuild/bazel/commit/3e373d0abc79e40b3fa46aca4aa268c5ae9b7dc2
> [7.5.0] Use long instead of int for thread indices

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleContext.java
- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/rules/objc/BUILD
- src/main/java/com/google/devtools/build/lib/rules/objc/ObjcStarlarkInternal.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkRuleContextApi.java
- src/test/java/com/google/devtools/build/lib/packages/semantics/ConsistencyTest.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleImplementationFunctionsTest.java
Work towards #11820
Fixes #20038
Fixes #23200
Fixes #24613
RELNOTES: Extra targets provided to `ctx.expand_location` now expand to their executable (if any) instead of resulting in an error if they provide a number of files different from one.
RELNOTES[INC]: The `--incompatible_locations_prefers_executable` flag has been added and enabled, which makes it so that `ctx.expand_location` expands `$(locations :x)` to the executable of an extra target `:x` if it provides one and the number of files provided by it is not one.
Closes #24690.
PiperOrigin-RevId: 713453768
Change-Id: I0d6e052bc70deea029554ab722feb544f9597a23 
(cherry picked from commit 457d248218540b0ae93d6454fa8a95ccad877063)
Fixes #24646
> [8.0.1] Add and flip `--incompatible_locations_prefers_executable`

- src/main/java/com/google/devtools/build/lib/bazel/BazelStartupOptionsModule.java
- src/test/shell/integration/startup_options_test.sh
Fixes #24730
Closes #24735.
PiperOrigin-RevId: 713606521
Change-Id: If8578fcdfc30dcbfb6af283089614f3364eb30d8
Commit https://github.com/bazelbuild/bazel/commit/e78bab504940ea2abce749cf8654320cc2fbf96f
> [8.0.1] Mark `--blazerc` as `allows_multiple` in flag docs

- src/main/java/com/google/devtools/build/lib/bazel/BazelStartupOptionsModule.java
- src/test/shell/integration/startup_options_test.sh
Fixes #24730
Closes #24735.
PiperOrigin-RevId: 713606521
Change-Id: If8578fcdfc30dcbfb6af283089614f3364eb30d8
Commit https://github.com/bazelbuild/bazel/commit/e78bab504940ea2abce749cf8654320cc2fbf96f
> [7.5.0] Mark `--blazerc` as `allows_multiple` in flag docs

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/commands/ModCommand.java
This fills in a few gaps in the timing profile.
Closes #24762.
PiperOrigin-RevId: 714028550
Change-Id: I5772b59c5d3b6d73306ea5d8380169465f348f27
Commit https://github.com/bazelbuild/bazel/commit/edb2b0648b426521ba14d0a00a5bf56e04430eb4
> [8.0.1] Add more Bzlmod-related profiler spans

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Registry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/FakeRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
- src/test/py/bazel/bzlmod/bazel_overrides_test.py
This makes it easier for users to discover that a module hasn't been found because its absence was recorded in the lockfile during a previous build.
Fixes #24803
Closes #24804.
PiperOrigin-RevId: 713142592
Change-Id: Id541f5710481bd947c09d8dba315d683a1666b1c 
(cherry picked from commit 6061e5eab4b0bf1b9424a348c32bdcda69a8280b)
Fixes #24805
> [7.5.0] Explain why a module hasn't been found in any registry

- tools/build_defs/repo/local.bzl
Fixes #24770
Closes #24887.
PiperOrigin-RevId: 714107497
Change-Id: Ib914aa54b2afa2a90fcce2f2263b9c1b2d2c193c
Commit https://github.com/bazelbuild/bazel/commit/6a141eab3fa5d57eb8b5dadbb6260a120c597fe9
> [8.0.1] Remove BUILD.bazel before symlinking when creating new_local_repository

- src/main/java/com/google/devtools/build/lib/runtime/commands/HelpCommand.java
- src/main/java/com/google/devtools/common/options/OptionDefinition.java
Fixes #24882
Closes #24883.
PiperOrigin-RevId: 714854122
Change-Id: I5e48e84f88606320223a9969e8367924aeeb13dd
Commit https://github.com/bazelbuild/bazel/commit/6423b04c1bf95bc0e9ef99667688b3763c3bce4e
> [7.5.0] Report options with `BoolOrEnumConverter` as supporting `--no...`

- tools/build_defs/repo/local.bzl
Fixes #24770
Closes #24887.
PiperOrigin-RevId: 714107497
Change-Id: Ib914aa54b2afa2a90fcce2f2263b9c1b2d2c193c
Commit https://github.com/bazelbuild/bazel/commit/6a141eab3fa5d57eb8b5dadbb6260a120c597fe9
> [7.5.0] Remove BUILD.bazel before symlinking when creating new_local_repository

- src/main/java/com/google/devtools/build/lib/exec/RunfilesTreeUpdater.java
- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java
- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeStrategy.java
- src/test/java/com/google/devtools/build/lib/exec/SymlinkTreeHelperTest.java
This makes it possible to hardcode in-process and get rid of out-of-process (in a future CL).
This change doesn't affect Bazel, as filesets only exist in Blaze.
PiperOrigin-RevId: 695279110
Change-Id: I404fa9a60b285f46e68697ec3342bf61831da36e
> [8.0.1] Also apply --experimental_inprocess_symlink_creation to filesets.

- src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
- src/main/protobuf/spawn.proto
- src/test/java/com/google/devtools/build/lib/exec/CompactSpawnLogContextTest.java
This makes it possible to retroactively link an execution log file to a particular build.
Closes #24790.
PiperOrigin-RevId: 715017597
Change-Id: Ia8f6a3677a165a9f428b59ab8a19587a357b8803
Commit https://github.com/bazelbuild/bazel/commit/fd6a9833ba9fe18799193295b82134bc64ab17b3
> [7.5.0] Include invocation ID in compact execution log

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkActionFactory.java
- src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRulesModule.java
- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkActionFactoryApi.java
- src/test/java/com/google/devtools/build/lib/packages/semantics/ConsistencyTest.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleContextTest.java
PiperOrigin-RevId: 715819891
Change-Id: I1c2e582a3d4c6e87e5c76837abb7a175eed3e850 
(cherry picked from commit c570f978e5bd67d90318a12e353c6e5ba099da36)
Fixes #24933
> Deprecate the `experimental_action_resource_set` flag.

- src/main/java/com/google/devtools/build/lib/actions/FileArtifactValue.java
- src/main/java/com/google/devtools/build/lib/actions/cache/CompactPersistentActionCache.java
- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
- src/main/java/com/google/devtools/build/lib/skyframe/FilesystemValueChecker.java
- src/test/java/com/google/devtools/build/lib/actions/ActionCacheCheckerTest.java
- src/test/java/com/google/devtools/build/lib/actions/CompletionContextTest.java
- src/test/java/com/google/devtools/build/lib/actions/cache/CompactPersistentActionCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/ActionInputPrefetcherTestBase.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTestBase.java
- src/test/java/com/google/devtools/build/lib/remote/ByteStreamBuildEventArtifactUploaderTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteActionFileSystemTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/ActionExecutionValueTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStoreTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/FileArtifactValueTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/FilesystemValueCheckerTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactBuildTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactValueTest.java
... if the corresponding output is materialized afterwards and hasn't been changed.
Failing to do so will cause an incremental build to re-check the action cache for actions whose outputs were materialized during last build. This can be very slow if the size of the outputs are large.
We achieved this by storing `FileContentsProxy` in the remote metadata after materialization. During dirtiness check, we compare remote metadata and the corresponding local metadata with their `digest`, or `proxy` if `digest` is not available for local metadata,
A user reported back the wall time of their very first increment build is improved by this change from `14s` to less than `1s` in common case, and from `115s` to less than `1s` in worst case. https://github.com/bazelbuild/bazel/issues/24763 …
> [7.5.0] Do not invalidate remote metadata during action dirtiness check

- src/main/cpp/option_processor.cc
- src/test/shell/integration/client_test.sh
This masked issues in Bazel wrappers in a very confusing way.
Fixes #24577
Closes #24579.
PiperOrigin-RevId: 704193424
Change-Id: Iaf486b9eb5764073439be9968f449eaf172667ca
Commit https://github.com/bazelbuild/bazel/commit/40c942ac484e8a5a5834a2c7686991a4f3e42746
> [8.1.0] Don't fall back to `help` command when command is empty

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
Included module file segments already had to have a `.MODULE.bazel` suffix, but this wasn't documented. Also prohibit a filename starting with a `.`, which would hide the file on Unix.
Closes #24575.
PiperOrigin-RevId: 703417032
Change-Id: Idc87e0012f42d5ba9b0e6c5a5a7be9294f99f636
Commit https://github.com/bazelbuild/bazel/commit/c6956af0825bf9d202db3d7c07d6390730440c1c
> [8.1.0] Document and enforce filename restrictions for module file segments

- src/tools/launcher/java_launcher.cc
wofstream cannot be constructed from wstring according to the standard https://en.cppreference.com/w/cpp/io/basic_ofstream/basic_ofstream.
Closes #24703.
PiperOrigin-RevId: 707172911
Change-Id: I973f9560c5b20748e4635cd757f53fff9c8ef0c5
Commit https://github.com/bazelbuild/bazel/commit/5b35276f57271bf1d81edade231abd667f1d034b
> [8.1.0] java_launcher: Fix non-portable ofstream usage

- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
Fix for #24530
--experimental_repository_downloader_retries will now retry on `SocketException` in addition to `ContentLengthMismatchException`
Closes #24608.
PiperOrigin-RevId: 704633572
Change-Id: Idd1fcbb768c9dabed596fe15d8ae9260ef3e895d
Commit https://github.com/bazelbuild/bazel/commit/459bb5736c5af6fc7a70e1cd9dceb40abb0ad71d
> [8.1.0] Also apply --experimental_repository_downloader_retries to a SocketException

- src/main/java/com/google/devtools/build/lib/analysis/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java
- src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java
- src/main/java/com/google/devtools/build/lib/analysis/config/RunUnder.java
- src/main/java/com/google/devtools/build/lib/analysis/config/RunUnderConverter.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestStrategy.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestTargetExecutionSettings.java
- src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java
- src/main/java/com/google/devtools/build/lib/skyframe/BUILD
- src/main/java/com/google/devtools/build/lib/skyframe/ConfiguredTargetFunction.java
- src/test/java/com/google/devtools/build/lib/analysis/config/RunUnderConverterTest.java
Closes #24318.
PiperOrigin-RevId: 696635274
Change-Id: Ib98b01132c535ce72002c5acfcadf846f9166119
Commit https://github.com/bazelbuild/bazel/commit/fccfaa170590383d93a654d16cad230ad6e09f7d
> [8.1.0] Make `RunUnder` a sealed interface

- src/main/java/com/google/devtools/build/lib/analysis/ExecGroupCollection.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/main/java/com/google/devtools/build/lib/packages/ExecGroup.java
- src/main/java/com/google/devtools/build/lib/packages/RuleClass.java
- src/test/java/com/google/devtools/build/lib/analysis/testing/ExecGroupSubject.java
- src/test/java/com/google/devtools/build/lib/packages/RuleClassBuilderTest.java
- src/test/java/com/google/devtools/build/lib/packages/RuleClassTest.java
Work towards #23802
Closes #24704.
PiperOrigin-RevId: 708006518
Change-Id: Ibe2294750d7238dc20c8c39dba9e63a987a46b14
Commit https://github.com/bazelbuild/bazel/commit/51a6c387459b42360faf64e94626bdd9716f6075
> [8.1.0] Remove the unused concept of exec group inheritance

- src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl
- src/test/java/com/google/devtools/build/lib/rules/cpp/CcToolchainProviderTest.java
Fixes https://github.com/bazelbuild/bazel/issues/23247
Closes #24670.
PiperOrigin-RevId: 707176116
Change-Id: I71ef3c630f8130467cc6a0c730c1278ae6b0817f
Commit https://github.com/bazelbuild/bazel/commit/03eae37f24dbaaacf8a0fa4299bd452b643014b8
> [8.1.0] Remove empty coverage environment

- src/main/java/com/google/devtools/build/lib/runtime/CommonCommandOptions.java
This option, which is different from the startup option of the same name, has no effect and doesn't even show a warning, which can be confusing.
Closes #24953.
PiperOrigin-RevId: 717853503
Change-Id: I8d7d1229f692007c4350b6c15526b7a95bbed5ef
Commit https://github.com/bazelbuild/bazel/commit/79508becbb9195dc59e24b9aa3dbaf880c209e2e
> [7.5.0] Remove no-op `--block_for_lock` command option

- src/main/cpp/blaze.cc
On Unix we use a fcntl() lock, not flock(), and on Windows we use LockFileEx.
PiperOrigin-RevId: 693314236
Change-Id: I6facfe2da1c2ece0bf75b6a815f73301e2db64b0
> [8.1.0] Improve the documentation for client/server synchronization.

- src/main/cpp/option_processor.cc
- src/main/cpp/rc_file.cc
- src/main/cpp/workspace_layout.cc
- src/main/cpp/workspace_layout.h
- src/test/cpp/rc_file_test.cc
PiperOrigin-RevId: 699910973
Change-Id: I12072b521fcbee6f7f9aa0274ecaf10eb769f715
> [8.1.0] Do not fall back to interpreting a %workspace% placeholder literally if resolution fails, even for try-import.

- src/main/java/com/google/devtools/build/lib/runtime/CommonCommandOptions.java
This option, which is different from the startup option of the same name, has no effect and doesn't even show a warning, which can be confusing.
Closes #24953.
PiperOrigin-RevId: 717853503
Change-Id: I8d7d1229f692007c4350b6c15526b7a95bbed5ef
Commit https://github.com/bazelbuild/bazel/commit/79508becbb9195dc59e24b9aa3dbaf880c209e2e
> [8.1.0] Remove no-op `--block_for_lock` command option

- src/main/cpp/archive_utils.cc
- src/main/cpp/blaze.cc
- src/main/cpp/util/file_platform.h
- src/main/cpp/util/file_posix.cc
- src/main/cpp/util/file_windows.cc
- src/main/cpp/util/path_posix.cc
- src/test/cpp/blaze_archive_test.cc
- src/test/cpp/util/file_test.cc
- src/test/cpp/util/file_windows_test.cc
PiperOrigin-RevId: 689335964
Change-Id: I62b1d8705e4e015cf6f7ab1188e93bc4f49d4446
> [8.1.0] Use static functions instead of a singleton class for mtime manipulation.

- src/test/shell/bazel/bazel_coverage_starlark_test.sh
- tools/test/extensions.bzl
- workspace_deps.bzl
Built at commit 82c1ff79.
Relevant changes:
* Log level for many messages changed from INFO to FINE (#22257).
* IOExceptions are no longer ignored (#21987).
* Baseline coverage files are not ignored (#24563).
RELNOTES: Baseline coverage files are no longer ignored.
Closes #24593.
PiperOrigin-RevId: 705492845
Change-Id: I6f7b99ec0f040f93cc148c9c8448d4395729adac
Commit https://github.com/bazelbuild/bazel/commit/6cd487048a69fc6a90707d5cce15b47e00d230a8
> [8.1.0] Update coverage output generator to coverage_output_generator-v2.7.

- tools/sh/sh_toolchain.bzl
Closes #24961.
PiperOrigin-RevId: 717997981
Change-Id: I1b80bb9cb483a1c2e2ad53f983ebae050b1c5fd4
Commit https://github.com/bazelbuild/bazel/commit/aa2e431415ff513f148b27a006ec7068d596681e
> [8.1.0] sh_toolchain: Fix broken alias

- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/FileApi.java
The previous doc say it told if it was a directory; probably a copy/paste mistake.
PiperOrigin-RevId: 714089602
Change-Id: Ib6f6bee762afdd41f7249f120f4f95a088a3ccef
Commit https://github.com/bazelbuild/bazel/commit/b69cba6807f5753435a7ccf61695ca371b1a790c
> [8.1.0] Fix File.is_symlink doc to correctly say it tells if it's a symlink.

- src/main/cpp/archive_utils.cc
- src/main/cpp/archive_utils.h
- src/main/cpp/bazel_startup_options.cc
- src/main/cpp/blaze.cc
- src/main/cpp/blaze_util_platform.h
- src/main/cpp/blaze_util_posix.cc
- src/main/cpp/blaze_util_windows.cc
- src/main/cpp/startup_options.cc
- src/main/cpp/startup_options.h
- src/main/cpp/util/file.cc
- src/main/cpp/util/file.h
- src/main/cpp/util/file_platform.h
- src/main/cpp/util/file_posix.cc
- src/main/cpp/util/file_windows.cc
- src/main/cpp/util/path_platform.h
- src/main/cpp/util/path_posix.cc
- src/main/cpp/util/path_windows.cc
- src/test/cpp/option_processor_test.cc
- src/test/cpp/rc_file_test.cc
- src/test/cpp/startup_options_test.cc
- src/test/cpp/util/BUILD
- src/test/cpp/util/file_posix_test.cc
- src/test/cpp/util/file_test.cc
- src/test/cpp/workspace_layout_test.cc
PiperOrigin-RevId: 698818638
Change-Id: Iea02eb6d3524ecc98970a63aa554927c701efe28
> [8.1.0] Use blaze_util::Path instead of std::string in more places.

- src/main/java/com/google/devtools/build/lib/analysis/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/config/OutputPathMnemonicComputer.java
- src/main/java/com/google/devtools/build/lib/analysis/config/RunUnder.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestConfiguration.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestTrimmingLogic.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestTrimmingTransitionFactory.java
- src/test/shell/integration/run_test.sh
Rollforward with fixes
Preserve analysis cache through `--run_under` command changes
Work towards https://github.com/bazelbuild/bazel/issues/3325 Fixes https://github.com/bazelbuild/bazel/issues/10782
RELNOTES: Changing any part of --run_under that isn't the label (such as the shell command) no longer invalidates the analysis cache.
Closes #24411.
PiperOrigin-RevId: 703516108
Change-Id: Ief9bd2547fe87b4c09b132ada87aed369753e550
Commit https://github.com/bazelbuild/bazel/commit/45d4cff7ff0ce0a6a3159ff537b0b0c65ddfbb76
> [8.1.0] Automated rollback of commit 650142fbe290d97e39b702d1dbcdbe126614b927.

- src/main/cpp/blaze.cc
PiperOrigin-RevId: 700351720
Change-Id: Ia30e7f217411cce329c053742f3262b70d386800
PiperOrigin-RevId: 704385156
Change-Id: I41b777e3e3b910175dfad8425d4e7913b7df0327
> [8.1.0] Print the client pid when --client_debug is set, which is useful for testing.

- src/main/cpp/blaze_util_platform.h
- src/main/cpp/blaze_util_posix.cc
- src/main/cpp/blaze_util_windows.cc
This makes it possible to use an exclusive lock to guard against concurrent deletion: otherwise, process 1 might delete the file and release the exclusive lock in between process 2 opening the file and acquiring a shared lock.
In practice, process 1 will be garbage-collecting an old install base while process 2 will be attempting to start itself on the same install base. (Note that install base locking is yet to be implemented.)
Also remove an ancient workaround for old glibcs: OFD locks have been available under _GNU_SOURCE on Linux since 2014.
PiperOrigin-RevId: 699142575
Change-Id: Ifc931c1f2952d97c449aaeee17e6ea43cb4c637e
> [8.1.0] Ensure that the lock file still exists when AcquireLock returns.

- src/main/cpp/blaze.cc
- src/main/cpp/blaze_util_platform.h
- src/main/cpp/blaze_util_posix.cc
- src/main/cpp/blaze_util_windows.cc
The current name is confusing because the method is used to create the output *user* root, not the output root. Use a name that reflects the behavior, not the presumed use.
PiperOrigin-RevId: 701287357
Change-Id: If9f5b95c96f1d0a5b7f080226daa8b5aa7b86ea2
> [8.1.0] Rename CreateSecureOutputRoot as CreateSecureDirectory.

- src/test/shell/integration/client_test.sh
In the end this wasn't required, because test cases that care set the `local = True` attribute on their build targets.
PiperOrigin-RevId: 701202168
Change-Id: I78bcea7888bbc2d15fecf2c6faaab77a7ab8ed97
> [8.1.0] Remove --spawn_strategy=local from client_test.sh.

- src/test/shell/integration/client_test.sh
PiperOrigin-RevId: 701236558
Change-Id: Idc83f9dbdcc930e380a300cd52206904744dbd85
> [8.1.0] Add an integration test to verify that SIGQUIT works.

- src/main/java/com/google/devtools/build/lib/actions/ActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/exec/AbstractSpawnStrategy.java
- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteActionInputFetcher.java
- src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java
- src/test/java/com/google/devtools/build/lib/remote/ActionInputPrefetcherTestBase.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteActionFileSystemTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteActionInputFetcherTest.java
ea4ad30d4e49b83b62df0e10b5abe2faadea7582 added an action as context for prefetches with BwoB, but assumed that all callers would use the prefetcher for inputs to locally executed actions. However, since then, it has also been used to download outputs of completed actions that have been explicitly requested (e.g. as outputs of top-level targets or those matching the regex path patterns). This resulted in downloads with a `prefetcher` action ID and action details for the action that produced the file, rather than consumed it, resulting in confusing situations for observability tools.
This is fixed by separately tracking the reason for the fetch. Using an action ID of `output` when the action has the requested file as an output, and "input" when the action has the requested file as an input. …
> [7.5.0] Distinguish between input and output prefetching in request metadata

- src/main/java/com/google/devtools/build/lib/rules/java/JavaStarlarkCommon.java
- src/test/shell/bazel/bazel_java_test.sh
Fixes https://github.com/bazelbuild/bazel/issues/25012
Closes #25043.
PiperOrigin-RevId: 719211390
Change-Id: I91267b3ce546a54cd065e4424f3e80aaa36cff28
Commit https://github.com/bazelbuild/bazel/commit/8fba20855f7979ecc61cb05bf9e3ec8890aeed90
> [8.1.0] Use runfiles path instead of root relative path in `JavaStarlarkCommon.collectNativeLibsDirs`

- src/main/java/com/google/devtools/build/docgen/bazel_link_map.json
Fixes https://github.com/bazelbuild/bazel/issues/24905
RELNOTES: None
PiperOrigin-RevId: 717532897
Change-Id: I620d8492689297f7c85824ea261b12bdfae2221b
Commit https://github.com/bazelbuild/bazel/commit/04a44fde9120ff11ab604b3ef7f0874eeddf78df
> [8.1.0] Fix docs link rewriting for rules_android

- src/main/native/windows/file.cc
- src/main/native/windows/process.cc
- src/tools/launcher/java_launcher.cc
- src/tools/launcher/launcher_main.cc
TEST: bazel build --platforms=//:windows_x86_64  --extra_toolchains=@llvm_mingw_linux_x86_64//:cc-toolchain-linux_x86_64-windows_x86_64 //src/tools/launcher:launcher
Closes #24752.
PiperOrigin-RevId: 711358608
Change-Id: Iedacad9b959427ed5d4598e0ea594cb25b8845c8
Commit https://github.com/bazelbuild/bazel/commit/a4bb2543bd2e796b472a5c33c1b68b4b9866d977
> [8.1.0] windows launcher: Make the launcher compile under mingw

- src/main/cpp/bazel_startup_options.cc
- src/main/cpp/bazel_startup_options.h
- src/main/cpp/blaze.cc
- src/main/cpp/blaze_util_bsd.cc
- src/main/cpp/blaze_util_darwin.cc
- src/main/cpp/blaze_util_linux.cc
- src/main/cpp/blaze_util_platform.h
- src/main/cpp/blaze_util_windows.cc
- src/main/cpp/main.cc
- src/main/cpp/startup_options.cc
- src/main/cpp/startup_options.h
- src/main/cpp/util/strings.cc
- src/main/cpp/util/strings.h
- src/main/cpp/workspace_layout.cc
- src/main/cpp/workspace_layout.h
- src/test/cpp/bazel_startup_options_test.cc
- src/test/cpp/blaze_archive_test.cc
- src/test/cpp/blaze_util_windows_test.cc
- src/test/cpp/option_processor_test.cc
- src/test/cpp/rc_file_test.cc
- src/test/cpp/startup_options_test.cc
- src/test/cpp/util/path_windows_test.cc
- src/test/shell/integration/bazel_command_log_test.sh
- src/test/shell/integration/client_test.sh
By refactoring the client code in the following manner:
* Make GetOutputRoot (now GetDefaultOutputRoot) a member of StartupOptions rather than WorkspaceLayout, as it doesn't have anything to do with a workspace.
* Remove output_root from StartupOptions as it's not an actual startup option, only an input into the computation of other option defaults.
* Move most of the late initialization in UpdateConfiguration() into a StartupOptions method.
* Move the tests for late initialization into the StartupOption subclasses, as they now depend on the GetDefaultOutputRoot implementation; also add missing test coverage.
PiperOrigin-RevId: 701980022
Change-Id: Ie1dfadc1555a237dd0c88318a2c143088baa43ce
> [8.1.0] Improve the encapsulation of StartupOptions.

- src/main/java/com/google/devtools/build/lib/rules/cpp/CompileCommandLine.java
This is required for toolchains where tools are generated files, e.g. wrappers around compilers.
Closes #25035.
PiperOrigin-RevId: 719209649
Change-Id: Iaa10a066bf271ffb485d25f38f8db87a020144c6
Commit https://github.com/bazelbuild/bazel/commit/c906e234966affd8f9c83a6ec982e96e38810fca
> [8.1.0] Path map tool paths in compilation actions

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkActionFactory.java
- src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRulesModule.java
- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkActionFactoryApi.java
- src/test/java/com/google/devtools/build/lib/packages/semantics/ConsistencyTest.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleContextTest.java
PiperOrigin-RevId: 715819891
Change-Id: I1c2e582a3d4c6e87e5c76837abb7a175eed3e850
Commit https://github.com/bazelbuild/bazel/commit/c570f978e5bd67d90318a12e353c6e5ba099da36
> [8.1.0] Deprecate the `experimental_action_resource_set` flag.

- src/main/cpp/blaze.cc
- src/main/cpp/startup_options.h
- src/main/java/com/google/devtools/build/lib/runtime/BlazeServerStartupOptions.java
The --lock_install_base startup flag must default to false, so that the client can obtain the desired behavior by either explicitly enabling or omitting it (explicitly disabling is problematic).
PiperOrigin-RevId: 704347325
Change-Id: I55b9b324c2c16035356673291c254e6629105d8e
> [8.1.0] Fix forward for breakage caused by https://github.com/bazelbuild/bazel/commit/3dcb585fb2f24c75d472df286ccd2891ff7f39b0.

- src/test/shell/bazel/client_test.sh
This requires fixing preexisting test cases that weren't actually passing.
PiperOrigin-RevId: 705082633
Change-Id: Ia00a30d0c8fc758148446029f635b2863d4a76e2
>  [8.1.0] Actually run the client integration tests.

- src/main/java/com/google/devtools/build/lib/packages/Attribute.java
- src/main/java/com/google/devtools/build/lib/rules/starlarkdocextract/ModuleInfoExtractor.java
- src/test/java/com/google/devtools/build/lib/rules/starlarkdocextract/ModuleInfoExtractorTest.java
Previously, we only supported attribute types which could be defined for Starlark rules, with the result that a cherry-pick in the 7.x branch exposing a formerly native-only attribute type to Starlark broke Stardoc: https://github.com/bazelbuild/stardoc/issues/277
Instead of picking and choosing, let's support all attribute types, same as we already do in Bazel 8 and newer.
Cherry-pick of a subset of changes in commit
https://github.com/bazelbuild/bazel/commit/1ce4ab15fab18063d8291132ea84e71fa02d27c4
PiperOrigin-RevId: 675169119
Change-Id: I6541a5eb99d6257339032850d360d2da4bd5aeb4
> [7.5.0] Backport support for all attribute types in Starlark documentation extraction

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepoRecordedInput.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryFunction.java
- src/test/py/bazel/bzlmod/bazel_vendor_test.py
Work towards #23243
Closes #24857.
PiperOrigin-RevId: 719146087
Change-Id: I03b1bfa4770fceca4c6eef1675094d39d7fee02e
(cherry picked from commit 1b4106310701c7db10e951eb13ddbe0f4d9da4f9)
Fixes #24862
> [8.1.0] Explain why vendored repositories are considered out-of-date

- src/test/java/com/google/devtools/build/lib/runtime/BlazeRuntimeTest.java
PiperOrigin-RevId: 705040576
Change-Id: I3c912c1d268c6600c873e2e89d3e09b7173e80fa
> [8.1.0] Factor out boilerplate in BlazeRuntimeTest.

- src/main/java/com/google/devtools/build/lib/worker/WorkerOptions.java
Before we completely deprecate the old worker pool, we should flip this to `true` and wait for a grace period.
PiperOrigin-RevId: 694418770
Change-Id: I5d6eb2159f3028aa17cf56fd9dfe85ecf63bc775
Commit https://github.com/bazelbuild/bazel/commit/b8e96e565ba1ff9b640ae2b152d6034af1db0bf2
> [8.1.0] Flip the default value of flag `--experimental_use_new_worker_pool` to true.

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegularRunnableExtension.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/StarlarkBazelModule.java
- src/main/java/com/google/devtools/build/lib/packages/LabelConverter.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/StarlarkBazelModuleTest.java
- src/test/py/bazel/bzlmod/bazel_lockfile_test.py
- src/test/tools/bzlmod/MODULE.bazel.lock
The mapping of an apparent name in a module extension tag's `attr.label` attribute to the corresponding canonical name has to be recorded in the lockfile so that instantiated repo rules don't reference the stale repos.
Fixes #25063
Closes #25067.
PiperOrigin-RevId: 720592796
Change-Id: Ia202ca4a8482a81da8085ee18ecaca5fe233bddb
> [7.5.0] Record repo mapping entries for labels in module extension tags

- src/main/java/com/google/devtools/build/lib/BUILD
- src/main/java/com/google/devtools/build/lib/runtime/BlazeRuntime.java
- src/main/java/com/google/devtools/build/lib/runtime/CommonCommandOptions.java
- src/main/java/com/google/devtools/build/lib/server/BUILD
- src/main/java/com/google/devtools/build/lib/server/InstallBaseGarbageCollector.java
- src/main/java/com/google/devtools/build/lib/server/InstallBaseGarbageCollectorIdleTask.java
- src/test/java/com/google/devtools/build/lib/runtime/BUILD
- src/test/java/com/google/devtools/build/lib/runtime/BlazeRuntimeTest.java
- src/test/shell/bazel/client_test.sh
The `--experimental_install_base_gc_max_age` flag determines the criteria for considering an install base stale; zero disables garbage collection. The default will be replaced with a suitable nonzero value in a future CL.
Progress on #2109.
PiperOrigin-RevId: 705874241
Change-Id: I3c8526a4a0e20a12d52c08cb282f24e268cbc633
> [8.1.0] Implement an idle task to garbage collect stale install bases.

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegularRunnableExtension.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/StarlarkBazelModule.java
- src/main/java/com/google/devtools/build/lib/packages/LabelConverter.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/StarlarkBazelModuleTest.java
- src/test/py/bazel/bzlmod/bazel_lockfile_test.py
- src/test/tools/bzlmod/MODULE.bazel.lock
The mapping of an apparent name in a module extension tag's `attr.label` attribute to the corresponding canonical name has to be recorded in the lockfile so that instantiated repo rules don't reference the stale repos.
Fixes #25063
Closes #25067.
PiperOrigin-RevId: 720592796
Change-Id: Ia202ca4a8482a81da8085ee18ecaca5fe233bddb
Commit https://github.com/bazelbuild/bazel/commit/59cb6fe990933eb764fd22ef3115c0d7f51baded
> [8.1.0] Record repo mapping entries for labels in module extension tags

- src/main/java/com/google/devtools/build/lib/actions/FileArtifactValue.java
- src/main/java/com/google/devtools/build/lib/actions/cache/CompactPersistentActionCache.java
- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
- src/main/java/com/google/devtools/build/lib/skyframe/FilesystemValueChecker.java
- src/test/java/com/google/devtools/build/lib/actions/ActionCacheCheckerTest.java
- src/test/java/com/google/devtools/build/lib/actions/CompletionContextTest.java
- src/test/java/com/google/devtools/build/lib/actions/cache/CompactPersistentActionCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/ActionInputPrefetcherTestBase.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTestBase.java
- src/test/java/com/google/devtools/build/lib/remote/ByteStreamBuildEventArtifactUploaderTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteActionFileSystemTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/ActionExecutionValueTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStoreTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/FileArtifactValueTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/FilesystemValueCheckerTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactBuildTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactValueTest.java
... if the corresponding output is materialized afterwards and hasn't been changed.
Failing to do so will cause an incremental build to re-check the action cache for actions whose outputs were materialized during last build. This can be very slow if the size of the outputs are large.
We achieved this by storing `FileContentsProxy` in the remote metadata after materialization. During dirtiness check, we compare remote metadata and the corresponding local metadata with their `digest`, or `proxy` if `digest` is not available for local metadata,
A user reported back the wall time of their very first increment build is improved by this change from `14s` to less than `1s` in common case, and from `115s` to less than `1s` in worst case. https://github.com/bazelbuild/bazel/issues/24763 …
> [8.1.0] Do not invalidate remote metadata during action dirtiness check

- src/main/java/com/google/devtools/build/lib/runtime/CommonCommandOptions.java
PiperOrigin-RevId: 720535693
Change-Id: I2467ab2d2426b44382904d50b58edc7602ee457e
> [8.1.0] Garbage collect install bases older than 30 days by default.

- src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
- src/test/java/com/google/devtools/build/lib/analysis/StarlarkExecGroupTest.java
- src/test/shell/bazel/remote/BUILD
- src/test/shell/bazel/remote/remote_execution_test.sh
This makes `exec_properties` such as `no-remote-exec` effective for the main test spawn, where they previously only affected post-processing spawns such as test XML generation.
Pros:
* relatively simple (and more precise than `tags`) way to affect test execution using existing API
* provides consistency between test spawns
* provides consistency between test spawns and spawns produced by Starlark actions
Cons:
* similar to Starlark actions, execution info is "polluted" with `exec_properties` such as `OSFamily` and `container-image`, which shows up in `aquery` and may increase memory usage
* the fact that `exec_properties` end up in execution info appears to have been an unintentional side effect of https://github.com/bazelbuild/bazel/commit/adb56ccd811b60db5dc05c5434cd7c436a6cb81b rather …
> [8.1.0]  Forward `exec_properties` to main test spawn's execution info

- src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java
- src/test/shell/integration/run_test.sh
Previously this only applied if you did `bazel run` without
`--script_path`.
Closes #25060.
PiperOrigin-RevId: 720874776
Change-Id: Ib118fe970cac94e87ace9ac870b2b70d7b65bbc0
Commit https://github.com/bazelbuild/bazel/commit/b3a04919a2112460afe7485e71bc343d3b7bdd1c
> [8.1.0] Include --run_env in --script_path

- src/main/java/com/google/devtools/build/lib/actions/ActionExecutionContext.java
- src/main/java/com/google/devtools/build/lib/exec/AbstractSpawnStrategy.java
- src/main/java/com/google/devtools/build/lib/includescanning/SpawnIncludeScanner.java
- src/main/java/com/google/devtools/build/lib/query2/aquery/ActionGraphTextOutputFormatterCallback.java
- src/main/java/com/google/devtools/build/lib/sandbox/SymlinkedSandboxedSpawn.java
- src/main/java/com/google/devtools/build/lib/util/CommandFailureUtils.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerKey.java
- src/test/java/com/google/devtools/build/lib/util/CommandFailureUtilsTest.java
This makes it easier to tell whether a given spawn ran remotely or sandboxed, which is especially important for test actions (which run multiple spawns).
Closes #24987.
PiperOrigin-RevId: 718862807
Change-Id: Ib88102c06d4641fed717b809eaee4e9485853452
Commit https://github.com/bazelbuild/bazel/commit/60fb7a4733d7d7582b77600396c3e50d686cf36f
> [8.1.0] Emit spawn runner with `--subcommands`

- src/main/java/net/starlark/java/eval/StarlarkThread.java
- src/main/java/net/starlark/java/syntax/Resolver.java
- src/test/java/net/starlark/java/eval/StarlarkThreadDebuggingTest.java
The Starlark interpreter, for optimization reasons, stores the bindings of comprehension variables in their enclosing function's locals array. This means we cannot naively transform the locals array into a name -> value map for debugger output: there may be multiple initialized variables having the same name.
And since we have been building this map using buildOrThrow(), attempting to debug a function with a comprehension variable having the same name as a parameter or other local variable would crash Bazel.
The immediate fix would be to track comprehension bindings' lexical scope (by saving a pointer to the comprehension AST node; note that a comprehension's scope has a non-trivial shape - it has a "hole" punched out for the first `for` clause), so we can ignore comprehension variables …
> [8.1.0] Respect comprehension variable shadowing in Starlark debugger output

- src/main/cpp/blaze.cc
Fixes #24827
Closes #25087.
PiperOrigin-RevId: 721285704
Change-Id: Id5c1a8b699f7c5bca1995dba7a8c871805b1a598
Commit https://github.com/bazelbuild/bazel/commit/f64f3605226e380d322f8cf503b014c05747f990
> [8.1.0] See and use more than 64 CPUs on Windows

- src/main/java/com/google/devtools/build/lib/actions/AbstractCommandLine.java
- src/main/java/com/google/devtools/build/lib/actions/BUILD
- src/main/java/com/google/devtools/build/lib/actions/PathMapper.java
- src/main/java/com/google/devtools/build/lib/actions/PathMapperConstants.java
- src/main/java/com/google/devtools/build/lib/analysis/actions/PathMappers.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcStarlarkInternal.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainFeatures.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainVariables.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkAction.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionBuilder.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/LinkBuildVariables.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/LinkCommandLine.java
- src/main/starlark/builtins_bzl/common/cc/link/cpp_link_action.bzl
- src/main/starlark/builtins_bzl/common/cc/link/link_build_variables.bzl
- src/test/java/com/google/devtools/build/lib/analysis/actions/PathMappersTest.java
- src/test/java/com/google/devtools/build/lib/rules/cpp/CcToolchainFeaturesTest.java
- src/test/java/com/google/devtools/build/lib/rules/cpp/LibraryToLinkValueTest.java
- src/test/java/com/google/devtools/build/lib/rules/cpp/LinkBuildVariablesTest.java
- src/test/java/com/google/devtools/build/lib/rules/cpp/LinkCommandLineTest.java
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/path_mapping_test.sh
This mostly requires wiring up the existing machinery for structured variables and (most) link build variables.
Utility methods on `PathMappers` are moved to `PathMapper` so that they can be dependend on by `AbstractCommandLine` without creating a cycle.
Work towards https://github.com/bazelbuild/bazel/discussions/22658#discussioncomment-11966720
Closes #25081.
PiperOrigin-RevId: 721499678
Change-Id: I4551f268093c7b851791a41deb57292b2c23afb7
Commit https://github.com/bazelbuild/bazel/commit/7f6e6496726aad4038368979c772e944bc323b7f
> [8.1.0] Add support for path mapping to `CppArchive`

- src/main/java/com/google/devtools/build/lib/analysis/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/FileProvider.java
- src/main/java/com/google/devtools/build/lib/analysis/FilesToRunProvider.java
- src/main/java/com/google/devtools/build/lib/analysis/Runfiles.java
Simplifies `print` style debugging.
Closes #24156.
PiperOrigin-RevId: 721850583
Change-Id: I8b3c3a1063f1dbfa3c0c1556e1112c1885a5c6a9
Commit https://github.com/bazelbuild/bazel/commit/fe7b4abe4d9f20a1c5d4807f7bb737fbbe7fb14d
> [8.1.0] Implement `debugPrint` for built-in file providers

- src/main/java/com/google/devtools/build/lib/worker/BUILD
- src/main/java/com/google/devtools/build/lib/worker/WorkerModule.java
This is a bug fix for the FileNotFoundException introduced by flipping the default value of `incompatible_use_new_cgroup_implementation`.
PiperOrigin-RevId: 718390659
Change-Id: Ibad1e7361c9d69b791df9cc058153e942c92f915
Commit https://github.com/bazelbuild/bazel/commit/a87ca4fc42d60b0cc8dd816176ed2b44b8476f53
> [8.1.0] Check the OS version before we initialize the cgroup factory.

- src/main/java/com/google/devtools/build/lib/analysis/platform/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/platform/ToolchainTypeInfo.java
- src/main/java/com/google/devtools/build/lib/rules/ToolchainType.java
- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunction.java
- src/test/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunctionTest.java
- src/test/shell/bazel/bazel_java_test_defaults.sh
- src/test/shell/integration/toolchain_test.sh
Fixes #12318
RELNOTES: The new `no_match_error` attribute on `toolchain_type` can be used to show a custom message when no matching toolchain is found for that type, but one is required.
Closes #25134.
PiperOrigin-RevId: 722733008
Change-Id: I2ff51f7524325be1b70314bb2db24c829602f5fc
Commit https://github.com/bazelbuild/bazel/commit/d514705c1de20b9b6af74d20008e5fc062a18073
> [8.1.0] Add `no_match_error` attribute to `toolchain_type`

- src/main/java/com/google/devtools/build/lib/analysis/platform/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/platform/ToolchainTypeInfo.java
- src/main/java/com/google/devtools/build/lib/rules/ToolchainType.java
- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunction.java
- src/test/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunctionTest.java
- src/test/shell/bazel/bazel_java_test_defaults.sh
- src/test/shell/integration/toolchain_test.sh
Fixes #12318
RELNOTES: The new `no_match_error` attribute on `toolchain_type` can be used to show a custom message when no matching toolchain is found for that type, but one is required.
Closes #25134.
PiperOrigin-RevId: 722733008
Change-Id: I2ff51f7524325be1b70314bb2db24c829602f5fc
Commit https://github.com/bazelbuild/bazel/commit/d514705c1de20b9b6af74d20008e5fc062a18073
> Add `no_match_error` attribute to `toolchain_type`

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/main/java/com/google/devtools/build/lib/packages/RuleClass.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleClassFunctionsTest.java
Using collection types that aren't guaranteed to preserve insertion order risks errors that differ across machines or builds.
Closes #25175.
PiperOrigin-RevId: 722768825
Change-Id: Id84c6b5b4bc9a1e6938de727e07c20ee761cbf3d
Commit https://github.com/bazelbuild/bazel/commit/2ee6f9232283408442f7a18ab566607e29d96e26
> [8.1.0] Preserve order of exec groups, toolchain types and exec constraints

- tools/test/extensions.bzl
- workspace_deps.bzl
Built at commit ee12906c
Relevant changes:
* Add support for input FN lines that include a function end line (#25118).
RELNOTES:
LCOV parsing does not break on FN lines including an end line number.
Closes #25200.
PiperOrigin-RevId: 723451534
Change-Id: I8912082ae6517bf0359329004d9a4f5e9ac76188
Commit https://github.com/bazelbuild/bazel/commit/df92905c72607ea369458e4a6af43bb785670528
> [8.1.0] Update to use coverage_output_generator-v2.8

- tools/build_defs/repo/BUILD
- tools/build_defs/repo/index.md.tmpl
- tools/build_defs/repo/preamb.md.tmpl
After https://github.com/bazelbuild/bazel/commit/20c02afe2a7192e8b25dac180451b6ea4fb8c7cf, I _think_ the repo rule docs (e.g. https://bazel.build/versions/7.4.0/rules/lib/repo/http) are the only ones missing the version selectors now. This CL should fix that for nightlies; will send another one to fix the released versions.
PiperOrigin-RevId: 721807046
Change-Id: Ib1e5287a0b2d22993a6014130235f32cf268952c
> [8.1.0] Add version selector buttons to repo rule docs

- src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java
- src/test/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloaderTest.java
Fixes https://bazelbuild.slack.com/archives/CA31HN1T3/p1738763759125489
Closes #25206.
PiperOrigin-RevId: 724267755
Change-Id: Ia23bdae310231bd0ee5763311b948f3465aa8ed0
Commit https://github.com/bazelbuild/bazel/commit/ef45e02bfb4af1124bb9ad1ef94f36c70c82ce48
> [8.1.0] Use digest function matching the checksum in gRPC remote downloader

- src/main/java/com/google/devtools/build/lib/rules/cpp/LtoBackendArtifacts.java
- src/test/java/com/google/devtools/build/lib/analysis/mock/cc_toolchain_config.bzl
- src/test/java/com/google/devtools/build/lib/rules/cpp/CcBinaryThinLtoTest.java
PiperOrigin-RevId: 700351238
Change-Id: If9e0686bee0756b0af56cda91ac70d184858fd72
Commit https://github.com/bazelbuild/bazel/commit/0937e3543ec3fe904361244377baff315adf2091
> [8.1.0] Add environment variables to LTO backend actions.

- src/main/java/com/google/devtools/build/lib/packages/BuiltinProvider.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkRuleImplementationFunctionsTest.java
Built-in providers always have an immutable `hashCode`. Making them hashable makes it easier to deduplicate a list of providers, which is sometimes required as the list of provider instances returned by a rule must not contain two instances for a given provider.
Starlark-defined providers are already hashable, so this brings the behavior of built-in providers in line with them.
Closes #24848.
PiperOrigin-RevId: 724370319
Change-Id: I68147b1f707249a8b09ad170c5fc5b3da4776ccf
Commit https://github.com/bazelbuild/bazel/commit/c94a9bdbaa389f4ed64d895237d443fcca57e8b4
> [8.1.0] Mark built-in providers as hashable

- src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
- src/test/java/com/google/devtools/build/lib/exec/StandaloneTestStrategyTest.java
Fixes #25165
I hope I did this right. I am able to see the output in my repro on rules_apple (which I can share if required by code review). Let me know if there's anything I've overlooked!
It would be great to get this into 8.1.0 if possible.
Closes #25203.
PiperOrigin-RevId: 725718124
Change-Id: I9c845ce1dc18307f5932da972f4ad31058a42f89
Commit https://github.com/bazelbuild/bazel/commit/d5d9385ebd4c4f1f1a8e9e1e058e7e8c3e22317b
> [8.2.0] Set exit_code unconditionally on TestResult in BEP

- src/main/java/com/google/devtools/build/lib/analysis/platform/PlatformInfo.java
- src/main/java/com/google/devtools/build/lib/rules/platform/Platform.java
- src/main/java/com/google/devtools/build/lib/rules/platform/PlatformRule.java
- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunction.java
- src/test/java/com/google/devtools/build/lib/analysis/platform/PlatformInfoTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/toolchains/PlatformLookupUtilTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunctionTest.java
- src/test/shell/integration/toolchain_test.sh
This allows platforms to provide custom error messages to users when no required toolchain can be found for a specific type (similar to the `toolchain_type.no_match_error` from b60a0f4b4072567e482419fac48c5da91f102648).
This should point to documentation or directions for users to properly use the platform.
When this is set it replaces the previous message "For more information on platforms or toolchains see https://bazel.build/concepts/platforms-intro."
RELNOTES: Add `missing_toolchain_error` to the `platform` rule, to customize error messages when a required toolchain type cannot be found for that platform.
Closes #25234.
PiperOrigin-RevId: 725775441
Change-Id: Ica00d215ad4ec8fb0edb714369e1d240d52c08f5
> [8.2.0] Add `missing_toolchain_error` to the `platform` rule.

- src/main/java/com/google/devtools/build/lib/analysis/ConfiguredRuleClassProvider.java
- src/main/java/com/google/devtools/build/lib/analysis/ExecGroupCollection.java
- src/main/java/com/google/devtools/build/lib/analysis/ToolchainCollection.java
- src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfigurationValue.java
- src/main/java/com/google/devtools/build/lib/analysis/config/OptionsDiff.java
- src/main/java/com/google/devtools/build/lib/analysis/platform/PlatformProperties.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Discovery.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpConnectorMultiplexer.java
- src/main/java/com/google/devtools/build/lib/cmdline/RepositoryMapping.java
- src/main/java/com/google/devtools/build/lib/exec/TestPolicy.java
- src/main/java/com/google/devtools/build/lib/metrics/PostGCMemoryUseRecorder.java
- src/main/java/com/google/devtools/build/lib/packages/BazelStarlarkEnvironment.java
- src/main/java/com/google/devtools/build/lib/packages/Package.java
- src/main/java/com/google/devtools/build/lib/runtime/StarlarkOptionsParser.java
- src/main/java/com/google/devtools/build/lib/skyframe/BUILD
- src/main/java/com/google/devtools/build/lib/skyframe/PackageFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/RepositoryMappingFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/RepositoryMappingValue.java
- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainTypeLookupUtil.java
Consumers of an `Immutable{List,Map,Set}` cannot know whether it has been created from a source with unspecified iteration order, such as `HashMap`. Since `ImmutableMap` itself prescribes that it preserves insertion order, it's reasonable for consumers to expect a specified, reasonable, deterministic order. While the current implementation of `HashMap` in the OpenJDK still results in a deterministic order, this kind of "sequenced-washing" doesn't cause non-determinism, but it still runs the risk of having the order of elements change between JDK versions or vendors.
The locations changed in this PR have been identified by instrumenting the factory methods of the `Immutable{List,Map,Set}` classes to track whether they 1) have been created from an unsequenced collection and 2) are iterated …
> [8.2.0] Preserve insertion order in maps that are traversed

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java
The default for the attribute is the empty string, not `null`.
Fixes #25286
Closes #25296.
PiperOrigin-RevId: 728298504
Change-Id: Ibc7209e248c3abb57a5fb2487e7dab7202960bbd
Commit https://github.com/bazelbuild/bazel/commit/fa7900a64c31427bddc1730a6b60178fa866fa6c
> [8.1.1] Fall back to `rctx.name` if `$original_name` is empty

- src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java
- src/test/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloaderTest.java
https://github.com/bazelbuild/bazel/pull/25206#issuecomment-2663193705
*** Original change description ***
Use digest function matching the checksum in gRPC remote downloader
Fixes https://bazelbuild.slack.com/archives/CA31HN1T3/p1738763759125489
Closes #25206.
PiperOrigin-RevId: 728572171
Change-Id: Ifc72c3d48d742ff236ec3424d3989c1738989069
Commit https://github.com/bazelbuild/bazel/commit/6f072751f1ac481b06eeb27aeca88ad58ff8a4e2
> [8.1.1] Rollback of Use digest function matching the checksum in gRPC remote downloader

- src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java
Closes #25298.
PiperOrigin-RevId: 728297901
Change-Id: Iad223ae19c8b8f589129223771420f9627500a9b
Commit https://github.com/bazelbuild/bazel/commit/ddde16b267eeb239d8b16272cc4b2ff7d94f27b9
> [8.2.0] Include output path in Remote Asset API client errors

- src/main/cpp/blaze.cc
`-XX:-IgnoreUnrecognizedVMOptions` is always evaluated at the beginning of argument parsing and thus can't be used to disable the feature before consuming `--host_jvm_args`.
Fixes #25312
Closes #25342.
PiperOrigin-RevId: 729186918
Change-Id: Iafe65a6ad8774dcb5605bdfe0adeb17547291b4c
Commit https://github.com/bazelbuild/bazel/commit/6d64e2e87e1c2bb069d6f622b0a2b51033252ef5
> [8.1.1] Restore compatibility with any JDK 23 on Windows

- src/main/cpp/blaze.cc
`-XX:-IgnoreUnrecognizedVMOptions` is always evaluated at the beginning of argument parsing and thus can't be used to disable the feature before consuming `--host_jvm_args`.
Fixes #25312
Closes #25342.
PiperOrigin-RevId: 729186918
Change-Id: Iafe65a6ad8774dcb5605bdfe0adeb17547291b4c
Commit https://github.com/bazelbuild/bazel/commit/6d64e2e87e1c2bb069d6f622b0a2b51033252ef5
> [8.2.0] Restore compatibility with any JDK 23 on Windows

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModTidyFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Discovery.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/InterimModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Selection.java
- src/main/java/com/google/devtools/build/lib/skyframe/BzlmodRepoRuleFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/StarlarkBuiltinsFunction.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodTestUtil.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/DiscoveryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
This PR implements the "nodep" edges from https://docs.google.com/document/d/1JsfbH9kdMe3dyOY-IR8SUakS541A7OM8pQcKpxTRMRs/edit?tab=t.0, using the syntax of `bazel_dep(..., repo_name=None)`. The behavior is that these edges are "unfulfilled" unless the module they refer to already exist in the dep graph by some other means.
Most of the changes are in the Discovery class -- I reorganized the code in there to hopefully help with readability, given the new multi-round discovery logic.
Also changed `ModuleFileValue.Key` to no longer take the applicable override next to the module key -- `ModuleFileFunction` now gets the root module from Skyframe itself and looks up the correct override. The old setup was always weird (what does it mean to request `foo@1.0` with an incorrect override??).
Beyond …
> [8.2.0] Bzlmod: nodep deps

- scripts/bootstrap/bootstrap.sh
The `apple_support` toolchain doesn't pass `-std=c++17` by default (like the `rules_cc` toolchain did), which broke boostrapping on macOS.
Closes #25407.
PiperOrigin-RevId: 731754906
Change-Id: Ida37babf9837a8e841b31d1d64e2e47376f37fe1
Commit https://github.com/bazelbuild/bazel/commit/1fb83714fd3c34d48c994fc837a331a582849f10
> [8.2.0] Fix bootstrap test by setting C++ standard to `c++17`

- MODULE.bazel
- MODULE.bazel.lock
- src/main/tools/daemonize.cc
The Xcode toolchain in `apple_support` used to be part of Bazel and was used to build Bazel itself back then. Since it has been moved to `apple_support`, Bazel has been building with the generic Unix toolchain, which isn't frequently used with Xcode and much less actively maintained than the one in `apple_support`. Switching back also gets rid of a number of warnings.
Also avoid compiling unused functions on macOS to get rid of the last C/C++ compilation warnings.
Closes https://github.com/bazelbuild/bazel/pull/25388.
PiperOrigin-RevId: 731395289
Change-Id: Ia75e50dbe38d039be840ae9bc3d74bba41598d34
Commit https://github.com/bazelbuild/bazel/commit/2683cf0def20cc6b2c071dbb235acd9d95927232
> [8.2.0] Use apple_support toolchain to build Bazel on macOS

- src/main/java/com/google/devtools/build/lib/remote/RemoteOutputChecker.java
- src/test/shell/bazel/remote/build_without_the_bytes_test.sh
This was an unintentional regression introduced by https://github.com/bazelbuild/bazel/commit/62b38cbb28a28cb037f27d02632827eeff85f7fb.
PiperOrigin-RevId: 732063949
Change-Id: I619f17077dd8409cbe75662d3a680847f39102ef
> [8.2.0] Also download test outputs for coverage commands when building without the bytes.

- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java
This one-line fix speeds up some real-life builds by 90%, saving over 20 minutes!
We only need to remove labels from the weak interner when a package is freshly computed (`directDeps != null`), not when it is already up-to-date as a top-level key in a skyframe evaluation. Without this guard, the removal code is being superfluously executed (in sequence) for each top-level target's package (without deduplication) twice during `BuildView#update`: once when computing the `labelToTargets` map, and again during `checkTargetEnvironmentRestrictions()`.
PiperOrigin-RevId: 733025147
Change-Id: Ief68c375a5d8444df1869968b4008af4a314b9c9
Commit https://github.com/bazelbuild/bazel/commit/3e115b937d7f6eff5c819667c6f6226c8fdba466
> [8.2.0] Fix a severe performance bug for builds with many top-level targets.

- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DelegatingDownloader.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/Downloader.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloader.java
- src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java
- src/main/java/com/google/devtools/build/lib/remote/util/TracingMetadataUtils.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
- src/test/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloaderTest.java
This makes it possible to correlate individual requests sent to the remote downloader with the repo rule or module extension they originated from.
Closes #25442.
PiperOrigin-RevId: 733425060
Change-Id: I713bbef1b450a27c95f7f263f84c0a198e37fcc2
Commit https://github.com/bazelbuild/bazel/commit/f6aaa32c9f3a250c4b51d2232c58c92b68c537fc
> [8.2.0] Attach context string to gRPC downloader requests

- src/main/native/unix_jni.cc
The earlier attempt in https://github.com/bazelbuild/bazel/commit/e9a18ce24b176f0d9a46af341ed44895c06b7214 was not the correct fix, due to the requirements spelled out in the utimensat(2) man page: if the current user has write permission but is not the owner of the file, it may set both atime and mtime to UTIME_NOW, but any other combination is forbidden. Although in theory we could still leave the atime alone in other cases, it's not worth the complexity: atime is often unreliable and Bazel doesn't care about it, anyway.
Unfortunately, it's difficult to write an integration test for this, because we can't arrange for the existence of multiple users in our CI environment.
Fixes https://github.com/bazelbuild/bazel/issues/23512.
PiperOrigin-RevId: 729042375
Change-Id: …
> [7.6.0] Actually fix setting the mtime on a shared disk cache.

- src/main/java/com/google/devtools/build/lib/analysis/BuildView.java
After parsing target patterns we build a `Map<Label, Target>` containing all top-level targets. The code was looking up packages of top-level targets by performing a `MemoizingEvaluator#evaluate` call for each, one at a time, in sequence. A skyframe evaluation is relatively heavyweight given that we can just look up the `PackageIdentifier` in the graph since we already evaluated it on the current build.
PiperOrigin-RevId: 733065574
Change-Id: Ib012c6fd60d8bf8e171b7ab07d4622ed73caaa43
Commit https://github.com/bazelbuild/bazel/commit/e12fdd93a3e22163d37209634ad5546f9fccd3b
> [8.2.0] Build the label to target map without performing skyframe evaluations.

- src/main/java/com/google/devtools/build/lib/actions/RemoteArtifactChecker.java
- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteOutputChecker.java
- src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTestBase.java
The TLL governs the lifetime of the remote metadata, but shouldn't by itself result in files being downloaded that otherwise wouldn't be (e.g., with `--remote_download_minimal`). This fixes a bug that causes warm Bazel servers with default settings apart from `--remote_download_minimal` to start downloading all top-level artifacts after three hours.
~This change also renames `shouldTrustArtifact` to `shouldTrustMetadata` and updates some comments on `{Remote,}OutputChecker` to avoid confusion between its two distinct purposes in the future: validating metadata and deciding which artifacts to download.~ This part isn't cherry-picked.
Example of the effect: https://github.com/buildbuddy-io/buildbuddy/pull/8502#issuecomment-2687734121
Closes #25398.
PiperOrigin-RevId: 733280515
Change-Id: …
> [7.6.0] Don't download all artifacts with BwoB when their TTL expires

- src/main/java/com/google/devtools/build/lib/remote/disk/DiskCacheClient.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTest.java
- src/test/java/com/google/devtools/build/lib/remote/DiskCacheIntegrationTest.java
- src/test/java/com/google/devtools/build/lib/remote/util/BUILD
- src/test/java/com/google/devtools/build/lib/remote/util/IntegrationTestUtils.java
This makes it easier to use in tests and also avoids restarting the worker for each test by only deleting its state.
Before:
```
//src/test/java/com/google/devtools/build/lib/remote:BuildWithoutTheBytesIntegrationTest PASSED in 33.4s
Stats over 5 runs: max = 33.4s, min = 28.8s, avg = 31.8s, dev = 1.7s
```
After:
```
//src/test/java/com/google/devtools/build/lib/remote:BuildWithoutTheBytesIntegrationTest PASSED in 11.5s
Stats over 5 runs: max = 11.5s, min = 9.0s, avg = 10.0s, dev = 0.8s
```
Requires fixing an `InputStream` leak in `DiskCacheClient`.
Suggested in https://github.com/bazelbuild/bazel/pull/25412#discussion_r1974688360
Closes #25432.
PiperOrigin-RevId: 734107531
Change-Id: Icf8f593f8c368c5d9daa36002a6fb1aa9b789dca
Commit …
> [8.2.0] Make `WorkerInstance` a `@ClassRule @Rule`

- src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java
- src/main/java/com/google/devtools/build/lib/runtime/BlazeWorkspace.java
- src/main/java/com/google/devtools/build/lib/runtime/CommandEnvironment.java
- src/test/java/com/google/devtools/build/lib/buildtool/util/BlazeRuntimeWrapper.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteModuleTest.java
- src/test/java/com/google/devtools/build/lib/runtime/BlazeRuntimeTest.java
- src/test/shell/bazel/remote/build_without_the_bytes_test.sh
Retries use new invocation IDs, but are linked together by using the same build request ID.
Closes #25303.
PiperOrigin-RevId: 728645945
Change-Id: Ie482a79c4ddbe23133a1cae50843fc2116f2ed0d 
(cherry picked from commit d3e663dbd6a1ee77df4e1220dff2a23df163c9c1)
Fixes #25304
> [8.2.0] Add support for cache eviction retries with fixed invocation ID

- src/main/java/com/google/devtools/build/lib/actions/RemoteArtifactChecker.java
- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteOutputChecker.java
- src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTestBase.java
The TLL governs the lifetime of the remote metadata, but shouldn't by itself result in files being downloaded that otherwise wouldn't be (e.g., with `--remote_download_minimal`). This fixes a bug that causes warm Bazel servers with default settings apart from `--remote_download_minimal` to start downloading all top-level artifacts after three hours.
~This change also renames `shouldTrustArtifact` to `shouldTrustMetadata` and updates some comments on `{Remote,}OutputChecker` to avoid confusion between its two distinct purposes in the future: validating metadata and deciding which artifacts to download.~ This part isn't cherry-picked.
Example of the effect:
https://github.com/buildbuddy-io/buildbuddy/pull/8502#issuecomment-2687734121
Closes #25398.
PiperOrigin-RevId: 733280515
Change-Id: …
> [8.2.0] Don't download all artifacts with BwoB when their TTL expires

- src/test/shell/integration/unicode_test.sh
C.UTF-8 is not available: https://storage.googleapis.com/bazel-testing-buildkite-artifacts/01956bf0-7263-4136-89f2-4e2d785b8762/src/test/shell/integration/unicode_test/test_attempts/attempt_1.log
With this CL we'll set LC_ALL as we already do in other tests (e.g. unicode_filenames_test.sh).
PiperOrigin-RevId: 734232499
Change-Id: I2a2c6ddbbfb4e9e7ac4c53dc80a9b0d28e007ab9
Commit https://github.com/bazelbuild/bazel/commit/8dbfcfae924b014366a0b47cd26632c5076b51a2
> [7.6.0] Fix unicode_test on macos sequoia

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModTidyFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleInspectorFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Discovery.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/InterimModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileValue.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Selection.java
- src/main/java/com/google/devtools/build/lib/skyframe/BzlmodRepoRuleFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/StarlarkBuiltinsFunction.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodTestUtil.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/DiscoveryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/SelectionTest.java
This PR implements the "nodep" edges from https://docs.google.com/document/d/1JsfbH9kdMe3dyOY-IR8SUakS541A7OM8pQcKpxTRMRs/edit?tab=t.0, using the syntax of `bazel_dep(..., repo_name=None)`. The behavior is that these edges are "unfulfilled" unless the module they refer to already exist in the dep graph by some other means.
Most of the changes are in the Discovery class -- I reorganized the code in there to hopefully help with readability, given the new multi-round discovery logic.
Also changed `ModuleFileValue.Key` to no longer take the applicable override next to the module key -- `ModuleFileFunction` now gets the root module from Skyframe itself and looks up the correct override. The old setup was always weird (what does it mean to request `foo@1.0` with an incorrect override??).
Work …
> [7.6.0] Bzlmod: nodep deps

- src/main/java/com/google/devtools/build/lib/worker/WorkerFactory.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerMultiplexer.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerMultiplexerManager.java
- src/test/java/com/google/devtools/build/lib/worker/SandboxedWorkerProxyTest.java
Prior to this change, multiplex sandboxed workers shared a working directory per mnemonic. This caused a race condition when a new multiplex sandboxed worker with the same mnemonic was launched because when launching it cleaned the working directory. That could cause problems for any actions executing in that directory.
This change makes it so each multiplex sandbox worker process has a unique working directory. It does so while ensuring each SandboxedWorkerProxy and the associated sandbox are still associated with the correct multiplexer process and working directory.
Resolves #22589
I couldn't figure out if the Bazel repo has an autoformatter somewhere, so I did my best to manually format the code with a style that follows the existing code.
Closes #25400.
PiperOrigin-RevId: 732256101 …
> [7.6.0] Fix race condition with multiplex sandboxed workers

- src/main/java/com/google/devtools/build/lib/rules/config/ConfigGlobalLibrary.java
- src/test/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleTransitionProviderTest.java
PiperOrigin-RevId: 735948913
Change-Id: I89c0728f8ede368a77225551c81a16d3fdc5f199
Commit https://github.com/bazelbuild/bazel/commit/7027f001b863ec7b179b0092f928ea6c7b5a4b10
> [8.2.0] Permit analysis tests to transition on --experimental_* or --incompatible_* options

- src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl
- src/test/py/bazel/bzlmod/bazel_repo_mapping_test.py
Bazel 7 emits the `BAZEL_CURRENT_REPOSITORY` preprocessor macro only
when depending on the copy of the cc runfiles library in `@bazel_tools`,
breaking users who want to write forwards-compatible code which pulls that
library from `@rules_cc`.  In commit 6f7faa659, a backport of 8a5e70c78,
Bazel 8.1 replaced its own implementation with a passthrough and updated
the check that macro uses to permit both locations.
This patch gives rules_cc users forwards-compatibility by backporting
the portion of that commit which emits the `BAZEL_CURRENT_REPOSITORY`
variable when using the runfiles library from rules_cc, but stops short
of actually removing the built-in runfiles library.
> [7.6.0] Emit BAZEL_CURRENT_REPOSITORY when using @rules_cc//cc/runfiles

- src/main/java/com/google/devtools/build/lib/remote/util/BUILD
- src/main/java/com/google/devtools/build/lib/remote/util/DigestUtil.java
Closes #25390.
PiperOrigin-RevId: 732260576
Change-Id: I51bfa5ecb0916e90608b6323cbd657859b0393c4
Commit https://github.com/bazelbuild/bazel/commit/13092462982d3d1fa6d7336962a75f78b52a8604
> [8.2.0] Remove an unnecessary large dep from `DigestUtil`

- src/main/java/com/google/devtools/build/lib/rules/java/JavaStarlarkCommon.java
- src/test/shell/bazel/bazel_java_test.sh
Fixes https://github.com/bazelbuild/bazel/issues/25012
Closes #25043.
PiperOrigin-RevId: 719211390
Change-Id: I91267b3ce546a54cd065e4424f3e80aaa36cff28
Commit https://github.com/bazelbuild/bazel/commit/8fba20855f7979ecc61cb05bf9e3ec8890aeed90
> [7.6.0] Use runfiles path instead of root relative path in `JavaStarlarkCommon.collectNativeLibsDirs`

- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/net/starlark/java/eval/Starlark.java
- src/main/java/net/starlark/java/eval/StarlarkSemantics.java
- src/main/java/net/starlark/java/eval/StringModule.java
- src/main/java/net/starlark/java/lib/json/Json.java
- src/test/java/com/google/devtools/build/lib/packages/semantics/ConsistencyTest.java
- src/test/java/net/starlark/java/eval/BUILD
- src/test/java/net/starlark/java/eval/ScriptTest.java
- src/test/java/net/starlark/java/eval/testdata/json.star
- src/test/java/net/starlark/java/eval/testdata/sorted.star
- src/test/java/net/starlark/java/eval/testdata/string_misc.star
Bazel internally uses `String` as a container for raw bytes assumed to be UTF-8, which differs from ordinary usage of `String` as a container for UTF-16 characters. This requires special implementations of certain Starlark functions that care about the notion of a "character":
* `{l,r,}strip` must not strip non-ASCII whitespace as it may be part of a UTF-8-encoded non-whitespace character.
* `json.decode` has to emit UTF-8 bytes rather than UTF-16 characters.
To avoid affecting other users of the Starlark interpreter, a new `StarlarkSemantics.INTERNAL_BAZEL_ONLY_UTF_8_BYTE_STRINGS` setting, defaulting to false but overridden to true for Bazel, determines which of the two behaviors to adopt.
Compatibility is verified by running all script-based tests under both values of the setting. …
> [8.2.0] Fix Unicode encoding issues in Bazel's use of Starlark

- src/main/java/com/google/devtools/build/lib/metrics/MetricsCollector.java
This would previously show confusing metrics such as
```
{
"mnemonic": "FileWrite",
"firstStartedMs": "10965232776311",
"lastEndedMs": "1741860739457",
"actionsCreated": "10"
},
```
PiperOrigin-RevId: 737613747
Change-Id: I544f220766c4170318c7f1438584c5613fdc8fa0
Commit https://github.com/bazelbuild/bazel/commit/bcfd3e7be9e0414ecb11f0d0d9d9a55d3d276fd6
> [8.2.0] build metrics: Do not set start/end of mnemonics that were only created but not executed.

- src/main/java/com/google/devtools/build/lib/remote/merkletree/DirectoryTree.java
- src/main/java/com/google/devtools/build/lib/remote/merkletree/DirectoryTreeBuilder.java
- src/main/java/com/google/devtools/build/lib/remote/merkletree/MerkleTree.java
- src/test/java/com/google/devtools/build/lib/remote/merkletree/ActionInputDirectoryTreeTest.java
- src/test/java/com/google/devtools/build/lib/remote/merkletree/DirectoryTreeTest.java
The instance size is reduced from 32 to 24 bytes, which matters for builds with high `--jobs` count, where `MerkleTree`s take up a significant chunk of memory.
Closes #25576.
PiperOrigin-RevId: 737731300
Change-Id: I47014614f974a5651f9eb1ebabe9ac8067b581b7
Commit https://github.com/bazelbuild/bazel/commit/1c6c3bd0a33a7ab6cf37c09cd6658c976ff039cd
> [8.2.0] Reduce memory footprint of `DirectoryTree.FileNode`

- src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java
This should have been a part of https://github.com/bazelbuild/bazel/pull/23525, but was inexplicably missing when it was cherry-picked from 8c5e9da.
> [7.6.0] Actually use 0777 when creating directories.

- src/main/java/net/starlark/java/lib/json/Json.java
Encoders are stateful, and `json.decode` may be called concurrently by multiple threads. This will (if we're lucky) manifest as an `IllegalStateException` thrown by `CharsetEncoder.encode()`.
We could consider keeping a single instance around for reuse (i.e. a one-element object pool), but I'll refrain from doing so until we have evidence that it's worth optimizing.
PiperOrigin-RevId: 737594384
Change-Id: I8d8c87a9919661ef49490293f54d513ee1fe6b69
> [8.2.0] Prevent concurrent use of the same `CharsetEncoder` in `json.decode`

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Version.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/VersionTest.java
Numeric segments can now be unsigned longs rather than just signed integers. Segments that exceed this (large) range now result in an error rather than a crash.
Work towards #23461
Closes #24945.
PiperOrigin-RevId: 718451995
Change-Id: I141b707e8c28d5fe764b47b4c35f163a3621e4c5
> [7.6.0] Handle large numeric segments in Bazel module versions

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/Version.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/VersionTest.java
Numeric segments can now be unsigned longs rather than just signed integers. Segments that exceed this (large) range now result in an error rather than a crash.
Work towards #23461
Closes #24945.
PiperOrigin-RevId: 718451995
Change-Id: I141b707e8c28d5fe764b47b4c35f163a3621e4c5
Commit https://github.com/bazelbuild/bazel/commit/a8a2c0c1fa063a0bba4e7222a1b1d2c8a4e0e632
> [8.2.0] Handle large numeric segments in Bazel module versions

- src/main/java/com/google/devtools/build/lib/runtime/BlazeRuntime.java
Closes #25327.
PiperOrigin-RevId: 736919575
Change-Id: I008207f53b9464f69fff3be81862f5d3f3a0f15d
Commit https://github.com/bazelbuild/bazel/commit/03df6839898acf92a32157e53d504c3d4c5bc1b6
> [8.2.0] Fix encoding of Starlark source lines in error messages

- src/main/java/com/google/devtools/build/lib/runtime/UiStateTracker.java
Don't retain ExecutionProgressReceiver after a build
Also delete a set that is always empty.
Closes https://github.com/bazelbuild/bazel/pull/25582.
PiperOrigin-RevId: 737927900
Change-Id: I0afa21d8fd3960ee4387254dfbe2ebe3c972056c
Commit https://github.com/bazelbuild/bazel/commit/1b7366a3f0912b0b4d5c99329d803616dfca2212
> [8.2.0] Don't retain ExecutionProgressReceiver after a build

- src/main/starlark/builtins_bzl/bazel/java/bazel_java_binary.bzl
Backports https://github.com/bazelbuild/rules_java/commit/b3a0580e0a9a6b8b28b611c7dd6164c06b279539
Fixes https://github.com/bazelbuild/bazel/issues/25648
> [7.6.0] Don't attempt to enable the Security Manager for jdk >= 24

- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
Bazel itself uses this: https://github.com/bazelbuild/bazel/blob/master/bazel_downloader.cfg
And many companies rely on this for security.
Therefore, `--downloader_config` should be non-experimental.
Resolves #25485
RELNOTES: `--experimental_downloader_config` is now no longer experimental, and has been renamed to `--downloader_config`. The old flag name can still be used.
Closes #25649.
PiperOrigin-RevId: 739116828
Change-Id: Icaa0bceb84d088c610f41938b194f209bdbe7f70
Commit https://github.com/bazelbuild/bazel/commit/a3b53de16985aedf6f6d4b9e95eb7507a4eeb500
> [8.2.0] feat(RepositoryOptions): make downloader config non-experimental

- src/main/java/com/google/devtools/build/lib/worker/WorkerFactory.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerMultiplexer.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerMultiplexerManager.java
- src/test/java/com/google/devtools/build/lib/worker/SandboxedWorkerProxyTest.java
Prior to this change, multiplex sandboxed workers shared a working directory per mnemonic. This caused a race condition when a new multiplex sandboxed worker with the same mnemonic was launched because when launching it cleaned the working directory. That could cause problems for any actions executing in that directory.
This change makes it so each multiplex sandbox worker process has a unique working directory. It does so while ensuring each SandboxedWorkerProxy and the associated sandbox are still associated with the correct multiplexer process and working directory.
Resolves #22589
I couldn't figure out if the Bazel repo has an autoformatter somewhere, so I did my best to manually format the code with a style that follows the existing code.
Closes #25400.
PiperOrigin-RevId: 732256101 …
> [8.2.0] Fix race condition with multiplex sandboxed workers

- scripts/bash_completion_test.sh
- src/main/java/com/google/devtools/build/lib/BUILD
- src/main/java/com/google/devtools/build/lib/buildtool/AqueryProcessor.java
- src/main/java/com/google/devtools/build/lib/buildtool/CqueryProcessor.java
- src/main/java/com/google/devtools/build/lib/buildtool/PostAnalysisQueryProcessor.java
- src/main/java/com/google/devtools/build/lib/query2/common/CommonQueryOptions.java
- src/main/java/com/google/devtools/build/lib/runtime/QueryRuntimeHelper.java
- src/main/java/com/google/devtools/build/lib/runtime/commands/QueryEnvironmentBasedCommand.java
- src/test/shell/integration/bazel_query_test.sh
This is a proposed fix for https://github.com/bazelbuild/bazel/issues/24293
This speeds up a fully warm `bazel query ...` by 23.7%, reducing wall time from 1m49s to 1m23s
```
$ time bazel query '...' --output=streamed_proto > queryoutput4.streamedproto
real    1m48.768s
user    0m27.410s
sys     0m19.646s
$ time bazel query '...' --output=streamed_proto --output_file=queryoutput5.streamedproto
real    1m22.920s
user    0m0.045s
sys     0m0.016s
```
_💁‍♂️ Note: when combined with https://github.com/bazelbuild/bazel/pull/24305, total wall time is 37s, an overall reduction of 66%._
Closes #24298.
PiperOrigin-RevId: 700583890
Change-Id: Ic13f0611aca60c2ce8641e72a0fcfc330f13c803
Commit https://github.com/bazelbuild/bazel/commit/791e1f71876daf57b0ac8757eda037148f1470ea
> [8.2.0] Add `bazel query --output_file` option, which writes query results directly to a file

- src/main/java/com/google/devtools/build/lib/runtime/commands/BUILD
- src/main/java/com/google/devtools/build/lib/runtime/commands/InfoCommand.java
Closes #25662.
PiperOrigin-RevId: 739859052
Change-Id: I794ca50a74ed6b7ebba90ee13ae0a524a1b93b3d
Commit https://github.com/bazelbuild/bazel/commit/97cdefbb991bc9500e100a9d8c023c03c19d4cc3
> [8.2.0] Add spelling suggestions to `bazel info` error message

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteExecutionServiceTest.java
Valid empty `Tree` messages, which correspond to empty output directories, serialize to two bytes since they always contain an empty but present `Tree` message in the `root` field. Since such directories are very common (for example, as undeclared test output directories), it pays off to avoid downloading them.
Closes #25374.
PiperOrigin-RevId: 731614115
Change-Id: I64902afbecb55f718eb4d04fdd1f6207a7e8b97a 
(cherry picked from commit 6795c28a7be0b79c47ef94c42f6d128d2615f39a)
Closes #25376
> [8.2.0] Avoid downloading the empty `Tree` message

- src/main/java/net/starlark/java/syntax/Parser.java
This brings code closer to readability standards. The benchmarks show there's no regression or improvement. There's a bit more edenSpaceGarbage, however so small, that I believe readability should be more important.
PiperOrigin-RevId: 739291019
Change-Id: Id037395e812556771789f8ea4b810bff6b933f05
Commit
https://github.com/bazelbuild/bazel/commit/9250141e98e34ebe599145927068550481058fdd
> [8.2.0] Use ImmutableList.Builders in Parser

- src/main/java/com/google/devtools/build/lib/remote/util/AsyncTaskCache.java
- src/test/java/com/google/devtools/build/lib/remote/util/AsyncTaskCacheTest.java
`RemoteActionInputPrefetcher` is retained through `RemoteActionFileSystem` and in turn retains all finished `AsyncTaskCache` tasks, which are only relevant intra-build and can thus be dropped after shutdown. This saves ~1% of retained heap on the Bazel frontend example.
Closes #25579.
PiperOrigin-RevId: 738084614
Change-Id: Ia6f5e9a20f026a861f649090e6f72f8b2152443f
Commit https://github.com/bazelbuild/bazel/commit/0ce2f955e3f2516737202a3377ca65838eb3b7c7
> [8.2.0] Clear `AsyncTaskCache`s after shutdown

- site/en/concepts/visibility.md
- site/en/extending/macros.md
- src/main/java/com/google/devtools/build/lib/analysis/CommonPrerequisiteValidator.java
- src/test/java/com/google/devtools/build/lib/analysis/MacroVisibilityTest.java
Previously, finalizers used the same visibility semantics as normal symbolic macros. As a result, migrating an epilogue legacy macro to a finalizer could result in visibility errors if, for example, a finalizer-defined target declared a dependency on a legacy-macro-defined target which was visible to the BUILD file but not to the finalizer's definition.
PiperOrigin-RevId: 739300166
Change-Id: I480dde3d2a9704ef85a64ba8346038e784172ee6
Commit
https://github.com/bazelbuild/bazel/commit/4c2d91e762ab6e492853b021408129dd93fb5904
> [8.2.0] Allow finalizer targets to see targets visible either to BUILD file or to finalizer macro class definition

- src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteOutputService.java
- src/test/shell/bazel/remote/build_without_the_bytes_test.sh
Cache evictions encountered during reads of remote files in `RemoteActionFileSystem` now result in the build being retried when `--experimental_remote_cache_eviction_retries` is set to a positive value (the default).
This is enabled by implementing the `checkForLostInputs` method on the `RemoteOutputService`,  building on the refactoring performed in https://github.com/bazelbuild/bazel/pull/25396.
Closes #25358.
PiperOrigin-RevId: 736064349
Change-Id: Idc70d55138c3366d22ece7f0579b242b3c217da8
Commit https://github.com/bazelbuild/bazel/commit/85d9cc9cc6e1bc46116fb6163d43cad9aa17ffc7
> [8.2.0] Retry build when `RemoteActionFileSystem` encounters a missing digest

- src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileAction.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaConfiguration.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileAction.java
- src/test/shell/bazel/bazel_java_test.sh
This change introduces a new option, `--experimental_java_classpath=bazel_no_fallback`, which operates similarly to `--experimental_java_classpath=bazel` but does not fall back to the full transitive classpath. Instead, the build fails if javac cannot compile with the reduced classpath.
Fixes https://github.com/bazelbuild/bazel/issues/24875
Closes #24876.
PiperOrigin-RevId: 739864240
Change-Id: I53b25c35ac57e4a4ef3baa49eadc1952dac6457d
Commit https://github.com/bazelbuild/bazel/commit/f25433a3c86b267799333325acb114105495086e
> [8.2.0] Add `--experimental_java_classpath=bazel_no_fallback` option

- src/main/java/net/starlark/java/syntax/ListExpression.java
Closes #25600.
PiperOrigin-RevId: 740273301
Change-Id: I70252d84f24a414ea328b4100c886b3f0b188048
Commit https://github.com/bazelbuild/bazel/commit/65676a1b29ed11cc8b5e3a864c9595b2eed8e729
> [8.2.0] Use ImmutableList in `ListExpression`

- src/main/java/com/google/devtools/build/lib/analysis/platform/DeclaredToolchainInfo.java
- src/main/java/com/google/devtools/build/lib/rules/platform/Toolchain.java
- src/main/java/com/google/devtools/build/lib/rules/platform/ToolchainRule.java
- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/SingleToolchainResolutionFunction.java
This causes the toolchain to always match the current target platform, whatever it is. Needed to support test toolchains.
Work towards #25160
Part of #25123.
RELNOTES: Add `use_target_platform_constraints` attribute to the `toolchain` rule, although it is not used, to enable writing custom test toolchains that are valid in 8.2.0 and later releases.
PiperOrigin-RevId: 732123054
Change-Id: I1b65e8881048187fe825bb26812ac6bdfa2b4c16
> [8.2.0] Add `use_target_platform_constraints` attribute to the `toolchain` rule.

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
The in-flight executions need to be cleaned up also in case of a cache hit or an exception while interacting with the cache, otherwise `inFlightExecutions` grows over time retaining large `Spawn`s.
Closes #25668.
PiperOrigin-RevId: 740058969
Change-Id: I42045219510df0347e38234d6d3bd1ebb6167d9b
Commit https://github.com/bazelbuild/bazel/commit/0f957c185f671cf9d088cf551818f0442a80c6f9
> [8.2.0] Don't leak in-flight execution in `RemoteSpawnCache`

- src/main/java/com/google/devtools/build/lib/worker/SandboxedWorkerProxy.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerFactory.java
- src/main/java/com/google/devtools/build/lib/worker/WorkerMultiplexer.java
- src/test/java/com/google/devtools/build/lib/worker/WorkerMultiplexerTest.java
Manual cherry-pick for bceaf635e945bdd89bbdbb0f8a9f5453ed0686f5.
Fixes #25655
> [8.2.0] Stop deleting the whole worker directory when we destroy a worker proxy.

- src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java
- src/main/java/com/google/devtools/build/lib/profiler/ProfilerTask.java
These ended up spamming the timing profile with very short nested spans.
Closes #25634.
PiperOrigin-RevId: 740188492
Change-Id: I3afc3a7ea6dc43ac999e3ca3d14d036c7b1570f0
Commit https://github.com/bazelbuild/bazel/commit/b5dc94f3b76f5d0436dc76b293c50dadd2ecb2a7
> [8.2.0] Don't add very short compact spawn log spans to profile

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
The in-flight executions need to be cleaned up also in case of a cache hit or an exception while interacting with the cache, otherwise `inFlightExecutions` grows over time retaining large `Spawn`s.
Closes #25668.
PiperOrigin-RevId: 740058969
Change-Id: I42045219510df0347e38234d6d3bd1ebb6167d9b 
(cherry picked from commit 0f957c185f671cf9d088cf551818f0442a80c6f9)
> [7.6.1] Don't leak in-flight execution in `RemoteSpawnCache`

- src/main/java/com/google/devtools/build/lib/analysis/configuredtargets/AbstractConfiguredTarget.java
All targets observed from Starlark advertise the `DefaultInfo` provider, but internally that provider is split into `FilesProvider`, `FilesToRunProvider` and `RunfilesProvider`. This is confusing to users that use `cquery` to inspect targets using Starlark expressions. This is improved by synthesizing a `DefaultInfo` provider in the same way as during regular analysis. As a result, the `default_runfiles` and `data_runfiles` of a target can now be inspected with `cquery`.
Closes #25702.
PiperOrigin-RevId: 741291403
Change-Id: Ieeb92afb47cd3215fe8dde15c305831806c7bf87
Commit https://github.com/bazelbuild/bazel/commit/c3661a2471e79cfc189d9dc6bd383084d4e13e6e
> [8.2.0] Include `DefaultInfo` in `cquery` `providers` dict

- src/test/shell/bazel/starlark_git_repository_test.sh
- tools/build_defs/repo/git.bzl
- tools/build_defs/repo/git_worker.bzl
Add a sparse_checkout_patterns and sparse_checkout_file arguments to the git_repository rule. If non-empty, this will cause the rule to perform a sparse checkout of the repository, only checking out files that match the .gitignore-style patterns in this list.
Fixes issue https://github.com/bazelbuild/bazel/issues/24069.
Cherry-pick of https://github.com/bazelbuild/bazel/commit/4006e059737d214fc4116083d9c4e58d5a2e40c0
> [8.2.0] Enable sparse checkout in git_repository rule

- src/main/java/com/google/devtools/build/lib/packages/BuiltinRestriction.java
This will permit writing tests in `@rules_java//test` that assert on private API access failures.
PiperOrigin-RevId: 743908855
Change-Id: I520cf57d7719d70866df6bbd99a45142e36839c0 (cherry picked from commit 176b9b4df99299efb1e1e10f0c919ae58be025ba)
> [8.2.0] Restrict private API allowlisting to `@rules_java//java`

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/main/java/com/google/devtools/build/lib/packages/CallStack.java
- src/main/java/com/google/devtools/build/lib/packages/MacroClass.java
- src/main/java/com/google/devtools/build/lib/packages/MacroInstance.java
- src/main/java/com/google/devtools/build/lib/packages/Rule.java
- src/main/java/com/google/devtools/build/lib/packages/RuleFactory.java
- src/main/java/com/google/devtools/build/lib/packages/TargetDefinitionContext.java
- src/test/java/com/google/devtools/build/lib/analysis/BUILD
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
- src/test/java/com/google/devtools/build/lib/packages/CallStackTest.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkIntegrationTest.java
Before, we did not set generator_* pseudo-attributes for rules generated in a symbolic macro. However, it turns out that there are existing tools which expect to be able to filter rule targets by generator_name in query expressions; and such tools get broken when legacy macros are migrated to symbolic. The easiest solution is to set generator_name and friends consistently for both legacy and symbolic macro rule targets.
In the long term, we wish to deprecate and remove generator_* pseudo-attrs, since the API has numerous problems and doesn't expose the information users really need:
But for now, however, we ought to support the broken API symmetrically for all varieties of macro.
In addition, take the opportunity to concatenate the Starlark stacks of BUILD and symbolic macro threads for …
> [8.2.0] Set generator_name, generator_function, generator_location, full Starlark stack for rules in symbolic macros

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
Fixes #25232.
Closes #25786.
PiperOrigin-RevId: 745164203
Change-Id: I58cc9f83b6c6cc8cb2c728cfe132e220a7678cea
Commit https://github.com/bazelbuild/bazel/commit/06455bbcf932355d287960acd7fbac5493daf2b8
> [8.2.0] Fix a deadlock when using `--remote_cache_async` and HTTP cache.

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkSubrule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileGlobals.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/packages/StarlarkDefinedAspect.java
- src/main/java/com/google/devtools/build/lib/packages/StarlarkExportable.java
- src/main/java/com/google/devtools/build/lib/packages/StarlarkProvider.java
- src/main/java/com/google/devtools/build/lib/packages/TargetDefinitionContext.java
- src/main/java/com/google/devtools/build/lib/rules/BUILD
- src/main/java/com/google/devtools/build/lib/rules/test/StarlarkTestingModule.java
- src/main/java/com/google/devtools/build/lib/skyframe/BzlLoadFunction.java
- src/main/java/net/starlark/java/eval/Eval.java
- src/main/java/net/starlark/java/eval/StarlarkThread.java
- src/test/java/com/google/devtools/build/lib/analysis/SymbolicMacroTest.java
- src/test/java/com/google/devtools/build/lib/packages/RequiredProvidersTest.java
- src/test/java/net/starlark/java/eval/EvaluationTestCase.java
This ensures Starlark instantiation stack for rule targets defined in a symbolic macro shows both the macro's location and symbol.
Requires changing StarlarkThread to track the location of where symbols are exported.
As follow-up, we should do the same for rules, providers, and aspects.
PiperOrigin-RevId: 745731053
Change-Id: I6732a9762fbc932d823a70d7753a2b6edc140df6
Commit
https://github.com/bazelbuild/bazel/commit/a3e26ed827badf6c4cf4f09aa37747622357635c
> [8.2.0] Set macro symbol's exported location as MacroFunction's callable location for Starlark stack

- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTest.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTestBase.java
The downloads in `AbstractActionInputPrefetcher#prefetchInputs` reported lost inputs that are symlinks to other artifacts with the exec path of the target, which results in a crash when the target is not also an input to the action. This is fixed by always reporting the exec path of the symlink.
Fixes #25841
Closes #25847.
PiperOrigin-RevId: 747819887
Change-Id: Iff9125c95a2598851b8a31ed4ca18fd7218a97aa 
(cherry picked from commit a7da0d8e693b6c73a99a8bb7ebff6611fbd994ab)
Closes #25849
> [8.2.1] Fix crash on lost inputs that are symlinks

- src/main/java/com/google/devtools/build/lib/exec/local/XcodeLocalEnvProvider.java
- src/main/starlark/builtins_bzl/common/xcode/providers.bzl
- src/main/starlark/builtins_bzl/common/xcode/xcode_config.bzl
On macOS, this change ensures that when `DEVELOPER_DIR` environment variable is used, it will be propagated to `/usr/bin/xcrun` to query the SDKROOT. This takes precedence over the `--xcode_version` flag when selecting the Xcode installation. This aligns with the intended use as documented in `man xcrun`:
`The tool xcode-select(1) is used to set a system default for the active developer directory, and may be overridden by the DEVELOPER_DIR environment variable (see ENVIRONMENT).`
To leverage this, developers must propagate the `DEVELOPER_DIR` environment variable to Bazel actions using `--action_env=DEVELOPER_DIR`.
Closes #25657.
PiperOrigin-RevId: 748404233
Change-Id: I52181098658d33e2bd2ec992ad1cd38d64abb293
Commit https://github.com/bazelbuild/bazel/commit/d2e8c82570c63e9a0c6ef369ef458a …
> [8.3.0] macOS: respect DEVELOPER_DIR for Xcode selection.

- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTest.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTestBase.java
The downloads in `AbstractActionInputPrefetcher#prefetchInputs` reported lost inputs that are symlinks to other artifacts with the exec path of the target, which results in a crash when the target is not also an input to the action. This is fixed by always reporting the exec path of the symlink.
Fixes #25841
Closes #25847.
PiperOrigin-RevId: 747819887
Change-Id: Iff9125c95a2598851b8a31ed4ca18fd7218a97aa  (cherry picked from commit a7da0d8e693b6c73a99a8bb7ebff6611fbd994ab)
Closes #25849
Commit https://github.com/bazelbuild/bazel/commit/74da5dd52ecb2a7a3573121ea028992e8e827723
> [8.3.0] Fix crash on lost inputs that are symlinks (#25856)

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteExecutionServiceTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerTest.java
Without `--guard_against_concurrent_changes`, locally executed actions can easily pollute the disk or remote cache when inputs are modified during execution, which is in stark contrast to Bazel's correctness guarantees. But with the flag enabled, the additional file system operations can unnecessarily slow down non-interactive builds and also, in rare but not negligible cases, result in false positives, which has made it difficult to flip the flag.
This change aims to resolve this issue by introducing a "lite" value of the flag that only checks source files in the main repository. Since output files are made read-only after digesting and files in external repositories are rarely modified during execution (`local_repository` being a notable exception), this gets most of the benefits for …
> [8.3.0] Add and set `--guard_against_concurrent_changes=lite`

- site/en/external/registry.md
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
Context: https://github.com/bazelbuild/bazel-central-registry/issues/4320
RELNOTES: source.json now supports a new attribute `mirror_urls` as backup URLs for the source archive.
Closes #25928.
PiperOrigin-RevId: 750663220
Change-Id: I23ed94200ad555f7b1a756d76f3621fc0bd1b50f
Commit https://github.com/bazelbuild/bazel/commit/15497ff89b40d346f2bdef4a509f620f72837543
> [8.3.0] Allow `mirror_urls` in source.json

- src/main/java/com/google/devtools/build/lib/bazel/commands/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/commands/ModCommand.java
Also don't print the `bazel help mod` suggestion for evaluation errors.
Closes #25972.
PiperOrigin-RevId: 754834429
Change-Id: I0fa59e88b0f670127ceb2b8fe971dbf3c84a5915
Commit https://github.com/bazelbuild/bazel/commit/e64ed65d1aec268a06c72dac6419878fe191817a
> [8.3.0] Report cycles in `bazel mod`

- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/RegisteredExecutionPlatformsFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/toolchains/RegisteredToolchainsFunction.java
Fixes:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'RegisteredExecutionPlatformsValue.Key{configurationKey=BuildConfigurationKey[9717a88017211d5216fbdbc464e63175f64ccddbf8228373e570ef6207784c59], debug=false}' (requested by nodes 'ToolchainContextKey{configurationKey=BuildConfigurationKey[9717a88017211d5216fbdbc464e63175f64ccddbf8228373e570ef6207784c59], toolchainTypes=[ToolchainTypeRequirement[toolchainType=@@rules_shell+//shell:toolchain_type, mandatory=false, ignoreIfInvalid=false]], execConstraintLabels=[], forceExecutionPlatform=Optional.empty, debugTarget=false}', 'ToolchainContextKey{configurationKey=BuildConfigurationKey[9717a88017211d5216fbdbc464e63175f64ccddbf8228373e570ef6207784c59], toolchainTypes=[], execConstraintLabels=[], …
```
> [8.3.0] Fix a crash when an execution platform is registered twice

- src/main/java/com/google/devtools/build/lib/remote/merkletree/DirectoryTreeBuilder.java
- src/test/shell/bazel/remote/remote_execution_test.sh
Also add a test verifying that source directories and globbed directory contents have the exact same representation with remote execution.
Fixes #11495
Work towards #25834
Closes #25868.
PiperOrigin-RevId: 755896046
Change-Id: I19d919f7b37e5eb173c0dfb9046f22f9ae7da56c
Commit https://github.com/bazelbuild/bazel/commit/154dae57d1c6616fd2f3ced07f6887326fc812f3
> [8.3.0] Add support for source directories in runfiles with remote execution

- src/main/cpp/blaze.cc
- src/test/shell/integration/startup_options_test.sh
Recently I was debugging why my bazel server was getting killed seemingly for no reason and noticed that there is no information in stdout. This would be incredibly helpful to have officially in bazel.
Fixes https://github.com/bazelbuild/bazel/issues/25364
Closes #26016.
PiperOrigin-RevId: 756687906
Change-Id: Id3d6565276a2eb15fbd6f83d0a33fab2e31b3ad8
Commit https://github.com/bazelbuild/bazel/commit/cac54c46e5fd14b202066e7da8d05ddc098357c5
> [8.3.0] Print exactly what startup options have changed

- src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java
Previously Bazel would just hang on `Computing main repo mapping:` with no further information if any external repo fetch occurs during Starlark option parsing. With this change, fetch and download progress is now reported as usual.
Closes #25962.
PiperOrigin-RevId: 757646419
Change-Id: I091c7a518d160972ec3370f9fa682be7be9c3f3c
Commit https://github.com/bazelbuild/bazel/commit/040ec46e2237a2f794e3dc5795f486e93c5fce1d
> [8.3.0] Report progress for fetches occuring during Starlark option parsing

- src/main/java/com/google/devtools/build/lib/remote/GrpcRemoteExecutor.java
We are seeing profiles in which there is a large gap between the start of the `execute remotely` span and the the start of the `queue` span reported by the remote executor. The current theory is that there is contention on the channel with async tasks spawned by `--remote_cache_async` which this span could help pin down.
Closes #25947.
PiperOrigin-RevId: 753068760
Change-Id: I2b004152ab695530d02d160b8c7b446fcc89e60f
Commit https://github.com/bazelbuild/bazel/commit/659d5f9b8b116aec3fc2d9643ca537226f459e3d
> [8.3.0] Add profiler span for sending the `Execute` request

- src/main/java/com/google/devtools/build/lib/shell/JavaSubprocessFactory.java
This method wasn't available when the code was written but has since been added.
Closes #26067.
PiperOrigin-RevId: 758817223
Change-Id: Ia5b09f45168da37f7db2330f942a201216acb8ad
Commit https://github.com/bazelbuild/bazel/commit/5072ebcd16860228988040e883e6895ef0ecdc52
> [8.3.0] Call `Process#destroyForcibly` in `JavaSubprocess#close`

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java
The current message ("not a regular file") is inaccurate -- we actually support "special files" like pipes here, and can mislead people into thinking that symlinks aren't supported here (they totally are).
PiperOrigin-RevId: 750761748
Change-Id: I8ba6e6b420fddf69e0d6a4f2584f9d39914d47f1
Commit https://github.com/bazelbuild/bazel/commit/443012d75ec9c6306ec59c7e3d4804ac135c1aa4
> [8.3.0] Fix error message when `single_version_override` patches don't exist

- src/test/shell/bazel/local_repository_test.sh
- tools/build_defs/repo/local.bzl
This was accidentally found while debugging https://github.com/bazelbuild/bazel/pull/26080. Technically a minor regression introduced by the Starlarkification of `local_repository`.
Closes #26104.
PiperOrigin-RevId: 761143618
Change-Id: Id04a8ace04e812c39bb8c5cd811959e731901606
Commit https://github.com/bazelbuild/bazel/commit/26672bcc2487528da1c8ca437ea13e4db120a69f
> [8.3.0] Make `local_repository` watch the target path in case it gets removed

- src/main/java/com/google/devtools/build/lib/rules/java/JavaInfo.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaStarlarkCommon.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaCommonApi.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaInfoApi.java
This adds experimental, unimplemented Java Starlark APIs for header compilation direct deps.
PiperOrigin-RevId: 759653952
Change-Id: If4c6bb7c03dfbba25487b15b8f12d3a9cf0140af (cherry picked from commit eea08821fde648485d08d93daad5c5c34e17dc25)
> [8.3.0] Initial API changes for header compilation direct deps

- src/main/java/com/google/devtools/build/lib/rules/java/ResourceJarActionBuilder.java
- src/test/shell/integration/java_integration_test.sh
- src/tools/singlejar/options.cc
- src/tools/singlejar/options.h
- src/tools/singlejar/output_jar.cc
A separate resource jar action is used for java targets with resources, and we invoke singlejar to create the final combined class jar. In these cases, we shouldn't be stripping the module-info.
Work towards https://github.com/bazelbuild/rules_java/issues/293
Closes #26081.
PiperOrigin-RevId: 762316383
Change-Id: Ifccddd8862186953213a30cc399e1867c68cc7e4 (cherry picked from commit 83255bc52b88e6d8990572a6f75853db5154e70b)
> [8.3.0] Don't strip module-info from regular class jars

- src/main/java/com/google/devtools/build/lib/analysis/BUILD
- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptionConverters.java
- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java
- src/main/java/com/google/devtools/build/lib/analysis/starlark/FunctionTransitionUtil.java
- src/test/java/com/google/devtools/build/lib/analysis/config/BuildConfigurationValueTest.java
Adds:
- https://github.com/bazelbuild/bazel/commit/324c900110fc5083e03985e0389df9b5e7d63316
- https://github.com/bazelbuild/bazel/commit/e1d5e86cc1b15cd136ccd76514399a0463004941
Result:
- support `//foo/...` syntax
- correctly handle label conversion
Fixes https://github.com/bazelbuild/bazel/issues/25271.
> [8.3.0] Manual merge 324c900 and e1d5e86

- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/vfs/Path.java
Remote metadata that is later materialized as a local file frequently hits the code path in `AbstractActionInputPrefetcher` that checks for discrepancies between the metadata and the local filesystem state. Since computing the digest is potentially costly and often unnecessary in this case, short-circuit by comparing sizes and contents proxies, if available.
Also add comments to `Path#statNullable` and `Path#statIfFound` to more clearly explain the subtle difference.
Closes #26146.
PiperOrigin-RevId: 763396727
Change-Id: I081d6d8b4efba661348746ba56c39120d18c31c3 
(cherry picked from commit 914542ba3b97e5cef10127177bef610f7d2ee0e4)
Fixes #26152
> [8.3.0] Avoid digesting files in `AbstractActionInputPrefetcher` if possible

- BUILD
- MODULE.bazel
- src/java_tools/buildjar/java/com/google/devtools/build/java/turbine/BUILD
- src/test/shell/bazel/bazel_java_test.sh
- third_party/rules_graalvm_unicode.patch
This requires patching rules_graalvm with https://github.com/sgammon/rules_graalvm/pull/514 to ensure the native image runs with `sun.jnu.encoding` set to `UTF-8` on Linux.
Also enable unrelated tests after the recent java_tools update.
Work towards #24444
Unblocks #24457
Closes #24565.
PiperOrigin-RevId: 703409662
Change-Id: I44de4387de4a6da404436f5a35a2b27274122bbb
Commit https://github.com/bazelbuild/bazel/commit/a37d288b80d8b51e96f13b3a7bce82d54dfe7ff9
> [8.3.0] Let Turbine handle Unicode paths

- src/main/java/com/google/devtools/build/lib/skyframe/StarlarkBuildSettingsDetailsFunction.java
Speculative fix for #22066
Closes #26101.
PiperOrigin-RevId: 765255882
Change-Id: I7569c3b2175d3bca527673f8aa13d1649c86942a
Commit https://github.com/bazelbuild/bazel/commit/6387e0d8e6c435eb18437d5711ad43f6e7721f58
> [8.3.0] Add a missing null check on `SkyframeLookupResult#getOrThrow`

- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java
- src/main/java/com/google/devtools/build/lib/runtime/CommandEnvironment.java
- src/main/java/com/google/devtools/build/lib/runtime/CommonCommandOptions.java
- src/test/shell/bazel/starlark_repository_test.sh
This adds a new flag `--incompatible_repo_env_ignores_action_env` which when flipped stops `--action_env=NAME=VALUE` from affecting repository rule and module extension environments.
Split from #24404.
Closes #25238.
PiperOrigin-RevId: 767031987
Change-Id: I1683935ab2728f6bbfcf499ea8a598770002020d
Commit https://github.com/bazelbuild/bazel/commit/216ae9d3b000695a72c70d5e3651d017c773714d
> [8.3.0] Add `--incompatible_repo_env_ignores_action_env` option

- src/main/java/com/google/devtools/build/lib/analysis/test/TestActionBuilder.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestProvider.java
- src/main/java/com/google/devtools/build/lib/bazel/coverage/CoverageArgs.java
- src/main/java/com/google/devtools/build/lib/bazel/coverage/CoverageReportActionBuilder.java
This ensures that exec properties are set for some deterministic test exec platform, which may be required if the coverage report action is run remotely.
Fixes #20578
Closes #25960.
PiperOrigin-RevId: 762481198
Change-Id: I55e0514d02f91dffc32ff8fa13fa8f9f458189a1
(cherry picked from commit 3087f179e107b0d746ba9a26189109f8f10c1750)
Fixes #26108
> [8.3.0] Use a real `ActionOwner` for coverage report actions

- src/main/java/com/google/devtools/build/lib/cmdline/RepositoryName.java
- src/test/java/com/google/devtools/build/lib/packages/WorkspaceFactoryTest.java
- src/test/shell/bazel/local_repository_test.sh
RELNOTES: User-provided repo names may now start with a number.
Closes #25974.
PiperOrigin-RevId: 753128093
Change-Id: I9e026495f17bace30949b9842307afdba7c44692
> [8.3.0] Loosen up repo name rule - Support repos which start with number

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java
These are entirely internal and not meant to be locked.
Closes #26232.
PiperOrigin-RevId: 769783817
Change-Id: Iaafae94fb5d41e74127400c220b9cdbed268a22c
Commit https://github.com/bazelbuild/bazel/commit/b584b91167ba1291bce22046790ee728aecd37ae
> [8.3.0] Don't lock innate extensions

- BUILD
- MODULE.bazel
- MODULE.bazel.lock
- distdir.bzl
- repositories.bzl
- src/main/java/com/google/devtools/build/lib/bazel/debug/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/debug/WorkspaceRuleEvent.java
- src/main/java/com/google/devtools/build/lib/bazel/debug/workspace_log.proto
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkWasmExecutionResult.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkWasmModule.java
- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/profiler/ProfilerTask.java
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/starlark_repository_test.sh
- src/test/shell/bazel/testdata/BUILD
- src/test/shell/bazel/testdata/exec_wasm.wat
- src/test/tools/wasm.bzl
- src/tools/bzlmod/utils.bzl
- third_party/BUILD
- third_party/chicory/BUILD
RELNOTES: Added the `load_wasm` and `execute_wasm` methods to `repository_ctx` and `module_ctx` that allow repo rules and module extensions to run a WebAssembly binary. These methods are only available if `--experimental_repository_ctx_execute_wasm` is set.
Closes #26248
> [8.3.0] Implement executing WebAssembly in repository rules

- src/main/java/com/google/devtools/build/lib/runtime/commands/TargetPatternsHelper.java
- src/test/shell/integration/target_pattern_file_test.sh
Target files specified via `--target_pattern_file` supported Unicode labels prior to Bazel 8 in some (unreliable) capacity, but this regressed due to the Unicode fixes in other parts of Bazel introduced in time for Bazel 8. This change ensures that the file is parsed in the "internal" string encoding, matching the rest of Bazel and restoring support for labels containing Unicode characters.
Closes #26166.
PiperOrigin-RevId: 770609137
Change-Id: Ib8735d2ecd7918c42317952324effb8a50e09820 
(cherry picked from commit 2f51ed6120bbbf9514719f1fa0a33c35ee5183e4)
Fixes #26172
> [8.3.0] Fix `--target_pattern_file` with Unicode labels

- src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleConfiguredTargetUtil.java
- src/test/java/com/google/devtools/build/lib/starlark/StarlarkIntegrationTest.java
- src/test/shell/integration/test_test.sh
This is already being done in the stateless case and avoids a costly check that used to flatten the runfiles tree.
In fact, the check was not sufficient as it also considered the executable to be present if it is the target of a custom symlink - but both test actions and dependents using location expansion assume that the executable is present in its default location. A new test verifies these cases.
Fixes #26242
Closes #26246.
PiperOrigin-RevId: 770712680
Change-Id: I8eaf1185909c201c28109da9849407ede2e3844f 
(cherry picked from commit d60d578f330da7a78f6d237c6ac7bf447c6a5d2e)
Fixes #26250
> [8.3.0] Add executable to stateful runfiles if necessary

- src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl
- src/main/starlark/builtins_bzl/common/cc/cc_library.bzl
The Starlark embedded in Bazel, that can get used when building other repos, has problems exposed by enabling
--incompatible_disable_target_default_provider_fields
Since this code is embedded in Bazel, there is no way for users to patch it in the course of trying to disable target default provider fields in their own repos.  We here address these issues.
Closes #26276.
PiperOrigin-RevId: 770991995
Change-Id: I4b29e9d52dd1789afe7de990ca9500812a8ec211
Commit https://github.com/bazelbuild/bazel/commit/784685969d11d096c5d4a65f11e1c3c6ee2427b8
> [8.3.0] use DefaultInfo in Bazel's embedded Starlark

- src/main/starlark/builtins_bzl/common/cc/cc_compilation_helper.bzl
- src/main/starlark/tests/builtins_bzl/cc/basics/test/BUILD.builtin_test
- src/main/starlark/tests/builtins_bzl/cc/basics/test/nested/lib.cc
- src/main/starlark/tests/builtins_bzl/cc/basics/test/nested/lib.h
- src/main/starlark/tests/builtins_bzl/cc/basics/test/test_include_textual.cc
Fixes https://github.com/bazelbuild/bazel/issues/12424
Closes #25749.
PiperOrigin-RevId: 771948570
Change-Id: Id470ecc19f4c67bf1911c0f568a0150c2a0b381a
Commit https://github.com/bazelbuild/bazel/commit/4f3a4fd92f970d8256f3cf8430d85d3793975d99
> [8.3.0] Make strip_include_prefix apply to textual_hdrs

- src/main/java/com/google/devtools/build/lib/bazel/rules/tools.WORKSPACE
Speculative fix for https://github.com/bazel-contrib/bazel_features/pull/100#issuecomment-2980133474, only `MODULE.tools` registered the toolchain.
> [8.3.0] Register `launcher_maker_toolchain` with WORKSPACE

- src/main/java/com/google/devtools/build/lib/bazel/repository/DecompressorValue.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/DecompressorValueTest.java
The `download_and_extract` function supported various archive formats, but did not recognize `.whl` as a valid file extension for archive extraction. Since wheel files are ZIP archives with a `.whl` extension (per PEP 427), this commit adds support for them by treating `.whl` files the same as other ZIP-based formats.
This enables using Python wheel files directly with rules_multitool and other tools without requiring workarounds, particularly useful for air-gapped environments with private PyPI repositories.
Changes:
- Add .whl to ZIP decompressor condition in DecompressorValue.java
- Update error message to include .whl in supported extensions list
- Update API documentation to include .whl as supported archive type
- Add test case for .whl file extension handling
Fixes #26307 …
> [8.3.0] feat: add support for `.whl` file extension in `repository_ctx.download_and_extract`

- src/test/shell/bazel/cc_integration_test.sh
We started seeing cc_integration_test failures on Ubuntu only on Bazel CI. Example failed CI run:
https://buildkite.com/bazel/google-bazel-presubmit/builds/92979
Failing test log (Ctrl+F `tsan`):
https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/019784eb-e36a-476b-8268-eb41dd690353/src/test/shell/bazel/cc_integration_test/shard_4_of_10/test.log
This CL fixes the failure, though I have no idea why this suddenly started happening earlier today (things I ruled out: Bazel code changes, docker container pushes, remote cache poisoning).
PiperOrigin-RevId: 773497839
Change-Id: I2324a9668bfe28e24c222c12d6c82de60e7bd1df
Commit https://github.com/bazelbuild/bazel/commit/387ed02
> [8.4.0] Fix CI failures on Ubuntu 

- src/test/shell/bazel/cc_integration_test.sh
We started seeing cc_integration_test failures on Ubuntu only on Bazel CI. Example failed CI run: https://buildkite.com/bazel/google-bazel-presubmit/builds/92979
Failing test log (Ctrl+F `tsan`): https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/019784eb-e36a-476b-8268-eb41dd690353/src/test/shell/bazel/cc_integration_test/shard_4_of_10/test.log
This CL fixes the failure, though I have no idea why this suddenly started happening earlier today (things I ruled out: Bazel code changes, docker container pushes, remote cache poisoning).
PiperOrigin-RevId: 773497839
Change-Id: I2324a9668bfe28e24c222c12d6c82de60e7bd1df
Commit https://github.com/bazelbuild/bazel/commit/387ed02
> [8.3.1] Attempt to fix Bazel CI failure on Ubuntu

- src/main/java/com/google/devtools/build/lib/runtime/mobileinstall/MobileInstallCommand.java
--mobile_install_aspect points to the rules_android MI aspect, rather than the non-existent one in android_test_support
--mobile_install_supported_rules defaults to android_binary. No other rules are planned to the supported in the forseeable future.
RELNOTES: Add better defaults for mobile-install flags
PiperOrigin-RevId: 746132439
Change-Id: I562ffa76148f9be498e7048a6e99f420f1a62e4f
> [8.4.0] Add better defaults for mobile-install flags

- src/package-bazel.sh
Since 56329b9, `//src:bazel-dev` crashes on startup with:
```
FATAL: Failed to find member 'build-label.txt' in zip file '.../execroot/_main/bazel-out/.../bin/src/bazel-dev'
```
This is fixed by always adding a `build-label.txt` file to the server zip.
Closes #24385.
PiperOrigin-RevId: 698275249
Change-Id: I97000834940e6a2f31020de797a557ee213f4ff5
Commit https://github.com/bazelbuild/bazel/commit/222d47f3bd57370f9a462ebdd86dfe1510795cd2
> [8.4.0] Fix `//src:bazel-dev` crash on startup

- src/main/java/com/google/devtools/build/lib/bazel/repository/cache/RepoContentsCache.java
This always failed since the target of the move was an existing directory.
Closes #26401.
PiperOrigin-RevId: 776662445
Change-Id: Ideac0547efda8e2e44b0f962c8e0f9af6b6a0c65
Commit https://github.com/bazelbuild/bazel/commit/f5cf3c593e0f9de33f060b2aee77152935c46f3e
> [8.4.0] Fix fast path in repo contents cache

- src/main/starlark/builtins_bzl/common/builtin_exec_platforms.bzl
This ports https://github.com/bazelbuild/bazel/pull/15978, which never got merged, to Starlark.
Closes #26346.
PiperOrigin-RevId: 777732082
Change-Id: I699c8fc248d18e1e6db168725f49fc051829b45e
Commit https://github.com/bazelbuild/bazel/commit/7c40bbeac7560aabf506c4f3a6cf1c98b156475e
> [8.4.0] Forward `--host_jvmopt` to the exec configuration

- tools/test/extensions.bzl
Built at commit d49967e8.
Relevant changes:
* Branches for a given line will not be dropped when the to-be-merged reports disagree on the number of branches for that line; they will simply be merged on a best effort basis.
RELNOTES:
Branches will always be merged as best as possible based on branch and
block numbers during coverage report generation.
Closes #26407.
PiperOrigin-RevId: 776513248
Change-Id: I29b2a75e86738aa08650945f9804d73aa9235a6e
Commit https://github.com/bazelbuild/bazel/commit/71cc37f22d96c27994d66614219e68d44e20023b
> [8.4.0] Update to use coverage_output_generator-v2.9

- src/main/java/com/google/devtools/build/lib/sandbox/SymlinkedSandboxedSpawn.java
Makes the interactive environment more representative of the actual sandbox environment.
Closes #26448.
PiperOrigin-RevId: 778888610
Change-Id: I73f12b29a24b45ef5a072ecb9174b7ef86dffef7
Commit https://github.com/bazelbuild/bazel/commit/8709d090d032ed9e096ba0223ddf9c05e520aa98
> [8.4.0] Set working directory in interactive `--sandbox_debug` command

- src/main/java/com/google/devtools/build/lib/worker/WorkerMultiplexer.java
See #26292.
The user suggested a potential fix "the simplest solution is to have WorkerMultiplexer only remove the work request from requestChecker if an InterruptedException (or CancellationException?) wasn’t thrown."
The suggested fix makes sense. I've also added another check to gracefully handle the cancellation requests.
PiperOrigin-RevId: 779179061
Change-Id: Ieafb404ef03d3e6897b3cb11e8043492d45e623d
Commit https://github.com/bazelbuild/bazel/commit/a40faeda91939b1f50aad758221c9a0aa361332b
> [8.4.0] Fix a race condition caused by our semaphore-handling mechanism in WorkerMultiplexer.

- .gitattributes
Fixes #26467
Closes #26469.
PiperOrigin-RevId: 780195145
Change-Id: Icc9835df06dd3e87849a1a54c0eea32b92e36208
Commit https://github.com/bazelbuild/bazel/commit/1dd48679c6d84e60e9a03c00186df437eae13bd6
> [8.4.0] Preserve line endings for all checked-in files

- src/main/java/com/google/devtools/build/lib/sandbox/HardlinkedSandboxedSpawn.java
- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
When running with --experimental_use_hermetic_linux_sandbox, this allows us to see the interactive debug instructions like we'd see without it.
Note that `EnterWorkingDirectory()` in `linux-sandbox` requires that the working directory is under the sandbox_root path, so we need to include `cwd=sandboxExecRoot()` when calling `describeCommand`. This is a stricter requirement than for SymlinkedSandboxedSpawn which was changed in #26448 more for UX reasons.
Fixes #26580.
Closes #26581.
PiperOrigin-RevId: 786165593
Change-Id: Ib1a2dfccb7731691314d88d10e4c6a168977c875
Commit https://github.com/bazelbuild/bazel/commit/289e3859aedab2af7253b6053f6fd575bfd0f3af
> [8.4.0] Print interactive debug instructions in HardlinkedSandboxedSpawn

- src/main/java/com/google/devtools/build/lib/exec/ExecutionOptions.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteActionContextProvider.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteExecutionServiceTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerWithGrpcRemoteExecutorTest.java
Before this change parameter files were only materialized with remote execution.
Also makes the existing test for remote execution more precise.
Closes #26566.
PiperOrigin-RevId: 785431102
Change-Id: If3b8a1995bf3269a9e1a087eedaf22540b12b488
Commit https://github.com/bazelbuild/bazel/commit/7527a0423f78914da36479aac2c61acf8a8ce2b2
> [8.4.0] Materialize parameter files with a remote cache if requested

- src/main/java/com/google/devtools/build/lib/analysis/test/TestActionBuilder.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestActionContext.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestConfiguration.java
- src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java
- src/main/java/com/google/devtools/build/lib/rules/test/ExclusiveTestStrategy.java
- src/main/java/com/google/devtools/build/lib/standalone/StandaloneModule.java
- src/test/java/com/google/devtools/build/lib/exec/BUILD
- src/test/java/com/google/devtools/build/lib/exec/StandaloneTestStrategyTest.java
- src/test/shell/bazel/bazel_test_test.sh
The existing `--experimental_cancel_concurrent_tests` flag can be used to let Bazel cancel concurrent runs of the same test as soon as one run passes with `--runs_per_test_detects_flakes`. This change turns the boolean-valued into an enum-valued flag that also accepts the value `on_failed` to instead cancel on the first failed run. This can be used to avoid reruns of flaky tests when the intention is to only detect flakes, not their probability of being flaky.
Also fix the quirk that `--experimental_cancel_concurrent_tests` has no effect with default Bazel settings since the `exclusive` test strategy is registered last and thus always wins. Perhaps surprisingly, this is the only effect of that incorrect registration order - all other `exclusive` logic is explicitly gated behind the value …
> [8.4.0] Add `--experimental_cancel_concurrent_tests=on_failed`

- src/tools/launcher/BUILD
- src/tools/launcher/bash_launcher.cc
- src/tools/launcher/bash_launcher.h
- src/tools/launcher/java_launcher.cc
- src/tools/launcher/launcher.cc
- src/tools/launcher/launcher.h
- src/tools/launcher/python_launcher.cc
It's the fix for #26666.
Closes #26667.
PiperOrigin-RevId: 789833713
Change-Id: I54ac9740cbd528c7f115c132671e5416f0118400
Commit https://github.com/bazelbuild/bazel/commit/b64805173bf7b3d1b8cb1893d62e9d61bcb07f8b
> [8.4.0] Properly escape arguments passed to LaunchProcess() in JavaBinaryLauncher::CreateClasspathJar

- src/main/java/com/google/devtools/build/lib/analysis/RuleContext.java
- src/main/java/com/google/devtools/build/lib/analysis/constraints/ConstraintConstants.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java
- src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainFeatures.java
- src/main/java/com/google/devtools/build/lib/vfs/OsPathPolicy.java
- src/main/java/com/google/devtools/build/lib/vfs/PathFragment.java
- src/main/java/com/google/devtools/build/lib/vfs/WindowsOsPathPolicy.java
- src/test/java/com/google/devtools/build/lib/rules/cpp/BUILD
- src/test/java/com/google/devtools/build/lib/rules/cpp/StarlarkCcCommonTest.java
Work towards #19208
RELNOTES: Tool paths specified in `cc_toolchain` action configs are now normalized based on the current execution platform's OS rather than the host OS. In particular, Windows-style absolute paths are now treated as absolute paths when building on a Windows executor from a non-Windows host.
Closes #22218.
PiperOrigin-RevId: 785464222
Change-Id: I0866b0c9d87ab518c061369d836a8a08fb793630
Commit https://github.com/bazelbuild/bazel/commit/71a7c2b8d5dc0eb3ba73a3e701a20a21aa3c06c0
> [8.4.0] Normalize C++ action config tool paths based on exec platform OS

- src/main/java/com/google/devtools/build/lib/skyframe/AspectFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/ConfiguredTargetFunction.java
- src/test/java/com/google/devtools/build/lib/buildtool/OutputArtifactConflictTest.java
This makes it possible to debug config-dependent errors.
Closes #26690.
PiperOrigin-RevId: 792275177
Change-Id: I026d6aae8a3dbc1da20a155f4b873d0349b76a8d
Commit https://github.com/bazelbuild/bazel/commit/8e552b02e336a54808ecc8840618a905044fdf27
> [8.4.0] Add configuration short ID to analysis error

- src/main/java/com/google/devtools/build/lib/query2/aquery/ActionGraphQueryEnvironment.java
- src/main/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryEnvironment.java
- src/test/java/com/google/devtools/build/lib/query2/testutil/AbstractQueryTest.java
- src/test/java/com/google/devtools/build/lib/query2/testutil/PostAnalysisQueryTest.java
Rule transitions that are not idempotent are owned by a `ConfiguredTargetKey` that has `shouldApplyRuleTransition` set to `false`. Since this is not the default, `cquery` and `aquery`'s iteration over all configurations in the build does not pick up these configured targets and their filtering logic removed them when encountered.
This is fixed by augmenting the filtering logic to keep these targets if they wouldn't be encountered in any other way.
Adding a suitable test required removing logic in a test helper that uniquified results.
Closes #26738.
PiperOrigin-RevId: 794272905
Change-Id: Ie6fc0716bf75b77c287ff9e09163aeaee9692584
Commit https://github.com/bazelbuild/bazel/commit/90b76d6d412c48b3a0a951db9f10c60c33bd5723
> [8.4.0] Include targets with non-idempotent rule transition in query output

- src/main/java/com/google/devtools/build/lib/buildtool/PostAnalysisQueryProcessor.java
- src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java
- src/test/shell/integration/configured_query_test.sh
The deletion of dirty nodes in the Skyframe graph is delayed for performance reasons, which resulted in rdeps pointing to stale nodes being present when `aquery` or `cquery` walked the graph. Fix this by cleaning up these nodes eagerly when running with an analysis postprocessor.
The PR has been manually verified on the reproducer provided in https://github.com/bazelbuild/bazel/issues/15079#issuecomment-1695781700. The reproducer no longer failed at HEAD since 099f0e50610c9abbdb71c6d88553f99df7bead9f, as it apparently required a more complex setup to evade the existing `null` checks and produce a crash.
The test added with this PR is simpler and did not produce an NPE even prior to this change due to the protective `null` checks. It does produce a failure before this PR and passes with it …
> [8.4.0] Clear out stale rdeps before running analysis postprocessors

- site/en/extending/macros.md
Fix typos and grammatical errors in site/en/extending/macros.md
> [8.4.0] Cherry pick several documentation fixes

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactory.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryImpl.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
- src/main/java/com/google/devtools/build/lib/skyframe/packages/BazelPackageLoader.java
- src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisMock.java
- src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisTestCase.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodRepoRuleFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/DiscoveryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/FakeRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryTest.java
- src/test/java/com/google/devtools/build/lib/query2/testutil/SkyframeQueryHelper.java
- src/test/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/PrepareDepsOfPatternsFunctionTest.java
The new flag allows users to specify additional mirrors for Bazel registry source URLs, taking precedence over those specified by registries. This provides a way to add mirrors without changing `bazel_registry.json`, the hash of which is stored in lockfiles.
RELNOTES: The new `--module_mirrors` flag accepts a comma-separated list of mirrors to use for source URLs provided by modules obtained from Bazel registries.
Closes #26832.
PiperOrigin-RevId: 800384242
Change-Id: I3b56eb5fe0405f460568d7563b2ad93f6b7461a5
Commit https://github.com/bazelbuild/bazel/commit/c3889fc68087223d530a04f2db28c69acc7e7473
> [8.4.0] Add `--module_mirrors`

- src/main/cpp/archive_utils.h
- src/main/cpp/util/logging.h
Fixes https://github.com/bazelbuild/bazel/issues/25514
Closes #26963.
PiperOrigin-RevId: 807611171
Change-Id: Ie4102be364146bc142389756b04160cf30e9d39f
Commit https://github.com/bazelbuild/bazel/commit/b39e21fb27cfaf8ee2f6212562ac9e194a78588a
> [8.5.0] Add the missing headers

- site/en/external/registry.md
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistryTest.java
Context: https://github.com/bazelbuild/bazel-central-registry/issues/4320
RELNTOES[NEW]: source.json now supports a new attribute `mirror_urls` as backup URLs for the source archive.
Closes #25928.
PiperOrigin-RevId: 750663220
Change-Id: I23ed94200ad555f7b1a756d76f3621fc0bd1b50f
Commit https://github.com/bazelbuild/bazel/commit/15497ff89b40d346f2bdef4a509f620f72837543
> [7.7.0] Allow `mirror_urls` in source.json

- tools/osx/BUILD
These workarounds were added (in 76b3c24283, bazelbuild/bazel#14168) to enable hermetic macOS toolchain setup, but are no longer necessary as far as I can tell (see also: bazelbuild/apple_support@44c43c715a, bazelbuild/apple_support#373).
It should be noted that macOS Tahoe seems to have enforced that LC_UUID must be present in executables. Executables without it are rejected by dyld with `dyld: missing LC_UUID load command`, effectively stops Bazel from working. It is therefore necessary to drop these workarounds here and in Apple support (done in bazelbuild/apple_support@44c43c715a) in order for Bazel to function on macOS Tahoe.
CC @keith
Closes #27014.
PiperOrigin-RevId: 811436317
Change-Id: I9d819fdbc2b76ad4ee5abb1fc0c4eb1ee1b442fb
Commit …
> [7.7.0] Remove xcode_locator's no_uuid and codesigning workarounds

- MODULE.bazel
- MODULE.bazel.lock
- src/MODULE.tools
- src/test/shell/bazel/path_mapping_test.sh
This drops a few extension entries that would otherwise be contained in the lockfile of every Bazel project, even an empty one.
Closes #27065.
PiperOrigin-RevId: 812741057
Change-Id: Ibe879ebf9af0091c31c8e16ef1e2680acb9de004
> [8.4.2] Clean up default lockfile
