- README.md
> Revert README.md changes that were pushed to GitHub directly.

- third_party/protobuf/README.md
Change-Id: Ib3f4d12dcd71100bef0563b6ada175a767b8be19
> Protobuf update instructions: update and fix.

- WORKSPACE
- src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE
- src/test/shell/bazel/testdata/jdk_http_archives
Fixes https://github.com/bazelbuild/java_tools/issues/47
> Update to java_tools javac11 10.6

- src/main/java/com/google/devtools/build/lib/runtime/UiStateTracker.java
Fixes https://github.com/bazelbuild/bazel/issues/13713.
b51b31dbe75a5bc73227fccb4484f3454df81b42
None.
> Cherrypicks for 4.2.0: Fix a race when reporting action progresses.

- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnRunnerTest.java
Breaks some targets.
PiperOrigin-RevId: 412968486
> [5.x] Automated rollback of commit d84f7998ef8f15e27376a0c8f25b320145c4ba9e.

- scripts/bootstrap/bootstrap.sh
- site/docs/install-compile-source.md
- src/test/shell/bazel/bazel_bootstrap_distfile_test.sh
Closes #14708.
PiperOrigin-RevId: 435014309
> [5.1] Update Bazel bootstrap documentation and remove obsolete flags.

- scripts/packages/chocolatey/bazel.nuspec.template
Note: 5.2.0 edition of #15369.
> Choco docsurl (against release 5.2.0)

- src/main/java/com/google/devtools/build/lib/profiler/Profiler.java
Fixes #14949.
PiperOrigin-RevId: 439775241
> Catch NumberFormatException while trying to parse thread id.

- src/main/java/com/google/devtools/build/lib/clock/BlazeClock.java
- src/main/java/com/google/devtools/build/lib/remote/BUILD
- src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java
Closes #15348.
PiperOrigin-RevId: 445882024
> Record additional profiling information for remotely executed actions.

- src/main/java/com/google/devtools/build/lib/skyframe/ToolchainResolutionFunction.java
- src/test/java/com/google/devtools/build/lib/skyframe/ToolchainResolutionFunctionTest.java
- src/test/shell/bazel/toolchain_test.sh
Closes #15135.
PiperOrigin-RevId: 447028054
> Improve error message for unresolved toolchains

- tools/build_defs/repo/http.bzl
Hi wonderful Bazel folks,
I--like probably everyone else--make heavy use of the (super handy) http repository rules.
While using them, I'd noticed that the docs for the URL attributes they have in common had started drifting. For example, http_file's URLs array doc was mostly same as http_archive's, except that it forgot to specify that the URLs were tried in the order they were specified. jar_file's were much less complete. Similarly, only http_file was missing the URL parameter, which seems a shame, since probably most people only want to supply one authoritative source most of the time. When I looked at the code, it became clear that this was because the implementations were copy-pasted, and being updated separately.
So I spent a few minutes cleaning things up and making these commonly …
> Unify URL/URLs parameter code across http_archive, http_file, http_jar

- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java
- src/test/shell/bazel/bazel_symlink_test.sh
See https://github.com/bazelbuild/bazel/issues/10298#issuecomment-1097097541
Work towards https://github.com/bazelbuild/bazel/issues/10298
Closes #15702.
PiperOrigin-RevId: 456480627
Change-Id: Ib1237ce9e2c0bab0d7eabd8743f08ec60b8b7ab7
> Preserve --experimental_allow_unresolved_symlinks in exec cfg

- src/main/java/com/google/devtools/build/lib/authandtls/BUILD
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/BUILD
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelper.java
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelperProvider.java
- src/test/java/com/google/devtools/build/lib/authandtls/BUILD
- src/test/java/com/google/devtools/build/lib/authandtls/credentialhelper/BUILD
- src/test/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelperProviderTest.java
Progress on https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md
Closes #15707.
PiperOrigin-RevId: 458456496
Change-Id: I751a594144c3563096ee9794c41329b49755824e
> Add util for finding credential helper to use

- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelper.java
- src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelperException.java
- src/main/java/com/google/devtools/build/lib/remote/util/BUILD
- src/main/java/com/google/devtools/build/lib/remote/util/Utils.java
- src/test/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelperTest.java
Closes #16012.
PiperOrigin-RevId: 464732834
Change-Id: If51ce914098ff17ffe23fa4614947e7f4a5088dc
> Propagate the error message when a credential helper fails.

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionCache.java
Closes #16118.
PiperOrigin-RevId: 468429355
Change-Id: I3b32a28ce3e7c6711fdc15839e5a88fad812184c
> [5.3.2] Avoid unnecessary iteration on action inputs.

- src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java
PiperOrigin-RevId: 483615392
Change-Id: Ic8b301ef6fd004a88f9a563e04ba961f6dfb5708
> [6.0.0] Temporarily set parent directory of the input to writable if it is not.

- site/en/BUILD.bazel
- site/en/bazel.css
This allows us to build release docs.
PiperOrigin-RevId: 484473280
Change-Id: Id67858ff692bf825dc796342beef78ae2304089e
> Bazel DevSite: Add required css file.

- src/test/java/com/google/devtools/build/lib/remote/RemoteActionFileSystemTest.java
- src/test/java/com/google/devtools/build/lib/remote/RemoteActionFileSystemTestBase.java
PiperOrigin-RevId: 485588407
Change-Id: Ie9f3919c703c968eb19328539334548238e273b9
> [6.0.0]Moving some tests for `RemoteActionFileSystem` of BwoB to a base class.

- src/main/java/com/google/devtools/build/lib/analysis/AnalysisOptions.java
- src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTest.java
This reverts commit fe169654a29d8ad33105d5d0034a7857834fed5d.
Breaks rules_apple (and possibily other projects).
> Revert "[6.0.0] Default --incompatible_strict_conflict_checks to true (#16864)"

- src/test/shell/bazel/remote/remote_execution_test.sh
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/RemoteWorker.java
- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/RemoteWorkerOptions.java
Closes #15996.
PiperOrigin-RevId: 463851754
Change-Id: I13b851454f0b8e6550b2335caa2d802312931929
> [5.4.0] Add integration tests for --experimental_credential_helper.

- distdir_deps.bzl
The newer version adds some constants that rules are starting to use.
> Update @platforms to version 0.0.5

- tools/cpp/windows_cc_toolchain_config.bzl
Closes #17068.
PiperOrigin-RevId: 504229788
Change-Id: I7b6f7f4f2c8ccb802f5a76bd54eaf0a8358793b1
> [6.1.0]Enable archive_param_file feature by default for Windows

- src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPyTestRule.java
> Add exec transition to Java version of py_test

- src/main/java/com/google/devtools/build/lib/profiler/BUILD
- src/main/java/com/google/devtools/build/lib/profiler/Profiler.java
This is basically the same as
https://github.com/bazelbuild/bazel/pull/17562/files before we did the JSON trace profile refactoring.
> Include Bazel version information in profile metadata.

- src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCcTestRule.java
- src/main/java/com/google/devtools/build/lib/bazel/rules/sh/BazelShTestRule.java
> Apply exec transition to lcov_merge in sh_test and cc_test

- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java
Fixes https://github.com/bazelbuild/bazel/issues/13839#issuecomment-1448208320
Closes #17625.
PiperOrigin-RevId: 513249316
Change-Id: Ied4ab6958febaf320ae9e0f906c8071db0077e43
> [6.1.0]Fix --host_features with multiple transitions

- third_party/zlib/gzguts.h
- third_party/zlib/zlib.patch
Fixes https://github.com/bazelbuild/bazel/issues/17956
Partial commit for third_party/*, see #17987.
Closes #17987
Commit: [1f2b3ed](https://github.com/bazelbuild/bazel/commit/1f2b3ed4ac717b814d02a0d125f160ddabe78003)
> [6.2.0] Patch zlib to fix compatibility with latest Xcode

- third_party/zlib/gzguts.h
- third_party/zlib/zlib.patch
Fixes https://github.com/bazelbuild/bazel/issues/17956
Partial commit for third_party/*, see #17987.
Closes #17987
Commit: [1f2b3ed]((https://github.com/bazelbuild/bazel/commit/1f2b3ed4ac717b814d02a0d125f160ddabe78003))
> [6.1.2]Patch zlib to fix compatibility with latest Xcode

- third_party/zlib/gzguts.h
- third_party/zlib/zlib.patch
Fixes https://github.com/bazelbuild/bazel/issues/17956
Partial commit for third_party/*, see #17987.
Closes #17987
Commit: [1f2b3ed](https://github.com/bazelbuild/bazel/commit/1f2b3ed4ac717b814d02a0d125f160ddabe78003)
> [4.2.4]Patch zlib to fix compatibility with latest Xcode

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
- src/test/shell/bazel/BUILD
- Disable failing tests that are already disabled in the master branch
- Add fix for timed out test (https://github.com/bazelbuild/bazel/commit/352eca759926b9615000ac389f988e1db940cbe7)
> [5.4.1] Disable failing tests

- site/en/rules/performance.md
- src/main/java/com/google/devtools/build/lib/profiler/Profiler.java
Repeating change from #17636 for 6.2 release
> profile: add profile_finish_ts

- src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRulesModule.java
- src/main/java/com/google/devtools/build/lib/rules/android/AndroidConfiguration.java
- src/main/java/com/google/devtools/build/lib/rules/android/DexArchiveAspect.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/android/AndroidConfigurationApi.java
- src/test/shell/bazel/android/desugarer_integration_test.sh
- tools/android/BUILD.tools
Cherry picking the worker fixes into the 6.2.0 branch https://github.com/bazelbuild/bazel/pull/17351
> [6.2.0]Fix worker and multiplex workers for DexBuilder and Desugar actions

- distdir_deps.bzl
Closes #18314.
PiperOrigin-RevId: 529665382
Change-Id: Iba616a0b705a20dcb5e28d06f431b0a79801d769
> [6.2.0] Update java_tools v12.3

- src/main/java/com/google/devtools/build/lib/query2/query/output/BUILD
- src/main/java/com/google/devtools/build/lib/query2/query/output/JSONProtoOutputFormatter.java
- src/main/java/com/google/devtools/build/lib/query2/query/output/OutputFormatters.java
- src/main/java/com/google/devtools/build/lib/query2/query/output/QueryOptions.java
- src/test/shell/integration/bazel_query_test.sh
Addresses https://github.com/bazelbuild/bazel/issues/17627
Closes #18187.
Commit https://github.com/bazelbuild/bazel/commit/a94383f8928abd379f7edef61bbaa04d262bcf98
PiperOrigin-RevId: 530859727
Change-Id: Ie12e6c783448def4b891055647cfe568f7b71b14
> [6.3.0] Add jsonproto option to query --output flag

- scripts/release/relnotes.py
- Replace removeprefix since this requires python 3.9
- Include authors/co-authors with @users.noreply.github.com in acknowledgement section (we're currently not adding contributors w/o public emails)
Commit https://github.com/bazelbuild/bazel/commit/991113a4f6908cf5ab27c002bf71aa518bcf12f5
PiperOrigin-RevId: 534091486
Change-Id: I455f96310062069148d2a28758e65f9f5675d3ff
> [6.3.0] Updates and fixes to relnotes script

- scripts/release/relnotes.py
Commit https://github.com/bazelbuild/bazel/commit/38682d2a09f1b4ab60f3fc2bc58ede8d4aa1eb52
PiperOrigin-RevId: 536324450
Change-Id: I62c0aa7c91f5b38ddae9fae0127ea7b3fb601862
> [6.3.0] Fix formatting of release notes

- src/test/java/com/google/devtools/build/lib/buildtool/BUILD
- src/test/java/com/google/devtools/build/lib/buildtool/ConvenienceSymlinkTest.java
In support of https://github.com/bazelbuild/bazel/pull/18854.
Commit https://github.com/bazelbuild/bazel/commit/8781e5ce9f8a0341b763d9e6dd75747f72cc4af1
PiperOrigin-RevId: 546346128
Change-Id: Ie3f6976b74cba351573a7f35b0d09391da10fb55
> [6.3.0] Open-source Google test `ConvenienceSymlinkTest`

- src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD
- src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
- src/main/java/com/google/devtools/build/lib/metrics/BUILD
- src/main/java/com/google/devtools/build/lib/metrics/MetricsCollector.java
Cherry pick PR for release-6.3.0 based on comments from @brentleyjones and @iancha1992 in #17615 .
> [6.3.0] Add ActionCacheStatistics to BEP

- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
Commit https://github.com/bazelbuild/bazel/commit/f0ad0fe0e1fc663412a400c4e6d7960f220dd647
PiperOrigin-RevId: 550955814
Change-Id: I548580ffad6bda28f69c181e43cb503e8134204d
> [6.3.1] Add documentation for --experimental_isolated_extension_usage

- src/main/starlark/builtins_bzl/common/cc/cc_import.bzl
- src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/BUILD.builtin_test
> [6.3.1] Advertise CcInfo from cc_import

- CODEOWNERS
> [6.4.0] Update CODEOWNERS file

- .bazelci/build_bazel_binaries.yml
- .bazelrc
- BUILD
- third_party/blake3/blake3.BUILD
- https://github.com/bazelbuild/bazel/commit/138f06fc90a5a238cc505ac075178889f7efb687
- https://github.com/bazelbuild/bazel/commit/d0de5e044c65fe7c5e414f860887be20087732da
> Cherry-pick required commits into 7.0.0-pre.20230810.1rc1

- src/main/java/com/google/devtools/build/lib/analysis/AnalysisOptions.java
- src/main/java/com/google/devtools/build/lib/analysis/BuildView.java
- src/main/java/com/google/devtools/build/lib/buildeventstream/BUILD
- src/main/java/com/google/devtools/build/lib/buildeventstream/BuildCompletingEvent.java
- src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
- src/main/java/com/google/devtools/build/lib/buildtool/buildevent/BuildCompleteEvent.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeBuildView.java
- src/main/protobuf/failure_details.proto
- src/test/java/com/google/devtools/build/lib/analysis/AnalysisCachingTest.java
- src/test/java/com/google/devtools/build/lib/analysis/BUILD
- src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewForTesting.java
Forked from https://github.com/bazelbuild/bazel/pull/16805.
Manually merged conflicts observed at https://github.com/bazelbuild/bazel/pull/16805#issuecomment-1664767974.
Fixes https://github.com/bazelbuild/bazel/issues/19162.
> [6.4.0] feat: add option to exit early if analysis cache is discarded

- MODULE.bazel
- distdir_deps.bzl
- src/MODULE.tools
- src/test/shell/bazel/bazel_rules_java_test.sh
Context: https://github.com/bazelbuild/bazel/issues/19598#issuecomment-1740539160
~Release: https://github.com/bazelbuild/rules_java/releases/tag/6.3.2~
~BCR PR: https://github.com/bazelbuild/bazel-central-registry/pull/966~
Release: https://github.com/bazelbuild/rules_java/releases/tag/5.5.1
BCR PR: https://github.com/bazelbuild/bazel-central-registry/pull/967
> [6.4.0] Update rules_java 5.5.1

- scripts/release/release.sh
PiperOrigin-RevId: 571350496
Change-Id: I95f5a1ef32ba1df4dad7ebb9c25bf87333bc25ff
> Bazel release process: Fix push justification.

- src/main/java/com/google/devtools/build/lib/rules/config/ConfigGlobalLibrary.java
- src/test/java/com/google/devtools/build/lib/rules/LabelBuildSettingTest.java
When a label pointing to an unavailable repository is specified as a transition's input or output, an early error is raised instead of crashing during transition evaluation.
Fixes #19632
Closes #19634.
PiperOrigin-RevId: 570634319
Change-Id: Icda2946313898db2372484b4f845aafcf5a8b272
Fixes #19641
> Raise an early error on invalid labels in transitions inputs/outputs

- scripts/release/release.sh
Commit: https://github.com/bazelbuild/bazel/commit/46404353f8295fb6306e34b7138b622b083c8ec0
PiperOrigin-RevId: 571350496
Change-Id: I95f5a1ef32ba1df4dad7ebb9c25bf87333bc25ff
> [6.4.0] Bazel release process: Fix push justification.

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
- .bazelrc
- BUILD
- MODULE.bazel
- MODULE.bazel.lock
- rbe_extension.bzl
Working towards https://github.com/bazelbuild/continuous-integration/issues/1757.
Closes #19866.
Commit https://github.com/bazelbuild/bazel/commit/553c2bc904865fa94a9e077ac34d7d7147fa928d
PiperOrigin-RevId: 574451509
Change-Id: I00bc491365a69558038293ad2035c5133da2059a
> [7.0.0] Upgrade to rbe_ubuntu2004

- src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/FetchCommand.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/FetchOptions.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/SyncCommand.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/fetch.txt
- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/packages/BazelPackageLoader.java
- src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisMock.java
- src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisTestCase.java
- src/test/java/com/google/devtools/build/lib/analysis/util/ConfigurationTestCase.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/DiscoveryTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java
- src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/buildtool/util/BuildIntegrationTestCase.java
- src/test/java/com/google/devtools/build/lib/query2/testutil/SkyframeQueryHelper.java
- src/test/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/AbstractCollectPackagesUnderDirectoryTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/ContainingPackageLookupFunctionTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/FileFunctionTest.java
- src/test/java/com/google/devtools/build/lib/skyframe/PackageLookupFunctionTest.java
- src/test/py/bazel/bzlmod/bazel_fetch_test.py
Cherry picking 
-------
Refactor delegator function for clearer understanding
PiperOrigin-RevId: 574440757
Change-Id: Ib37f1024709a5d604913088efdbfbd71d869d308
-------
Add --force option to fetch
This option can be used alongside any fetch operation to compel the fetching process.
PiperOrigin-RevId: 574810048
Change-Id: I3df8fc18ac701cf0ca7a0ce68f1565fb064d59b5
> Add force fetch option

- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/Checksum.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HashInputStream.java
- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HashOutputStream.java
- src/test/shell/bazel/external_integration_test.sh
- src/test/shell/bazel/external_patching_test.sh
Work towards https://github.com/bazelbuild/bazel/issues/17803
Closes #20155.
Commit https://github.com/bazelbuild/bazel/commit/651c185389241acda7cd0cf3e30faed280f4815a
PiperOrigin-RevId: 582237355
Change-Id: I65dfabe0b3a7a87c5d85a9d0383d3831bbb56590
> [7.0.0] Emit actual hash in same format as expected hash

- src/main/java/com/google/devtools/build/lib/rules/java/JavaOptions.java
See https://github.com/bazelbuild/bazel/issues/20159
Commit https://github.com/bazelbuild/bazel/commit/1d7af7ea70c2a08c90f7ebb34b24172fb1a44298
PiperOrigin-RevId: 582437396
Change-Id: I2945bd05ef1a36645a63b8158997e70286e3b7c5
> [7.0.0] Flip --incompatible_multi_release_deploy_jars

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegistryFactoryImpl.java
Commit https://github.com/bazelbuild/bazel/commit/52b5c8ccb80385b3eca071cfa353df9b94680852
PiperOrigin-RevId: 582665923
Change-Id: I3e9005401a135c5d8d5c23513323c09b96d8610e
> [7.0.0] Update registry invalid path error message

- scripts/ci/build.sh
The release script now automatically updates the rolling release index at https://releases.bazel.build/rolling.html as part of the release process. The code is not particularly elegant, but at least it's a starting point.
Progress towards https://github.com/bazelbuild/bazel/issues/20203
> Automatically update rolling release index

- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaStarlarkCommon.java
- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaCommonApi.java
- src/main/starlark/builtins_bzl/common/java/java_import.bzl
- src/main/starlark/builtins_bzl/common/java/java_info.bzl
- src/main/starlark/builtins_bzl/common/java/java_semantics.bzl
- src/test/java/com/google/devtools/build/lib/rules/java/JavaInfoStarlarkApiTest.java
- src/test/java/com/google/devtools/build/lib/view/java/BUILD
- src/test/java/com/google/devtools/build/lib/view/java/JavaImportConfiguredTargetTest.java
Backport #20036, #20035, and #20037.
Fixes #20258.
> [7.0.0] Backport add_exports/add_opens fixes

- MODULE.bazel
- MODULE.bazel.lock
Fixes #20276
PiperOrigin-RevId: 584535765
Change-Id: I0096c2f982961d7dcbb63ff2a588f296336bd35b
> [7.0.0] Update abseil-cpp version to 20230125.1

- .github/workflows/update-lockfiles.yml
This is to test whether it's possible to update the lockfile and push the changes to anoter person's branch in their own forked repo.
> [Please ignore] Lockfile testing for Automation

- src/main/java/com/google/devtools/build/lib/server/GrpcServerImpl.java
Fixes https://github.com/bazelbuild/bazel/issues/20743
Commit https://github.com/bazelbuild/bazel/commit/1a0b3a0db9f9eab72ddfdd7dbaf6e4801a6126fa
PiperOrigin-RevId: 595935153
Change-Id: I0409552aa92f3886c5abf3bd3ce50d67594dab7e
> [7.1.0] Retry binding to ipv6 localhost

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
As per https://github.com/bazelbuild/bazel/pull/20729#discussion_r1442892410
> [6.5.0] Disable rewriter test

- src/main/java/com/google/devtools/build/lib/actions/ActionInputHelper.java
- src/main/java/com/google/devtools/build/lib/actions/Artifact.java
- src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
- src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
- src/main/java/com/google/devtools/build/lib/skyframe/ActionExecutionFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/ActionInputMapHelper.java
- src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java
Includes 3 commits.
https://github.com/bazelbuild/bazel/commit/c48392c54a92b7bc5b04883bd6499c7a5677205d, https://github.com/bazelbuild/bazel/commit/bc1d9d38bea907beea8fd82c362c9882ddf48cfd, https://github.com/bazelbuild/bazel/commit/b0db044227d62178a7e578b8e03c452d8c17af33
Progress towards https://github.com/bazelbuild/bazel/issues/20753
> [7.1.0] Fixes for Bazel's own integration tests fail locally on Linux

- scripts/ci/build.sh
Commit https://github.com/bazelbuild/bazel/commit/275000c430de7436a1dd09f0874f6151a7ca9162
PiperOrigin-RevId: 602440856
Change-Id: I5c1a3c4ba3fa70d1ea928ad3d23f472da7af65d7
> [7.1.0] Publish RCs to GitHub

- src/tools/execlog/BUILD
- src/tools/execlog/src/main/java/com/google/devtools/build/execlog/BUILD
- src/tools/execlog/test/main/java/com/google/devtools/build/execlog/BUILD
- src/tools/workspacelog/BUILD
PiperOrigin-RevId: 601430837
Change-Id: Ie7739e2e4aead81a8a3ab7d9eedf47294ed9f855
> [7.1.0] Harmonize BUILD files.

- src/main/java/com/google/devtools/build/lib/exec/ExpandedSpawnLogContext.java
PiperOrigin-RevId: 602985772
Change-Id: I8e05a462069ea43940bd6121987673a1f5b918a3
> [7.1.0] Add missing close().

- src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java
> [7.1.0] Document --incompatible_disallow_unsound_directory_outputs.

- src/main/java/com/google/devtools/build/lib/remote/UploadManifest.java
PiperOrigin-RevId: 612440278
Change-Id: I9ba6bbb212013596df330d1d3da45e80b4280647
> [7.1.0] Add a profiler span for the findMissingDigests call associated with an upload.

- .bazelci/build_bazel_binaries.yml
Commit https://github.com/bazelbuild/bazel/commit/63dcbfbe6556ff52518cacd5ae943183bfe9a171
PiperOrigin-RevId: 614625205
Change-Id: If7cd3ef4af084aff2a9b3d70b7a11e2d4eefe844
> [7.1.1] Update centos7 platform in build_bazel_binaries.yml

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
- src/main/java/com/google/devtools/build/lib/bazel/rules/android/BazelAndroidLocalTest.java
- src/main/java/com/google/devtools/build/lib/rules/java/JavaRuntimeInfo.java
- src/test/java/com/google/devtools/build/lib/rules/java/JavaRuntimeTest.java
- Reverted https://github.com/bazelbuild/bazel/pull/21892
- Cherry-picked https://github.com/bazelbuild/bazel/commit/86ac024c2bb0d0371710686a2aab47af1402599f to fix the original test failures.
> [7.2.0] Enable android tests

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
If `--experimental_remote_output_service` is set, Bazel issue a FinalizeBuild RPC to the output service after the build is done.
Closes #21739.
PiperOrigin-RevId: 617487580
Change-Id: Ib07e9c97f74dfa2fe6f78ec46f7674f59e39ae12
Commit https://github.com/bazelbuild/bazel/commit/c8187acd6fa9217ea8dd03bbea46af641888d1b9
> [7.2.0] Implement FinalizeBuild

- src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java
If `--experimental_remote_output_service` is set, Bazel issues a Clean RPC to the output service when running `bazel clean`.
Closes #21743.
PiperOrigin-RevId: 617501624
Change-Id: Idf83b45913f5b35acfb1a29231f2fa7e5aedc850
Commit https://github.com/bazelbuild/bazel/commit/3b6aac055cdb28ae67e6a87f1c0cef1fc30fe64d
> [7.2.0] Implement Clean

- src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/ExecutionServer.java
Found to fix flaky local behavior of remote tests when invoking `bazel shutdown`:
```
Load240418 11:57:38.114:XT 85 [com.google.devtools.build.remote.worker.ExecutionServer.lambda$waitExecution$1] Work failed: 9bcaa872-d921-4889-a762-66c242993c59
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled. Use ServerCallStreamObserver.setOnCancelHandler() to disable this exception
at io.grpc.Status.asRuntimeException(Status.java:526)
at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:366)
at com.google.devtools.build.remote.worker.ExecutionServer.lambda$waitExecution$1(ExecutionServer.java:171)
at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFu …
```
> [7.2.0] Deflake remote tests by setting an `OnCancelHandler`

- MODULE.bazel.lock
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/AbridgedModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GsonTypeAdapterUtil.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionUsage.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionUsagesFunction.java
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionUsagesValue.java
- src/test/py/bazel/bzlmod/bazel_lockfile_test.py
- src/test/tools/bzlmod/MODULE.bazel.lock
Fixes #22121
Closes #22123.
PiperOrigin-RevId: 630277746
Change-Id: I893a69b0048e933554f515684c6ab1fdae541c0b
> [7.2.0] Detect extension staleness due root module name/version change

- src/main/java/com/google/devtools/build/lib/profiler/JsonTraceFileWriter.java
- src/main/java/com/google/devtools/build/lib/profiler/Profiler.java
- src/main/java/com/google/devtools/build/lib/profiler/ThreadMetadata.java
Cherry-pick commits:
- 10777215a95224f8dfd163572d98a301862a277e
- 10e02a15a6f5b915b7a8d25ad7a4be3481210037
> [7.2.0] Support profiling in an virtual thread.

- src/main/java/com/google/devtools/build/lib/exec/TestPolicy.java
- src/test/shell/bazel/bazel_test_test.sh
Fixes https://github.com/bazelbuild/bazel/issues/14418
Closes #22420.
PiperOrigin-RevId: 635740423
Change-Id: Iffd4d172c4175be2e1b6cfad04ddad2759adb987
Commit https://github.com/bazelbuild/bazel/commit/01a90d64c4279e8160bc358a417ec50def710cf1
> [7.2.0] Make env on test rules override --test_env

- src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
- src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloaderTest.java
The retry doesn't work if the ContentLengthMismatchException is wrapped in an IOException.
PiperOrigin-RevId: 636107102
Change-Id: I721e0be325dfd7c4e8a3dd697f5d513f42bcb7aa
Commit https://github.com/bazelbuild/bazel/commit/758f399f0e6064d470c5c5bac0eeace9ba863f58
> [7.2.0] Correctly detect ContentLengthMismatchException and retry.

- src/main/java/com/google/devtools/build/lib/skyframe/IncrementalPackageRoots.java
**The Issue**
Some external users reported the following sequence:
1. Build starts
2. Build interrupted very early on
3. Another build is started. The command line says "A previous command is running", while the server is stuck.
What happened under the hood:
The issue could be reproduced very reliably by placing a breakpoint here[1] and interrupt the build.
Bazel is in the middle of the recursive `IncrementalPackageRoots.registerAndPlantMissingSymlinks` method when it received the interruption.
One important detail: we only add a NestedSet to the `donePackagesRef` set when the _method_ is done successfully. When there's an interruption, we always bail early and never actually reach this line where the NestedSet is added to the set[2].
Without deduplication, this could lead to what feels …
> [7.2.0] Fix a potential infinite loop in the case of an interruption.

- BUILD
- MODULE.bazel
- MODULE.bazel.lock
- repositories.bzl
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RepoSpec.java
- src/main/java/com/google/devtools/build/lib/skyframe/BzlmodRepoRuleFunction.java
- src/test/shell/bazel/BUILD
- src/tools/bzlmod/utils.bzl
Closes #22400.
PiperOrigin-RevId: 642564375
Change-Id: I1326aa33ddd30d29a51b928adcea0def42304fe9
Commit https://github.com/bazelbuild/bazel/commit/2758f55c1d4a11a296c0d9649880300d20ae96f9
> [7.3.0] Clean up build after update to 7.2.0

- MODULE.bazel
- MODULE.bazel.lock
- scripts/BUILD
Closes #18444.
PiperOrigin-RevId: 642659695
Change-Id: I97f2c2a20a8dd7a3958e6d814475395a2802dc70
Commit https://github.com/bazelbuild/bazel/commit/0ca7099eb81b2d1a4d8b85e8f7ad0bd83536fbee
> [7.3.0] Add a jq version for arm64

- src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java
- src/main/protobuf/failure_details.proto
Fixes #22741.
PiperOrigin-RevId: 643932127
Change-Id: Ia9566acb7b828224679ad57b71644281a8e52db4
> [7.2.1] Add missing category submessage.

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/ModExecutor.java
- src/main/java/com/google/devtools/build/lib/bazel/commands/ModCommand.java
- src/test/py/bazel/bzlmod/mod_command_test.py
Fixes #22642
Closes #22887.
PiperOrigin-RevId: 646981159
Change-Id: I3fc42339ab7013d0a01e3f5feb16a781b799edd5
Commit https://github.com/bazelbuild/bazel/commit/9c4e73d9f0a76ed7203cea05c651ad570da05208
> [7.3.0] Add error message instead of NPE with mod show_extension

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionUsagesValue.java
- src/test/py/bazel/bzlmod/bazel_lockfile_test.py
- src/test/tools/bzlmod/MODULE.bazel.lock
This was missed in #19055.
Closes #23527.
PiperOrigin-RevId: 672480631
Change-Id: Ib2ef0edb6b6c90a7336085da20e2794a93763182
Commit https://github.com/bazelbuild/bazel/commit/926b57474fbcf7ad630ebb8944b10c4b96c9f00f
> [7.4.0] Invalidate lockfile entry when the extension name prefix changes

- .github/workflows/cherry-picker.yml
This is in regards to https://github.com/bazelbuild/bazel/commit/55535cbb9a97d6be66e41a78f66ffeee678d4fb1
> Update cherry-picker.yml to include the security vulnerability fix

- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/android/AndroidStarlarkCommonApi.java
PiperOrigin-RevId: 667957493
Change-Id: I013e29baa30d19ba1c5c0f1afee67b4bffd358f7
Commit https://github.com/bazelbuild/bazel/commit/b17552bfba80e69a4d86d5566c0237e6b8438fcf
> [7.4.0] Cherrypick b17552bfba80e69a4d86d5566c0237e6b8438fcf

- src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaBootstrap.java
PiperOrigin-RevId: 670945599
Change-Id: I7aeb2c67ad3c0f17b56f4a972ec87659bd157f99
Commit https://github.com/bazelbuild/bazel/commit/384e381fa841537987691f170ed9408dcfeed2ea
> [7.4.0] Cherrypick 384e381fa841537987691f170ed9408dcfeed2ea into 7.4.0

- tools/build_defs/repo/git_worker.bzl
This commit adds the `-c core.fsmonitor=false` arguments to all git commands (excluding `git init`) in `git_worker.bzl`. The purpose of this is to disable git from spawning a file system monitor, when many of these are spawned on a machine that is already under load or out of file descriptors, the git commands will hang indefinitely.
Fixes https://github.com/bazelbuild/bazel/issues/21438
Closes #23626.
PiperOrigin-RevId: 675472544
Change-Id: I79e0b6d1e406a9076cdb810747c382de52face1a
Commit https://github.com/bazelbuild/bazel/commit/bb577b0b7c441275b83c9b8cb2ce276ec73ab2d3
> [7.4.0] Disable git fsmonitor in git_worker to fix hangs when fetching repositories

- src/main/java/com/google/devtools/build/lib/cmdline/RepositoryName.java
PiperOrigin-RevId: 676817381
Change-Id: I66b566ed75be858b3f2d92a8ac751bc97358a578
Commit https://github.com/bazelbuild/bazel/commit/5949aacc3a92e36e25293120c93d409f42e79b46
> [7.4.0] Precompute hashcode for `RepositoryName`.

- src/main/java/com/google/devtools/build/lib/rules/cpp/HeaderDiscovery.java
- src/test/shell/bazel/path_mapping_test.sh
Fixes header inclusion errors with path mapping when including a header that is a non-direct child of a tree artifact.
Fixes #23681
Closes #23690.
PiperOrigin-RevId: 678118252
Change-Id: I37f4d5e8827785b291b5655967afba8f2a673df2
Commit https://github.com/bazelbuild/bazel/commit/9cfffdf5d002e566103127349b57cdf49ad16641
> [7.4.0] Path map non-direct children of tree artifacts during header discovery

- src/main/java/com/google/devtools/build/lib/server/IdleTaskManager.java
Otherwise they are lost, making debugging very difficult.
PiperOrigin-RevId: 679540076
Change-Id: I4000ad55745578b0cd8d5c2cc9766e5c7f18059d
> [7.4.0] Log exceptions from tasks in IdleTaskManager.

- src/main/java/com/google/devtools/build/lib/exec/BUILD
- src/main/java/com/google/devtools/build/lib/exec/SpawnLogReconstructor.java
- src/tools/execlog/README.md
- src/tools/execlog/src/main/java/com/google/devtools/build/execlog/BUILD
- src/tools/execlog/src/main/java/com/google/devtools/build/execlog/ExecLogParser.java
- src/tools/execlog/test/main/java/com/google/devtools/build/execlog/BUILD
- src/tools/execlog/test/main/java/com/google/devtools/build/execlog/ExecLogParserTest.java
The format is auto-detected from the first few bytes of the input file.
PiperOrigin-RevId: 680915789
Change-Id: I6f1b4a2334912f25a8c41761a970e8f75265cc13
> [7.4.0] Teach ExecLogParser how to parse all three execution log formats.

- bazel_downloader.cfg
- repositories.bzl
Also switch back to Zulu where possible.
Closes #23913.
PiperOrigin-RevId: 684397892
Change-Id: I1b563bd45f85bd8ec5cfbaf8550f0a59ea8f0b54
> [7.4.0] Update embedded JDKs to latest patch release

- src/main/starlark/builtins_bzl/common/cc/experimental_cc_static_library.bzl
Closes #23800.
PiperOrigin-RevId: 684529045
Change-Id: I14dc53b6f2e39c7a05ee3a8b872eb220af45cef9
> [7.4.0] Mark `cc_static_library` as experimental in docs

- src/main/java/com/google/devtools/build/lib/rules/repository/RepoRecordedInput.java
- src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/PrecomputedValue.java
- src/test/shell/bazel/starlark_repository_test.sh
> [7.4.0] Make repo marker file parsing robust to version changes

- bazel_downloader.cfg
- repositories.bzl
Also switch back to Zulu where possible.
Closes #23913.
PiperOrigin-RevId: 684397892
Change-Id: I1b563bd45f85bd8ec5cfbaf8550f0a59ea8f0b54
Commit https://github.com/bazelbuild/bazel/commit/78b8871c6b9f93a8f5e4fcf3f32b1a2c8e1532c3
> [8.0.0] Update embedded JDKs to latest patch release

- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD
- src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java
Fixes #23981
Closes #23982.
PiperOrigin-RevId: 686486627
Change-Id: I5f03b63601a535f8d551c005b00bf040846a324d
Commit https://github.com/bazelbuild/bazel/commit/b0f1430f0e9b7608b9ecc64b20c3b0fe40ac4a43
> [7.4.0] Show "did you mean" suggestion for `{override,inject}_repo`

- src/test/java/com/google/devtools/build/lib/skyframe/BUILD
- src/test/py/bazel/BUILD
- src/test/py/bazel/test_base.py
Commits:
- 49aa26881a209e21eedaa3a59a5e59a89c05fc30 
- 11a909aa560e8ed67f048c3917389f9b8674a441 
- 1bb31854200a67941edf9e3d9cc036432c00a7a2
> [8.0.0] Backport a few commits to address flaky tests in release-8.0.0

- src/main/cpp/blaze_util_windows.cc
Compare with blaze_util_posix.cc.
PiperOrigin-RevId: 692927012
Change-Id: Ibd7f44ec288c436e891157c82c1b5484c7e5c0f7
> [8.0.0] Avoid a print loop when busy-waiting on the client lock on Windows.

- src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt
- src/package-bazel.sh
- src/test/shell/bazel/bazel_determinism_test.sh
Closes #24016.
PiperOrigin-RevId: 693253221
Change-Id: I3c51ed1900bd3fa47a3448239389e57cb5505fa6
Commit https://github.com/bazelbuild/bazel/commit/de9debba61ad729ae9f81a1a36e8869703f845fd
> [8.0.0] Improve support for spaces in output base

- src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java
- src/test/java/com/google/devtools/build/lib/exec/SymlinkTreeHelperTest.java
Compare with EnsureDirReadAndWritePerms in build-runfiles.cc.
PiperOrigin-RevId: 695254434
Change-Id: If8694ad4fdd666739419ca02373a35a2cf36f4ac
> [8.0.0] Fix permissions on directories while incrementally updating a symlink tree.

- src/test/shell/bazel/bazel_ui_test.sh
Closes #24243.
PiperOrigin-RevId: 696968080
Change-Id: I8ad1dbe03c54b3a8d13f699026140f114f75e928
Commit https://github.com/bazelbuild/bazel/commit/54a9c0b7e8b23eb7338bf38022745e9095b80641
> [8.0.0] Add test for Unicode console output

- repositories.bzl
Work towards #23497
Work towards #24389
Closes #24431.
PiperOrigin-RevId: 698846634
Change-Id: I3fb2d46597b225833a918af9731665bb276322dd
Commit https://github.com/bazelbuild/bazel/commit/27a5e4593fb661518aaa1bad96ff1fc5257733eb
> [8.0.0] Update embedded JDK to 21.0.5

- src/main/java/com/google/devtools/build/lib/skyframe/RepoFileFunction.java
- src/test/shell/bazel/workspace_test.sh
Fixes https://github.com/bazelbuild/bazel/issues/24498
RELNOTES: None
PiperOrigin-RevId: 700720057
Change-Id: Ieb656821c41d5dde64c0807f2220f8b212267880
Commit https://github.com/bazelbuild/bazel/commit/dbb94574c7a6cbc0aed1b5bd86508535ee471a68
> [8.0.0] Fix crashing issue with WORKSPACE

- src/main/java/com/google/devtools/build/lib/profiler/CollectLocalResourceUsage.java
This guards against an ineffective `null` check in the JDK.
Also use `getCpuLoad()` instead of `getSystemCpuLoad()` as the latter has been deprecated.
Fixes #24519
Closes #24569.
PiperOrigin-RevId: 703413335
Change-Id: I66189d7e44962363be8a0c36496ce89fd388b9c9
Commit https://github.com/bazelbuild/bazel/commit/a85a3205e6a2106af0a9bd4a331d25d6ef3c5fb3
> [8.0.0] Guard against NPE when calling `OperatingSystemMXBean.getCpuLoad()`

- tools/test/test-setup.sh
Addressing https://github.com/bazelbuild/bazel/pull/24256#discussion_r1877753150
PiperOrigin-RevId: 704624513
Change-Id: I73ec6559a7a7b2465abd2faae0e687a97ea77db9
Commit https://github.com/bazelbuild/bazel/commit/9ed06ad024bfc6633fb098ed57d2a8cbb
> [8.0.1] Make rlocation in test-setup.sh compatible with /bin/sh

- src/main/cpp/blaze.cc
PiperOrigin-RevId: 699935027
Change-Id: I5d14a0e916e43b02d8a1a70067839b937e626326
> [8.1.0] Remove unnecessary workaround.

- scripts/release/relnotes.py
PiperOrigin-RevId: 718504556
Change-Id: I54f42e07721935c44a6f2a314b59864d6433d865
Commit https://github.com/bazelbuild/bazel/commit/c38bed0592ad2a2a5a8402dc0fb625ea63c6643d
> [8.1.0] Update relnotes script to follow the patch release format for minor releases with no RELNOTES tags

- scripts/release/relnotes.py
PiperOrigin-RevId: 718504556
Change-Id: I54f42e07721935c44a6f2a314b59864d6433d865
Commit https://github.com/bazelbuild/bazel/commit/c38bed0592ad2a2a5a8402dc0fb625ea63c6643d
> [7.5.0] Update relnotes script to follow the patch release format for minor releases with no RELNOTES tags

- src/main/cpp/util/file_windows.cc
There's no need to create a dummy file; we can try to open the directory with the desired permissions.
PiperOrigin-RevId: 699951625
Change-Id: Id72c643ad1258be81c80236485bdc42a2cc8698b
> [8.1.0] Simplify CanAccessDirectory on Windows.

- src/test/shell/integration/BUILD
- src/test/shell/integration/client_test.sh
PiperOrigin-RevId: 701013126
Change-Id: I5944f71989afdbf0cd53e2f7e17726ef0ae5211b
> [8.1.0] Add a few more integration tests verifying concurrent use of the install and output bases.

- src/main/cpp/blaze.cc
- src/main/java/com/google/devtools/build/lib/BUILD
- src/main/java/com/google/devtools/build/lib/runtime/BlazeRuntime.java
- src/main/java/com/google/devtools/build/lib/runtime/BlazeServerStartupOptions.java
- src/main/protobuf/failure_details.proto
- src/test/java/com/google/devtools/build/lib/testutil/BUILD
- src/test/java/com/google/devtools/build/lib/testutil/ExternalFileSystemLock.java
- src/test/java/com/google/devtools/build/lib/testutil/ExternalFileSystemLockHelper.java
- src/test/shell/bazel/BUILD
- src/test/shell/bazel/client_test.sh
Progress on #2109.
PiperOrigin-RevId: 704253963
Change-Id: Ib5ef94bbcbad769ca19ac89f97e1d7f82eba4dba
> [8.1.0] Take a shared lock on the install base from the server side.

- src/main/java/com/google/devtools/build/lib/exec/TestXmlOutputParser.java
Technically strings like "1e2" are not valid for the `time` attribute (that
attribute's schema is supposed to be `xs:decimal`), however some JUNIT writers
are non-compliant and use scientific e notation and we want Bazel to still work
with them.
While I'm here, improve the code comments (the existing comment about us having
to support values without decimal points like "12" as milliseconds is backwards as
noted in https://github.com/bazelbuild/bazel/issues/24605#issuecomment-2524851929) and add tests.
Fixes #24605.
PiperOrigin-RevId: 722963681
Change-Id: I9383cf7435ae7843f07a5abddbcf790f275403d0
Commit https://github.com/bazelbuild/bazel/commit/f52568f1d5fa15538d2f7c99401417d2cd24679c
> [8.1.0] Bazel's test XML parser now supports scientific e notation for time durations.

- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryResolvedEvent.java
Fixes #25192
Closes #25194.
PiperOrigin-RevId: 723594158
Change-Id: I12aaced1db4f167c4a9691623128fe0d3eb15686
Commit https://github.com/bazelbuild/bazel/commit/5e2dfbaf7394b099e56d0893b98cef163af87a6b
> [8.1.0] Don't suggest updates to private repo rule attributes

- src/test/py/bazel/launcher_test.py
- src/tools/launcher/java_launcher.cc
Addresses: https://github.com/bazelbuild/bazel/pull/24703#issuecomment-2665963637
PiperOrigin-RevId: 728571293
Change-Id: Ic1a292b6a6394e1c996cdaa1189e33431eb6f6d2
Commit https://github.com/bazelbuild/bazel/commit/77137d42d1958b7ca68fe1a3ed7644cde1b7328c
> [8.1.1] Fix building binary launchers on windows with clang-cl

- src/test/py/bazel/launcher_test.py
- src/tools/launcher/java_launcher.cc
Addresses: https://github.com/bazelbuild/bazel/pull/24703#issuecomment-2665963637
PiperOrigin-RevId: 728571293
Change-Id: Ic1a292b6a6394e1c996cdaa1189e33431eb6f6d2
Commit https://github.com/bazelbuild/bazel/commit/77137d42d1958b7ca68fe1a3ed7644cde1b7328c
> [8.2.0] Fix building binary launchers on windows with clang-cl

- src/main/java/com/google/devtools/build/lib/analysis/BuildView.java
- src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java
* https://github.com/bazelbuild/bazel/commit/3e115b937d7f6eff5c819667c6f6226c8fdba466
* https://github.com/bazelbuild/bazel/commit/e12fdd93a3e22163d37209634ad5546f9fccd3bf
> [7.6.0] Performance improvements for builds with many top-level targets

- src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java
- src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
- src/main/java/com/google/devtools/build/lib/skyframe/BzlCompileFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/BzlLoadFunction.java
- src/main/java/com/google/devtools/build/lib/skyframe/PackageFunction.java
- src/test/shell/integration/incompatible_autoload_externally_test.sh
Flag disables autoloads in the main repository.
PiperOrigin-RevId: 729406986
Change-Id: I0528451f4371454ae2205bb7da54af974f599b12
> [8.2.0] Implement incompatible_disable_autoloads_in_main_repo

- src/main/java/com/google/devtools/build/lib/remote/UploadManifest.java
Closes #25375.
PiperOrigin-RevId: 731613804
Change-Id: I8815d8b0a9de82b91ba812c974dc6ac26b48a100
Commit https://github.com/bazelbuild/bazel/commit/8c8b7c0f6bf85f27f12b393d337cfcfab209f510
> [8.2.0] Avoid unnecessary copying in `DirectoryBuilder.build()`

- src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryModule.java
This avoids retaining one `RuleClass` instance per repository.
Closes #25581.
PiperOrigin-RevId: 738094342
Change-Id: Iab53cc0e755b693e90051bc5bdeb234d06aa9784
Commit https://github.com/bazelbuild/bazel/commit/6141636e7e42f7cff3fb6541f64e929d582fb2c2
> [8.2.0] Cache `RuleClass` per repository rule object

- src/main/java/com/google/devtools/build/lib/packages/Package.java
Bzlmod creates a fake package per repo, each of which retains a unique instance of the module file path as well as the fake package ID, both of which can be deduplicated across all repos created by an extension.
Closes #25577.
PiperOrigin-RevId: 738091643
Change-Id: I88482bdde6b299cbf9dab3588ba1be5e205d1dd1 
(cherry picked from commit cbd752089bdda10fe72c1a83537651eb0150e6a5)
Closes #25578
> [8.2.0] Intern Bzlmod fake package metadata

- tools/build_defs/repo/git_worker.bzl
Closes #25773.
cc: @jpc-sf
Closes #25774.
PiperOrigin-RevId: 744751249
Change-Id: Idd9eaa5a524b86d2f357b311d92a586f4f0116ab
Commit https://github.com/bazelbuild/bazel/commit/441c563bd43cccdfad71040557a7e229970475c3
> [8.2.0] Do not require sparse checkout attrs

- .bazelci/build_bazel_binaries.yml
- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
- src/test/shell/bazel/bazel_example_test.sh
- src/test/shell/bazel/bazel_sandboxing_networking_test.sh
Safe to submit once https://github.com/bazelbuild/continuous-integration/pull/2286 has been merged.
Progress towards https://github.com/bazelbuild/continuous-integration/issues/2272
PiperOrigin-RevId: 755425618
Change-Id: I114e8b3cd88891d25843fcc32b90e9c64a615e3d
Commit https://github.com/bazelbuild/bazel/commit/ff7a28347e511610a28fd4fba661befe5a83abe1, https://github.com/bazelbuild/bazel/commit/498a0c8e5547dea97f3049d8e1ea16fe9db4977d
> [8.3.0] Bazel CI: Stop building binaries on CentOS 7

- src/main/java/com/google/devtools/build/lib/exec/TestXmlOutputParser.java
- src/main/java/com/google/devtools/build/lib/runtime/TerminalTestResultNotifier.java
- src/main/java/com/google/devtools/build/lib/runtime/TestSummary.java
- src/main/java/com/google/devtools/build/lib/runtime/TestSummaryPrinter.java
- src/main/protobuf/test_status.proto
- src/test/java/com/google/devtools/build/lib/runtime/TerminalTestResultNotifierTest.java
- src/test/java/com/google/devtools/build/lib/runtime/TestSummaryTest.java
Cherry-picking 48e940f18d4f75bd6ba79415abfbac088687a1fa
> [8.3.0] Reporting skipped test cases

- src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
Closes #25986.
PiperOrigin-RevId: 762397218
Change-Id: I60c231934becdb620dadc3bec878d828abe450b8
Commit https://github.com/bazelbuild/bazel/commit/c1165a6df76e90061fe666b7ee9362b8c0f4923e
> [8.3.0] Avoid two stats for non-directory symlinks created remotely

- src/main/tools/linux-sandbox-pid1.cc
Fixes:
```
src/main/tools/linux-sandbox-pid1.cc:98: "open": File exists
...
src/main/tools/linux-sandbox-pid1.cc:110: "link dev/null": File exists
```
Work towards #24081
Closes #26437.
PiperOrigin-RevId: 778620293
Change-Id: I01f06915c4ef92b69b0202a93c533cc8d1db6a9d
Commit https://github.com/bazelbuild/bazel/commit/ef77d4e6a74d2658ef2373636fea2bba847cf792
> [8.4.0] Allow running `--sandbox_debug` command multiple times

- src/main/java/com/google/devtools/build/lib/query2/cquery/ProtoOutputFormatterCallback.java
Fixes #26494
Closes #26516.
PiperOrigin-RevId: 781682351
Change-Id: Id982ff70dd8b561b9a6c8f4c620c13d3bb913e02
Commit https://github.com/bazelbuild/bazel/commit/f419da7c3d28018101a4896f0e7f4baad1e7d974
> [8.4.0] Don't crash if cquery proto output exceeds 2GB

- src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java
- src/test/py/bazel/bzlmod/bazel_fetch_test.py
- src/test/shell/bazel/external_integration_test.sh
> [8.4.0] Disable the repo contents cache by default
